Repository SAP/fundamental-ngx, pull requests merged in 2018-09, with the labels that each got.

#192 Update Icon component documentation
  docs/modules/documentation/AppConstants.ts
  docs/modules/documentation/IconsAriba.ts
  docs/modules/documentation/IconsSAP.ts
  docs/modules/documentation/components/documentation/documentation.component.html
  docs/modules/documentation/components/documentation/documentation.component.scss
  docs/modules/documentation/components/documentation/documentation.component.ts
  docs/modules/documentation/containers/icon/icon-docs.component.html
  docs/modules/documentation/containers/icon/icon-docs.component.scss
  docs/modules/documentation/containers/icon/icon-docs.component.ts
Labels: enhancement

#191 Update documentation to support RTL testing for components.
  docs/modules/documentation/components/RTL/RTLToggle.component.ts
  docs/modules/documentation/documentation.module.ts
Labels: enhancement

#189 Update Icon component with Ariba-Icons
  docs/styles.scss
  package.json
  projects/fundamental-ngx/src/lib/icon/icon.directive.ts
Labels: enhancement

#218 Feature/#181 add home page
  docs/app/components/home/home.component.html
  docs/app/components/home/home.component.scss
  docs/assets/images/logo-sap.svg
  docs/modules/documentation/components/documentation/documentation.component.html
  docs/modules/documentation/containers/home/home.component.html
  docs/modules/documentation/containers/home/home.component.ts
  docs/modules/documentation/containers/installation/installation.component.html
  docs/modules/documentation/documentation.module.ts
Labels: documentation

#221 #220 update fundamental-ui version to 1.2
  docs/modules/documentation/containers/installation/installation.component.html
  docs/modules/documentation/containers/navbar/navbar-docs.component.html
  package-lock.json
  package.json
  projects/fundamental-ngx/src/lib/popover/popover.component.html
Labels: enhancement

#223 #222 update package.json libraries
  package-lock.json
  package.json
Labels: enhancement

#226 Update contact information
  CONTRIBUTING.md
Labels: documentation

#219 Panel row col span
  docs/modules/documentation/containers/panel/panel-docs.component.html
  docs/modules/documentation/containers/panel/panel-docs.component.ts
  projects/fundamental-ngx/src/lib/panel/panel.component.spec.ts
  projects/fundamental-ngx/src/lib/panel/panel.component.ts
Labels: bug

#234 Feature/#224 enable right-to-left simulator in playground
  .editorconfig
  .vscode/settings.json
  docs/modules/documentation/components/component-example/component-example.component.ts
  docs/modules/documentation/components/directionality/directionality.component.ts
  docs/modules/documentation/components/documentation/documentation.component.html
  docs/modules/documentation/components/documentation/documentation.component.ts
  docs/modules/documentation/components/example-background/example-background.component.ts
  docs/modules/documentation/containers/action-bar/action-bar-docs.component.html
  docs/modules/documentation/containers/alert/alert-docs.component.html
  docs/modules/documentation/containers/badge-label/badge-label-docs.component.html
  docs/modules/documentation/containers/breadcrumb/breadcrumb-docs.component.html
  docs/modules/documentation/containers/button-group/button-group-docs.component.html
  docs/modules/documentation/containers/button/button-docs.component.html
  docs/modules/documentation/containers/calendar/calendar-docs.component.html
  docs/modules/documentation/containers/date-picker/date-picker-docs.component.html
  docs/modules/documentation/containers/dropdown/dropdown-docs.component.html
  docs/modules/documentation/containers/form/form-docs.component.html
  docs/modules/documentation/containers/icon/icon-docs.component.html
  docs/modules/documentation/containers/identifier/identifier-docs.component.html
  docs/modules/documentation/containers/image/image-docs.component.html
  docs/modules/documentation/containers/inline-help/inline-help-docs.component.html
  docs/modules/documentation/containers/input-group/input-group-docs.component.html
  docs/modules/documentation/containers/list/list-docs.component.html
  docs/modules/documentation/containers/mega-menu/mega-menu-docs.component.html
  docs/modules/documentation/containers/menu/menu-docs.component.html
  docs/modules/documentation/containers/modal/modal-docs.component.html
  docs/modules/documentation/containers/navbar/navbar-docs.component.html
  docs/modules/documentation/containers/pagination/pagination-docs.component.html
  docs/modules/documentation/containers/panel/panel-docs.component.html
  docs/modules/documentation/containers/popover/popover-docs.component.html
  docs/modules/documentation/containers/side-navigation/side-navigation-docs.component.html
  docs/modules/documentation/containers/table/table-docs.component.html
  docs/modules/documentation/containers/tabs/tabs-docs.component.html
  docs/modules/documentation/containers/tile/tile-docs.component.html
  docs/modules/documentation/containers/time-picker/time-picker-docs.component.html
  docs/modules/documentation/containers/time/time-docs.component.html
  docs/modules/documentation/containers/tree/tree-docs.component.html
  docs/modules/documentation/documentation.module.ts
Labels: documentation, enhancement

#236 #235 update to fundamental-ui 1.2.1
  package-lock.json
  package.json
Labels: enhancement

#238 #237 fix an issue during gh page build and publish
  package.json
  projects/fundamental-ngx/package.json
Labels: bug

#240 #237 downgrade to fundamental-ui 1.1 and hide RTL mode
  docs/modules/documentation/components/component-example/component-example.component.ts
  package-lock.json
  package.json
Labels: bug

#244 Table refactor (open for debate?)
  docs/modules/documentation/containers/panel/panel-docs.component.html
  docs/modules/documentation/containers/panel/panel-docs.component.ts
  docs/modules/documentation/containers/table/table-docs.component.html
  docs/modules/documentation/containers/table/table-docs.component.ts
  projects/fundamental-ngx/src/lib/table/table-body.component.html
  projects/fundamental-ngx/src/lib/table/table-body.component.ts
  projects/fundamental-ngx/src/lib/table/table-header.component.html
  projects/fundamental-ngx/src/lib/table/table-header.component.ts
  projects/fundamental-ngx/src/lib/table/table-row-object.model.ts
  projects/fundamental-ngx/src/lib/table/table.component.html
  projects/fundamental-ngx/src/lib/table/table.component.scss
  projects/fundamental-ngx/src/lib/table/table.component.spec.ts
  projects/fundamental-ngx/src/lib/table/table.component.ts
  projects/fundamental-ngx/src/lib/table/table.module.ts
Labels: enhancement
