Repository SAP/fundamental-ngx, pull requests merged in 2018-11, with the labels that each got.

#327 Update README.md
  README.md
Labels: documentation

#326 #295 and #325 to swap type secondary to options light buttons
  docs/modules/documentation/containers/button/button-docs.component.html
  docs/modules/documentation/containers/dropdown/examples/dropdown-contextual-menu-example.component.html
  docs/modules/documentation/containers/internationalization/internationalization.component.html
  docs/modules/documentation/containers/internationalization/internationalization.component.ts
  docs/modules/documentation/containers/list/examples/list-actions-example.component.html
  docs/modules/documentation/containers/modal/examples/modal-confirmation-example.component.ts
  docs/modules/documentation/containers/navbar/examples/navbar-example.component.html
  docs/modules/documentation/containers/tile/examples/tile-actions-example.component.html
  docs/modules/documentation/containers/tile/tile-docs.component.html
  library/src/lib/calendar/calendar.component.html
  library/src/lib/date-picker/date-picker.component.html
  library/src/lib/input-group/input-group.component.html
  library/src/lib/time-picker/time-picker.component.html
  library/src/lib/time/time.component.html
  library/src/lib/tree/tree-child.component.html
Labels: enhancement

#321 #320 refactored to add dropdown alignment and no arrow options
  docs/modules/documentation/containers/popover/examples/popover-example.component.html
  library/src/lib/popover/popover.component.html
  library/src/lib/popover/popover.component.ts
Labels: enhancement

#322 Feature/#296 add compact mode to time-picker
  docs/modules/documentation/containers/time-picker/examples/time-picker-compact-example.component.html
  docs/modules/documentation/containers/time-picker/examples/time-picker-examples.component.ts
  docs/modules/documentation/containers/time-picker/time-picker-docs.component.html
  docs/modules/documentation/containers/time-picker/time-picker-docs.component.ts
  docs/modules/documentation/documentation.module.ts
  library/src/lib/time-picker/time-picker.component.html
  library/src/lib/time-picker/time-picker.component.ts
Labels: code refactoring, enhancement

#337 add email to readme
  README.md
  library/README.md
Labels: documentation

#336 Bug/#335 remove rtl examples
  docs/modules/documentation/components/documentation/documentation.component.html
  docs/modules/documentation/containers/button/button-docs.component.html
  docs/modules/documentation/containers/button/button-docs.component.ts
  docs/modules/documentation/containers/button/examples/button-examples.component.ts
  docs/modules/documentation/containers/button/examples/button-rtl-example.component.html
  docs/modules/documentation/documentation.module.ts
Labels: documentation
