Repository SAP/fundamental-ngx, pull requests merged in 2018-12, with the labels that each got.

#341 #339 add angular 7 support
  docs/polyfills.ts
  package-lock.json
  package.json
  tsconfig.json
Labels: enhancement

#334 add option for calendar weeks to start on Monday instead of Sunday
  docs/modules/documentation/containers/calendar/calendar-docs.component.html
  docs/modules/documentation/containers/calendar/calendar-docs.component.ts
  docs/modules/documentation/containers/calendar/examples/calendar-monday-start-example.component.ts
  docs/modules/documentation/documentation.module.ts
  library/src/lib/calendar/calendar.component.ts
Labels: bug, documentation, enhancement

#344 #343 fix the doc build
  package-lock.json
  package.json
Labels: bug
