Repository SAP/fundamental-ngx, pull requests merged in 2019-09, with the labels that each got.

#1203 docs: Added disabled state in reactive forms
  docs/app/documentation/component-docs/calendar/calendar-docs.component.html
  docs/app/documentation/component-docs/calendar/calendar-docs.component.ts
  docs/app/documentation/component-docs/calendar/examples/calendar-form-examples.component.html
  docs/app/documentation/component-docs/calendar/examples/calendar-form-examples.component.ts
  docs/app/documentation/component-docs/calendar/examples/calendar-form-range-example.component.ts
  docs/app/documentation/component-docs/calendar/examples/calendar-form-single-example.component.ts
  docs/app/documentation/component-docs/combobox/combobox-docs.component.html
  docs/app/documentation/component-docs/combobox/examples/combobox-disabled-example.component.html
  docs/app/documentation/component-docs/combobox/examples/combobox-disabled-example.component.ts
  docs/app/documentation/component-docs/date-picker/date-picker-docs.component.html
  docs/app/documentation/component-docs/date-picker/examples/date-picker-form-example.component.ts
  docs/app/documentation/component-docs/datetime-picker/datetime-picker-docs.component.html
  docs/app/documentation/component-docs/datetime-picker/examples/datetime-form-example/datetime-form-example.component.html
  docs/app/documentation/component-docs/datetime-picker/examples/datetime-form-example/datetime-form-example.component.ts
  docs/app/documentation/component-docs/input-group/examples/input-group-form-example.component.html
  docs/app/documentation/component-docs/input-group/examples/input-group-form-example.component.ts
  docs/app/documentation/component-docs/input-group/examples/input-group-number-form-example.component.html
  docs/app/documentation/component-docs/input-group/examples/input-group-number-form-example.component.ts
  docs/app/documentation/component-docs/input-group/input-group-docs.component.html
  docs/app/documentation/component-docs/input-group/input-group-docs.component.ts
  docs/app/documentation/component-docs/input/examples/input-form-group-example.component.html
  docs/app/documentation/component-docs/input/examples/input-form-group-example.component.scss
  docs/app/documentation/component-docs/input/examples/input-form-group-example.component.ts
  docs/app/documentation/component-docs/input/input-docs.component.html
  docs/app/documentation/component-docs/multi-input/examples/multi-input-form-example/multi-input-form-example.component.html
  docs/app/documentation/component-docs/multi-input/examples/multi-input-form-example/multi-input-form-example.component.ts
  docs/app/documentation/component-docs/multi-input/multi-input-docs.component.html
  docs/app/documentation/component-docs/radio/examples/radio-form-group-example.component.html
  docs/app/documentation/component-docs/radio/examples/radio-form-group-example.component.ts
  docs/app/documentation/component-docs/select-native/examples/select-native-form-group-example.component.html
  docs/app/documentation/component-docs/select-native/examples/select-native-form-group-example.component.scss
  docs/app/documentation/component-docs/select-native/examples/select-native-form-group-example.component.ts
  docs/app/documentation/component-docs/select-native/select-native-docs.component.html
  docs/app/documentation/component-docs/select/examples/select-forms/select-forms.component.html
  docs/app/documentation/component-docs/select/examples/select-forms/select-forms.component.scss
  docs/app/documentation/component-docs/select/examples/select-forms/select-forms.component.ts
  docs/app/documentation/component-docs/select/select-docs.component.html
  docs/app/documentation/component-docs/textarea/examples/textarea-form-group-example.component.html
  docs/app/documentation/component-docs/textarea/examples/textarea-form-group-example.component.ts
  docs/app/documentation/component-docs/time-picker/examples/time-picker-form-example.component.html
  docs/app/documentation/component-docs/time-picker/examples/time-picker-form-example.component.ts
  docs/app/documentation/component-docs/time/examples/time-form-example.component.html
  docs/app/documentation/component-docs/time/examples/time-form-example.component.ts
  docs/app/documentation/component-docs/time/time-docs.component.html
  docs/app/documentation/component-docs/toggle/examples/toggle-form-example/toggle-forms-example.component.html
  docs/app/documentation/component-docs/toggle/examples/toggle-form-example/toggle-forms-example.component.ts
  docs/app/documentation/component-docs/toggle/toggle-docs.component.html
  docs/app/documentation/documentation.module.ts
Labels: documentation

#1210 feat: added a directive that accepts only digits and special keys
  library/src/lib/time/time.component.html
  library/src/lib/time/time.module.ts
  library/src/lib/utils/directives/only-digits.directive.spec.ts
  library/src/lib/utils/directives/only-digits.directive.ts
Labels: timepicker

#1205 feat: introduce disabled token and fix disabled multi input
  docs/app/documentation/component-docs/multi-input/examples/multi-input-example/multi-input-example.component.html
  docs/app/documentation/component-docs/multi-input/examples/multi-input-example/multi-input-example.component.ts
  library/src/lib/multi-input/multi-input.component.html
  library/src/lib/token/token.component.scss
  library/src/lib/token/token.component.ts
Labels: bug, enhancement

#1206 fix: Datetime picker crash
  library/src/lib/datetime-picker/datetime-picker.component.ts
Labels: datepicker

#1077 feat: added option in combobox to return whole object; added forms example
  docs/app/documentation/component-docs/combobox/combobox-docs.component.html
  docs/app/documentation/component-docs/combobox/combobox-docs.component.ts
  docs/app/documentation/component-docs/combobox/examples/combobox-forms-example.component.html
  docs/app/documentation/component-docs/combobox/examples/combobox-forms-example.component.ts
  docs/app/documentation/documentation.module.ts
  library/src/lib/combobox/combobox.component.spec.ts
  library/src/lib/combobox/combobox.component.ts
Labels: enhancement

#1178 docs: add moment.js example on calendar
  docs/app/documentation/component-docs/calendar/calendar-docs.component.html
  docs/app/documentation/component-docs/calendar/calendar-docs.component.ts
  docs/app/documentation/component-docs/calendar/examples/calendar--i18n-moment-example.component.ts
  docs/app/documentation/documentation.module.ts
  package-lock.json
  package.json
Labels: datepicker

#1215 fix: Added missing components to public apis, add utils public api. Add html exmaples
  library/src/lib/action-bar/action-bar-header/action-bar-header.directive.ts
  library/src/lib/calendar/calendar.component.ts
  library/src/lib/calendar/public_api.ts
  library/src/lib/combobox/combobox.component.ts
  library/src/lib/combobox/public_api.ts
  library/src/lib/date-picker/date-picker.component.ts
  library/src/lib/date-picker/public_api.ts
  library/src/lib/datetime-picker/datetime-picker.component.ts
  library/src/lib/datetime-picker/public_api.ts
  library/src/lib/localizator-editor/localization-editor-item/localization-editor-item.component.ts
  library/src/lib/localizator-editor/public_api.ts
  library/src/lib/mega-menu/mega-menu-group/mega-menu-group.component.ts
  library/src/lib/mega-menu/mega-menu-item/mega-menu-item.component.ts
  library/src/lib/mega-menu/mega-menu-link/mega-menu-link.directive.ts
  library/src/lib/mega-menu/mega-menu-list/mega-menu-list.directive.ts
  library/src/lib/mega-menu/mega-menu-subitem.directive.ts
  library/src/lib/mega-menu/mega-menu-sublink.directive.ts
  library/src/lib/mega-menu/mega-menu.component.ts
  library/src/lib/mega-menu/public_api.ts
  library/src/lib/menu/menu-keyboard.service.ts
  library/src/lib/menu/public_api.ts
  library/src/lib/scroll-spy/public_api.ts
  library/src/lib/search-input/public_api.ts
  library/src/lib/select/public_api.ts
  library/src/lib/shellbar/public_api.ts
  library/src/lib/side-navigation/public_api.ts
  library/src/lib/side-navigation/side-navigation-item/side-navigation-item.component.ts
  library/src/lib/side-navigation/side-navigation-link/side-navigation-link.directive.ts
  library/src/lib/side-navigation/side-navigation-list/side-navigation-list.directive.ts
  library/src/lib/side-navigation/side-navigation-subitem/side-navigation-subitem.directive.ts
  library/src/lib/side-navigation/side-navigation-sublist/side-navigation-sublist.directive.ts
  library/src/lib/tabs/public_api.ts
  library/src/lib/tile/public_api.ts
  library/src/lib/time-picker/public_api.ts
  library/src/lib/time/public_api.ts
  library/src/lib/toggle/public_api.ts
  library/src/lib/token/public_api.ts
  library/src/lib/tree/public_api.ts
  library/src/lib/utils/directives/only-digits.directive.ts
  library/src/lib/utils/public_api.ts
  library/src/public_api.ts
Labels: bug

#1214 fix: Reset input on invalid date
  library/src/lib/date-picker/date-picker.component.ts
Labels: bug, datepicker

#1209 feat: split modal alert service
  docs/app/documentation/utilities/api-files.ts
  library/src/lib/alert/alert-service/alert.service.spec.ts
  library/src/lib/alert/alert-service/alert.service.ts
  library/src/lib/alert/alert-utils/alert-config.ts
  library/src/lib/alert/alert-utils/alert-injector.ts
  library/src/lib/alert/alert.component.spec.ts
  library/src/lib/alert/alert.component.ts
  library/src/lib/alert/public_api.ts
  library/src/lib/modal/modal-header/modal-header.component.spec.ts
  library/src/lib/modal/modal-service/modal.service.spec.ts
  library/src/lib/modal/modal-service/modal.service.ts
  library/src/lib/modal/modal-utils/modal-backdrop.ts
  library/src/lib/modal/modal-utils/modal-config.ts
  library/src/lib/modal/modal-utils/modal-position.ts
  library/src/lib/modal/modal.component.ts
  library/src/lib/modal/modal.module.ts
  library/src/lib/modal/public_api.ts
  library/src/lib/utils/dynamic-component/dynamic-component-config.ts
  library/src/lib/utils/dynamic-component/dynamic-component-injector.ts
  library/src/lib/utils/dynamic-component/dynamic-component.service.ts
Labels: enhancement

#1222 docs: Add example of dynamic height popover body
  docs/app/documentation/component-docs/popover/examples/popover-dynamic/popover-dynamic-example.component.html
  docs/app/documentation/component-docs/popover/examples/popover-dynamic/popover-dynamic-example.component.ts
  docs/app/documentation/component-docs/popover/popover-docs.component.html
  docs/app/documentation/component-docs/popover/popover-docs.component.ts
  docs/app/documentation/documentation.module.ts
Labels: documentation

#1227 chore: Update mergeable.yml
  .github/mergeable.yml
Labels: tooling

#1228 chore: fix gh pages publishing
  package.json
Labels: documentation, tooling

#1224 docs: replaces the occurrence of fd-form__label class with fd-form-label directive
  apps/docs/src/app/documentation/component-docs/input-group/examples/input-group-button-example.component.html
  apps/docs/src/app/documentation/component-docs/input-group/examples/input-group-icon-example.component.html
  apps/docs/src/app/documentation/component-docs/input-group/examples/input-group-text-compact-example.component.html
  apps/docs/src/app/documentation/component-docs/input-group/examples/input-group-text-example.component.html
  libs/core/src/lib/list/list-checkbox.component.html
  libs/core/src/lib/toggle/toggle.component.html
Labels: documentation

#1232 docs: update README.md and schematics to reflect the latest package name
  README.md
  libs/core/schematics/collection.json
Labels: documentation, tooling

#1245 feat:change the way of showing selected items of multi-input selector
  libs/core/src/lib/multi-input/multi-input.component.html
Labels: enhancement

#1301 chore: update release script
  scripts/publish-release.sh
Labels: tooling
