Repository SAP/fundamental-ngx, pull requests merged in 2019-07, with the labels that each got.

#974 feat: Add split button component
  docs/app/documentation/component-docs/button/examples/button-split-example.component.html
  docs/app/documentation/component-docs/split-button/examples/split-button-examples.component.ts
  docs/app/documentation/component-docs/split-button/examples/split-button-examples.scss
  docs/app/documentation/component-docs/split-button/examples/split-button-icons-example.component.html
  docs/app/documentation/component-docs/split-button/examples/split-button-options-example.component.html
  docs/app/documentation/component-docs/split-button/examples/split-button-programmatical-example.component.html
  docs/app/documentation/component-docs/split-button/examples/split-button-template-example.component.html
  docs/app/documentation/component-docs/split-button/examples/split-button-types-example.component.html
  docs/app/documentation/component-docs/split-button/split-button-docs.component.html
  docs/app/documentation/component-docs/split-button/split-button-docs.component.ts
  docs/app/documentation/component-docs/split-button/split-button-header/split-button-header.component.html
  docs/app/documentation/component-docs/split-button/split-button-header/split-button-header.component.scss
  docs/app/documentation/component-docs/split-button/split-button-header/split-button-header.component.ts
  docs/app/documentation/core-helpers/documentation/documentation.component.ts
  docs/app/documentation/documentation.module.ts
  docs/app/documentation/documentation.routes.ts
  docs/app/documentation/utilities/api-files.ts
  library/src/lib/fundamental-ngx.module.ts
  library/src/lib/split-button/index.ts
  library/src/lib/split-button/split-button-utils/split-button.directives.ts
  library/src/lib/split-button/split-button.component.html
  library/src/lib/split-button/split-button.component.spec.ts
  library/src/lib/split-button/split-button.component.ts
  library/src/lib/split-button/split-button.module.ts
  library/src/lib/tabs/tabs.module.ts
Labels: enhancement

#1052 fix: #1051 include timepicker in public_api.ts
  library/src/public_api.ts
Labels: bug

#1053 chore: high security vulnerabilities
  package-lock.json
Labels: security

#1054 chore: security vulnerabilities in library/package
  library/package-lock.json
Labels: security

#1060 chore: update library/package.json version
  library/package-lock.json
  library/package.json
  package-lock.json
  package.json
Labels: security

#1059 fix: Make combobox dropdown trigger unfocusable
  library/src/lib/combobox/combobox.component.html
Labels: bug
