Repository SAP/fundamental-ngx, pull requests merged in 2020-01, with the labels that each got.

#1767 fix: (core:calendar) nextDay() method increasing year when used for date in January
  libs/core/src/lib/calendar/models/fd-date.ts
Labels: datepicker

#1646 fix: (core) Add Additional class to popover component, introduce nested popover example
  apps/docs/src/app/core/component-docs/popover/examples/popover-simple/popover-example.component.html
  apps/docs/src/app/core/component-docs/popover/examples/popover-simple/popover-example.component.ts
  apps/docs/src/app/core/component-docs/popover/popover-docs.component.html
  apps/docs/src/app/core/component-docs/popover/popover-docs.component.ts
  libs/core/src/lib/popover/popover-directive/popover.directive.ts
  libs/core/src/lib/popover/popover.component.html
  libs/core/src/lib/popover/popover.component.ts
Labels: core, v.0.13.0

#1773 fix: Add @angular/cdk to schematics, put more files to public_api.ts (0.12.1)
  libs/core/package.json
  libs/core/schematics/ng-add/index.ts
  libs/core/schematics/ng-add/versions.ts
  libs/core/src/lib/button/public_api.ts
  libs/core/src/lib/localizator-editor/public_api.ts
  libs/core/src/lib/modal/public_api.ts
  libs/core/src/lib/multi-input/public_api.ts
  libs/core/src/lib/notification/public_api.ts
  libs/core/src/lib/pagination/public_api.ts
  libs/core/src/lib/panel/public_api.ts
  libs/core/src/lib/popover/public_api.ts
  libs/core/src/lib/shellbar/public_api.ts
  libs/core/src/lib/split-button/public_api.ts
  libs/core/src/lib/table/public_api.ts
  libs/core/src/lib/tabs/public_api.ts
  libs/core/src/lib/utils/public_api.ts
Labels: v.0.13.0

#1768 fix: (core:Alert) Add new button classes to alert component
  libs/core/src/lib/alert/alert-service/alert.service.spec.ts
  libs/core/src/lib/alert/alert.component.html
  libs/core/src/lib/alert/alert.component.scss
  libs/core/src/lib/alert/alert.component.spec.ts
  libs/core/src/lib/alert/alert.module.ts
Labels: v.0.13.0

#1686 chore: (platofrm) fix read me link
  libs/platform/README.md
Labels: documentation

#1645 docs: (core) Update popover's usage of side nav, add important files of popover to public_api.ts
  apps/docs/src/app/core/component-docs/popover/examples/popover-dynamic/popover-dynamic-example.component.html
  apps/docs/src/app/core/component-docs/popover/examples/popover-dynamic/popover-dynamic-example.component.ts
  apps/docs/src/app/core/component-docs/side-navigation/examples/side-navigation-compact-example.component.html
  apps/docs/src/app/core/component-docs/side-navigation/examples/side-navigation-condensed-example/side-navigation-condensed-example.component.html
  apps/docs/src/app/core/component-docs/side-navigation/examples/side-navigation-condensed-object-example/side-navigation-condensed-object-example.component.ts
  apps/docs/src/app/core/component-docs/side-navigation/examples/side-navigation-example.component.html
  apps/docs/src/app/core/component-docs/side-navigation/examples/side-navigation-icons-example.component.html
  apps/docs/src/app/core/component-docs/side-navigation/examples/side-navigation-multiple-selected-example/side-navigation-multiple-selected-example.component.html
  apps/docs/src/app/core/component-docs/side-navigation/examples/side-navigation-object-example/side-navigation-object-example.component.ts
  apps/docs/src/app/core/component-docs/side-navigation/examples/side-navigation-programmatically-example/side-navigation-programmatically-example.component.html
  apps/docs/src/app/core/component-docs/side-navigation/examples/side-navigation-three-levels-example/side-navigation-three-levels-example.component.html
  apps/docs/src/app/core/component-docs/side-navigation/examples/side-navigation-titles-example.component.html
  apps/docs/src/app/core/component-docs/side-navigation/side-navigation-docs.component.html
  libs/core/src/lib/nested-list/nested-list-popover/nested-list-popover.component.html
  libs/core/src/lib/nested-list/nested-list/nested-list.directive.ts
Labels: core, v.0.13.0

#1774 platform(feat):adding new select with icon and adding documentation for the same
  apps/docs/src/app/platform/component-docs/platform-select/platform-select-docs.component.html
  apps/docs/src/app/platform/component-docs/platform-select/platform-select-docs.component.ts
  apps/docs/src/app/platform/component-docs/platform-select/platform-select-examples/platform-select-types-default-example.component.ts
  apps/docs/src/app/platform/component-docs/platform-select/platform-select-examples/platform-select-types-noborder-example.component.ts
  apps/docs/src/app/platform/component-docs/platform-select/platform-select-examples/platform-select-types-split-example.component.ts
  apps/docs/src/app/platform/component-docs/platform-select/platform-select-examples/platform-select-types-with-icon-example.component.html
  apps/docs/src/app/platform/component-docs/platform-select/platform-select-examples/platform-select-types-with-icon-example.component.ts
  apps/docs/src/app/platform/platform-documentation.module.ts
  libs/platform/src/lib/components/select/select.component.html
  libs/platform/src/lib/components/select/select.component.scss
  libs/platform/src/lib/components/select/select.component.ts
  libs/platform/src/lib/components/select/select.module.ts
Labels: platform

#1783 fix: add ButtonFocusable flag to input-group related components
  libs/core/src/lib/combobox/combobox.component.html
  libs/core/src/lib/combobox/combobox.component.ts
  libs/core/src/lib/date-picker/date-picker.component.html
  libs/core/src/lib/date-picker/date-picker.component.ts
  libs/core/src/lib/datetime-picker/datetime-picker.component.html
  libs/core/src/lib/datetime-picker/datetime-picker.component.ts
  libs/core/src/lib/input-group/input-group.component.ts
  libs/core/src/lib/localizator-editor/localization-editor-main/localization-editor-main.component.html
  libs/core/src/lib/localizator-editor/localization-editor-main/localization-editor-main.component.ts
  libs/core/src/lib/multi-input/multi-input.component.html
  libs/core/src/lib/multi-input/multi-input.component.ts
  libs/core/src/lib/time-picker/time-picker.component.html
  libs/core/src/lib/time-picker/time-picker.component.ts
Labels: v.0.13.0

#1807 feat: added new radio button component
  apps/docs/src/app/core/component-docs/list/examples/list-single-select-example.component.html
  apps/docs/src/app/core/component-docs/radio/examples/radio-example.component.html
  apps/docs/src/app/core/component-docs/radio/examples/radio-examples.component.ts
  apps/docs/src/app/core/component-docs/radio/examples/radio-form-group-example.component.html
  apps/docs/src/app/core/component-docs/radio/examples/radio-form-group-example.component.ts
  libs/core/src/lib/form/form-group/form-group.component.html
  libs/core/src/lib/form/form-group/form-group.component.scss
  libs/core/src/lib/form/form-group/form-group.component.spec.ts
  libs/core/src/lib/form/form-group/form-group.component.ts
  libs/core/src/lib/fundamental-ngx-core.module.ts
  libs/core/src/lib/radio/radio-button/radio-button-reactive-form.component.spec.ts
  libs/core/src/lib/radio/radio-button/radio-button.component.html
  libs/core/src/lib/radio/radio-button/radio-button.component.scss
  libs/core/src/lib/radio/radio-button/radio-button.component.spec.ts
  libs/core/src/lib/radio/radio-button/radio-button.component.ts
  libs/core/src/lib/radio/radio.module.ts
  libs/core/src/lib/utils/decorators/apply-css-class.decorator.ts
  libs/core/src/lib/utils/decorators/apply-css-style.decorator.ts
Labels: v.0.13.0

#1787 fix: (core) Datepicker and DateTimePicker: Respect disabled/block function by inputs
  apps/docs/src/app/core/component-docs/date-picker/date-picker-docs.component.html
  apps/docs/src/app/core/component-docs/date-picker/date-picker-docs.component.ts
  apps/docs/src/app/core/component-docs/date-picker/examples/date-picker-disable-func-example/date-picker-disable-func-example.component.html
  apps/docs/src/app/core/component-docs/date-picker/examples/date-picker-disable-func-example/date-picker-disable-func-example.component.ts
  apps/docs/src/app/core/component-docs/date-picker/examples/date-picker-form-example.component.ts
  apps/docs/src/app/core/component-docs/date-picker/examples/date-picker-form-range-example.component.ts
  apps/docs/src/app/core/component-docs/date-picker/examples/date-picker-range-disabled-example/date-picker-range-disabled-example.component.html
  apps/docs/src/app/core/component-docs/date-picker/examples/date-picker-range-disabled-example/date-picker-range-disabled-example.component.ts
  apps/docs/src/app/core/component-docs/date-picker/examples/date-picker-range-example.component.ts
  apps/docs/src/app/core/component-docs/datetime-picker/datetime-picker-docs.component.html
  apps/docs/src/app/core/component-docs/datetime-picker/examples/datetime-form-example/datetime-form-example.component.html
  apps/docs/src/app/core/component-docs/datetime-picker/examples/datetime-form-example/datetime-form-example.component.ts
  apps/docs/src/app/core/core-documentation.module.ts
  libs/core/src/lib/date-picker/date-picker.component.spec.ts
  libs/core/src/lib/date-picker/date-picker.component.ts
  libs/core/src/lib/datetime-picker/datetime-picker.component.html
  libs/core/src/lib/datetime-picker/datetime-picker.component.spec.ts
  libs/core/src/lib/datetime-picker/datetime-picker.component.ts
Labels: v.0.13.0

#1777 feat: rewrite Checkbox as a separate module | suit to Fiori3
  apps/docs/src/app/core/api-files.ts
  apps/docs/src/app/core/component-docs/checkbox/checkbox-docs.component.html
  apps/docs/src/app/core/component-docs/checkbox/checkbox-docs.component.ts
  apps/docs/src/app/core/component-docs/checkbox/checkbox-header/checkbox-header.component.html
  apps/docs/src/app/core/component-docs/checkbox/checkbox-header/checkbox-header.component.ts
  apps/docs/src/app/core/component-docs/checkbox/examples/checkbox-custom-label-example.component.ts
  apps/docs/src/app/core/component-docs/checkbox/examples/checkbox-custom-values-example.component.ts
  apps/docs/src/app/core/component-docs/checkbox/examples/checkbox-default-example.component.ts
  apps/docs/src/app/core/component-docs/checkbox/examples/checkbox-example.component.html
  apps/docs/src/app/core/component-docs/checkbox/examples/checkbox-examples.component.ts
  apps/docs/src/app/core/component-docs/checkbox/examples/checkbox-form-group-example.component.html
  apps/docs/src/app/core/component-docs/checkbox/examples/checkbox-form-group-example.component.ts
  apps/docs/src/app/core/component-docs/checkbox/examples/checkbox-reactive-forms-example.component.ts
  apps/docs/src/app/core/component-docs/checkbox/examples/checkbox-states-example.component.ts
  apps/docs/src/app/core/component-docs/checkbox/examples/checkbox-tristate-example.component.ts
  apps/docs/src/app/core/component-docs/checkbox/index.ts
  apps/docs/src/app/core/component-docs/list/examples/list-checkbox-example.component.html
  apps/docs/src/app/core/component-docs/list/examples/list-checkbox-form-example.component.html
  apps/docs/src/app/core/core-documentation.module.ts
  apps/docs/src/app/core/core-documentation.routes.ts
  apps/docs/src/app/schema/containers/schema-group/schema-group.component.html
  libs/core/src/lib/checkbox/checkbox.module.ts
  libs/core/src/lib/checkbox/checkbox/checkbox.component.html
  libs/core/src/lib/checkbox/checkbox/checkbox.component.scss
  libs/core/src/lib/checkbox/checkbox/checkbox.component.spec.ts
  libs/core/src/lib/checkbox/checkbox/checkbox.component.ts
  libs/core/src/lib/checkbox/checkbox/fd-checkbox-values.interface.ts
  libs/core/src/lib/form/form-control/form-control.directive.ts
  libs/core/src/lib/fundamental-ngx-core.module.ts
  libs/core/src/lib/multi-input/multi-input.component.html
  libs/core/src/lib/multi-input/multi-input.component.spec.ts
  libs/core/src/lib/multi-input/multi-input.module.ts
  libs/core/src/lib/utils/functions/compare-objects.spec.ts
  libs/core/src/lib/utils/functions/compare-objects.ts
  libs/core/src/lib/utils/functions/index.ts
  libs/core/src/lib/utils/public_api.ts
Labels: v.0.13.0

#1831 fix: (combobox) - reorder event throw
  libs/core/src/lib/combobox/combobox.component.ts
Labels: v.0.13.0

#1828 fix: multi-input 0.13.0 bugs
  libs/core/src/lib/combobox/combobox.component.html
  libs/core/src/lib/multi-input/multi-input.component.html
  libs/core/src/lib/multi-input/multi-input.component.spec.ts
  libs/core/src/lib/multi-input/multi-input.component.ts
  libs/core/src/lib/popover/popover.component.spec.ts
  libs/core/src/lib/popover/popover.component.ts
Labels: v.0.13.0

#1832 fix: change checkbox state update trigger
  apps/docs/src/app/core/component-docs/checkbox/examples/checkbox-states-example.component.ts
  libs/core/src/lib/checkbox/checkbox/checkbox.component.html
  libs/core/src/lib/checkbox/checkbox/checkbox.component.spec.ts
  libs/core/src/lib/checkbox/checkbox/checkbox.component.ts
Labels: v.0.13.0

#1827 feat: form messages adoption from styles 4.0
  apps/docs/src/app/core/api-files.ts
  apps/docs/src/app/core/component-docs/input/examples/input-state-example.component.html
  apps/docs/src/app/core/component-docs/input/input-docs.component.html
  apps/docs/src/app/core/component-docs/textarea/examples/textarea-state-example.component.html
  libs/core/src/lib/form/form-input-message-group/form-input-message-group.component.html
  libs/core/src/lib/form/form-input-message-group/form-input-message-group.component.scss
  libs/core/src/lib/form/form-input-message-group/form-input-message-group.component.spec.ts
  libs/core/src/lib/form/form-input-message-group/form-input-message-group.component.ts
  libs/core/src/lib/form/form-message/form-message.component.html
  libs/core/src/lib/form/form-message/form-message.component.ts
  libs/core/src/lib/form/form.module.ts
  libs/core/src/lib/form/public_api.ts
  libs/core/src/lib/popover/popover.component.html
  libs/core/src/lib/popover/popover.component.ts
Labels: v.0.13.0

#1856 chore: Update mergeable.yml
  .github/mergeable.yml
Labels: tooling

#1855 fix: added missing export
  libs/core/src/index.ts
  libs/core/src/lib/checkbox/public_api.ts
  libs/core/src/lib/radio/public_api.ts
Labels: bug

#1708 docs: fix StackBlitz for SideNav
  apps/docs/src/app/core/component-docs/side-navigation/side-navigation-docs.component.ts
Labels: documentation

#1851 fix: #1841 popover refactoring
  apps/docs/src/app/core/api-files.ts
  apps/docs/src/app/core/component-docs/popover/examples/popover-dynamic/popover-dynamic-example.component.ts
  apps/docs/src/app/core/component-docs/popover/examples/popover-simple/popover-example.component.html
  apps/docs/src/app/core/component-docs/popover/popover-header/popover-header.component.html
  libs/core/src/lib/popover/popover-body/popover-body-directives/popover-body-footer.directive.spec.ts
  libs/core/src/lib/popover/popover-body/popover-body-directives/popover-body-footer.directive.ts
  libs/core/src/lib/popover/popover-body/popover-body-directives/popover-body-header.directive.spec.ts
  libs/core/src/lib/popover/popover-body/popover-body-directives/popover-body-header.directive.ts
  libs/core/src/lib/popover/popover-body/popover-body-directives/popover-body-subheader.directive.spec.ts
  libs/core/src/lib/popover/popover-body/popover-body-directives/popover-body-subheader.directive.ts
  libs/core/src/lib/popover/popover-body/popover-body.component.html
  libs/core/src/lib/popover/popover.module.ts
  libs/core/src/lib/toggle/toggle.component.scss
  package-lock.json
  package.json
Labels: v.0.14.0

#1870 fix: Allow outside click for modal
  libs/core/src/lib/modal/modal.component.ts
Labels: v.0.14.0

#1862 feat: #1845 storybook integration
  .storybook/main.js
  .storybook/tsconfig.json
  .storybook/typings.d.ts
  apps/docs/tsconfig.app.json
  package-lock.json
  package.json
  src/stories/checkbox/fd-checkbox.stories.ts
  src/stories/radio/fd-radio-button.stories.ts
  src/stories/toggle/fd-toggle.stories.ts
Labels: tooling

#1865 chore: add PR date check in mergeable
  .github/mergeable.yml
Labels: tooling

#1880 docs: (core) stackblitz maintenance
  apps/docs/src/app/core/component-docs/alert/alert-docs.component.ts
  apps/docs/src/app/core/component-docs/alert/examples/alert-component-as-content.module.ts
  apps/docs/src/app/core/component-docs/modal/examples/stackable-modals/modal-in-modal-example.module.ts
  apps/docs/src/app/core/component-docs/modal/modal-docs.component.ts
  apps/docs/src/app/documentation/core-helpers/code-example/code-example.component.ts
  apps/docs/src/app/documentation/core-helpers/code-example/example-file.ts
Labels: documentation

#1872 fix: busy-indicator added aria-hidden attribute and a storybook for testing
  libs/core/src/lib/busy-indicator/busy-indicator.component.html
  src/stories/busy-indicator/fd-busy-indicator.stories.ts
Labels: testing, v.0.14.0

#1744 fix: (platform)add missing template reference `categoryDropdown`
  libs/platform/src/lib/components/menu/menu-item.component.spec.ts
  libs/platform/src/lib/components/menu/menu.component.spec.ts
  libs/platform/src/lib/components/search-input/search-input.component.html
  libs/platform/src/lib/components/search-input/search-input.component.spec.ts
Labels: platform
