Repository SAP/fundamental-ngx, pull requests merged in 2020-06, with the labels that each got.

#2511 fix: Create dynamic mobile view for Select component
  apps/docs/src/app/core/component-docs/select/examples/select-mobile-example/select-mobile-example.component.html
  apps/docs/src/app/core/component-docs/select/examples/select-mobile-example/select-mobile-example.component.ts
  apps/docs/src/app/core/component-docs/select/select-docs.component.html
  apps/docs/src/app/core/component-docs/select/select-docs.module.ts
  libs/core/src/lib/dialog/dialog-footer/dialog-footer.component.ts
  libs/core/src/lib/dialog/dialog-header/dialog-header.component.ts
  libs/core/src/lib/dialog/dialog.component.ts
  libs/core/src/lib/select/public_api.ts
  libs/core/src/lib/select/select-mobile.component.spec.ts
  libs/core/src/lib/select/select-mobile/select-mobile.module.ts
  libs/core/src/lib/select/select-mobile/select-mobile/select-mobile.component.html
  libs/core/src/lib/select/select-mobile/select-mobile/select-mobile.component.spec.ts
  libs/core/src/lib/select/select-mobile/select-mobile/select-mobile.component.ts
  libs/core/src/lib/select/select.component.html
  libs/core/src/lib/select/select.component.scss
  libs/core/src/lib/select/select.component.ts
  libs/platform/src/lib/components/select/select.component.ts
Labels: POC, enhancement, v.0.19.0

#2486 fix: Platform wrapper component for info Label with document changes
  apps/docs/src/app/platform/api-files.ts
  apps/docs/src/app/platform/component-docs/platform-info-label/platform-info-label-docs-module.ts
  apps/docs/src/app/platform/component-docs/platform-info-label/platform-info-label-docs.component.html
  apps/docs/src/app/platform/component-docs/platform-info-label/platform-info-label-docs.component.ts
  apps/docs/src/app/platform/component-docs/platform-info-label/platform-info-label-example/platform-info-label-aria-label-example.component.html
  apps/docs/src/app/platform/component-docs/platform-info-label/platform-info-label-example/platform-info-label-example.component.html
  apps/docs/src/app/platform/component-docs/platform-info-label/platform-info-label-example/platform-info-label-example.component.scss
  apps/docs/src/app/platform/component-docs/platform-info-label/platform-info-label-example/platform-info-label-example.component.ts
  apps/docs/src/app/platform/component-docs/platform-info-label/platform-info-label-example/platform-info-label-numeric-example.component.html
  apps/docs/src/app/platform/component-docs/platform-info-label/platform-info-label-example/platform-info-label-text-and-icon-example.component.html
  apps/docs/src/app/platform/component-docs/platform-info-label/platform-info-label-example/platform-info-label-text-example.component.html
  apps/docs/src/app/platform/component-docs/platform-info-label/platform-info-label-header/platform-info-label-header.component.html
  apps/docs/src/app/platform/component-docs/platform-info-label/platform-info-label-header/platform-info-label-header.component.ts
  apps/docs/src/app/platform/documentation/platform-documentation.component.ts
  apps/docs/src/app/platform/platform-documentation.module.ts
  apps/docs/src/app/platform/platform-documentation.routes.ts
  libs/core/src/lib/info-label/info-label.component.ts
  libs/platform/src/index.ts
  libs/platform/src/lib/components/form/public_api.ts
  libs/platform/src/lib/components/info-label/info-label.component.html
  libs/platform/src/lib/components/info-label/info-label.component.spec.ts
  libs/platform/src/lib/components/info-label/info-label.component.ts
  libs/platform/src/lib/components/info-label/info-label.module.ts
  libs/platform/src/lib/components/info-label/public_api.ts
  libs/platform/src/lib/platform.module.ts
Labels: platform

#2490 feat: Side Navigation styles markup adaptation
  apps/docs/src/app/core/component-docs/side-navigation/examples/side-navigation-condensed-example/side-navigation-condensed-example.component.html
  apps/docs/src/app/core/component-docs/side-navigation/examples/side-navigation-icons-example.component.html
  apps/docs/src/app/core/component-docs/side-navigation/examples/side-navigation-multiple-selected-example/side-navigation-multiple-selected-example.component.html
  apps/docs/src/app/core/component-docs/side-navigation/examples/side-navigation-non-selectable-example/side-navigation-non-selectable-example.component.html
  apps/docs/src/app/core/component-docs/side-navigation/examples/side-navigation-non-selectable-example/side-navigation-non-selectable-example.component.ts
  apps/docs/src/app/core/component-docs/side-navigation/examples/side-navigation-programmatically-example/side-navigation-programmatically-example.component.html
  apps/docs/src/app/core/component-docs/side-navigation/examples/side-navigation-three-levels-example/side-navigation-three-levels-example.component.html
  apps/docs/src/app/core/component-docs/side-navigation/side-navigation-docs.component.html
  apps/docs/src/app/core/component-docs/side-navigation/side-navigation-docs.component.ts
  apps/docs/src/app/core/component-docs/side-navigation/side-navigation-docs.module.ts
  apps/docs/src/app/core/component-docs/side-navigation/side-navigation-header/side-navigation-header.component.html
  libs/core/package-lock.json
  libs/core/src/lib/nested-list/nested-content/nested-list-content.directive.spec.ts
  libs/core/src/lib/nested-list/nested-content/nested-list-content.directive.ts
  libs/core/src/lib/nested-list/nested-item/nested-item.directive.spec.ts
  libs/core/src/lib/nested-list/nested-item/nested-item.directive.ts
  libs/core/src/lib/nested-list/nested-item/nested-item.interface.ts
  libs/core/src/lib/nested-list/nested-item/nested-item.service.ts
  libs/core/src/lib/nested-list/nested-link/nested-link.directive.spec.ts
  libs/core/src/lib/nested-list/nested-link/nested-link.directive.ts
  libs/core/src/lib/nested-list/nested-list-directives.spec.ts
  libs/core/src/lib/nested-list/nested-list-directives.ts
  libs/core/src/lib/nested-list/nested-list-keyboard.service.spec.ts
  libs/core/src/lib/nested-list/nested-list-keyboard.service.ts
  libs/core/src/lib/nested-list/nested-list-popover/nested-list-popover.component.html
  libs/core/src/lib/nested-list/nested-list-popover/nested-list-popover.component.scss
  libs/core/src/lib/nested-list/nested-list-popover/nested-list-popover.component.ts
  libs/core/src/lib/nested-list/nested-list-state.service.ts
  libs/core/src/lib/nested-list/nested-list.module.ts
  libs/core/src/lib/nested-list/nested-list/nested-list.directive.spec.ts
  libs/core/src/lib/nested-list/nested-list/nested-list.directive.ts
  libs/core/src/lib/nested-list/nested-list/nested-list.interface.ts
  libs/core/src/lib/nested-list/prepared-nested-list/prepared-nested-list.component.html
  libs/core/src/lib/nested-list/prepared-nested-list/prepared-nested-list.component.ts
  libs/core/src/lib/select/select.component.spec.ts
  libs/core/src/lib/side-navigation/side-navigation.component.scss
  libs/core/src/lib/side-navigation/side-navigation.component.spec.ts
  libs/core/src/lib/side-navigation/side-navigation.component.ts
  package-lock.json
  package.json
Labels: v.0.19.0

#2592 fix: Use KeyUtil in MenuKeyboardService
  libs/core/src/lib/menu/menu-keyboard.service.spec.ts
  libs/core/src/lib/menu/menu-keyboard.service.ts
Labels: bug, core

#2578 fix: checkbox crashing chrome fix and unit tests
  libs/core/src/lib/breadcrumb/breadcrumb.component.spec.ts
  libs/core/src/lib/checkbox/checkbox/checkbox.component.html
  libs/core/src/lib/checkbox/checkbox/checkbox.component.spec.ts
  libs/core/src/lib/checkbox/checkbox/checkbox.component.ts
  libs/core/src/lib/token/tokenizer.component.spec.ts
  libs/core/src/lib/utils/tests/when-stable.ts
Labels: bug, v.0.19.0

#2604 fix: checkbox for reverted
  libs/core/src/lib/checkbox/checkbox/checkbox.component.html
  libs/core/src/lib/checkbox/checkbox/checkbox.component.ts
Labels: bug

#2605 fix: Add 0.8.1 Css to time component
  libs/core/src/lib/time/time.component.scss
Labels: v.0.19.0

#2606 fix: enable :empty selector on checkbox
  libs/core/src/lib/checkbox/checkbox/checkbox.component.html
Labels: v.0.19.0

#2603 fix(platform): Split menu button Rtl fix, Accessibility and documentation updated
  apps/docs/src/app/platform/component-docs/platform-split-menu-button/platform-split-menu-button-examples/platform-split-menu-button-examples.component.html
  apps/docs/src/app/platform/component-docs/platform-split-menu-button/platform-split-menu-button-examples/platform-split-menu-button-options.component.html
  apps/docs/src/app/platform/component-docs/platform-split-menu-button/platform-split-menu-button-header/platform-split-menu-button-header.component.html
  apps/docs/src/app/platform/component-docs/platform-split-menu-button/platform-split-menu-button.component.html
  libs/platform/src/index.ts
  libs/platform/src/lib/components/split-menu-button/split-menu-button.component.html
  libs/platform/src/lib/components/split-menu-button/split-menu-button.component.ts
Labels: platform

#2609 fix: Provide way to put placement to shellbar product menu
  apps/docs/src/app/core/component-docs/shellbar/shellbar-docs.component.html
  libs/core/src/lib/shellbar/product-menu/product-menu.component.html
  libs/core/src/lib/shellbar/shellbar-actions/shellbar-actions.component.html
  libs/core/src/lib/shellbar/user-menu/shellbar-user-menu.component.html
Labels: shell-bar, v.0.19.0

#2646 docs: exp has been changed fix
  apps/docs/src/app/core/documentation/core-documentation.component.html
  apps/docs/src/app/core/documentation/core-documentation.component.ts
  apps/docs/src/app/documentation/core-helpers/sections-toolbar/sections-toolbar.component.html
  apps/docs/src/app/documentation/core-helpers/sections-toolbar/sections-toolbar.component.ts
  apps/docs/src/app/documentation/documentation-base.component.ts
  apps/docs/src/app/platform/documentation/platform-documentation.component.html
  apps/docs/src/app/platform/documentation/platform-documentation.component.ts
Labels: documentation, v.0.19.0

#2638 chore: Add fixes to stackblitz examples
  apps/docs/src/app/core/component-docs/action-bar/action-bar-docs.component.ts
  apps/docs/src/app/core/component-docs/calendar/calendar-docs.component.ts
  apps/docs/src/app/core/component-docs/checkbox/checkbox-docs.component.ts
  apps/docs/src/app/core/component-docs/date-picker/date-picker-docs.component.ts
  apps/docs/src/app/core/component-docs/segmented-button/segmented-button-docs.component.ts
Labels: bug, stackblitz

#2656 fix: Failing tests on checkbox and switch
  libs/core/src/lib/checkbox/checkbox/checkbox.component.spec.ts
  libs/core/src/lib/switch/switch.component.spec.ts
Labels: testing

#2654 fix: update pagination class name
  libs/core/src/lib/pagination/pagination.component.html
Labels: bug

#2294 feat: (platform) Fixing Menu/SearchField styles after fundamental-style upgrade
  apps/docs/src/app/platform/component-docs/platform-search-field/platform-search-field-examples/platform-search-field-basic-example.component.html
  apps/docs/src/app/platform/component-docs/platform-search-field/platform-search-field-examples/platform-search-field-categories-example.component.html
  apps/docs/src/app/platform/component-docs/platform-search-field/platform-search-field-header/platform-search-field-header.component.html
  libs/platform/src/lib/components/button/button.component.scss
  libs/platform/src/lib/components/menu/menu-item.component.scss
  libs/platform/src/lib/components/menu/menu-item.component.ts
  libs/platform/src/lib/components/menu/menu.component.scss
  libs/platform/src/lib/components/search-field/search-field.component.html
  libs/platform/src/lib/components/search-field/search-field.component.scss
  libs/platform/src/lib/components/search-field/search-field.component.spec.ts
  libs/platform/src/lib/components/search-field/search-field.component.ts
Labels: platform

#2640 docs: change versioning
  libs/core/README.md
Labels: documentation

#2607 fix: Fix initially open popover, change example on popover with side nav
  apps/docs/src/app/core/component-docs/popover/examples/popover-dynamic/popover-dynamic-example.component.html
  libs/core/src/lib/popover/popover-directive/popover.directive.ts
Labels: v.0.19.0

#2678 docs: fix overflowing header on landscape calendar mobile view
  apps/docs/src/app/core/component-docs/calendar/examples/calendar-mobile-example/calendar-mobile-example.component.ts
Labels: documentation

#2293 fix: (platform) Introduce Checkbox as a Component
  apps/docs/src/app/platform/api-files.ts
  apps/docs/src/app/platform/component-docs/platform-forms/checkbox/platform-checkbox-docs.component.html
  apps/docs/src/app/platform/component-docs/platform-forms/checkbox/platform-checkbox-docs.component.ts
  apps/docs/src/app/platform/component-docs/platform-forms/checkbox/platform-checkbox-docs.module.ts
  apps/docs/src/app/platform/component-docs/platform-forms/checkbox/platform-checkbox-examples/platform-binary-checkbox-no-form.component.html
  apps/docs/src/app/platform/component-docs/platform-forms/checkbox/platform-checkbox-examples/platform-binary-checkbox-no-form.component.ts
  apps/docs/src/app/platform/component-docs/platform-forms/checkbox/platform-checkbox-examples/platform-binary-checkbox.component.html
  apps/docs/src/app/platform/component-docs/platform-forms/checkbox/platform-checkbox-examples/platform-binary-checkbox.component.ts
  apps/docs/src/app/platform/component-docs/platform-forms/checkbox/platform-checkbox-examples/platform-checkbox-error-handling.component.html
  apps/docs/src/app/platform/component-docs/platform-forms/checkbox/platform-checkbox-examples/platform-checkbox-error-handling.component.ts
  apps/docs/src/app/platform/component-docs/platform-forms/checkbox/platform-checkbox-examples/platform-multiselect-checkbox.component.html
  apps/docs/src/app/platform/component-docs/platform-forms/checkbox/platform-checkbox-examples/platform-multiselect-checkbox.component.ts
  apps/docs/src/app/platform/component-docs/platform-forms/checkbox/platform-checkbox-examples/platform-tristate-checkbox.component.html
  apps/docs/src/app/platform/component-docs/platform-forms/checkbox/platform-checkbox-examples/platform-tristate-checkbox.component.ts
  apps/docs/src/app/platform/component-docs/platform-forms/checkbox/platform-checkbox-header/platform-checkbox-header.component.html
  apps/docs/src/app/platform/component-docs/platform-forms/checkbox/platform-checkbox-header/platform-checkbox-header.component.ts
  apps/docs/src/app/platform/documentation/platform-documentation.component.ts
  apps/docs/src/app/platform/platform-documentation.module.ts
  apps/docs/src/app/platform/platform-documentation.routes.ts
  libs/platform/src/lib/components/form/checkbox/checkbox.component.html
  libs/platform/src/lib/components/form/checkbox/checkbox.component.spec.ts
  libs/platform/src/lib/components/form/checkbox/checkbox.component.ts
  libs/platform/src/lib/components/form/checkbox/checkbox.module.ts
  libs/platform/src/lib/components/form/form-group/form-group.component.ts
  libs/platform/src/lib/components/form/public_api.ts
  libs/platform/src/lib/platform.module.ts
Labels: platform

#2673 fix: Fix failing Switch test
  libs/core/src/lib/radio/radio-button/radio-button-reactive-form.component.spec.ts
  libs/core/src/lib/switch/switch.component.spec.ts
Labels: testing

#2676 fix: Stop propagating clicks from nested icon
  libs/core/src/lib/nested-list/nested-item/nested-item.directive.spec.ts
  libs/core/src/lib/nested-list/nested-list-directives.spec.ts
  libs/core/src/lib/nested-list/nested-list-directives.ts
Labels: v.0.19.0

#2677 fix: Bring IE11 support for tristate on checkbox
  libs/core/src/lib/checkbox/checkbox/checkbox.component.html
  libs/core/src/lib/checkbox/checkbox/checkbox.component.ts
Labels: v.0.19.0

#2700 test: uncomment accidentally commented out tests for Date Picker
  libs/core/src/lib/date-picker/date-picker.component.spec.ts
Labels: testing

#2699 test: Remove click event testing on native radio/checkbox input elements
  libs/core/src/lib/checkbox/checkbox/checkbox.component.spec.ts
  libs/core/src/lib/radio/radio-button/radio-button.component.spec.ts
  libs/core/src/lib/switch/switch.component.spec.ts
Labels: v.0.19.0

#2698 fix: bring old list css
  libs/core/src/lib/list/list.component.scss
Labels: v.0.19.0

#2642 fix: Add support for focus/trigger on breadcrumb overflow indicator
  libs/core/src/lib/breadcrumb/breadcrumb.component.html
  libs/core/src/lib/breadcrumb/breadcrumb.component.ts
Labels: v.0.19.0

#2696 fix: remove circular dependency on mobile modes
  libs/core/src/lib/multi-input/multi-input-mobile/multi-input-mobile.component.spec.ts
  libs/core/src/lib/multi-input/multi-input-mobile/multi-input-mobile.component.ts
  libs/core/src/lib/multi-input/multi-input.component.ts
  libs/core/src/lib/multi-input/multi-input.interface.ts
  libs/core/src/lib/select/select-mobile/select-mobile/select-mobile.component.ts
  libs/core/src/lib/select/select.component.ts
  libs/core/src/lib/select/select.interface.ts
Labels: v.0.19.0

#2695 fix: Fix sizing of mobile mode multi input, fix dialog components configuration passing
  libs/core/src/lib/dialog/dialog.component.ts
  libs/core/src/lib/multi-input/multi-input-mobile/multi-input-mobile.component.html
  libs/core/src/lib/multi-input/multi-input-mobile/multi-input-mobile.component.scss
Labels: v.0.19.0

#2447 fix: combobox click autocomplete
  apps/docs/src/app/core/component-docs/combobox/combobox-docs.component.html
  apps/docs/src/app/core/component-docs/combobox/examples/combobox-columns-example.component.html
  apps/docs/src/app/core/component-docs/combobox/examples/combobox-displaywith-example.component.html
  apps/docs/src/app/core/component-docs/combobox/examples/combobox-dynamic-example.component.html
  apps/docs/src/app/core/component-docs/combobox/examples/combobox-dynamic-example.component.ts
  apps/docs/src/app/core/component-docs/combobox/examples/combobox-example.component.html
  apps/docs/src/app/core/component-docs/combobox/examples/combobox-example.component.ts
  apps/docs/src/app/core/component-docs/combobox/examples/combobox-forms-example.component.ts
  apps/docs/src/app/core/component-docs/combobox/examples/combobox-group-example.component.html
  apps/docs/src/app/core/component-docs/combobox/examples/combobox-open-control-example.component.html
  apps/docs/src/app/core/component-docs/combobox/examples/combobox-open-control-example.component.ts
  apps/docs/src/app/core/component-docs/combobox/examples/combobox-template-example.component.html
  apps/docs/src/app/core/component-docs/combobox/examples/combobox-template-example.component.ts
  libs/core/src/lib/combobox/auto-complete.directive.spec.ts
  libs/core/src/lib/combobox/auto-complete.directive.ts
  libs/core/src/lib/combobox/combobox.component.html
  libs/core/src/lib/combobox/combobox.component.spec.ts
  libs/core/src/lib/combobox/combobox.component.ts
  libs/core/src/lib/combobox/combobox.module.ts
  libs/core/src/lib/input-group/input-group-directives.ts
  libs/core/src/lib/input-group/input-group.component.html
  libs/core/src/lib/input-group/input-group.component.ts
  libs/core/src/lib/utils/functions/key-util.ts
  libs/platform/src/lib/components/form/combo-box/combo-box.component.html
Labels: bug, v.0.19.0

#2690 chore: bump theming package
  package-lock.json
  package.json
Labels: theming

#2689 feat: Remove button options
  apps/docs/src/app/core/component-docs/popover/examples/popover-complex-example/popover-complex-example.component.html
  apps/docs/src/app/core/component-docs/popover/popover-docs.component.html
  apps/docs/src/app/documentation/core-helpers/api/api.component.html
  apps/docs/src/app/platform/component-docs/platform-button/platform-button-docs.component.html
  libs/core/src/lib/button/button.component.ts
  libs/core/src/lib/split-button/split-button.component.html
  libs/core/src/lib/split-button/split-button.component.ts
  src/stories/notification/notification.stories.ts
Labels: core, enhancement, v.0.19.0

#2697 fix: focus over loading Busy Indicators on IE11
  libs/core/src/lib/busy-indicator/busy-indicator.component.html
  libs/core/src/lib/busy-indicator/busy-indicator.component.scss
Labels: bug, v.0.19.0

#2703 docs: fix theme selector
  apps/docs/src/app/documentation/core-helpers/toolbar/toolbar.component.ts
Labels: bug, documentation

#2708 fix: Remove max-width limits from dropdown
  libs/core/src/lib/list/list.component.scss
Labels: v.0.19.0

#2706 docs: Fix notification API content
  apps/docs/src/app/core/component-docs/notification/notification-docs.module.ts
Labels: documentation, v.0.19.0

#2649 test: (platform) Adding tests for FormGroup/FormField and fixing tests for ActionBar and RadioGroup
  apps/docs/src/fd-typedoc/helpers/main.helpers.js
  libs/platform/src/lib/components/action-bar/action-bar.component.spec.ts
  libs/platform/src/lib/components/form/collection-base.input.ts
  libs/platform/src/lib/components/form/form.spec.ts
  libs/platform/src/lib/components/form/radio-group/radio-group.component.spec.ts
Labels: platform

#2707 fix: Menu circular dependency
  libs/core/src/lib/menu/menu-mobile/menu-mobile.component.ts
  libs/core/src/lib/menu/menu.component.ts
  libs/core/src/lib/menu/menu.interface.ts
  libs/core/src/lib/multi-input/multi-input.component.ts
  libs/core/src/lib/select/select.component.ts
Labels: bug, core, v.0.19.0

#2712 fix(core) Localization editor using list instead of menu
  libs/core/src/lib/localizator-editor/localization-editor.component.html
  libs/core/src/lib/localizator-editor/localization-editor.component.spec.ts
  libs/core/src/lib/localizator-editor/localization-editor.module.ts
Labels: bug, v.0.19.0

#2710 Fix panel expanded binding
  libs/core/src/lib/panel/panel-expand/panel-expand.component.spec.ts
  libs/core/src/lib/panel/panel-expand/panel-expand.component.ts
  libs/core/src/lib/panel/panel.component.spec.ts
  libs/core/src/lib/panel/panel.component.ts
  libs/core/src/lib/panel/panel.service.ts
Labels: core, v.0.19.0

#2715 fix: fixed docs and restored old tile styles
  apps/docs/src/app/core/component-docs/table/table-docs.component.scss
  apps/docs/src/app/documentation/core-helpers/component-example/component-example.component.scss
  apps/docs/src/app/documentation/core-helpers/component-example/component-example.component.ts
  apps/docs/src/app/documentation/core-helpers/example-background/example-background.component.ts
  apps/docs/src/styles.scss
  libs/core/src/lib/tile/tile.component.scss
Labels: bug

#2702 fix: add Panel component improvements
  apps/docs/src/app/core/component-docs/panel/examples/panel-compact-example.component.html
  apps/docs/src/app/core/component-docs/panel/examples/panel-expandable-example.component.html
  apps/docs/src/app/core/component-docs/panel/examples/panel-fixed-example.component.html
  apps/docs/src/app/core/component-docs/panel/examples/panel-fixed-height-example.component.html
  libs/core/src/lib/panel/panel-expand/panel-expand.component.spec.ts
  libs/core/src/lib/panel/panel-expand/panel-expand.component.ts
  libs/core/src/lib/panel/panel.component.spec.ts
  libs/core/src/lib/panel/panel.component.ts
  libs/core/src/lib/panel/panel.service.ts
Labels: code refactoring

#2716 chore: bump angular versions
  package-lock.json
  package.json
Labels: dependencies, v.0.19.0

#2717 docs: fix docs tile background
  apps/docs/src/app/documentation/core-helpers/component-example/component-example.component.scss
Labels: documentation

#2718 docs: platform docs cleanup
  apps/docs/src/app/platform/component-docs/platform-button/platform-button-docs.component.html
  apps/docs/src/app/platform/component-docs/platform-button/platform-button-header/platform-button-header.component.html
  apps/docs/src/app/platform/component-docs/platform-forms/checkbox/platform-checkbox-header/platform-checkbox-header.component.html
  apps/docs/src/app/platform/component-docs/platform-info-label/platform-info-label-header/platform-info-label-header.component.html
  apps/docs/src/app/platform/component-docs/platform-split-menu-button/platform-split-menu-button-header/platform-split-menu-button-header.component.html
  libs/platform/src/lib/components/form/checkbox/checkbox.component.ts
Labels: documentation

#2619 feat(select): Complete refactoring based on material common behavior
  .travis.yml
  apps/docs/src/app/core/component-docs/select/examples/select-adding-example/select-adding-example.component.html
  apps/docs/src/app/core/component-docs/select/examples/select-custom-trigger/select-custom-trigger.component.html
  apps/docs/src/app/core/component-docs/select/examples/select-custom-trigger/select-custom-trigger.component.scss
  apps/docs/src/app/core/component-docs/select/examples/select-forms/select-forms.component.html
  apps/docs/src/app/core/component-docs/select/examples/select-forms/select-forms.component.ts
  apps/docs/src/app/core/component-docs/select/examples/select-height/select-max-height-example.component.html
  apps/docs/src/app/core/component-docs/select/examples/select-height/select-max-height-example.component.ts
  apps/docs/src/app/core/component-docs/select/examples/select-mobile-example/select-mobile-example.component.html
  apps/docs/src/app/core/component-docs/select/examples/select-mode-example/select-mode-example.component.html
  apps/docs/src/app/core/component-docs/select/examples/select-nested-options/select-nested-options.component.html
  apps/docs/src/app/core/component-docs/select/examples/select-nested-options/select-nested-options.component.ts
  apps/docs/src/app/core/component-docs/select/examples/select-programmatic-example/select-programmatic-example.component.html
  apps/docs/src/app/core/component-docs/select/examples/select-programmatic-example/select-programmatic-example.component.ts
  apps/docs/src/app/core/component-docs/select/examples/select-semantic-state-example/select-semantic-state-example.component.html
  apps/docs/src/app/core/component-docs/select/select-docs.component.html
  apps/docs/src/app/core/component-docs/select/select-docs.component.ts
  apps/docs/src/app/core/component-docs/select/select-docs.module.ts
  apps/docs/src/app/core/component-docs/select/select-header/select-header.component.html
  apps/docs/src/app/documentation/core-helpers/playground/playground.component.ts
  apps/docs/src/app/platform/api-files.ts
  apps/docs/src/app/platform/component-docs/platform-select/platform-select-docs.component.html
  apps/docs/src/app/platform/component-docs/platform-select/platform-select-docs.component.ts
  apps/docs/src/app/platform/component-docs/platform-select/platform-select-examples/platform-select-types-default-example.component.html
  apps/docs/src/app/platform/component-docs/platform-select/platform-select-examples/platform-select-types-default-example.component.ts
  apps/docs/src/app/platform/component-docs/platform-select/platform-select-examples/platform-select-types-noborder-example.component.html
  apps/docs/src/app/platform/component-docs/platform-select/platform-select-examples/platform-select-types-noborder-example.component.ts
  apps/docs/src/app/platform/component-docs/platform-select/platform-select-examples/platform-select-types-split-example.component.html
  apps/docs/src/app/platform/component-docs/platform-select/platform-select-examples/platform-select-types-split-example.component.ts
  apps/docs/src/app/platform/component-docs/platform-select/platform-select-examples/platform-select-types-with-icon-example.component.html
  apps/docs/src/app/platform/component-docs/platform-select/platform-select-examples/platform-select-types-with-icon-example.component.ts
  apps/docs/src/app/platform/component-docs/platform-select/platform-select-header/platform-select-header.component.html
  apps/docs/src/app/platform/component-docs/platform-select/platform-select-header/platform-select-header.component.scss
  apps/docs/src/app/platform/component-docs/platform-select/platform-select-header/platform-select-header.component.ts
  apps/docs/src/app/platform/component-docs/platform-select/platform-select.module.ts
  apps/docs/src/app/platform/platform-documentation.routes.ts
  libs/core/src/lib/select/commons/select-commons.ts
  libs/core/src/lib/select/option/option.component.spec.ts
  libs/core/src/lib/select/option/option.component.ts
  libs/core/src/lib/select/public_api.ts
  libs/core/src/lib/select/select-mobile/select-mobile.module.ts
  libs/core/src/lib/select/select-mobile/select-mobile/select-mobile.component.html
  libs/core/src/lib/select/select-mobile/select-mobile/select-mobile.component.spec.ts
  libs/core/src/lib/select/select-mobile/select-mobile/select-mobile.component.ts
  libs/core/src/lib/select/select-proxy.service.ts
  libs/core/src/lib/select/select.component.html
  libs/core/src/lib/select/select.component.scss
  libs/core/src/lib/select/select.component.spec.ts
  libs/core/src/lib/select/select.component.ts
  libs/core/src/lib/select/select.interface.ts
  libs/core/src/lib/select/select.module.ts
  libs/core/src/lib/utils/functions/key-util.ts
  libs/platform/src/index.ts
  libs/platform/src/lib/components/select/public_api.ts
  libs/platform/src/lib/components/select/select.component.html
  libs/platform/src/lib/components/select/select.component.scss
  libs/platform/src/lib/components/select/select.component.spec.ts
  libs/platform/src/lib/components/select/select.component.ts
  libs/platform/src/lib/components/select/select.module.ts
  libs/platform/src/lib/platform.module.ts
Labels: code refactoring, v.0.20.0

#2738 fix: manually remove 1.0.0-rc.0
  CHANGELOG.md
  package-lock.json
  package.json
Labels: tooling

#2745 docs: format button example
  apps/docs/src/app/core/component-docs/button/button-docs.module.ts
Labels: documentation

#2746 test: commend randomly failing test
  libs/core/src/lib/radio/radio-button/radio-button-reactive-form.component.spec.ts
Labels: testing

#2748 chore: bump semantic version to 8
  package-lock.json
  package.json
Labels: dependencies, tooling

#2728 fix: replace datepicker icon
  libs/core/src/lib/date-picker/date-picker.component.html
Labels: code refactoring, datepicker

#2652 docs: fiori 3 table pagination
  apps/docs/src/app/core/component-docs/table/examples/table-pagination-example.component.html
  apps/docs/src/app/core/component-docs/table/examples/table-pagination-example.component.ts
  apps/docs/src/app/core/component-docs/table/table-docs.component.html
  apps/docs/src/app/core/component-docs/table/table-docs.component.ts
  apps/docs/src/app/core/component-docs/table/table-docs.module.ts
Labels: documentation, table

#2744 feat(select): Complete refactoring based on material common behavior
  .travis.yml
  apps/docs/src/app/core/component-docs/select/examples/select-adding-example/select-adding-example.component.html
  apps/docs/src/app/core/component-docs/select/examples/select-custom-trigger/select-custom-trigger.component.html
  apps/docs/src/app/core/component-docs/select/examples/select-custom-trigger/select-custom-trigger.component.scss
  apps/docs/src/app/core/component-docs/select/examples/select-forms/select-forms.component.html
  apps/docs/src/app/core/component-docs/select/examples/select-forms/select-forms.component.ts
  apps/docs/src/app/core/component-docs/select/examples/select-height/select-max-height-example.component.html
  apps/docs/src/app/core/component-docs/select/examples/select-height/select-max-height-example.component.ts
  apps/docs/src/app/core/component-docs/select/examples/select-mobile-example/select-mobile-example.component.html
  apps/docs/src/app/core/component-docs/select/examples/select-mode-example/select-mode-example.component.html
  apps/docs/src/app/core/component-docs/select/examples/select-nested-options/select-nested-options.component.html
  apps/docs/src/app/core/component-docs/select/examples/select-nested-options/select-nested-options.component.ts
  apps/docs/src/app/core/component-docs/select/examples/select-programmatic-example/select-programmatic-example.component.html
  apps/docs/src/app/core/component-docs/select/examples/select-programmatic-example/select-programmatic-example.component.ts
  apps/docs/src/app/core/component-docs/select/examples/select-semantic-state-example/select-semantic-state-example.component.html
  apps/docs/src/app/core/component-docs/select/select-docs.component.html
  apps/docs/src/app/core/component-docs/select/select-docs.component.ts
  apps/docs/src/app/core/component-docs/select/select-docs.module.ts
  apps/docs/src/app/core/component-docs/select/select-header/select-header.component.html
  apps/docs/src/app/documentation/core-helpers/playground/playground.component.ts
  apps/docs/src/app/platform/api-files.ts
  apps/docs/src/app/platform/component-docs/platform-select/platform-select-docs.component.html
  apps/docs/src/app/platform/component-docs/platform-select/platform-select-docs.component.ts
  apps/docs/src/app/platform/component-docs/platform-select/platform-select-examples/platform-select-types-default-example.component.html
  apps/docs/src/app/platform/component-docs/platform-select/platform-select-examples/platform-select-types-default-example.component.ts
  apps/docs/src/app/platform/component-docs/platform-select/platform-select-examples/platform-select-types-noborder-example.component.html
  apps/docs/src/app/platform/component-docs/platform-select/platform-select-examples/platform-select-types-noborder-example.component.ts
  apps/docs/src/app/platform/component-docs/platform-select/platform-select-examples/platform-select-types-split-example.component.html
  apps/docs/src/app/platform/component-docs/platform-select/platform-select-examples/platform-select-types-split-example.component.ts
  apps/docs/src/app/platform/component-docs/platform-select/platform-select-examples/platform-select-types-with-icon-example.component.html
  apps/docs/src/app/platform/component-docs/platform-select/platform-select-examples/platform-select-types-with-icon-example.component.ts
  apps/docs/src/app/platform/component-docs/platform-select/platform-select-header/platform-select-header.component.html
  apps/docs/src/app/platform/component-docs/platform-select/platform-select-header/platform-select-header.component.scss
  apps/docs/src/app/platform/component-docs/platform-select/platform-select-header/platform-select-header.component.ts
  apps/docs/src/app/platform/component-docs/platform-select/platform-select.module.ts
  apps/docs/src/app/platform/platform-documentation.routes.ts
  libs/core/src/lib/select/commons/select-commons.ts
  libs/core/src/lib/select/option/option.component.spec.ts
  libs/core/src/lib/select/option/option.component.ts
  libs/core/src/lib/select/public_api.ts
  libs/core/src/lib/select/select-mobile/select-mobile.module.ts
  libs/core/src/lib/select/select-mobile/select-mobile/select-mobile.component.html
  libs/core/src/lib/select/select-mobile/select-mobile/select-mobile.component.spec.ts
  libs/core/src/lib/select/select-mobile/select-mobile/select-mobile.component.ts
  libs/core/src/lib/select/select-proxy.service.ts
  libs/core/src/lib/select/select.component.html
  libs/core/src/lib/select/select.component.scss
  libs/core/src/lib/select/select.component.spec.ts
  libs/core/src/lib/select/select.component.ts
  libs/core/src/lib/select/select.interface.ts
  libs/core/src/lib/select/select.module.ts
  libs/core/src/lib/utils/functions/key-util.ts
  libs/platform/src/index.ts
  libs/platform/src/lib/components/select/public_api.ts
  libs/platform/src/lib/components/select/select.component.html
  libs/platform/src/lib/components/select/select.component.scss
  libs/platform/src/lib/components/select/select.component.spec.ts
  libs/platform/src/lib/components/select/select.component.ts
  libs/platform/src/lib/components/select/select.module.ts
  libs/platform/src/lib/platform.module.ts
Labels: code refactoring

#2735 fix: replace hardcoded colors in Product switch with theme variables
  apps/docs/src/app/documentation/core-helpers/toolbar/toolbar.component.scss
  libs/core/src/lib/product-switch/product-switch-body/product-switch-body.component.scss
Labels: code refactoring

#2732 fix: Resolve menu declaration order issue
  libs/core/src/lib/menu/menu-item/menu-item.component.ts
Labels: bug, core, v.0.19.0

#2737 fix: pagination layout and dot hover issues
  libs/core/src/lib/pagination/pagination.component.html
Labels: bug

#2719 fix: simplify Panel's implementation
  apps/docs/src/app/core/component-docs/panel/examples/panel-compact-example.component.html
  apps/docs/src/app/core/component-docs/panel/examples/panel-expandable-example.component.html
  apps/docs/src/app/core/component-docs/panel/examples/panel-fixed-example.component.html
  apps/docs/src/app/core/component-docs/panel/examples/panel-fixed-height-example.component.html
  libs/core/src/lib/panel/panel-expand/panel-expand.component.html
  libs/core/src/lib/panel/panel-expand/panel-expand.component.spec.ts
  libs/core/src/lib/panel/panel-expand/panel-expand.component.ts
  libs/core/src/lib/panel/panel-header/panel-header.component.html
  libs/core/src/lib/panel/panel-header/panel-header.component.spec.ts
  libs/core/src/lib/panel/panel-header/panel-header.component.ts
  libs/core/src/lib/panel/panel.component.html
  libs/core/src/lib/panel/panel.component.spec.ts
  libs/core/src/lib/panel/panel.component.ts
  libs/core/src/lib/panel/panel.module.ts
  libs/core/src/lib/panel/panel.service.spec.ts
  libs/core/src/lib/panel/panel.service.ts
  libs/core/src/lib/panel/public_api.ts
Labels: code refactoring, core

#2756 fix: super call error when using NotificationComponent
  libs/core/src/lib/notification/notification/notification.component.ts
Labels: core

#2575 fix: only display "show all" text when options have been filtered
  apps/docs/src/app/core/component-docs/multi-input/examples/multi-input-compact-example/multi-input-compact-example.component.ts
  apps/docs/src/app/core/component-docs/multi-input/examples/multi-input-example/multi-input-example.component.ts
  libs/core/src/lib/multi-input/multi-input.component.html
  libs/core/src/lib/multi-input/multi-input.component.spec.ts
  libs/core/src/lib/multi-input/multi-input.component.ts
  libs/core/src/lib/token/tokenizer.component.html
  libs/core/src/lib/token/tokenizer.component.spec.ts
  libs/core/src/lib/token/tokenizer.component.ts
Labels: bug

#2657 feat: introduce toolbar component
  apps/docs/src/app/core/api-files.ts
  apps/docs/src/app/core/component-docs/toolbar/examples/toolbar-example.component.ts
  apps/docs/src/app/core/component-docs/toolbar/examples/toolbar-overflow-example.component.html
  apps/docs/src/app/core/component-docs/toolbar/examples/toolbar-separator-example.component.html
  apps/docs/src/app/core/component-docs/toolbar/examples/toolbar-size-example.component.html
  apps/docs/src/app/core/component-docs/toolbar/examples/toolbar-spacer-example.component.html
  apps/docs/src/app/core/component-docs/toolbar/examples/toolbar-title-example.component.html
  apps/docs/src/app/core/component-docs/toolbar/examples/toolbar-type-example.component.html
  apps/docs/src/app/core/component-docs/toolbar/toolbar-docs.component.html
  apps/docs/src/app/core/component-docs/toolbar/toolbar-docs.component.scss
  apps/docs/src/app/core/component-docs/toolbar/toolbar-docs.component.ts
  apps/docs/src/app/core/component-docs/toolbar/toolbar-docs.module.ts
  apps/docs/src/app/core/component-docs/toolbar/toolbar-header/toolbar-header.component.html
  apps/docs/src/app/core/component-docs/toolbar/toolbar-header/toolbar-header.component.scss
  apps/docs/src/app/core/component-docs/toolbar/toolbar-header/toolbar-header.component.ts
  apps/docs/src/app/core/core-documentation.routes.ts
  apps/docs/src/app/core/documentation/core-documentation.component.ts
  apps/docs/src/app/documentation/core-helpers/toolbar/toolbar.component.ts
  apps/docs/src/app/documentation/shared-documentation.module.ts
  libs/core/src/index.ts
  libs/core/src/lib/toolbar/public_api.ts
  libs/core/src/lib/toolbar/toolbar-form-label.directive.ts
  libs/core/src/lib/toolbar/toolbar-item.directive.ts
  libs/core/src/lib/toolbar/toolbar-label.directive.ts
  libs/core/src/lib/toolbar/toolbar-separator.component.ts
  libs/core/src/lib/toolbar/toolbar-spacer.component.ts
  libs/core/src/lib/toolbar/toolbar.component.html
  libs/core/src/lib/toolbar/toolbar.component.scss
  libs/core/src/lib/toolbar/toolbar.component.spec.ts
  libs/core/src/lib/toolbar/toolbar.component.ts
  libs/core/src/lib/toolbar/toolbar.module.ts
  src/stories/toolbar/fd-toolbar.stories.ts
Labels: v.0.20.0

#2714 fix: Change addon place on multi input, remove doubled padding from dropdown list on multi input
  libs/core/src/lib/checkbox/checkbox/checkbox.component.html
  libs/core/src/lib/checkbox/checkbox/checkbox.component.ts
  libs/core/src/lib/multi-input/multi-input.component.html
  libs/core/src/lib/multi-input/multi-input.component.scss
  libs/core/src/lib/multi-input/multi-input.component.ts
Labels: v.0.20.0

#2749 chore: only run travis prerelease job on merge to master
  .travis.yml
Labels: core

#2633 fix: (platform) Menu button Accessibility fix and Documentation changes.
  apps/docs/src/app/platform/component-docs/platform-menu-button/platform-menu-button-docs.component.html
  apps/docs/src/app/platform/component-docs/platform-menu-button/platform-menu-button-header/platform-menu-button-header.component.html
  libs/platform/src/lib/components/menu-button/menu-button.component.html
  libs/platform/src/lib/components/menu-button/menu-button.component.spec.ts
  libs/platform/src/lib/components/menu-button/menu-button.component.ts
Labels: platform

#2766 fix: Add change detection, when passed null value on datepicker
  libs/core/src/lib/date-picker/date-picker.component.ts
Labels: core, datepicker

#2750 docs(platform): action bar document update
  apps/docs/src/app/platform/component-docs/platform-action-bar/platform-action-bar-header/platform-action-bar-header.component.html
Labels: documentation, platform

#2768 docs: removed status indicator component
  apps/docs/src/app/core/api-files.ts
  apps/docs/src/app/core/component-docs/badge-label/badge-label-docs.component.html
  apps/docs/src/app/core/component-docs/badge-label/badge-label-docs.component.ts
  apps/docs/src/app/core/component-docs/badge-label/badge-label-docs.module.ts
  apps/docs/src/app/core/component-docs/badge-label/badge-label-header/badge-label-header.component.html
  apps/docs/src/app/core/component-docs/badge-label/badge-label-header/badge-label-header.component.scss
  apps/docs/src/app/core/component-docs/badge-label/badge-label-header/badge-label-header.component.ts
  apps/docs/src/app/core/component-docs/badge-label/examples/badge-default-example.component.html
  apps/docs/src/app/core/component-docs/badge-label/examples/badge-filled-example.component.html
  apps/docs/src/app/core/component-docs/badge-label/examples/badge-label-examples.component.scss
  apps/docs/src/app/core/component-docs/badge-label/examples/badge-label-examples.component.ts
  apps/docs/src/app/core/component-docs/badge-label/examples/badge-pill-example.component.html
  apps/docs/src/app/core/component-docs/badge-label/examples/label-build-status-example.component.html
  apps/docs/src/app/core/component-docs/badge-label/examples/label-default-example.component.html
  apps/docs/src/app/core/component-docs/badge-label/examples/label-icon-status-example.component.html
  apps/docs/src/app/core/component-docs/badge-label/examples/label-status-colors-example.component.html
  apps/docs/src/app/core/component-docs/schemas.ts
  apps/docs/src/app/core/core-documentation.routes.ts
  apps/docs/src/app/core/documentation/core-documentation.component.ts
  libs/core/src/index.ts
  libs/core/src/lib/badge-label/badge-label.module.ts
  libs/core/src/lib/badge-label/badge-label/badge-label.component.scss
  libs/core/src/lib/badge-label/badge-label/badge.component.ts
  libs/core/src/lib/badge-label/badge-label/badge.componet.spec.ts
  libs/core/src/lib/badge-label/label/label.component.scss
  libs/core/src/lib/badge-label/label/label.component.spec.ts
  libs/core/src/lib/badge-label/label/label.component.ts
  libs/core/src/lib/badge-label/public_api.ts
  libs/core/src/lib/badge-label/status-label/status-label.component.scss
  libs/core/src/lib/badge-label/status-label/status-label.component.spec.ts
  libs/core/src/lib/badge-label/status-label/status-label.component.ts
  libs/core/src/lib/fundamental-ngx-core.module.ts
Labels: core, documentation
