Repository SAP/fundamental-ngx, pull requests merged in 2020-11, with the labels that each got.

#3707 feat: implement title component
  apps/docs/src/app/core/api-files.ts
  apps/docs/src/app/core/component-docs/title/examples/title-elision-example.component.html
  apps/docs/src/app/core/component-docs/title/examples/title-examples.component.ts
  apps/docs/src/app/core/component-docs/title/examples/title-semantic-example.component.html
  apps/docs/src/app/core/component-docs/title/examples/title-visual-example.component.html
  apps/docs/src/app/core/component-docs/title/examples/title-wrapping-example.component.html
  apps/docs/src/app/core/component-docs/title/title-docs.component.html
  apps/docs/src/app/core/component-docs/title/title-docs.component.ts
  apps/docs/src/app/core/component-docs/title/title-docs.module.ts
  apps/docs/src/app/core/component-docs/title/title-header/title-header.component.html
  apps/docs/src/app/core/component-docs/title/title-header/title-header.component.ts
  apps/docs/src/app/core/core-documentation.routes.ts
  apps/docs/src/app/core/documentation/core-documentation.component.ts
  libs/core/src/index.ts
  libs/core/src/lib/title/public_api.ts
  libs/core/src/lib/title/title.component.scss
  libs/core/src/lib/title/title.component.spec.ts
  libs/core/src/lib/title/title.component.ts
  libs/core/src/lib/title/title.module.ts
Labels: 0.23.0, core

#3596 feat: (Core) introduce Action sheet component
  apps/docs/src/app/core/api-files.ts
  apps/docs/src/app/core/component-docs/action-sheet/action-sheet-docs.component.html
  apps/docs/src/app/core/component-docs/action-sheet/action-sheet-docs.component.ts
  apps/docs/src/app/core/component-docs/action-sheet/action-sheet-docs.module.ts
  apps/docs/src/app/core/component-docs/action-sheet/action-sheet-header/action-sheet-header.component.html
  apps/docs/src/app/core/component-docs/action-sheet/action-sheet-header/action-sheet-header.component.scss
  apps/docs/src/app/core/component-docs/action-sheet/action-sheet-header/action-sheet-header.component.ts
  apps/docs/src/app/core/component-docs/action-sheet/examples/action-sheet-compact/action-sheet-compact-example.component.html
  apps/docs/src/app/core/component-docs/action-sheet/examples/action-sheet-compact/action-sheet-compact-example.component.ts
  apps/docs/src/app/core/component-docs/action-sheet/examples/action-sheet-cosy/action-sheet-cosy-example.component.html
  apps/docs/src/app/core/component-docs/action-sheet/examples/action-sheet-cosy/action-sheet-cosy-example.component.ts
  apps/docs/src/app/core/component-docs/action-sheet/examples/action-sheet-mobile/action-sheet-mobile-example.component.html
  apps/docs/src/app/core/component-docs/action-sheet/examples/action-sheet-mobile/action-sheet-mobile-example.component.ts
  apps/docs/src/app/core/component-docs/action-sheet/examples/index.ts
  apps/docs/src/app/core/core-documentation.routes.ts
  apps/docs/src/app/core/documentation/core-documentation.component.ts
  libs/core/src/index.ts
  libs/core/src/lib/action-sheet/action-sheet-body/action-sheet-body.component.html
  libs/core/src/lib/action-sheet/action-sheet-body/action-sheet-body.component.spec.ts
  libs/core/src/lib/action-sheet/action-sheet-body/action-sheet-body.component.ts
  libs/core/src/lib/action-sheet/action-sheet-control/action-sheet-control.component.html
  libs/core/src/lib/action-sheet/action-sheet-control/action-sheet-control.component.spec.ts
  libs/core/src/lib/action-sheet/action-sheet-control/action-sheet-control.component.ts
  libs/core/src/lib/action-sheet/action-sheet-item/action-sheet-item.component.html
  libs/core/src/lib/action-sheet/action-sheet-item/action-sheet-item.component.spec.ts
  libs/core/src/lib/action-sheet/action-sheet-item/action-sheet-item.component.ts
  libs/core/src/lib/action-sheet/action-sheet-mobile/action-sheet-mobile.component.html
  libs/core/src/lib/action-sheet/action-sheet-mobile/action-sheet-mobile.component.spec.ts
  libs/core/src/lib/action-sheet/action-sheet-mobile/action-sheet-mobile.component.ts
  libs/core/src/lib/action-sheet/action-sheet-mobile/action-sheet-mobile.module.ts
  libs/core/src/lib/action-sheet/action-sheet.component.html
  libs/core/src/lib/action-sheet/action-sheet.component.scss
  libs/core/src/lib/action-sheet/action-sheet.component.spec.ts
  libs/core/src/lib/action-sheet/action-sheet.component.ts
  libs/core/src/lib/action-sheet/action-sheet.interface.ts
  libs/core/src/lib/action-sheet/action-sheet.module.ts
  libs/core/src/lib/action-sheet/public_api.ts
  libs/core/src/lib/fundamental-ngx-core.module.ts
  libs/core/src/lib/popover/popover.component.ts
Labels: Fiori 3 component, core, denoland

#3714 chore: bump angular versions in package.json
  package-lock.json
  package.json
Labels: dependencies, security

#3731 test: update imports on title test
  libs/core/src/lib/title/title.component.spec.ts
Labels: testing, unit tests

#3735 docs: Improve list with filtering example
  apps/docs/src/app/core/component-docs/list/examples/list-data-example/list-data-example.component.ts
Labels: 0.24.0, core, documentation

#3736 fix: Multi input list item height in compact mode
  libs/core/src/lib/multi-input/multi-input.component.html
  libs/core/src/lib/multi-input/multi-input.component.scss
Labels: 0.24.0, bug, core

#3730 fix: Add growing behavior to grid column
  apps/docs/src/app/core/component-docs/layout-grid/examples/index.ts
  apps/docs/src/app/core/component-docs/layout-grid/examples/layout-grid-examples.component.ts
  apps/docs/src/app/core/component-docs/layout-grid/examples/layout-grid-growing-example.component.html
  apps/docs/src/app/core/component-docs/layout-grid/layout-grid-docs.component.html
  apps/docs/src/app/core/component-docs/layout-grid/layout-grid-docs.component.ts
  libs/core/src/lib/layout-grid/constants.ts
  libs/core/src/lib/layout-grid/directives/layout-grid-col.directive.ts
  libs/core/src/lib/layout-grid/layout-grid.component.scss
Labels: core, enhancement

#3733 fix: Action sheet adapt to newest CDK
  libs/core/src/lib/action-sheet/action-sheet-body/action-sheet-body.component.ts
  libs/core/src/lib/action-sheet/action-sheet-control/action-sheet-control.component.ts
  libs/core/src/lib/action-sheet/action-sheet-item/action-sheet-item.component.ts
  libs/core/src/lib/action-sheet/action-sheet-mobile/action-sheet-mobile.component.html
  libs/core/src/lib/action-sheet/action-sheet-mobile/action-sheet-mobile.component.ts
  libs/core/src/lib/action-sheet/action-sheet.component.html
  libs/core/src/lib/action-sheet/action-sheet.component.ts
  libs/core/src/lib/action-sheet/action-sheet.interface.ts
Labels: core

#3740 docs: Change datepicker range width
  apps/docs/src/app/core/component-docs/date-picker/examples/date-picker-form-range-example.component.ts
  apps/docs/src/app/core/component-docs/date-picker/examples/date-picker-range-disabled-example/date-picker-range-disabled-example.component.html
Labels: Defect Hunting, documentation

#3738 fix: Add temporary styles for overflow toolbar
  libs/core/src/lib/toolbar/toolbar.component.scss
Labels: Defect Hunting, core

#3737 chore: Add overlay styles and hammerjs dep into stackblitz config file
  apps/docs/src/app/documentation/core-helpers/stackblitz/code-example-stack/styles.scss
  apps/docs/src/app/documentation/core-helpers/stackblitz/stackblitz-dependencies.ts
Labels: Defect Hunting, core, platform, stackblitz

#3759 chore: (Core) add hammerjs dependency to the library
  ci-scripts/sync-version.sh
  libs/core/ng-package.json
  libs/core/package.json
Labels: 0.24.0, core

#3739 fix: (Core) add border radius to List inside Popover
  libs/core/src/lib/popover/popover.component.scss
Labels: 0.24.0, Defect Hunting

#3754 fix: (Core) add stronger selector for Message strip
  libs/core/src/lib/message-strip/message-strip.component.scss
Labels: 0.24.0, Defect Hunting

#3783 fix:(Core) adding tooltip to the components for info label.
  apps/docs/src/app/core/component-docs/info-label/examples/info-label-default-example.component.html
  apps/docs/src/app/core/component-docs/info-label/examples/info-label-icon-numeric-example.component.html
  apps/docs/src/app/core/component-docs/info-label/examples/info-label-text-example.component.html
  apps/docs/src/app/core/component-docs/info-label/examples/info-label-text-icon-example.component.html
  apps/docs/src/app/core/component-docs/object-status/examples/object-status-default-example.component.html
  apps/docs/src/app/core/component-docs/object-status/examples/object-status-inverted-example.component.html
  apps/docs/src/app/core/component-docs/object-status/examples/object-status-large-example.component.html
  apps/docs/src/app/core/component-docs/object-status/examples/object-status-text-example.component.html
  libs/core/src/lib/info-label/info-label.component.html
  libs/core/src/lib/info-label/info-label.component.ts
Labels: Defect Hunting, bug

#3780 fix: remove deprecated isCheck from FormItemComponent
  libs/core/src/lib/form/form-item/form-item.component.ts
Labels: 0.24.0

#3782 fix: remove deprecated mega menu
  apps/docs/src/app/core/api-files.ts
  apps/docs/src/app/core/component-docs/mega-menu/examples/mega-menu-example.component.html
  apps/docs/src/app/core/component-docs/mega-menu/examples/mega-menu-examples.component.ts
  apps/docs/src/app/core/component-docs/mega-menu/examples/mega-menu-group-example.component.html
  apps/docs/src/app/core/component-docs/mega-menu/examples/mega-menu-position-example.component.html
  apps/docs/src/app/core/component-docs/mega-menu/examples/mega-menu-position-example.component.scss
  apps/docs/src/app/core/component-docs/mega-menu/mega-menu-docs.component.html
  apps/docs/src/app/core/component-docs/mega-menu/mega-menu-docs.component.ts
  apps/docs/src/app/core/component-docs/mega-menu/mega-menu-docs.module.ts
  apps/docs/src/app/core/component-docs/mega-menu/mega-menu-header/mega-menu-header.component.html
  apps/docs/src/app/core/component-docs/mega-menu/mega-menu-header/mega-menu-header.component.scss
  apps/docs/src/app/core/component-docs/mega-menu/mega-menu-header/mega-menu-header.component.ts
  apps/docs/src/app/core/component-docs/popover/popover-header/popover-header.component.html
  apps/docs/src/app/core/core-documentation.routes.ts
  apps/docs/src/app/core/documentation/core-documentation.component.ts
  libs/core/src/index.ts
  libs/core/src/lib/fundamental-ngx-core.module.ts
  libs/core/src/lib/mega-menu/mega-menu-group/mega-menu-group.component.html
  libs/core/src/lib/mega-menu/mega-menu-group/mega-menu-group.component.spec.ts
  libs/core/src/lib/mega-menu/mega-menu-group/mega-menu-group.component.ts
  libs/core/src/lib/mega-menu/mega-menu-item/mega-menu-item.component.html
  libs/core/src/lib/mega-menu/mega-menu-item/mega-menu-item.component.scss
  libs/core/src/lib/mega-menu/mega-menu-item/mega-menu-item.component.spec.ts
  libs/core/src/lib/mega-menu/mega-menu-item/mega-menu-item.component.ts
  libs/core/src/lib/mega-menu/mega-menu-link/mega-menu-link.directive.spec.ts
  libs/core/src/lib/mega-menu/mega-menu-link/mega-menu-link.directive.ts
  libs/core/src/lib/mega-menu/mega-menu-list/mega-menu-list.directive.spec.ts
  libs/core/src/lib/mega-menu/mega-menu-list/mega-menu-list.directive.ts
  libs/core/src/lib/mega-menu/mega-menu-subitem.directive.spec.ts
  libs/core/src/lib/mega-menu/mega-menu-subitem.directive.ts
  libs/core/src/lib/mega-menu/mega-menu-sublink.directive.spec.ts
  libs/core/src/lib/mega-menu/mega-menu-sublink.directive.ts
  libs/core/src/lib/mega-menu/mega-menu-title/mega-menu-title.directive.spec.ts
  libs/core/src/lib/mega-menu/mega-menu-title/mega-menu-title.directive.ts
  libs/core/src/lib/mega-menu/mega-menu.component.html
  libs/core/src/lib/mega-menu/mega-menu.component.scss
  libs/core/src/lib/mega-menu/mega-menu.component.spec.ts
  libs/core/src/lib/mega-menu/mega-menu.component.ts
  libs/core/src/lib/mega-menu/mega-menu.module.ts
  libs/core/src/lib/mega-menu/public_api.ts
Labels: 0.24.0

#3781 fix: remove deprecated localization editor
  apps/docs/src/app/core/api-files.ts
  apps/docs/src/app/core/component-docs/localization-editor/examples/localization-editor-example.component.html
  apps/docs/src/app/core/component-docs/localization-editor/examples/localization-editor-example.component.ts
  apps/docs/src/app/core/component-docs/localization-editor/examples/localization-editor-forms-example.component.html
  apps/docs/src/app/core/component-docs/localization-editor/examples/localization-editor-forms-example.component.ts
  apps/docs/src/app/core/component-docs/localization-editor/examples/localization-editor-template-example.component.html
  apps/docs/src/app/core/component-docs/localization-editor/examples/localization-editor-template-example.component.ts
  apps/docs/src/app/core/component-docs/localization-editor/examples/localization-editor-textarea-example.component.html
  apps/docs/src/app/core/component-docs/localization-editor/examples/localization-editor-textarea-example.component.ts
  apps/docs/src/app/core/component-docs/localization-editor/localization-editor-docs.component.html
  apps/docs/src/app/core/component-docs/localization-editor/localization-editor-docs.component.ts
  apps/docs/src/app/core/component-docs/localization-editor/localization-editor-docs.module.ts
  apps/docs/src/app/core/component-docs/localization-editor/localization-editor-header/localization-editor-header.component.html
  apps/docs/src/app/core/component-docs/localization-editor/localization-editor-header/localization-editor-header.component.ts
  apps/docs/src/app/core/core-documentation.routes.ts
  apps/docs/src/app/core/documentation/core-documentation.component.ts
  libs/core/src/index.ts
  libs/core/src/lib/fundamental-ngx-core.module.ts
  libs/core/src/lib/localizator-editor/index.ts
  libs/core/src/lib/localizator-editor/localization-editor-item/localization-editor-item.component.html
  libs/core/src/lib/localizator-editor/localization-editor-item/localization-editor-item.component.spec.ts
  libs/core/src/lib/localizator-editor/localization-editor-item/localization-editor-item.component.ts
  libs/core/src/lib/localizator-editor/localization-editor-main/localization-editor-main.component.html
  libs/core/src/lib/localizator-editor/localization-editor-main/localization-editor-main.component.spec.ts
  libs/core/src/lib/localizator-editor/localization-editor-main/localization-editor-main.component.ts
  libs/core/src/lib/localizator-editor/localization-editor.component.html
  libs/core/src/lib/localizator-editor/localization-editor.component.scss
  libs/core/src/lib/localizator-editor/localization-editor.component.spec.ts
  libs/core/src/lib/localizator-editor/localization-editor.component.ts
  libs/core/src/lib/localizator-editor/localization-editor.directives.ts
  libs/core/src/lib/localizator-editor/localization-editor.module.ts
  libs/core/src/lib/localizator-editor/public_api.ts
Labels: 0.24.0

#3769 fix: (Core) cursor on disabled Switch should not be pointer
  libs/core/src/lib/switch/switch.component.html
Labels: 0.24.0, core

#3723 fix: (Core) issues on Popover related components
  apps/docs/src/app/core/component-docs/combobox/examples/combobox-columns-example.component.html
  apps/docs/src/app/core/component-docs/combobox/examples/combobox-displaywith-example.component.html
  apps/docs/src/app/core/component-docs/combobox/examples/combobox-dynamic-example.component.html
  apps/docs/src/app/core/component-docs/combobox/examples/combobox-group-example.component.html
  apps/docs/src/app/core/component-docs/combobox/examples/combobox-mobile/combobox-mobile-example.component.html
  apps/docs/src/app/core/component-docs/combobox/examples/combobox-search-function-example.component.html
  apps/docs/src/app/core/component-docs/combobox/examples/combobox-template-example.component.html
  apps/docs/src/app/core/component-docs/select/examples/select-adding-example/select-adding-example.component.html
  apps/docs/src/app/core/component-docs/select/examples/select-height/select-max-height-example.component.html
  apps/docs/src/app/core/component-docs/select/examples/select-mobile-example/select-mobile-example.component.html
  apps/docs/src/app/core/component-docs/select/examples/select-mode-example/select-mode-example.component.html
  apps/docs/src/app/core/component-docs/select/examples/select-nested-options/select-nested-options.component.html
  apps/docs/src/app/core/component-docs/select/examples/select-programmatic-example/select-programmatic-example.component.html
  libs/core/src/lib/combobox/combobox.component.html
  libs/core/src/lib/combobox/combobox.component.scss
  libs/core/src/lib/combobox/combobox.component.ts
  libs/core/src/lib/datetime-picker/datetime-picker.component.scss
  libs/core/src/lib/menu/menu.component.ts
  libs/core/src/lib/multi-input/multi-input.component.html
  libs/core/src/lib/multi-input/multi-input.component.scss
  libs/core/src/lib/multi-input/multi-input.component.spec.ts
  libs/core/src/lib/multi-input/multi-input.component.ts
  libs/core/src/lib/popover/popover-position/popover-position.ts
  libs/core/src/lib/popover/popover.component.html
  libs/core/src/lib/popover/popover.component.scss
  libs/core/src/lib/popover/popover.component.spec.ts
  libs/core/src/lib/popover/popover.component.ts
  libs/core/src/lib/select/option/option.component.html
  libs/core/src/lib/select/option/option.component.ts
  libs/core/src/lib/select/select.component.html
  libs/core/src/lib/select/select.component.scss
  libs/core/src/lib/select/select.component.ts
Labels: 0.24.0, Defect Hunting, core

#3802 fix: (platform) export base input class
  libs/platform/src/lib/components/form/public_api.ts
Labels: Defect Hunting

#3770 fix: (Core) RTL mode arrows is showing wrong in Panel
  apps/docs/src/app/platform/component-docs/platform-panel/platform-panel-examples/platform-panel-expandable-example.component.html
  libs/core/src/lib/panel/panel.component.html
  libs/core/src/lib/panel/panel.component.scss
  libs/core/src/lib/panel/panel.component.spec.ts
  libs/core/src/lib/panel/panel.component.ts
Labels: 0.24.0, core

#3808 fix: (Core) removed angular-resize-event from fixed card layout and documention
  apps/docs/src/app/core/component-docs/fixed-card-layout/examples/default/fixed-card-layout-examples.component.html
  apps/docs/src/app/core/component-docs/fixed-card-layout/examples/disabled-drag-drop/fixed-card-layout-disabled-drag.component.html
  apps/docs/src/app/core/component-docs/fixed-card-layout/fixed-card-layout-docs-header/fixed-card-layout-docs-header.component.html
  apps/docs/src/app/core/component-docs/fixed-card-layout/fixed-card-layout-docs.module.ts
  package-lock.json
  package.json
Labels: Defect Hunting

#3785 fix: (Platform) add tooltip to the components
  apps/docs/src/app/platform/component-docs/platform-info-label/platform-info-label-example/platform-info-label-aria-label-example.component.html
  apps/docs/src/app/platform/component-docs/platform-info-label/platform-info-label-example/platform-info-label-example.component.html
  apps/docs/src/app/platform/component-docs/platform-info-label/platform-info-label-example/platform-info-label-example.component.ts
  apps/docs/src/app/platform/component-docs/platform-info-label/platform-info-label-example/platform-info-label-numeric-example.component.html
  apps/docs/src/app/platform/component-docs/platform-info-label/platform-info-label-example/platform-info-label-text-and-icon-example.component.html
  apps/docs/src/app/platform/component-docs/platform-info-label/platform-info-label-example/platform-info-label-text-example.component.html
  apps/docs/src/app/platform/component-docs/platform-object-marker/object-marker-example/object-marker-example.component.html
  apps/docs/src/app/platform/component-docs/platform-object-status/platform-object-status-example/platform-object-status-clickable-and-icon-example.component.html
  apps/docs/src/app/platform/component-docs/platform-object-status/platform-object-status-example/platform-object-status-example.component.html
  apps/docs/src/app/platform/component-docs/platform-object-status/platform-object-status-example/platform-object-status-generic-text-example.component.html
  apps/docs/src/app/platform/component-docs/platform-object-status/platform-object-status-example/platform-object-status-icon-text-example.component.html
  apps/docs/src/app/platform/component-docs/platform-object-status/platform-object-status-example/platform-object-status-inverted-example.component.html
  apps/docs/src/app/platform/component-docs/platform-object-status/platform-object-status-example/platform-object-status-inverted-generic-text-example.component.html
  apps/docs/src/app/platform/component-docs/platform-object-status/platform-object-status-example/platform-object-status-large-example.component.html
  apps/docs/src/app/platform/component-docs/platform-object-status/platform-object-status-example/platform-object-status-text-example.component.html
  libs/core/src/lib/info-label/info-label.component.html
  libs/core/src/lib/info-label/info-label.component.ts
  libs/platform/src/lib/components/info-label/info-label.component.html
  libs/platform/src/lib/components/info-label/info-label.component.ts
  libs/platform/src/lib/components/object-marker/object-marker.component.html
  libs/platform/src/lib/components/object-marker/object-marker.component.ts
  libs/platform/src/lib/components/object-status/object-status.component.html
  libs/platform/src/lib/components/object-status/object-status.component.ts
Labels: Defect Hunting, bug

#3883 fix: (Core) Add overlay css to Popover
  apps/docs/src/styles.scss
  libs/core/src/lib/popover/popover.component.scss
Labels: core

#3784 feat: (Core) add theme switcher API service
  angular.json
  apps/docs/src/app/core/api-files.ts
  apps/docs/src/app/core/component-docs/theme-switcher/examples/index.ts
  apps/docs/src/app/core/component-docs/theme-switcher/examples/theme-switcher-example.component.html
  apps/docs/src/app/core/component-docs/theme-switcher/examples/theme-switcher-example.component.ts
  apps/docs/src/app/core/component-docs/theme-switcher/examples/theme-url-example.component.html
  apps/docs/src/app/core/component-docs/theme-switcher/examples/theme-url-example.component.ts
  apps/docs/src/app/core/component-docs/theme-switcher/theme-switcher-docs.component.html
  apps/docs/src/app/core/component-docs/theme-switcher/theme-switcher-docs.component.ts
  apps/docs/src/app/core/component-docs/theme-switcher/theme-switcher-docs.module.ts
  apps/docs/src/app/core/component-docs/theme-switcher/theme-switcher-header/theme-switcher-header.component.html
  apps/docs/src/app/core/component-docs/theme-switcher/theme-switcher-header/theme-switcher-header.component.ts
  apps/docs/src/app/core/core-documentation.module.ts
  apps/docs/src/app/core/core-documentation.routes.ts
  apps/docs/src/app/core/documentation/core-documentation.component.ts
  apps/docs/src/app/documentation/core-helpers/stackblitz/stackblitz-dependencies.ts
  apps/docs/src/app/documentation/core-helpers/toolbar/toolbar.component.html
  apps/docs/src/app/documentation/core-helpers/toolbar/toolbar.component.ts
  apps/docs/src/app/documentation/services/docs-theme.service.ts
  apps/docs/src/app/platform/platform-documentation.module.ts
  libs/core/src/lib/fundamental-ngx-core.module.ts
  libs/core/src/lib/utils/public_api.ts
  libs/core/src/lib/utils/services/themes.service.ts
  package.json
Labels: theming

#3894 fix: (Core) fix closest element function
  libs/core/src/lib/utils/functions/closest-element.ts
Labels: core

#3889 fix: (Core) Popover sides position
  libs/core/src/lib/popover/popover.component.scss
Labels: 0.25.0, Defect Hunting

#3891 fix: (Core) add raw values for IE11 into popover arrow styles
  libs/core/src/lib/popover/popover.component.scss
Labels: 0.25.0, Defect Hunting

#3892 fix: (Core) add styles to shellbar elements
  libs/core/src/lib/shellbar/product-menu/product-menu.component.scss
  libs/core/src/lib/shellbar/shellbar.component.scss
Labels: 0.25.0, Defect Hunting

#3724 feat: (Platform) introduce DateTime Picker component in Platform
  apps/docs/src/app/platform/api-files.ts
  apps/docs/src/app/platform/component-docs/platform-forms/platform-datetime-picker/platform-datetime-picker-docs.component.html
  apps/docs/src/app/platform/component-docs/platform-forms/platform-datetime-picker/platform-datetime-picker-docs.component.ts
  apps/docs/src/app/platform/component-docs/platform-forms/platform-datetime-picker/platform-datetime-picker-docs.module.ts
  apps/docs/src/app/platform/component-docs/platform-forms/platform-datetime-picker/platform-datetime-picker-examples/platform-datetime-picker-basic-example.component.html
  apps/docs/src/app/platform/component-docs/platform-forms/platform-datetime-picker/platform-datetime-picker-examples/platform-datetime-picker-basic-example.component.ts
  apps/docs/src/app/platform/component-docs/platform-forms/platform-datetime-picker/platform-datetime-picker-examples/platform-datetime-picker-disable-function-example.component.html
  apps/docs/src/app/platform/component-docs/platform-forms/platform-datetime-picker/platform-datetime-picker-examples/platform-datetime-picker-disable-function-example.component.ts
  apps/docs/src/app/platform/component-docs/platform-forms/platform-datetime-picker/platform-datetime-picker-examples/platform-datetime-picker-reactive-example.component.html
  apps/docs/src/app/platform/component-docs/platform-forms/platform-datetime-picker/platform-datetime-picker-examples/platform-datetime-picker-reactive-example.component.ts
  apps/docs/src/app/platform/component-docs/platform-forms/platform-datetime-picker/platform-datetime-picker-examples/platform-datetime-picker-template-example.component.html
  apps/docs/src/app/platform/component-docs/platform-forms/platform-datetime-picker/platform-datetime-picker-examples/platform-datetime-picker-template-example.component.ts
  apps/docs/src/app/platform/component-docs/platform-forms/platform-datetime-picker/platform-datetime-picker-header/platform-datetime-picker-header.component.html
  apps/docs/src/app/platform/component-docs/platform-forms/platform-datetime-picker/platform-datetime-picker-header/platform-datetime-picker-header.component.ts
  apps/docs/src/app/platform/documentation/platform-documentation.component.ts
  apps/docs/src/app/platform/platform-documentation.routes.ts
  libs/core/src/lib/datetime-picker/datetime-picker.component.html
  libs/platform/src/lib/components/form/datetime-picker/datetime-picker.component.html
  libs/platform/src/lib/components/form/datetime-picker/datetime-picker.component.spec.ts
  libs/platform/src/lib/components/form/datetime-picker/datetime-picker.component.ts
  libs/platform/src/lib/components/form/datetime-picker/datetime-picker.module.ts
  libs/platform/src/lib/components/form/form-group/form-field/form-field.component.ts
  libs/platform/src/lib/components/form/input-message-group-with-template/input-message-group-with-template.component.html
  libs/platform/src/lib/components/form/input-message-group-with-template/input-message-group-with-template.component.scss
  libs/platform/src/lib/components/form/public_api.ts
  libs/platform/src/lib/platform.module.ts
Labels: platform

#3890 docs: (Core) add example behaviour to action sheet
  apps/docs/src/app/core/component-docs/action-sheet/action-sheet-docs.component.ts
  apps/docs/src/app/core/component-docs/action-sheet/examples/action-sheet-compact/action-sheet-compact-example.component.html
  apps/docs/src/app/core/component-docs/action-sheet/examples/action-sheet-compact/action-sheet-compact-example.component.ts
  apps/docs/src/app/core/component-docs/action-sheet/examples/action-sheet-cosy/action-sheet-cosy-example.component.html
  apps/docs/src/app/core/component-docs/action-sheet/examples/action-sheet-cosy/action-sheet-cosy-example.component.ts
  apps/docs/src/app/core/component-docs/action-sheet/examples/action-sheet-mobile/action-sheet-mobile-example.component.html
  apps/docs/src/app/core/component-docs/action-sheet/examples/action-sheet-mobile/action-sheet-mobile-example.component.ts
Labels: 0.25.0, Defect Hunting, documentation

#3900 fix: (Core) Shellbar IE11 shrink
  libs/core/src/lib/shellbar/shellbar.component.scss
Labels: 0.25.0, Defect Hunting

#3895 fix: (Core) adapt the Breaking Changes from fundamental-styles v.0.13.0
  apps/docs/src/app/core/component-docs/inline-help/inline-help-header/inline-help-header.component.html
  libs/core/src/lib/breadcrumb/breadcrumb.component.html
  libs/core/src/lib/form/form-control/form-control.component.scss
  libs/core/src/lib/form/form-control/form-control.component.ts
  libs/core/src/lib/inline-help/inline-help.component.scss
  libs/core/src/lib/inline-help/inline-help.component.ts
  libs/core/src/lib/inline-help/inline-help.module.ts
Labels: Sprint 50 - Denoland, core

#3912 chore: add netlify badge
  README.md
Labels: tooling

#3913 chore: add code of conduct file
  CODE_OF_CONDUCT.md
Labels: tooling

#3760 fix: (Core) Carousel documentation improvement and handling carousel item visibility
  apps/docs/src/app/core/component-docs/carousel/carousel-docs.component.html
  apps/docs/src/app/core/component-docs/carousel/carousel-docs.component.ts
  apps/docs/src/app/core/component-docs/carousel/carousel-docs.module.ts
  apps/docs/src/app/core/component-docs/carousel/examples/carousel-content-navigation.component.ts
  apps/docs/src/app/core/component-docs/carousel/examples/carousel-error-message.component.ts
  apps/docs/src/app/core/component-docs/carousel/examples/carousel-hidden-navigation.component.ts
  apps/docs/src/app/core/component-docs/carousel/examples/carousel-loading-content-example.component.html
  apps/docs/src/app/core/component-docs/carousel/examples/carousel-loading-content-example.component.ts
  apps/docs/src/app/core/component-docs/carousel/examples/carousel-looped-navigation.component.ts
  apps/docs/src/app/core/component-docs/carousel/examples/carousel-multiple-active-item.component.ts
  apps/docs/src/app/core/component-docs/carousel/examples/carousel-no-page-indicator.component.ts
  apps/docs/src/app/core/component-docs/carousel/examples/carousel-vertical-direction.component.ts
  libs/core/src/lib/carousel/carousel-item/carousel-item.component.html
  libs/core/src/lib/carousel/carousel-item/carousel-item.component.ts
  libs/core/src/lib/carousel/carousel.component.html
  libs/core/src/lib/carousel/carousel.component.ts
  libs/core/src/lib/utils/directives/carousel/carousel.module.ts
Labels: Defect Hunting, High, core

#3904 fix: (Core) FormMessage width reduce
  libs/core/src/lib/form/form-input-message-group/form-input-message-group.component.scss
  libs/core/src/lib/form/form-message/form-message.component.scss
Labels: 0.25.0, Defect Hunting

#3899 fix: (Core) Add icons to Action Tile buttons
  libs/core/src/lib/tile/directives/tile.directives.ts
Labels: 0.25.0, Defect Hunting

#3901 fix: (Core) change flex property on fixed card layout for IE11
  libs/core/src/lib/fixed-card-layout/fixed-card-layout.component.scss
Labels: 0.25.0, Defect Hunting, IE11

#3919 chore: upgrade to storybook version 6.1.2
  package-lock.json
  package.json
Labels: denoland, storybook

#3907 fix: (Core) add delete button support in tokenizer
  libs/core/src/lib/multi-input/multi-input.component.html
  libs/core/src/lib/multi-input/multi-input.component.ts
  libs/core/src/lib/token/tokenizer.component.ts
Labels: 0.25.0, Defect Hunting, core

#3921 fix: (Core) Toolbar label and button additional styles
  libs/core/src/lib/toolbar/toolbar.component.scss
Labels: 0.25.0, Defect Hunting

#3927 chore: version 0.24.1 bump
  CHANGELOG.md
  package-lock.json
  package.json
Labels: core, platform

#3861 feat: (Core) introduce new Form Header component
  apps/docs/src/app/core/api-files.ts
  apps/docs/src/app/core/component-docs/checkbox/examples/checkbox-states-example.component.ts
  apps/docs/src/app/core/component-docs/input-group/examples/input-group-text-example.component.html
  apps/docs/src/app/core/component-docs/input/examples/input-example.component.html
  apps/docs/src/app/core/component-docs/radio/examples/radio-example.component.html
  apps/docs/src/app/core/component-docs/textarea/examples/textarea-example.component.html
  libs/core/src/lib/form/form-header/form-header.component.scss
  libs/core/src/lib/form/form-header/form-header.component.spec.ts
  libs/core/src/lib/form/form-header/form-header.component.ts
  libs/core/src/lib/form/form-header/form-header.module.ts
  libs/core/src/lib/form/form.module.ts
  libs/core/src/lib/form/public_api.ts
  package-lock.json
  package.json
Labels: core, denoland

#3925 fix: (Platform) add accessibility fixes for Dynamic Page
  apps/docs/src/app/platform/component-docs/platform-dynamic-page/platform-dynamic-page-examples/platform-dynamic-page-example.component.html
  apps/docs/src/app/platform/component-docs/platform-dynamic-page/platform-dynamic-page-examples/platform-dynamic-page-example.component.ts
  apps/docs/src/app/platform/component-docs/platform-dynamic-page/platform-dynamic-page-examples/platform-dynamic-page-responsive-padding-example.component.html
  apps/docs/src/app/platform/component-docs/platform-dynamic-page/platform-dynamic-page-examples/platform-dynamic-page-responsive-padding-example.component.ts
  apps/docs/src/app/platform/component-docs/platform-dynamic-page/platform-dynamic-page-examples/platform-dynamic-page-snap-scroll-example.component.html
  apps/docs/src/app/platform/component-docs/platform-dynamic-page/platform-dynamic-page-examples/platform-dynamic-page-snap-scroll-example.component.ts
  apps/docs/src/app/platform/component-docs/platform-dynamic-page/platform-dynamic-page-examples/platform-dynamic-page-tabbed-example.component.html
  apps/docs/src/app/platform/component-docs/platform-dynamic-page/platform-dynamic-page-examples/platform-dynamic-page-tabbed-example.component.ts
  libs/platform/src/lib/components/dynamic-page/dynamic-page-content/dynamic-page-content.component.html
  libs/platform/src/lib/components/dynamic-page/dynamic-page.component.html
  libs/platform/src/lib/components/dynamic-page/dynamic-page.component.scss
Labels: accessibility, ariba, bug

#3942 fix: (Core) remove wrong examples Object marker and Object Status
  apps/docs/src/app/core/component-docs/object-marker/examples/object-marker-Icon-text-example.component.html
  apps/docs/src/app/core/component-docs/object-marker/examples/object-marker-clickable-example.component.html
  apps/docs/src/app/core/component-docs/object-status/examples/object-status-large-example.component.html
Labels: bug

#3945 fix: (Platform) remove wrong examples Object marker
  apps/docs/src/app/platform/component-docs/platform-object-marker/object-marker-example/object-marker-text-and-icon-example.component.html
  apps/docs/src/app/platform/component-docs/platform-object-marker/object-marker-example/object-marker-text-clickable-example.component.html
Labels: bug

#3725 feat: (Core) introduce Feed Input component
  apps/docs/src/app/core/api-files.ts
  apps/docs/src/app/core/component-docs/feed-input/examples/feed-input-disabled-example/feed-input-disabled-example.component.html
  apps/docs/src/app/core/component-docs/feed-input/examples/feed-input-disabled-example/feed-input-disabled-example.component.ts
  apps/docs/src/app/core/component-docs/feed-input/examples/feed-input-example/feed-input-example.component.html
  apps/docs/src/app/core/component-docs/feed-input/examples/feed-input-example/feed-input-example.component.ts
  apps/docs/src/app/core/component-docs/feed-input/examples/feed-input-grow-example/feed-input-grow-example.component.html
  apps/docs/src/app/core/component-docs/feed-input/examples/feed-input-grow-example/feed-input-grow-example.component.ts
  apps/docs/src/app/core/component-docs/feed-input/examples/feed-input-no-avatar-example/feed-input-no-avatar-example.component.html
  apps/docs/src/app/core/component-docs/feed-input/examples/feed-input-no-avatar-example/feed-input-no-avatar-example.component.ts
  apps/docs/src/app/core/component-docs/feed-input/examples/feed-input-placeholder-example/feed-input-placeholder-example.component.html
  apps/docs/src/app/core/component-docs/feed-input/examples/feed-input-placeholder-example/feed-input-placeholder-example.component.ts
  apps/docs/src/app/core/component-docs/feed-input/feed-input-docs.component.html
  apps/docs/src/app/core/component-docs/feed-input/feed-input-docs.component.ts
  apps/docs/src/app/core/component-docs/feed-input/feed-input-docs.module.ts
  apps/docs/src/app/core/component-docs/feed-input/feed-input-header/feed-input-header.component.html
  apps/docs/src/app/core/component-docs/feed-input/feed-input-header/feed-input-header.component.ts
  apps/docs/src/app/core/core-documentation.routes.ts
  apps/docs/src/app/core/documentation/core-documentation.component.ts
  libs/core/src/index.ts
  libs/core/src/lib/feed-input/directives/feed-input-avatar.directive.ts
  libs/core/src/lib/feed-input/directives/feed-input-button.directive.ts
  libs/core/src/lib/feed-input/directives/feed-input-textarea.directive.ts
  libs/core/src/lib/feed-input/feed-input.component.html
  libs/core/src/lib/feed-input/feed-input.component.scss
  libs/core/src/lib/feed-input/feed-input.component.spec.ts
  libs/core/src/lib/feed-input/feed-input.component.ts
  libs/core/src/lib/feed-input/feed-input.module.ts
  libs/core/src/lib/feed-input/public_api.ts
Labels: Fiori 3 component, core

#3851 feat: (Platform) introduce Feed Input component
  apps/docs/src/app/platform/api-files.ts
  apps/docs/src/app/platform/component-docs/platform-feed-input/platform-feed-input-docs.component.html
  apps/docs/src/app/platform/component-docs/platform-feed-input/platform-feed-input-docs.component.ts
  apps/docs/src/app/platform/component-docs/platform-feed-input/platform-feed-input-examples/platform-feed-input-disabled-example/platform-feed-input-disabled-example.component.html
  apps/docs/src/app/platform/component-docs/platform-feed-input/platform-feed-input-examples/platform-feed-input-disabled-example/platform-feed-input-disabled-example.component.ts
  apps/docs/src/app/platform/component-docs/platform-feed-input/platform-feed-input-examples/platform-feed-input-example/platform-feed-input-example.component.html
  apps/docs/src/app/platform/component-docs/platform-feed-input/platform-feed-input-examples/platform-feed-input-example/platform-feed-input-example.component.ts
  apps/docs/src/app/platform/component-docs/platform-feed-input/platform-feed-input-examples/platform-feed-input-max-height-example/platform-feed-input-max-height-example.component.html
  apps/docs/src/app/platform/component-docs/platform-feed-input/platform-feed-input-examples/platform-feed-input-max-height-example/platform-feed-input-max-height-example.component.ts
  apps/docs/src/app/platform/component-docs/platform-feed-input/platform-feed-input-examples/platform-feed-input-no-avatar-example/platform-feed-input-no-avatar-example.component.html
  apps/docs/src/app/platform/component-docs/platform-feed-input/platform-feed-input-examples/platform-feed-input-no-avatar-example/platform-feed-input-no-avatar-example.component.ts
  apps/docs/src/app/platform/component-docs/platform-feed-input/platform-feed-input-examples/platform-feed-input-placeholder-example/platform-feed-input-placeholder-example.component.html
  apps/docs/src/app/platform/component-docs/platform-feed-input/platform-feed-input-examples/platform-feed-input-placeholder-example/platform-feed-input-placeholder-example.component.ts
  apps/docs/src/app/platform/component-docs/platform-feed-input/platform-feed-input-header/platform-feed-input-header.component.html
  apps/docs/src/app/platform/component-docs/platform-feed-input/platform-feed-input-header/platform-feed-input-header.component.scss
  apps/docs/src/app/platform/component-docs/platform-feed-input/platform-feed-input-header/platform-feed-input-header.component.ts
  apps/docs/src/app/platform/component-docs/platform-feed-input/platform-feed-input.module.ts
  apps/docs/src/app/platform/documentation/platform-documentation.component.ts
  apps/docs/src/app/platform/platform-documentation.routes.ts
  libs/platform/src/index.ts
  libs/platform/src/lib/components/feed-input/feed-input.component.html
  libs/platform/src/lib/components/feed-input/feed-input.component.scss
  libs/platform/src/lib/components/feed-input/feed-input.component.spec.ts
  libs/platform/src/lib/components/feed-input/feed-input.component.ts
  libs/platform/src/lib/components/feed-input/feed-input.module.ts
  libs/platform/src/lib/components/feed-input/public_api.ts
  libs/platform/src/lib/platform.module.ts
Labels: platform

#3699 feat: (Core) introduce Rating Indicator component
  .vscode/extensions.json
  .vscode/settings.json
  README.md
  apps/docs/src/app/core/api-files.ts
  apps/docs/src/app/core/component-docs/rating-indicator/examples/index.ts
  apps/docs/src/app/core/component-docs/rating-indicator/examples/rating-indicator-example.component.html
  apps/docs/src/app/core/component-docs/rating-indicator/examples/rating-indicator-examples.component.ts
  apps/docs/src/app/core/component-docs/rating-indicator/examples/rating-indicator-ratings.component.html
  apps/docs/src/app/core/component-docs/rating-indicator/examples/rating-indicator-ratings.component.ts
  apps/docs/src/app/core/component-docs/rating-indicator/examples/rating-indicator-sizes.component.html
  apps/docs/src/app/core/component-docs/rating-indicator/examples/rating-indicator-sizes.component.ts
  apps/docs/src/app/core/component-docs/rating-indicator/examples/rating-indicator-style.component.scss
  apps/docs/src/app/core/component-docs/rating-indicator/examples/ri-custom-icon-example.component.html
  apps/docs/src/app/core/component-docs/rating-indicator/examples/ri-custom-icon-example.component.ts
  apps/docs/src/app/core/component-docs/rating-indicator/examples/ri-dynamic-example.component.html
  apps/docs/src/app/core/component-docs/rating-indicator/examples/ri-dynamic-example.component.ts
  apps/docs/src/app/core/component-docs/rating-indicator/rating-indicator-docs-header/rating-indicator-docs-header.component.html
  apps/docs/src/app/core/component-docs/rating-indicator/rating-indicator-docs-header/rating-indicator-docs-header.component.ts
  apps/docs/src/app/core/component-docs/rating-indicator/rating-indicator-docs.component.html
  apps/docs/src/app/core/component-docs/rating-indicator/rating-indicator-docs.component.ts
  apps/docs/src/app/core/component-docs/rating-indicator/rating-indicator-docs.module.ts
  apps/docs/src/app/core/core-documentation.routes.ts
  apps/docs/src/app/core/documentation/core-documentation.component.ts
  apps/docs/src/app/documentation/core-helpers/code-example/code-example.component.ts
  apps/docs/src/assets/README.md
  libs/core/src/index.ts
  libs/core/src/lib/fundamental-ngx-core.module.ts
  libs/core/src/lib/rating-indicator/components/rating-indicator.component.html
  libs/core/src/lib/rating-indicator/components/rating-indicator.component.scss
  libs/core/src/lib/rating-indicator/components/rating-indicator.component.spec.ts
  libs/core/src/lib/rating-indicator/components/rating-indicator.component.ts
  libs/core/src/lib/rating-indicator/components/rating-indicator.css
  libs/core/src/lib/rating-indicator/constants.ts
  libs/core/src/lib/rating-indicator/public_api.ts
  libs/core/src/lib/rating-indicator/rating-indicator.module.ts
Labels: Fiori 3 component, core

#3931 fix: (Platform) show default format for placeholder in DatetimePicker docs
  apps/docs/src/app/platform/component-docs/platform-forms/platform-datetime-picker/platform-datetime-picker-examples/platform-datetime-picker-basic-example.component.html
  apps/docs/src/app/platform/component-docs/platform-forms/platform-datetime-picker/platform-datetime-picker-examples/platform-datetime-picker-disable-function-example.component.html
  apps/docs/src/app/platform/component-docs/platform-forms/platform-datetime-picker/platform-datetime-picker-examples/platform-datetime-picker-reactive-example.component.html
Labels: bug, platform

#3947 chore: Add hotfix CI pipeline, remove archive pipeline
  .ci-env/flags.sh
  .travis.yml
  ci-scripts/hotfix-publish.sh
  ci-scripts/publish.sh
  package.json
  scripts/archive-publish-release.sh
  scripts/hotfix-publish-release.sh
Labels: tooling

#3948 chore: fixes to hotfix pipeline
  ci-scripts/hotfix-publish.sh
  scripts/hotfix-publish-release.sh
Labels: tooling

#3949 chore: fix hotfix pipeline
  ci-scripts/hotfix-publish.sh
Labels: tooling

#3958 chore: Add packages array to hotfix pipeline
  ci-scripts/hotfix-publish.sh
Labels: tooling

#3897 feat: (Core) introduce Wizard scroll
  apps/docs/src/app/core/component-docs/wizard/examples/wizard-branching-example.component.html
  apps/docs/src/app/core/component-docs/wizard/examples/wizard-branching-example.component.ts
  apps/docs/src/app/core/component-docs/wizard/examples/wizard-customizable-example.component.html
  apps/docs/src/app/core/component-docs/wizard/examples/wizard-customizable-example.component.ts
  apps/docs/src/app/core/component-docs/wizard/examples/wizard-example.component.html
  apps/docs/src/app/core/component-docs/wizard/examples/wizard-example.component.ts
  apps/docs/src/app/core/component-docs/wizard/examples/wizard-mobile-example.component.html
  apps/docs/src/app/core/component-docs/wizard/examples/wizard-mobile-example.component.ts
  apps/docs/src/app/core/component-docs/wizard/wizard-docs.component.html
  apps/docs/src/app/core/component-docs/wizard/wizard-docs.module.ts
  libs/core/src/lib/wizard/wizard-content/wizard-content.component.html
  libs/core/src/lib/wizard/wizard-content/wizard-content.component.scss
  libs/core/src/lib/wizard/wizard-content/wizard-content.component.ts
  libs/core/src/lib/wizard/wizard-next-step/wizard-next-step.component.ts
  libs/core/src/lib/wizard/wizard-step/wizard-step.component.html
  libs/core/src/lib/wizard/wizard-step/wizard-step.component.ts
  libs/core/src/lib/wizard/wizard.component.html
  libs/core/src/lib/wizard/wizard.component.scss
  libs/core/src/lib/wizard/wizard.component.spec.ts
  libs/core/src/lib/wizard/wizard.component.ts
  libs/core/src/lib/wizard/wizard.module.ts
Labels: 0.25.0, denoland
