Repository SAP/fundamental-ngx, pull requests merged in 2020-02, with the labels that each got.

#1900 fix: add new way to put class into modal container
  apps/docs/src/app/core/component-docs/modal/examples/backdrop-examples/backdrop-examples.component.html
  apps/docs/src/app/core/component-docs/modal/examples/backdrop-examples/backdrop-examples.component.ts
  apps/docs/src/app/core/component-docs/modal/modal-docs.component.html
  apps/docs/src/styles.scss
  libs/core/src/lib/modal/modal-service/modal.service.ts
  libs/core/src/lib/modal/modal-utils/modal-config.ts
Labels: v.0.14.0

#1927 chore: storybook updated
  package-lock.json
  package.json
Labels: dependencies

#1904 fix: add new link component
  apps/docs/src/app/core/api-files.ts
  apps/docs/src/app/core/component-docs/link/examples/link-example.component.html
  apps/docs/src/app/core/component-docs/link/examples/link-example.component.ts
  apps/docs/src/app/core/component-docs/link/link-docs.component.html
  apps/docs/src/app/core/component-docs/link/link-docs.component.ts
  apps/docs/src/app/core/component-docs/link/link-header/link-header.component.html
  apps/docs/src/app/core/component-docs/link/link-header/link-header.component.ts
  apps/docs/src/app/core/components.ts
  apps/docs/src/app/core/core-documentation.routes.ts
  apps/docs/src/app/core/documentation/core-documentation.component.ts
  apps/docs/src/styles.scss
  libs/core/src/index.ts
  libs/core/src/lib/fundamental-ngx-core.module.ts
  libs/core/src/lib/link/link.component.scss
  libs/core/src/lib/link/link.component.spec.ts
  libs/core/src/lib/link/link.component.ts
  libs/core/src/lib/link/link.module.ts
  libs/core/src/lib/link/public_api.ts
Labels: v.0.14.0

#1933 chore: optimize netlify build
  netlify.toml
  package.json
Labels: tooling

#1937 fix: Add nested-list module export to side-nav module
  libs/core/src/lib/side-navigation/side-navigation.module.ts
Labels: v.0.14.0

#1938 chore: fix netlify build
  package.json
Labels: tooling

#1903 feat: (platform) Link as a standalone component
  apps/docs/src/app/platform/api-files.ts
  apps/docs/src/app/platform/component-docs/platform-link/platform-link-docs.component.html
  apps/docs/src/app/platform/component-docs/platform-link/platform-link-docs.component.scss
  apps/docs/src/app/platform/component-docs/platform-link/platform-link-docs.component.spec.ts
  apps/docs/src/app/platform/component-docs/platform-link/platform-link-docs.component.ts
  apps/docs/src/app/platform/component-docs/platform-link/platform-link-examples/platform-link-disabled-emphasized-example.component.html
  apps/docs/src/app/platform/component-docs/platform-link/platform-link-examples/platform-link-disabled-example.component.html
  apps/docs/src/app/platform/component-docs/platform-link/platform-link-examples/platform-link-emphasized-example.component.html
  apps/docs/src/app/platform/component-docs/platform-link/platform-link-examples/platform-link-examples.component.ts
  apps/docs/src/app/platform/component-docs/platform-link/platform-link-examples/platform-link-icon-example.component.html
  apps/docs/src/app/platform/component-docs/platform-link/platform-link-examples/platform-link-inverted-example.component.html
  apps/docs/src/app/platform/component-docs/platform-link/platform-link-examples/platform-link-standard-example.component.html
  apps/docs/src/app/platform/component-docs/platform-link/platform-link-examples/platform-link-truncated-example.component.html
  apps/docs/src/app/platform/component-docs/platform-link/platform-link-header/platform-link-header.component.html
  apps/docs/src/app/platform/component-docs/platform-link/platform-link-header/platform-link-header.component.ts
  apps/docs/src/app/platform/documentation/platform-documentation.component.ts
  apps/docs/src/app/platform/platform-documentation.module.ts
  apps/docs/src/app/platform/platform-documentation.routes.ts
  libs/platform/src/index.ts
  libs/platform/src/lib/components/link/link.component.html
  libs/platform/src/lib/components/link/link.component.scss
  libs/platform/src/lib/components/link/link.component.spec.ts
  libs/platform/src/lib/components/link/link.component.ts
  libs/platform/src/lib/components/link/link.module.ts
  libs/platform/src/lib/components/link/public_api.ts
  libs/platform/src/lib/platform.module.ts
Labels: platform

#1952 chore: storybook update 5.3.13
  package-lock.json
  package.json
Labels: dependencies

#1941 fix: Speed up netlify builds
  angular.json
  ci-scripts/publish.sh
  package.json
Labels: bug, core

#1942 fix: (platform) Link component documentation and template structure change
  apps/docs/src/app/platform/component-docs/platform-link/platform-link-examples/platform-link-disabled-emphasized-example.component.html
  apps/docs/src/app/platform/component-docs/platform-link/platform-link-examples/platform-link-disabled-example.component.html
  apps/docs/src/app/platform/component-docs/platform-link/platform-link-examples/platform-link-emphasized-example.component.html
  apps/docs/src/app/platform/component-docs/platform-link/platform-link-examples/platform-link-examples.component.ts
  apps/docs/src/app/platform/component-docs/platform-link/platform-link-examples/platform-link-inverted-example.component.html
  apps/docs/src/app/platform/component-docs/platform-link/platform-link-examples/platform-link-truncated-example.component.html
  apps/docs/src/app/platform/component-docs/platform-link/platform-link-header/platform-link-header.component.html
  apps/docs/src/app/platform/component-docs/platform-link/platform-link-header/platform-link-header.component.ts
  libs/platform/src/lib/components/link/link.component.html
  libs/platform/src/lib/components/link/link.component.ts
Labels: platform

#1969 docs: Token, change naming on example
  apps/docs/src/app/core/component-docs/token/token-docs.component.html
Labels: documentation

#1977 docs: fix the time-picker example title and removed messages from localization editor
  apps/docs/src/app/core/component-docs/localization-editor/examples/localization-editor-forms-example.component.html
  apps/docs/src/app/core/component-docs/time-picker/examples/time-picker-no-seconds-example.component.html
  apps/docs/src/app/core/component-docs/time-picker/time-picker-docs.component.html
Labels: documentation

#1974 docs: update the library name
  .github/ISSUE_TEMPLATE.md
  CONTRIBUTING.md
  NEW_COMPONENT.md
  NEW_PLATFORM_COMPONENT.md
  PLATFORM_README.md
  README.md
  apps/docs/src/app/core/component-docs/table/table-docs.component.html
  apps/docs/src/app/core/component-docs/time-picker/time-picker-header/time-picker-header.component.html
  apps/docs/src/index.html
  libs/core/README.md
  libs/core/schematics/ng-add/schema.json
  libs/core/src/lib/shellbar/model/shellbar-user.ts
  libs/core/src/lib/utils/abstract-fd-ngx-class.ts
  libs/platform/README.md
  package.json
Labels: documentation

#1965 fix: for ignore flag for netlify
  ignore.sh
  netlify.toml
Labels: tooling

#1976 docs: use link component in list example
  apps/docs/src/app/core/component-docs/list/examples/list-example.component.html
Labels: documentation

#1975 docs: table checkbox
  apps/docs/src/app/core/component-docs/table/examples/table-checkboxes-example.component.html
  apps/docs/src/app/core/component-docs/table/examples/table-checkboxes-example.component.ts
Labels: bug

#1973 chore: Fix Stackblitz Service
  apps/docs/src/app/core/component-docs/panel/panel-docs.component.ts
  apps/docs/src/app/documentation/core-helpers/stackblitz/stackblitz.service.ts
Labels: tooling, v.0.14.0

#1991 chore: Change memory limit on travis
  .travis.yml
Labels: tooling

#1982 fix: rtl service added
  apps/docs/src/app/documentation/core-helpers/component-example/component-example.component.ts
  apps/docs/src/app/documentation/core-helpers/directionality/directionality.component.ts
  libs/core/src/lib/utils/public_api.ts
  libs/core/src/lib/utils/services/rtl.service.ts
Labels: RTL

#1987 docs: Replace Object.values by Object.keys in examples
  apps/docs/src/app/core/component-docs/checkbox/examples/checkbox-reactive-forms-example.component.ts
Labels: documentation

#1992 chore: fix security issues
  package-lock.json
  package.json
Labels: security

#1996 test: tabs - disable randomly failing tab list tests
  .travis.yml
  libs/core/src/lib/tabs/tab-list.component.spec.ts
Labels: testing, v.0.14.0

#1995 chore: disabled ivy on netlify till angular 9
  angular.json
  apps/docs/tsconfig.netlify.json
Labels: v.0.14.0

#1988 fix: tabs rtl service
  libs/core/src/lib/tabs/tabs.service.ts
Labels: v.0.14.0

#1994 fix: Remove event prevention on Checkbox
  libs/core/src/lib/checkbox/checkbox.module.ts
  libs/core/src/lib/checkbox/checkbox/checkbox.component.html
  libs/core/src/lib/checkbox/checkbox/checkbox.component.ts
Labels: v.0.14.0

#2003 chore: added feature to run unit test in parallel mode
  karma.conf.js
  package-lock.json
  package.json
Labels: tooling, v.0.14.0

#1958 fix: breadcrumb 0.5.0
  apps/docs/src/app/core/component-docs/breadcrumb/breadcrumb-docs.component.html
  apps/docs/src/app/core/component-docs/breadcrumb/breadcrumb-docs.component.ts
  apps/docs/src/app/core/component-docs/breadcrumb/examples/breadcrumb-examples.component.ts
  apps/docs/src/app/core/component-docs/breadcrumb/examples/breadcrumb-href-example.component.html
  apps/docs/src/app/core/component-docs/breadcrumb/examples/breadcrumb-responsive-example.component.html
  apps/docs/src/app/core/component-docs/breadcrumb/examples/breadcrumb-routerLink-example.component.html
  apps/docs/src/app/core/components.ts
  libs/core/src/lib/breadcrumb/breadcrumb-item.directive.ts
  libs/core/src/lib/breadcrumb/breadcrumb-link.directive.ts
  libs/core/src/lib/breadcrumb/breadcrumb.component.html
  libs/core/src/lib/breadcrumb/breadcrumb.component.scss
  libs/core/src/lib/breadcrumb/breadcrumb.component.spec.ts
  libs/core/src/lib/breadcrumb/breadcrumb.component.ts
  libs/core/src/lib/breadcrumb/breadcrumb.module.ts
  src/stories/breadcrumb/fd-breadcrumb.stories.ts
Labels: v.0.14.0

#2002 fix: unit test fails for tokenizer
  libs/core/src/lib/token/tokenizer.component.spec.ts
Labels: v.0.14.0

#1985 fix: Change select loader positioning to absolute center
  libs/core/src/lib/select/select.component.html
  libs/core/src/lib/select/select.component.scss
Labels: v.0.14.0

#1984 docs: (rtl) add RTL support for examples of scroll spy
  apps/docs/src/app/core/component-docs/scroll-spy/examples/scroll-spy-custom-example/scroll-spy-custom-example.component.html
  apps/docs/src/app/core/component-docs/scroll-spy/examples/scroll-spy-custom-example/scroll-spy-custom-example.component.scss
  apps/docs/src/app/core/component-docs/scroll-spy/examples/scroll-spy-custom-example/scroll-spy-custom-example.component.ts
  apps/docs/src/app/core/component-docs/scroll-spy/examples/scroll-spy-custom-offset/scroll-spy-offset-example.component.html
  apps/docs/src/app/core/component-docs/scroll-spy/examples/scroll-spy-custom-offset/scroll-spy-offset-example.component.scss
  apps/docs/src/app/core/component-docs/scroll-spy/examples/scroll-spy-custom-offset/scroll-spy-offset-example.component.ts
  apps/docs/src/app/core/component-docs/scroll-spy/examples/scroll-spy-example/scroll-spy-example.component.html
  apps/docs/src/app/core/component-docs/scroll-spy/examples/scroll-spy-example/scroll-spy-example.component.scss
  apps/docs/src/app/core/component-docs/scroll-spy/scroll-spy-docs.component.html
  apps/docs/src/styles.scss
Labels: RTL, v.0.14.0

#2001 fix: pagination RTL idea
  libs/core/src/lib/pagination/pagination.component.html
  libs/core/src/lib/pagination/pagination.component.scss
  libs/core/src/lib/pagination/pagination.component.spec.ts
  libs/core/src/lib/pagination/pagination.component.ts
  libs/core/src/lib/pagination/pagination.module.ts
  src/stories/pagination/fd-pagination.stories.ts
Labels: RTL, v.0.14.0

#2019 fix: product switch drag and drop blue box issue
  libs/core/src/lib/product-switch/product-switch-body/product-switch-body.component.scss
Labels: bug, v.0.14.0

#2015 fix: remove 2nd ellipses when 3rd to last page is selected
  libs/core/src/lib/pagination/pagination.service.spec.ts
  libs/core/src/lib/pagination/pagination.service.ts
Labels: bug

#2024 chore: increased execution units to 6
  karma.conf.js
Labels: tooling, v.0.14.0

#2021 Fix: (platform) stackblitz module not declared for PlatformDocumentationModule
  apps/docs/src/app/platform/platform-documentation.module.ts
Labels: platform, v.0.14.0

#2026 fix: Restore absolute modal position, fix ie11
  libs/core/src/lib/modal/modal-service/modal.service.spec.ts
  libs/core/src/lib/modal/modal-service/modal.service.ts
  libs/core/src/lib/modal/modal.component.scss
Labels: v.0.14.0

#2017 fix: make multi-input in modal example modal wider
  apps/docs/src/app/core/component-docs/popover/examples/popover-modal/popover-modal-example.component.html
  libs/core/src/lib/multi-input/multi-input.component.scss
Labels: v.0.14.0

#2033 fix: Add 3rd state support for Ie11
  libs/core/src/lib/checkbox/checkbox/checkbox.component.html
  libs/core/src/lib/checkbox/checkbox/checkbox.component.ts
Labels: IE11, v.0.14.0

#2035 chore: update to fundamental-styles 0.6.0
  libs/core/src/lib/multi-input/multi-input.component.scss
  libs/core/src/lib/popover/popover.component.scss
  package-lock.json
  package.json
Labels: v.0.15.0

#2042 docs: various minor doc issues
  apps/docs/src/app/core/component-docs/button-group/button-group-docs.component.html
  apps/docs/src/app/core/component-docs/scroll-spy/scroll-spy-docs.component.html
Labels: documentation, v.0.15.0

#2054 chore: update node version for security fix
  .nvmrc
  .travis.yml
Labels: dependencies, tooling

#2049 docs: Remove main language input from popover
  apps/docs/src/app/core/component-docs/localization-editor/examples/localization-editor-forms-example.component.html
  apps/docs/src/app/core/component-docs/localization-editor/examples/localization-editor-forms-example.component.ts
Labels: documentation

#2045 fix: Update Dropdown with icons example markup
  apps/docs/src/app/core/component-docs/dropdown/examples/dropdown-icons-example.component.html
Labels: documentation

#2047 fix: Add RTL support for input messages
  libs/core/src/lib/form/form-input-message-group/form-input-message-group.component.html
  libs/core/src/lib/form/form-input-message-group/form-input-message-group.component.ts
  libs/core/src/lib/input-group/input-group-number.component.html
  libs/core/src/lib/nested-list/nested-list-popover/nested-list-popover.component.ts
Labels: bug, v0.14.1

#2038 fix: combobox search term change popover positioning bug
  libs/core/src/lib/combobox/combobox.component.spec.ts
  libs/core/src/lib/combobox/combobox.component.ts
Labels: v.0.15.0

#2004 docs: separate core modules
  apps/docs/src/app/core/component-docs/action-bar/action-bar-docs.module.ts
  apps/docs/src/app/core/component-docs/alert/alert-docs.module.ts
  apps/docs/src/app/core/component-docs/badge-label/badge-label-docs.module.ts
  apps/docs/src/app/core/component-docs/breadcrumb/breadcrumb-docs.module.ts
  apps/docs/src/app/core/component-docs/busy-indicator/busy-indicator-docs.module.ts
  apps/docs/src/app/core/component-docs/button-group/button-group-docs.module.ts
  apps/docs/src/app/core/component-docs/button/button-docs.module.ts
  apps/docs/src/app/core/component-docs/calendar/calendar-docs.module.ts
  apps/docs/src/app/core/component-docs/checkbox/checkbox-docs.module.ts
  apps/docs/src/app/core/component-docs/combobox/combobox-docs.module.ts
  apps/docs/src/app/core/component-docs/date-picker/date-picker-docs.module.ts
  apps/docs/src/app/core/component-docs/datetime-picker/datetime-picker-docs.module.ts
  apps/docs/src/app/core/component-docs/dropdown/dropdown-docs.module.ts
  apps/docs/src/app/core/component-docs/file-input/file-input-docs.module.ts
  apps/docs/src/app/core/component-docs/icon/icon-docs.module.ts
  apps/docs/src/app/core/component-docs/identifier/identifier-docs.module.ts
  apps/docs/src/app/core/component-docs/image/image-docs.module.ts
  apps/docs/src/app/core/component-docs/infinite-scroll/infinite-scroll-docs.module.ts
  apps/docs/src/app/core/component-docs/inline-help/inline-help-docs.module.ts
  apps/docs/src/app/core/component-docs/input-group/input-group-docs.module.ts
  apps/docs/src/app/core/component-docs/input/input-docs.module.ts
  apps/docs/src/app/core/component-docs/layout-grid/layout-grid-docs.module.ts
  apps/docs/src/app/core/component-docs/link/link-docs.module.ts
  apps/docs/src/app/core/component-docs/list/list-docs.module.ts
  apps/docs/src/app/core/component-docs/loading-spinner-docs/loading-spinner-docs.module.ts
  apps/docs/src/app/core/component-docs/localization-editor/localization-editor-docs.module.ts
  apps/docs/src/app/core/component-docs/mega-menu/mega-menu-docs.module.ts
  apps/docs/src/app/core/component-docs/menu/menu-docs.module.ts
  apps/docs/src/app/core/component-docs/modal/modal-docs.module.ts
  apps/docs/src/app/core/component-docs/multi-input/multi-input-docs.module.ts
  apps/docs/src/app/core/component-docs/notification/notification-docs.module.ts
  apps/docs/src/app/core/component-docs/pagination/pagination-docs.module.ts
  apps/docs/src/app/core/component-docs/panel/panel-docs.module.ts
  apps/docs/src/app/core/component-docs/popover-directive/popover-directive-docs.module.ts
  apps/docs/src/app/core/component-docs/popover/popover-docs.module.ts
  apps/docs/src/app/core/component-docs/product-switch/product-switch-docs.module.ts
  apps/docs/src/app/core/component-docs/radio/radio-docs.module.ts
  apps/docs/src/app/core/component-docs/scroll-spy/scroll-spy-docs.module.ts
  apps/docs/src/app/core/component-docs/select-native/select-native-docs.module.ts
  apps/docs/src/app/core/component-docs/select/select-docs.module.ts
  apps/docs/src/app/core/component-docs/shellbar/shellbar-docs.module.ts
  apps/docs/src/app/core/component-docs/side-navigation/side-navigation-docs.module.ts
  apps/docs/src/app/core/component-docs/split-button/split-button-docs.module.ts
  apps/docs/src/app/core/component-docs/switch/switch-docs.module.ts
  apps/docs/src/app/core/component-docs/table/table-docs.module.ts
  apps/docs/src/app/core/component-docs/tabs/tabs-docs.module.ts
  apps/docs/src/app/core/component-docs/textarea/textarea-docs.module.ts
  apps/docs/src/app/core/component-docs/tile/tile-docs.module.ts
  apps/docs/src/app/core/component-docs/time-picker/time-picker-docs.module.ts
  apps/docs/src/app/core/component-docs/time/time-docs.module.ts
  apps/docs/src/app/core/component-docs/token/token-docs.module.ts
  apps/docs/src/app/core/component-docs/tree/tree-docs.module.ts
  apps/docs/src/app/documentation/shared-core-modules.ts
  apps/docs/src/app/documentation/shared-documentation.module.ts
  apps/docs/src/app/platform/platform-documentation.module.ts
  libs/core/src/lib/form/form-control/form-control.component.scss
Labels: v.0.15.0

#2048 docs: (select) fix example
  apps/docs/src/app/core/component-docs/select/examples/select-basic-example/select-basic-example.component.html
Labels: v0.14.1

#2051 fix: rtl support added to mega menu
  libs/core/src/lib/mega-menu/mega-menu-item/mega-menu-item.component.ts
  libs/core/src/lib/mega-menu/mega-menu.component.html
  libs/core/src/lib/mega-menu/mega-menu.component.scss
  libs/core/src/lib/mega-menu/mega-menu.component.ts
  libs/core/src/lib/utils/keyboard-unification.ts
  libs/core/src/lib/utils/public_api.ts
Labels: v0.14.1

#2046 fix: dropdown menu position fixed
  apps/docs/src/app/core/component-docs/popover/examples/popover-dropdown/popover-dropdown-example.component.ts
  apps/docs/src/app/core/component-docs/popover/examples/popover-dropdown/popover-dropdown.component.html
  libs/core/src/lib/popover/popover.component.ts
Labels: v0.14.1

#2067 fix: (select) fix select close behaviour
  libs/core/src/lib/select/option/option.component.scss
  libs/core/src/lib/select/option/option.component.ts
  libs/core/src/lib/select/select.component.ts
Labels: v0.14.1

#2069 feat: List component preparation before dropdowns
  apps/docs/src/app/core/api-files.ts
  apps/docs/src/app/core/component-docs/list/examples/list-actions-example.component.html
  apps/docs/src/app/core/component-docs/list/examples/list-checkbox-example.component.html
  apps/docs/src/app/core/component-docs/list/examples/list-checkbox-form-example.component.html
  apps/docs/src/app/core/component-docs/list/examples/list-checkbox-form-example.component.ts
  apps/docs/src/app/core/component-docs/list/examples/list-complex-example.component.html
  apps/docs/src/app/core/component-docs/list/examples/list-example.component.html
  apps/docs/src/app/core/component-docs/list/examples/list-examples.component.ts
  apps/docs/src/app/core/component-docs/list/examples/list-icon-example.component.html
  apps/docs/src/app/core/component-docs/list/examples/list-secondary-example.component.html
  apps/docs/src/app/core/component-docs/list/examples/list-single-select-example.component.html
  apps/docs/src/app/core/component-docs/list/examples/list-single-select-example.component.ts
  apps/docs/src/app/core/component-docs/list/list-docs.component.html
  apps/docs/src/app/core/component-docs/list/list-docs.component.ts
  apps/docs/src/app/core/component-docs/list/list-docs.module.ts
  libs/core/src/lib/form/form-message/form-message.component.html
  libs/core/src/lib/form/form-message/form-message.component.ts
  libs/core/src/lib/list/list-action.directive.spec.ts
  libs/core/src/lib/list/list-action.directive.ts
  libs/core/src/lib/list/list-item.directive.spec.ts
  libs/core/src/lib/list/list-item.directive.ts
  libs/core/src/lib/list/list-message.directive.spec.ts
  libs/core/src/lib/list/list-message.directive.ts
  libs/core/src/lib/list/list.component.scss
  libs/core/src/lib/list/list.component.spec.ts
  libs/core/src/lib/list/list.component.ts
  libs/core/src/lib/list/list.directives.ts
  libs/core/src/lib/list/list.module.ts
  libs/core/src/lib/list/public_api.ts
Labels: v.0.15.0

#2077 fix: add new Bar component
  apps/docs/src/app/core/api-files.ts
  apps/docs/src/app/core/component-docs/bar/bar-docs.component.html
  apps/docs/src/app/core/component-docs/bar/bar-docs.component.ts
  apps/docs/src/app/core/component-docs/bar/bar-docs.module.ts
  apps/docs/src/app/core/component-docs/bar/bar-header/bar-header.component.html
  apps/docs/src/app/core/component-docs/bar/bar-header/bar-header.component.ts
  apps/docs/src/app/core/component-docs/bar/examples/bar-default-example.component.html
  apps/docs/src/app/core/component-docs/bar/examples/bar-examples.component.ts
  apps/docs/src/app/core/component-docs/bar/examples/bar-floating-footer-example.component.html
  apps/docs/src/app/core/component-docs/bar/examples/bar-footer-example.component.html
  apps/docs/src/app/core/component-docs/bar/examples/bar-header-example.component.html
  apps/docs/src/app/core/component-docs/bar/examples/bar-header-subheader-example.component.html
  apps/docs/src/app/core/component-docs/bar/examples/bar-page-example.component.html
  apps/docs/src/app/core/component-docs/bar/examples/bar-page-responsive-example.component.html
  apps/docs/src/app/core/component-docs/bar/examples/bar-subheader-example.component.html
  apps/docs/src/app/core/core-documentation.routes.ts
  apps/docs/src/app/core/documentation/core-documentation.component.ts
  libs/core/src/index.ts
  libs/core/src/lib/bar/bar.component.html
  libs/core/src/lib/bar/bar.component.scss
  libs/core/src/lib/bar/bar.component.spec.ts
  libs/core/src/lib/bar/bar.component.ts
  libs/core/src/lib/bar/bar.module.ts
  libs/core/src/lib/bar/directives/bar-element.directive.spec.ts
  libs/core/src/lib/bar/directives/bar-element.directive.ts
  libs/core/src/lib/bar/directives/bar-left.directive.spec.ts
  libs/core/src/lib/bar/directives/bar-left.directive.ts
  libs/core/src/lib/bar/directives/bar-middle.directive.spec.ts
  libs/core/src/lib/bar/directives/bar-middle.directive.ts
  libs/core/src/lib/bar/directives/bar-right.directive.spec.ts
  libs/core/src/lib/bar/directives/bar-right.directive.ts
  libs/core/src/lib/bar/public_api.ts
  libs/core/src/lib/fundamental-ngx-core.module.ts
  src/stories/bar/fd-bar.stories.ts
Labels: v.0.15.0

#2081 docs: fix the broken Bar documentation
  apps/docs/src/app/core/component-docs/bar/bar-docs.component.html
Labels: documentation

#2079 fix: upgrade shellbar to fundamental-styles 0.6.0 update
  apps/docs/src/app/core/component-docs/shellbar/examples/shellbar-advanced/shellbar-advanced-example.component.html
  apps/docs/src/app/core/component-docs/shellbar/examples/shellbar-advanced/shellbar-advanced-example.component.ts
  apps/docs/src/app/core/component-docs/shellbar/examples/shellbar-side-nav/shellbar-side-nav-example.component.html
  apps/docs/src/app/core/component-docs/shellbar/shellbar-docs.component.html
  apps/docs/src/app/core/component-docs/shellbar/shellbar-docs.component.ts
  apps/docs/src/app/core/component-docs/shellbar/shellbar-docs.module.ts
  libs/core/src/lib/combobox/combobox.component.html
  libs/core/src/lib/combobox/combobox.component.ts
  libs/core/src/lib/input-group/input-group.component.html
  libs/core/src/lib/input-group/input-group.component.ts
  libs/core/src/lib/shellbar/product-menu/product-menu.component.html
  libs/core/src/lib/shellbar/shellbar-action/shellbar-action.component.html
  libs/core/src/lib/shellbar/shellbar-actions/shellbar-actions-mobile.component.html
  libs/core/src/lib/shellbar/shellbar-actions/shellbar-actions-mobile.component.ts
  libs/core/src/lib/shellbar/shellbar-actions/shellbar-actions.component.html
  libs/core/src/lib/shellbar/shellbar-actions/shellbar-actions.component.scss
  libs/core/src/lib/shellbar/shellbar-actions/shellbar-actions.component.spec.ts
  libs/core/src/lib/shellbar/shellbar-actions/shellbar-actions.component.ts
  libs/core/src/lib/shellbar/shellbar-sidenav.directive.ts
  libs/core/src/lib/shellbar/shellbar.component.html
  libs/core/src/lib/shellbar/shellbar.component.scss
  libs/core/src/lib/shellbar/shellbar.component.ts
  libs/core/src/lib/shellbar/shellbar.module.ts
  libs/core/src/lib/shellbar/user-menu/shellbar-user-menu.component.html
  src/stories/shellbar/fd-shellbar.stories.ts
Labels: v.0.15.0

#2044 fix: placeholder's position fixed in rtl
  libs/core/src/lib/select/select.component.html
  libs/core/src/lib/select/select.component.scss
  libs/core/src/lib/select/select.component.spec.ts
  libs/core/src/lib/select/select.component.ts
  libs/platform/src/lib/components/select/select.component.ts
Labels: v0.14.1

#2080 fix: upgrade Multi Input to fundamental-styles 0.6.0
  apps/docs/src/app/core/api-files.ts
  apps/docs/src/app/core/component-docs/multi-input/examples/multi-input-compact-example/multi-input-compact-example.component.html
  apps/docs/src/app/core/component-docs/multi-input/examples/multi-input-compact-example/multi-input-compact-example.component.ts
  apps/docs/src/app/core/component-docs/multi-input/examples/multi-input-example/multi-input-example.component.html
  apps/docs/src/app/core/component-docs/multi-input/multi-input-docs.component.html
  apps/docs/src/app/core/component-docs/multi-input/multi-input-docs.component.ts
  apps/docs/src/app/core/component-docs/multi-input/multi-input-docs.module.ts
  libs/core/src/lib/checkbox/checkbox/checkbox.component.ts
  libs/core/src/lib/list/list-item.directive.ts
  libs/core/src/lib/list/list.directives.ts
  libs/core/src/lib/menu/menu-keyboard.service.ts
  libs/core/src/lib/multi-input/multi-input.component.html
  libs/core/src/lib/multi-input/multi-input.component.scss
  libs/core/src/lib/multi-input/multi-input.component.spec.ts
  libs/core/src/lib/multi-input/multi-input.component.ts
  libs/core/src/lib/multi-input/multi-input.module.ts
Labels: v.0.15.0
