Repository SAP/fundamental-ngx, pull requests merged in 2020-05, with the labels that each got.

#2445 fix: change static placement value
  libs/core/src/lib/product-switch/product-switch/product-switch.component.html
  libs/core/src/lib/product-switch/product-switch/product-switch.component.ts
Labels: bug

#2450 docs: update new component documentation
  NEW_COMPONENT.md
  apps/docs/src/assets/NEW_COMPONENT.md
Labels: bug, documentation

#2477 fix: add ariaLabel input to product-switch for button
  libs/core/src/lib/product-switch/product-switch/product-switch.component.html
  libs/core/src/lib/product-switch/product-switch/product-switch.component.ts
Labels: accessibility

#2443 test: add link to storybook
  src/stories/link/link.stories.ts
Labels: accessibility, testing

#2434 test: add side nav to storybook
  src/stories/sidenav/fd-side-nav.stories.ts
Labels: accessibility, testing

#2488 test: Lower parallel tests to 3
  karma.conf.js
Labels: testing

#2400 test: add textarea to storybook
  src/stories/textarea/fd-textarea.stories.ts
Labels: testing

#2484 fix: Add popover update, when created
  libs/core/src/lib/popover/popover-directive/popover.directive.ts
Labels: v.0.18.0

#2487 fix: Fix indirect import path - Select tests
  libs/core/src/lib/select/select.component.spec.ts
Labels: bug, v.0.18.0

#2482 fix: Fix failing Select alphanumeric navigation test
  libs/core/src/lib/select/select.component.spec.ts
Labels: v.0.18.0

#2489 fix:Platform(action bar) Adopting fiori3 style and redesigning the com…
  apps/docs/src/app/platform/component-docs/platform-action-bar/platform-action-bar-docs.component.html
  apps/docs/src/app/platform/component-docs/platform-action-bar/platform-action-bar-docs.component.scss
  apps/docs/src/app/platform/component-docs/platform-action-bar/platform-action-bar-docs.component.ts
  apps/docs/src/app/platform/component-docs/platform-action-bar/platform-action-bar-examples/platform-action-bar-contextual-menu-example.component.html
  apps/docs/src/app/platform/component-docs/platform-action-bar/platform-action-bar-examples/platform-action-bar-contextual-menu-example.component.scss
  apps/docs/src/app/platform/component-docs/platform-action-bar/platform-action-bar-examples/platform-action-bar-contextual-menu-example.component.ts
  apps/docs/src/app/platform/component-docs/platform-action-bar/platform-action-bar-examples/platform-action-bar-edit-title-example.component.html
  apps/docs/src/app/platform/component-docs/platform-action-bar/platform-action-bar-examples/platform-action-bar-edit-title-example.component.scss
  apps/docs/src/app/platform/component-docs/platform-action-bar/platform-action-bar-examples/platform-action-bar-edit-title-example.component.ts
  apps/docs/src/app/platform/component-docs/platform-action-bar/platform-action-bar-examples/platform-action-bar-positive-and-negative-action-example.component.html
  apps/docs/src/app/platform/component-docs/platform-action-bar/platform-action-bar-examples/platform-action-bar-positive-and-negative-action-example.component.scss
  apps/docs/src/app/platform/component-docs/platform-action-bar/platform-action-bar-examples/platform-action-bar-positive-and-negative-action-example.component.ts
  apps/docs/src/app/platform/component-docs/platform-action-bar/platform-action-bar-examples/platform-action-bar-simple-example.component.html
  apps/docs/src/app/platform/component-docs/platform-action-bar/platform-action-bar-examples/platform-action-bar-simple-example.component.scss
  apps/docs/src/app/platform/component-docs/platform-action-bar/platform-action-bar-examples/platform-action-bar-simple-example.component.ts
  apps/docs/src/app/platform/component-docs/platform-action-bar/platform-action-bar-examples/platform-action-bar-with-back-button-example.component.html
  apps/docs/src/app/platform/component-docs/platform-action-bar/platform-action-bar-examples/platform-action-bar-with-back-button-example.component.scss
  apps/docs/src/app/platform/component-docs/platform-action-bar/platform-action-bar-examples/platform-action-bar-with-back-button-example.component.ts
  apps/docs/src/app/platform/component-docs/platform-action-bar/platform-action-bar-examples/platform-action-bar-with-description-example.component.html
  apps/docs/src/app/platform/component-docs/platform-action-bar/platform-action-bar-examples/platform-action-bar-with-description-example.component.scss
  apps/docs/src/app/platform/component-docs/platform-action-bar/platform-action-bar-examples/platform-action-bar-with-description-example.component.ts
  apps/docs/src/app/platform/component-docs/platform-action-bar/platform-action-bar-examples/platform-action-bar-with-long-title-example.component.html
  apps/docs/src/app/platform/component-docs/platform-action-bar/platform-action-bar-examples/platform-action-bar-with-long-title-example.component.scss
  apps/docs/src/app/platform/component-docs/platform-action-bar/platform-action-bar-examples/platform-action-bar-with-long-title-example.component.ts
  apps/docs/src/app/platform/component-docs/platform-action-bar/platform-action-bar-header/platform-action-bar-header.component.html
  apps/docs/src/app/platform/component-docs/platform-action-bar/platform-action-bar-header/platform-action-bar-header.component.ts
  apps/docs/src/app/platform/platform-documentation.module.ts
  apps/docs/src/app/platform/platform-documentation.routes.ts
  libs/platform/src/lib/components/action-bar/action-bar-actions/action-bar-actions.component.html
  libs/platform/src/lib/components/action-bar/action-bar-actions/action-bar-actions.component.spec.ts
  libs/platform/src/lib/components/action-bar/action-bar-actions/action-bar-actions.component.ts
  libs/platform/src/lib/components/action-bar/action-bar.component.html
  libs/platform/src/lib/components/action-bar/action-bar.component.spec.ts
  libs/platform/src/lib/components/action-bar/action-bar.component.ts
  libs/platform/src/lib/components/action-bar/action-bar.module.ts
  libs/platform/src/lib/components/action-bar/public_api.ts
  libs/platform/src/lib/components/action-button-group/action-button-group.component.html
  libs/platform/src/lib/components/action-button-group/action-button-group.component.scss
  libs/platform/src/lib/components/action-button-group/action-button-group.component.spec.ts
  libs/platform/src/lib/components/action-button-group/action-button-group.component.ts
  libs/platform/src/lib/components/action-button-group/action-button-group.module.ts
  libs/platform/src/lib/components/action-button-group/public_api.ts
  libs/platform/src/lib/platform.module.ts
Labels: platform

#2510 fix: Add default button type to buttons
  libs/core/src/lib/button/button.component.ts
Labels: v.0.18.0

#2509 fix: Add default behaviour to checkbox
  apps/docs/src/app/core/component-docs/checkbox/examples/checkbox-reactive-forms-example.component.ts
  libs/core/src/lib/checkbox/checkbox/checkbox.component.ts
Labels: v.0.18.0

#2515 fix: ie11 fixed
  package-lock.json
  package.json
Labels: bug

#2516 fix: Remove hard coded background color from popover
  libs/core/src/lib/popover/popover-directive/popover-container.scss
Labels: v.0.18.0

#2524 docs: Remove menu with checkbox example
  apps/docs/src/app/core/component-docs/menu/examples/menu-addon-example.component.html
Labels: documentation

#2523 docs: Hide select mobile section
  apps/docs/src/app/core/component-docs/select/select-docs.component.html
Labels: documentation, v.0.18.0

#2512 fix: add tabindex to shellbar button and user menu
  libs/core/src/lib/shellbar/user-menu/shellbar-user-menu.component.html
Labels: accessibility, bug, v.0.18.0

#2526 docs: fix the calendars using moment.js localization packages
  apps/docs/src/app/core/component-docs/calendar/examples/calendar--i18n-moment-example.component.ts
  apps/docs/src/app/core/component-docs/date-picker/examples/date-picker-complex-i18n-example/date-picker-complex-i18n-example.component.ts
  apps/docs/src/app/core/component-docs/datetime-picker/examples/datetime-picker-complex-i18n-example/datetime-picker-complex-i18n-example.component.ts
  package-lock.json
  package.json
Labels: datepicker, documentation, v.0.18.0

#2525 chore: update package versions to fix security issues
  package-lock.json
  package.json
Labels: dependencies, security, v.0.18.0

#2519 fix: (platform) implementation of lazyloading for platform Documentation
  apps/docs/src/app/platform/api-files.ts
  apps/docs/src/app/platform/component-docs/platform-action-bar/platform-action-bar.module.ts
  apps/docs/src/app/platform/component-docs/platform-button/platform-button.module.ts
  apps/docs/src/app/platform/component-docs/platform-forms/radio-group/platform-radio-group.module.ts
  apps/docs/src/app/platform/component-docs/platform-link/platform-link-examples/platform-link-examples.component.ts
  apps/docs/src/app/platform/component-docs/platform-link/platform-link-header/platform-link-header.component.ts
  apps/docs/src/app/platform/component-docs/platform-link/platform-link.module.ts
  apps/docs/src/app/platform/component-docs/platform-menu-button/platform-menu-button.module.ts
  apps/docs/src/app/platform/component-docs/platform-menu/platform-menu.module.ts
  apps/docs/src/app/platform/component-docs/platform-search-field/platform-search-field.module.ts
  apps/docs/src/app/platform/component-docs/platform-select/platform-select.module.ts
  apps/docs/src/app/platform/component-docs/platform-split-menu-button/platform-split-menu-button.module.ts
  apps/docs/src/app/platform/platform-documentation.module.ts
  apps/docs/src/app/platform/platform-documentation.routes.ts
  libs/platform/src/index.ts
  libs/platform/src/lib/components/form/public_api.ts
  libs/platform/src/lib/components/form/radio-group/public_api.ts
Labels: platform

#2513 fix: multi input mobile
  apps/docs/src/app/core/component-docs/multi-input/examples/multi-input-mobile-example/multi-input-mobile-example.component.html
  apps/docs/src/app/core/component-docs/multi-input/examples/multi-input-mobile-example/multi-input-mobile-example.component.ts
  apps/docs/src/app/core/component-docs/multi-input/multi-input-docs.component.html
  apps/docs/src/app/core/component-docs/multi-input/multi-input-docs.component.ts
  apps/docs/src/app/core/component-docs/multi-input/multi-input-docs.module.ts
  libs/core/src/lib/fundamental-ngx-core.module.ts
  libs/core/src/lib/multi-input/multi-input-mobile/multi-input-mobile.component.html
  libs/core/src/lib/multi-input/multi-input-mobile/multi-input-mobile.component.scss
  libs/core/src/lib/multi-input/multi-input-mobile/multi-input-mobile.component.spec.ts
  libs/core/src/lib/multi-input/multi-input-mobile/multi-input-mobile.component.ts
  libs/core/src/lib/multi-input/multi-input-mobile/multi-input-mobile.module.ts
  libs/core/src/lib/multi-input/multi-input.component.html
  libs/core/src/lib/multi-input/multi-input.component.scss
  libs/core/src/lib/multi-input/multi-input.component.spec.ts
  libs/core/src/lib/multi-input/multi-input.component.ts
  libs/core/src/lib/multi-input/multi-input.module.ts
  libs/core/src/lib/multi-input/public_api.ts
  libs/core/src/lib/utils/interfaces/mobile-mode-config.ts
  libs/core/src/lib/utils/public_api.ts
  package-lock.json
Labels: v.0.19.0

#2548 fix: added click event to set focus on input
  libs/core/src/lib/switch/switch.component.html
Labels: bug, v.0.19.0

#2547 fix: removed extra space from first and last child
  libs/core/src/lib/menu/menu.component.scss
Labels: bug, v.0.19.0

#2549 fix: more powerful selector added
  libs/core/src/lib/form/form-input-message-group/form-input-message-group.component.scss
Labels: bug, v.0.19.0

#2546 fix: missing button restored, removed selected state from header
  libs/core/src/lib/calendar/calendar-header/calendar-header.component.html
Labels: bug, v.0.19.0

#2567 fix: Add loaded to dialog component
  libs/core/src/lib/dialog/dialog-utils/dialog-ref.class.ts
  libs/core/src/lib/dialog/dialog.component.ts
Labels: v.0.18.1

#2545 docs: Update platform lib README.md with i18n section
  PLATFORM_README.md
  libs/platform/README.md
Labels: documentation, platform

#2570 chore: update mergeable
  .github/mergeable.yml
Labels: tooling

#2554 Fix(Platform): RTL Action bar back button.
  apps/docs/src/app/core/component-docs/action-bar/action-bar-docs.module.ts
  apps/docs/src/app/platform/component-docs/platform-action-bar/platform-action-bar-docs.component.html
  apps/docs/src/app/platform/component-docs/platform-action-bar/platform-action-bar-docs.component.ts
  apps/docs/src/app/platform/component-docs/platform-action-bar/platform-action-bar-examples/platform-action-bar-contextual-menu-example.component.html
  apps/docs/src/app/platform/component-docs/platform-action-bar/platform-action-bar-examples/platform-action-bar-cozy-mode-example.component.html
  apps/docs/src/app/platform/component-docs/platform-action-bar/platform-action-bar-examples/platform-action-bar-cozy-mode-example.component.scss
  apps/docs/src/app/platform/component-docs/platform-action-bar/platform-action-bar-examples/platform-action-bar-cozy-mode-example.component.ts
  apps/docs/src/app/platform/component-docs/platform-action-bar/platform-action-bar-examples/platform-action-bar-positive-and-negative-action-example.component.html
  apps/docs/src/app/platform/component-docs/platform-action-bar/platform-action-bar-examples/platform-action-bar-simple-example.component.html
  apps/docs/src/app/platform/component-docs/platform-action-bar/platform-action-bar-examples/platform-action-bar-with-back-button-example.component.html
  apps/docs/src/app/platform/component-docs/platform-action-bar/platform-action-bar-examples/platform-action-bar-with-description-example.component.html
  apps/docs/src/app/platform/component-docs/platform-action-bar/platform-action-bar-examples/platform-action-bar-with-long-title-example.component.html
  apps/docs/src/app/platform/component-docs/platform-action-bar/platform-action-bar.module.ts
  libs/platform/src/lib/components/action-bar/action-bar.component.html
  libs/platform/src/lib/components/action-bar/action-bar.component.ts
Labels: bug, platform

#2517 fix: Add Dialog Generated from Object
  apps/docs/src/app/core/component-docs/dialog/dialog-docs.component.html
  apps/docs/src/app/core/component-docs/dialog/dialog-docs.component.ts
  apps/docs/src/app/core/component-docs/dialog/dialog-docs.module.ts
  apps/docs/src/app/core/component-docs/dialog/examples/dialog-object-example/dialog-object-example.component.html
  apps/docs/src/app/core/component-docs/dialog/examples/dialog-object-example/dialog-object-example.component.ts
  libs/core/src/lib/dialog/default-dialog/default-dialog-object.ts
  libs/core/src/lib/dialog/default-dialog/default-dialog.component.html
  libs/core/src/lib/dialog/default-dialog/default-dialog.component.spec.ts
  libs/core/src/lib/dialog/default-dialog/default-dialog.component.ts
  libs/core/src/lib/dialog/dialog-container/dialog-container.component.spec.ts
  libs/core/src/lib/dialog/dialog-container/dialog-container.component.ts
  libs/core/src/lib/dialog/dialog-service/dialog.service.ts
  libs/core/src/lib/dialog/dialog.module.ts
  libs/core/src/lib/dialog/public_api.ts
Labels: v.0.19.0

#2573 fix: highlightsjs version downgraded in order to fix ie 11
  package-lock.json
  package.json
Labels: bug
