Repository SAP/fundamental-ngx, pull requests merged in 2020-03, with the labels that each got.

#2085 feat: refactor Popover component to reflect fundamental-styles 0.6.0
  apps/docs/src/app/core/component-docs/popover/examples/popover-simple/popover-example.component.html
  apps/docs/src/app/core/component-docs/popover/popover-docs.component.html
  apps/docs/src/app/core/component-docs/popover/popover-docs.module.ts
  libs/core/src/lib/popover/popover-body/popover-body-directives/popover-body-footer.directive.spec.ts
  libs/core/src/lib/popover/popover-body/popover-body-directives/popover-body-footer.directive.ts
  libs/core/src/lib/popover/popover-body/popover-body-directives/popover-body-header.directive.spec.ts
  libs/core/src/lib/popover/popover-body/popover-body-directives/popover-body-header.directive.ts
  libs/core/src/lib/popover/popover-body/popover-body-directives/popover-body-subheader.directive.spec.ts
  libs/core/src/lib/popover/popover-body/popover-body-directives/popover-body-subheader.directive.ts
  libs/core/src/lib/popover/popover.module.ts
  libs/core/src/lib/popover/public_api.ts
Labels: v.0.15.0

#2107 docs: link icon direction in rtl mode and provide example source code
  apps/docs/src/app/core/component-docs/link/examples/link-example.component.html
  apps/docs/src/app/core/component-docs/link/examples/link-example.component.ts
  apps/docs/src/app/core/component-docs/link/link-docs.component.ts
Labels: documentation, v.0.15.0

#2112 docs: Add RTL support to Simple Popovers example
  apps/docs/src/app/core/component-docs/popover/examples/popover-simple/popover-example.component.html
  apps/docs/src/app/core/component-docs/popover/examples/popover-simple/popover-example.component.ts
Labels: documentation, v.0.15.0

#2108 docs: bar nav arrow direction in RTL mode, example source code
  apps/docs/src/app/core/component-docs/bar/bar-docs.component.ts
  apps/docs/src/app/core/component-docs/bar/bar-docs.module.ts
  apps/docs/src/app/core/component-docs/bar/examples/bar-default-example.component.html
  apps/docs/src/app/core/component-docs/bar/examples/bar-default-example.component.ts
  apps/docs/src/app/core/component-docs/bar/examples/bar-header-example.component.html
  apps/docs/src/app/core/component-docs/bar/examples/bar-header-example.component.ts
  apps/docs/src/app/core/component-docs/bar/examples/bar-page-example.component.html
  apps/docs/src/app/core/component-docs/bar/examples/bar-page-example.component.ts
  apps/docs/src/app/core/component-docs/bar/examples/bar-page-responsive-example.component.html
  apps/docs/src/app/core/component-docs/bar/examples/bar-page-responsive-example.component.ts
  apps/docs/src/app/core/component-docs/bar/examples/bar-simple-examples.component.ts
Labels: documentation, v.0.15.0

#2113 fix: fixed popover in modal
  libs/core/src/lib/multi-input/multi-input.component.scss
Labels: bug, v.0.15.0

#2115 docs: get installation README.md up to date
  libs/core/README.md
Labels: documentation

#2154 fix: add type button to input group and select
  libs/core/src/lib/input-group/input-group.component.html
  libs/core/src/lib/select/select.component.html
Labels: bug

#2180 chore(deps-dev): storybook plugins updated
  package-lock.json
  package.json
Labels: dependencies, v.0.16.0

#2162 docs: update platform README.md with UpToDate info
  libs/platform/README.md
Labels: documentation

#2163 docs: add new section with headers/footers for popover
  apps/docs/src/app/core/component-docs/popover/examples/popover-complex-example/popover-complex-example.component.html
  apps/docs/src/app/core/component-docs/popover/examples/popover-complex-example/popover-complex-example.component.scss
  apps/docs/src/app/core/component-docs/popover/examples/popover-complex-example/popover-complex-example.component.ts
  apps/docs/src/app/core/component-docs/popover/examples/popover-simple/popover-example.component.scss
  apps/docs/src/app/core/component-docs/popover/popover-docs.component.html
  apps/docs/src/app/core/component-docs/popover/popover-docs.component.ts
  apps/docs/src/app/core/component-docs/popover/popover-docs.module.ts
Labels: v.0.16.0

#2156 fix: Change datepickers model on ngModelChange
  libs/core/src/lib/date-picker/date-picker.component.html
  libs/core/src/lib/datetime-picker/datetime-picker.component.html
  libs/core/src/lib/datetime-picker/datetime-picker.component.ts
Labels: datepicker, enhancement, v.0.15.x, v.0.16.0

#2195 fix: use menu button for "select a file"
  apps/docs/src/app/documentation/core-helpers/api/api.component.html
Labels: Defect Hunting, bug

#2199 test: remove errors in bar story
  src/stories/bar/fd-bar.stories.ts
Labels: Visual Testing

#2197 docs: remove duplicate section headings in the documentation
  apps/docs/src/app/core/component-docs/file-input/file-input-docs.component.html
  apps/docs/src/app/core/component-docs/image/image-docs.component.html
Labels: Defect Hunting, documentation

#2187 fix: bring icons and fonts
  angular.json
  apps/docs/src/styles.scss
  libs/core/src/lib/icon/icon.component.scss
  libs/platform/src/lib/components/button/button.component.ts
  package-lock.json
  package.json
Labels: v.0.16.0

#2191 docs: Update README and Contributing
  CONTRIBUTING.md
  README.md
Labels: documentation

#2200 test: breadcrumb storybook cleanup
  src/stories/breadcrumb/fd-breadcrumb.stories.ts
Labels: Visual Testing, testing

#2165 fix: remove product switch bullets
  apps/docs/src/styles.scss
  libs/core/src/lib/product-switch/product-switch-body/product-switch-body.component.scss
Labels: bug

#2196 fix: Make properties DND IE11 compatible
  libs/core/src/lib/utils/drag-and-drop/dnd-container/dnd-container.directive.spec.ts
  libs/core/src/lib/utils/drag-and-drop/dnd-container/dnd-container.directive.ts
  libs/core/src/lib/utils/drag-and-drop/dnd-list/dnd-list.directive.ts
Labels: Defect Hunting, IE11

#2186 chore: Add way to put provided services into stackblitz, follow more dependencies version
  apps/docs/src/app/core/component-docs/switch/examples/semantic-switch-example/semantic-switch-example.component.ts
  apps/docs/src/app/core/component-docs/switch/switch-docs.component.html
  apps/docs/src/app/documentation/core-helpers/code-example/example-file.ts
  apps/docs/src/app/documentation/core-helpers/stackblitz/interfaces/stackblitz-parameters.ts
  apps/docs/src/app/documentation/core-helpers/stackblitz/stackblitz-dependencies.ts
  apps/docs/src/app/documentation/core-helpers/stackblitz/stackblitz-module-wrapper.ts
  apps/docs/src/app/documentation/core-helpers/stackblitz/stackblitz.service.ts
  libs/core/src/lib/utils/services/rtl.service.ts
Labels: v.0.16.0

#2185 fix: fixed-width breadcrumb containers not collapsing overflowing breadcrumbs
  apps/docs/src/app/core/component-docs/breadcrumb/breadcrumb-docs.component.html
  libs/core/src/lib/breadcrumb/breadcrumb.component.ts
Labels: bug, v.0.16.0

#2190 fix: (input group) Add type of input group and example
  apps/docs/src/app/core/component-docs/input-group/examples/input-group-search-example/input-group-search-example.component.html
  apps/docs/src/app/core/component-docs/input-group/examples/input-group-search-example/input-group-search-example.component.ts
  apps/docs/src/app/core/component-docs/input-group/input-group-docs.component.html
  libs/core/src/lib/input-group/input-group.component.html
  libs/core/src/lib/input-group/input-group.component.ts
Labels: v.0.16.0

#2205 chore: Change property of anaytics CLI to false
  angular.json
Labels: angular 9

#2220 docs: fix width of documentation on small screens
  apps/docs/src/app/core/documentation/core-documentation.component.scss
Labels: documentation

#2221 fix: button fiori3 fixes and documentation improvements
  apps/docs/src/app/core/api-files.ts
  apps/docs/src/app/core/component-docs/button/button-docs.component.html
  apps/docs/src/app/core/component-docs/button/examples/button-icons-example.component.html
  apps/docs/src/app/core/component-docs/button/examples/button-types-example.component.html
  apps/docs/src/app/core/component-docs/segmented-button/segmented-button-docs.component.ts
  apps/docs/src/app/core/component-docs/segmented-button/segmented-button-docs.module.ts
  apps/docs/src/app/core/component-docs/split-button/examples/split-button-programmatical-example.component.html
  apps/docs/src/app/core/component-docs/split-button/examples/split-button-programmatical-example.component.ts
  apps/docs/src/app/core/component-docs/split-button/examples/split-button-types-example.component.ts
  libs/core/src/lib/button/button.component.ts
  libs/core/src/lib/segmented-button/segmented-button.component.ts
  libs/core/src/lib/segmented-button/segmented-button.directive.spec.ts
  libs/core/src/lib/segmented-button/segmented-button.directive.ts
  libs/core/src/lib/split-button/split-button.component.html
  libs/core/src/lib/split-button/split-button.component.ts
Labels: v.0.16.0

#2206 docs: improve datepicker/datetimepicker placeholder formatting info
  apps/docs/src/app/core/component-docs/date-picker/date-picker-docs.component.html
  apps/docs/src/app/core/component-docs/date-picker/examples/date-picker-format-example.component.ts
  apps/docs/src/app/core/component-docs/datetime-picker/datetime-picker-docs.component.html
  apps/docs/src/app/core/component-docs/datetime-picker/examples/datetime-format-example/datetime-format-example.component.html
Labels: documentation

#2202 test: add input with form message to storybok
  src/stories/fd-form-control/fd-form-control.stories.ts
Labels: Visual Testing, testing

#2230 docs: Update CONTRIBUTING.md
  CONTRIBUTING.md
Labels: documentation

#2219 fix: do not require callback function for shellbar actions
  angular.json
  apps/docs/src/app/core/api-files.ts
  apps/docs/src/app/core/component-docs/info-label/examples/info-label-default-example.component.html
  apps/docs/src/app/core/component-docs/info-label/examples/info-label-examples.component.ts
  apps/docs/src/app/core/component-docs/info-label/examples/info-label-icon-numeric-example.component.html
  apps/docs/src/app/core/component-docs/info-label/examples/info-label-text-example.component.html
  apps/docs/src/app/core/component-docs/info-label/examples/info-label-text-icon-example.component.html
  apps/docs/src/app/core/component-docs/info-label/info-label-docs.component.html
  apps/docs/src/app/core/component-docs/info-label/info-label-docs.component.ts
  apps/docs/src/app/core/component-docs/info-label/info-label-docs.module.ts
  apps/docs/src/app/core/component-docs/info-label/info-label-header/info-label-header.component.html
  apps/docs/src/app/core/component-docs/info-label/info-label-header/info-label-header.component.scss
  apps/docs/src/app/core/component-docs/info-label/info-label-header/info-label-header.component.ts
  apps/docs/src/app/core/core-documentation.routes.ts
  apps/docs/src/app/core/documentation/core-documentation.component.ts
  libs/core/src/index.ts
  libs/core/src/lib/button-group/button-group.component.scss
  libs/core/src/lib/fundamental-ngx-core.module.ts
  libs/core/src/lib/info-label/info-label.component.html
  libs/core/src/lib/info-label/info-label.component.scss
  libs/core/src/lib/info-label/info-label.component.spec.ts
  libs/core/src/lib/info-label/info-label.component.ts
  libs/core/src/lib/info-label/info-label.module.ts
  libs/core/src/lib/info-label/public_api.ts
  libs/core/src/lib/modal/modal.component.scss
  libs/core/src/lib/shellbar/shellbar-actions/shellbar-actions-mobile.component.ts
  package-lock.json
  package.json
Labels: bug
