Repository SAP/fundamental-ngx, pull requests merged in 2020-04, with the labels that each got.

#2204 fix: add notification to storybook
  angular.json
  libs/core/src/lib/button/button.component.ts
  libs/core/src/lib/notification/notification/notification.component.ts
  src/stories/notification/notification.stories.ts
Labels: Visual Testing, testing

#2254 fix: broken toolbar replaced by Shellbar
  apps/docs/src/app/documentation/core-helpers/sections-toolbar/sections-toolbar.component.scss
  apps/docs/src/app/documentation/core-helpers/toolbar/toolbar.component.html
  apps/docs/src/app/documentation/core-helpers/toolbar/toolbar.component.scss
  apps/docs/src/app/documentation/core-helpers/toolbar/toolbar.component.ts
  libs/core/src/lib/shellbar/product-menu/product-menu.component.html
Labels: bug, documentation, v.0.16.0

#2256 test:add inline help story to storybook
  src/stories/inline-help/inline-help.stories.ts
Labels: testing

#2249 chore: support for multiple directive in cssclassbuilder added
  libs/core/src/lib/utils/decorators/apply-css-class.decorator.ts
  libs/core/src/lib/utils/decorators/apply-css-class.spec.ts
  libs/core/src/lib/utils/functions/get-string-from-hashmap.ts
  libs/core/src/lib/utils/functions/index.ts
  libs/core/src/lib/utils/functions/uuidv4-generator.ts
  libs/core/src/lib/utils/public_api.ts
Labels: enhancement, tooling, v.0.16.0

#2259 test: add input-group to storybook
  src/stories/input-group/input-group.stories.ts
Labels: testing

#2228 fix: replacing setters to ngonchanges
  libs/core/src/lib/bar/bar.component.ts
  libs/core/src/lib/form/form-group/form-group.component.ts
  libs/core/src/lib/link/link.component.spec.ts
  libs/core/src/lib/link/link.component.ts
  libs/core/src/lib/list/list-message.directive.ts
  libs/core/src/lib/list/list.component.ts
  libs/core/src/lib/list/list.directives.ts
  libs/core/src/lib/radio/radio-button/radio-button.component.spec.ts
  libs/core/src/lib/radio/radio-button/radio-button.component.ts
  libs/core/src/lib/segmented-button/segmented-button.component.html~HEAD
  libs/core/src/lib/segmented-button/segmented-button.component.html~feat: replaced setters in favor of ngOnChanges
  libs/core/src/lib/segmented-button/segmented-button.component.spec.ts~HEAD
  libs/core/src/lib/segmented-button/segmented-button.component.spec.ts~feat: replaced setters in favor of ngOnChanges
  libs/core/src/lib/tabs/tab-item/tab-item.directive.ts
  libs/core/src/lib/tabs/tab-nav/tab-nav.component.ts
  libs/core/src/lib/tabs/tab-utils/tab-directives.ts
Labels: v.0.16.0

#2152 fix: status indicator refactoring to Object Status
  angular.json
  apps/docs/src/app/core/api-files.ts
  apps/docs/src/app/core/component-docs/object-status/examples/object-status-clickable-and-icon-example.component.html
  apps/docs/src/app/core/component-docs/object-status/examples/object-status-default-example.component.html
  apps/docs/src/app/core/component-docs/object-status/examples/object-status-examples.component.scss
  apps/docs/src/app/core/component-docs/object-status/examples/object-status-examples.component.ts
  apps/docs/src/app/core/component-docs/object-status/examples/object-status-generic-text-example.component.html
  apps/docs/src/app/core/component-docs/object-status/examples/object-status-icon-text-example.component.html
  apps/docs/src/app/core/component-docs/object-status/examples/object-status-inverted-example.component.html
  apps/docs/src/app/core/component-docs/object-status/examples/object-status-inverted-generic-text-example.component.html
  apps/docs/src/app/core/component-docs/object-status/examples/object-status-large-example.component.html
  apps/docs/src/app/core/component-docs/object-status/examples/object-status-text-example.component.html
  apps/docs/src/app/core/component-docs/object-status/object-status-docs.component.html
  apps/docs/src/app/core/component-docs/object-status/object-status-docs.component.ts
  apps/docs/src/app/core/component-docs/object-status/object-status-docs.module.ts
  apps/docs/src/app/core/component-docs/object-status/object-status-header/object-status-header.component.html
  apps/docs/src/app/core/component-docs/object-status/object-status-header/object-status-header.component.scss
  apps/docs/src/app/core/component-docs/object-status/object-status-header/object-status-header.component.ts
  apps/docs/src/app/core/core-documentation.routes.ts
  apps/docs/src/app/core/documentation/core-documentation.component.ts
  apps/docs/src/styles.scss
  libs/core/src/index.ts
  libs/core/src/lib/button-group/button-group.component.scss
  libs/core/src/lib/fundamental-ngx-core.module.ts
  libs/core/src/lib/modal/modal.component.scss
  libs/core/src/lib/object-status/object-status.component.scss
  libs/core/src/lib/object-status/object-status.component.spec.ts
  libs/core/src/lib/object-status/object-status.component.ts
  libs/core/src/lib/object-status/object-status.module.ts
  libs/core/src/lib/object-status/public_api.ts
  libs/platform/src/lib/components/form/form-group/form-group.component.scss
  package-lock.json
Labels: v.0.16.0

#2260 feat: update form validation states and messages
  apps/docs/src/app/core/component-docs/checkbox/checkbox-docs.component.html
  apps/docs/src/app/core/component-docs/checkbox/examples/checkbox-states-example.component.ts
  apps/docs/src/app/core/component-docs/date-picker/examples/date-picker-allow-null-example.component.ts
  apps/docs/src/app/core/component-docs/date-picker/examples/date-picker-disable-func-example/date-picker-disable-func-example.component.html
  apps/docs/src/app/core/component-docs/date-picker/examples/date-picker-form-example.component.ts
  apps/docs/src/app/core/component-docs/date-picker/examples/date-picker-range-disabled-example/date-picker-range-disabled-example.component.html
  apps/docs/src/app/core/component-docs/datetime-picker/examples/datetime-allow-null-example/datetime-allow-null-example.component.ts
  apps/docs/src/app/core/component-docs/datetime-picker/examples/datetime-form-example/datetime-form-example.component.html
  apps/docs/src/app/core/component-docs/input-group/examples/input-group-states-example/input-group-states-example.component.html
  apps/docs/src/app/core/component-docs/input-group/input-group-docs.component.ts
  apps/docs/src/app/core/component-docs/input/examples/input-state-example.component.html
  apps/docs/src/app/core/component-docs/multi-input/examples/multi-input-form-example/multi-input-form-example.component.html
  apps/docs/src/app/core/component-docs/radio/examples/radio-example.component.html
  apps/docs/src/app/core/component-docs/select-native/examples/select-native-state-example.component.html
  apps/docs/src/app/core/component-docs/textarea/examples/textarea-state-example.component.html
  libs/core/src/lib/checkbox/checkbox/checkbox.component.spec.ts
  libs/core/src/lib/checkbox/checkbox/checkbox.component.ts
  libs/core/src/lib/combobox/combobox.component.ts
  libs/core/src/lib/date-picker/date-picker.component.html
  libs/core/src/lib/date-picker/date-picker.component.ts
  libs/core/src/lib/datetime-picker/datetime-picker.component.html
  libs/core/src/lib/datetime-picker/datetime-picker.component.ts
  libs/core/src/lib/form/form-control/form-control.directive.ts
  libs/core/src/lib/form/form-control/form-states.ts
  libs/core/src/lib/form/form-input-message-group/form-input-message-group.component.html
  libs/core/src/lib/form/form-input-message-group/form-input-message-group.component.scss
  libs/core/src/lib/input-group/input-group-directives.ts
  libs/core/src/lib/input-group/input-group.component.ts
  libs/core/src/lib/localizator-editor/localization-editor-main/localization-editor-main.component.ts
  libs/core/src/lib/multi-input/multi-input.component.ts
  libs/core/src/lib/radio/radio-button/radio-button.component.spec.ts
  libs/core/src/lib/radio/radio-button/radio-button.component.ts
  libs/core/src/lib/time-picker/time-picker.component.html
  libs/core/src/lib/time-picker/time-picker.component.ts
  libs/core/src/lib/time/time.component.html
Labels: v.0.16.0

#2218 fix: update action bar to new fundamental-styles
  apps/docs/src/app/core/component-docs/action-bar/action-bar-docs.component.ts
  apps/docs/src/app/core/component-docs/action-bar/action-bar-docs.module.ts
  apps/docs/src/app/core/component-docs/action-bar/examples/action-bar-back-example.component.html
  apps/docs/src/app/core/component-docs/action-bar/examples/action-bar-back-example.component.ts
  apps/docs/src/app/core/component-docs/action-bar/examples/action-bar-contextual-menu-example.component.html
  apps/docs/src/app/core/component-docs/action-bar/examples/action-bar-examples.component.ts
  apps/docs/src/app/core/component-docs/action-bar/examples/action-bar-long-string-title-truncation-example.component.html
  apps/docs/src/app/core/component-docs/action-bar/examples/action-bar-long-string-title-truncation-example.component.ts
  apps/docs/src/app/core/component-docs/action-bar/examples/action-bar-mobile-example.component.html
  apps/docs/src/app/core/component-docs/action-bar/examples/action-bar-mobile-example.component.ts
  apps/docs/src/app/core/component-docs/action-bar/examples/action-bar-no-back-example.component.html
  libs/core/src/lib/action-bar/action-bar-description/action-bar-description.directive.ts
Labels: v.0.16.0

#2283 fix: reverted changes, removed 'this' keyboard from function call
  libs/core/src/lib/button/button.component.ts
Labels: v.0.16.0

#2290 fix: add missing class to Shellbar button
  libs/core/src/lib/product-switch/product-switch/product-switch.component.html
Labels: v.0.16.0

#2281 chore: add fonts to stackblitz
  apps/docs/src/app/documentation/core-helpers/stackblitz/code-example-stack/styles.scss
  apps/docs/src/app/documentation/core-helpers/stackblitz/stackblitz-dependencies.ts
  apps/docs/src/app/documentation/core-helpers/stackblitz/stackblitz.service.ts
Labels: v.0.16.0

#2296 chore: bring old styles for menu component
  apps/docs/src/styles.scss
  libs/core/src/lib/menu/menu.component.scss
  libs/core/src/lib/menu/mixins.scss
Labels: v.0.16.0

#2282 chore: add missing dependencies to package.json
  package-lock.json
  package.json
Labels: dependencies

#2279 fix: side navigation selected state on parent/child
  apps/docs/src/app/core/component-docs/side-navigation/examples/side-navigation-condensed-example/side-navigation-condensed-example.component.html
  apps/docs/src/app/core/component-docs/side-navigation/examples/side-navigation-condensed-object-example/side-navigation-condensed-object-example.component.ts
  apps/docs/src/app/core/component-docs/side-navigation/examples/side-navigation-icons-example.component.html
  apps/docs/src/app/core/component-docs/side-navigation/examples/side-navigation-multiple-selected-example/side-navigation-multiple-selected-example.component.html
  apps/docs/src/app/core/component-docs/side-navigation/examples/side-navigation-object-example/side-navigation-object-example.component.ts
  apps/docs/src/app/core/component-docs/side-navigation/examples/side-navigation-programmatically-example/side-navigation-programmatically-example.component.html
  apps/docs/src/app/core/component-docs/side-navigation/side-navigation-docs.component.html
  apps/docs/src/app/core/component-docs/side-navigation/side-navigation-header/side-navigation-header.component.html
  libs/core/src/lib/nested-list/nested-link/nested-link.directive.ts
  libs/core/src/lib/nested-list/nested-list-state.service.spec.ts
  libs/core/src/lib/nested-list/nested-list-state.service.ts
  libs/core/src/lib/nested-list/prepared-nested-list/prepared-nested-list.component.ts
  libs/core/src/lib/side-navigation/side-navigation.component.scss
  libs/core/src/lib/side-navigation/side-navigation.component.ts
Labels: v.0.15.x, v.0.16.0

#2188 fix: update combobox with latest fundamental-styles
  apps/docs/src/app/core/component-docs/combobox/combobox-docs.component.html
  apps/docs/src/app/core/component-docs/combobox/combobox-docs.component.ts
  apps/docs/src/app/core/component-docs/combobox/combobox-docs.module.ts
  apps/docs/src/app/core/component-docs/combobox/examples/combobox-columns-example.component.html
  apps/docs/src/app/core/component-docs/combobox/examples/combobox-columns-example.component.ts
  apps/docs/src/app/core/component-docs/combobox/examples/combobox-disabled-example.component.html
  apps/docs/src/app/core/component-docs/combobox/examples/combobox-disabled-example.component.ts
  apps/docs/src/app/core/component-docs/combobox/examples/combobox-forms-example.component.html
  apps/docs/src/app/core/component-docs/combobox/examples/combobox-group-example.component.html
  apps/docs/src/app/core/component-docs/combobox/examples/combobox-group-example.component.ts
  apps/docs/src/app/core/component-docs/combobox/examples/combobox-search-function-example.component.html
  libs/core/src/lib/combobox/combobox.component.html
  libs/core/src/lib/combobox/combobox.component.scss
  libs/core/src/lib/combobox/combobox.component.spec.ts
  libs/core/src/lib/combobox/combobox.component.ts
  libs/core/src/lib/combobox/combobox.module.ts
  libs/core/src/lib/list/list.component.scss
  libs/core/src/lib/utils/pipes/list-group.pipe.ts
  libs/core/src/lib/utils/pipes/pipe.module.ts
Labels: v.0.16.0

#2295 test: ngonchanges removed from unit test when unnecessary
  libs/core/src/lib/link/link.component.spec.ts
  libs/core/src/lib/message-strip/message-strip.component.spec.ts
  libs/core/src/lib/object-status/object-status.component.spec.ts
Labels: testing, v.0.16.0

#2086 fix: make tokenizer/multiinput responsive
  apps/docs/src/app/core/component-docs/multi-input/examples/multi-input-compact-example/multi-input-compact-example.component.html
  apps/docs/src/app/core/component-docs/multi-input/examples/multi-input-example/multi-input-example.component.html
  apps/docs/src/app/core/component-docs/multi-input/examples/multi-input-new-tokens-example/multi-input-new-tokens-example.component.html
  apps/docs/src/app/core/component-docs/multi-input/examples/multi-input-new-tokens-example/multi-input-new-tokens-example.component.ts
  apps/docs/src/app/core/component-docs/multi-input/multi-input-docs.component.html
  apps/docs/src/app/core/component-docs/multi-input/multi-input-docs.component.ts
  apps/docs/src/app/core/component-docs/multi-input/multi-input-docs.module.ts
  apps/docs/src/app/core/component-docs/token/examples/tokenizer-compact-example/tokenizer-compact-example.component.html
  apps/docs/src/app/core/component-docs/token/examples/tokenizer-compact-example/tokenizer-compact-example.component.ts
  apps/docs/src/app/core/component-docs/token/examples/tokenizer-example/tokenizer-example.component.html
  apps/docs/src/app/core/component-docs/token/examples/tokenizer-example/tokenizer-example.component.ts
  apps/docs/src/app/core/component-docs/token/token-docs.component.html
  libs/core/src/lib/breadcrumb/breadcrumb.component.spec.ts
  libs/core/src/lib/breadcrumb/breadcrumb.component.ts
  libs/core/src/lib/form/form-control/form-control.directive.spec.ts
  libs/core/src/lib/form/form-control/form-control.directive.ts
  libs/core/src/lib/input-group/input-group-directives.ts
  libs/core/src/lib/input-group/input-group.component.html
  libs/core/src/lib/multi-input/multi-input.component.html
  libs/core/src/lib/multi-input/multi-input.component.scss
  libs/core/src/lib/multi-input/multi-input.component.ts
  libs/core/src/lib/multi-input/multi-input.module.ts
  libs/core/src/lib/token/token-input.directive.ts
  libs/core/src/lib/token/token.component.html
  libs/core/src/lib/token/token.component.ts
  libs/core/src/lib/token/token.module.ts
  libs/core/src/lib/token/tokenizer.component.html
  libs/core/src/lib/token/tokenizer.component.scss
  libs/core/src/lib/token/tokenizer.component.spec.ts
  libs/core/src/lib/token/tokenizer.component.ts
Labels: v.0.16.0

#2302 chore: package downgraded to fix IE 11
  package-lock.json
  package.json
Labels: bug, documentation, v.0.16.0

#2289 docs: remove bit about importing fonts and icons in angular.json
  libs/core/README.md
Labels: documentation

#2312 docs: space added for example's buttons
  apps/docs/src/app/core/component-docs/button/examples/button-examples.component.scss
Labels: documentation, v.0.16.0

#2310 fix: input group number arrow's size fixed
  libs/core/src/lib/input-group/input-group-number.component.html
Labels: bug, v.0.16.0

#2324 fix: Center dialog on IE11
  libs/core/src/lib/dialog/dialog-header/dialog-header.component.html
  libs/core/src/lib/dialog/dialog.component.ts
Labels: bug

#2326 fix: Dialog with header has body with rounded top corners | IE11
  libs/core/src/lib/dialog/dialog.component.scss
Labels: bug

#2325 fix: Close Dialog on Esc key | IE11
  libs/core/src/lib/dialog/dialog.component.ts
Labels: bug

#2332 chore: migrate NX lib to version 9
  angular.json
  nx.json
  package-lock.json
  package.json
Labels: dependencies

#2308 fix: add fix for Shellbar search input hover styles and Shellbar side nav button
  libs/core/src/lib/shellbar/shellbar.component.scss
Labels: bug

#2306 fix: bug where user cannot click edges of multi input item
  libs/core/src/lib/multi-input/multi-input.component.html
  libs/core/src/lib/multi-input/multi-input.component.scss
Labels: bug, v.0.16.0

#2330 fix: add RTL support for keyboard calendar service
  libs/core/src/lib/calendar/calendar.service.ts
Labels: v.0.16.0

#2305 docs: popover placement menus
  apps/docs/src/app/core/component-docs/popover/examples/popover-placement/popover-placement-example.component.scss
Labels: bug

#2307 fix: input group directives should use CssClassBuilder
  libs/core/src/lib/input-group/input-group-directives.ts
Labels: bug, v.0.16.0

#2327 chore: bump packages' versions in package.json
  package-lock.json
  package.json
Labels: dependencies

#2337 fix: set ViewEncapsulation.None for radio button and split button
  libs/core/src/lib/radio/radio-button/radio-button.component.ts
  libs/core/src/lib/split-button/split-button.component.ts
Labels: bug, v.0.16.0

#2342 fix: Support Calendar key navigation | IE11
  libs/core/src/lib/calendar/calendar.service.ts
Labels: bug, v.0.16.0

#2311 fix: radio button reactive form
  libs/core/src/lib/radio/radio-button/radio-button.component.html
  libs/core/src/lib/radio/radio-button/radio-button.component.ts
Labels: bug, v.0.16.0

#2339 fix:rRemove default week count for Calendar
  libs/core/src/lib/calendar/calendar.component.ts
Labels: v.0.16.0

#2340 fix: Misaligned select icon | IE11
  libs/core/src/lib/select/select.component.scss
Labels: bug, v.0.16.0

#2344 chore: Add new font imports to schematics
  ci-scripts/sync-version.sh
  libs/core/ng-package.json
  libs/core/package.json
  libs/core/schematics/ng-add/index.ts
  libs/core/schematics/ng-add/schema.json
  libs/core/schematics/ng-add/styles.ts
  libs/core/tsconfig.lib.prod.json
  package-lock.json
  package.json
Labels: tooling, v.0.16.0

#2350 fix: DatePickers add focus trap
  libs/core/src/lib/date-picker/date-picker.component.html
  libs/core/src/lib/datetime-picker/datetime-picker.component.html
Labels: v.0.16.0

#2349 fix: changed ngOnInit to ngAfterViewInit
  libs/core/src/lib/radio/radio-button/radio-button.component.ts
Labels: bug, v.0.16.0

#2345 fix: side nav Shellbar RTL support
  libs/core/src/lib/shellbar/shellbar.component.scss
Labels: RTL, bug, v.0.16.0

#2341 fix: removed option and changed button fdtype
  libs/core/src/lib/input-group/input-group.component.html
  libs/core/src/lib/input-group/input-group.component.ts
Labels: bug, v.0.16.0

#2348 docs: Deprecate Loading Spinner and Status Indicator
  apps/docs/src/app/core/component-docs/alert/alert-header/alert-header.component.html
  apps/docs/src/app/core/component-docs/badge-label/badge-label-docs.module.ts
  apps/docs/src/app/core/component-docs/badge-label/badge-label-header/badge-label-header.component.html
  apps/docs/src/app/core/component-docs/dropdown/dropdown-docs.module.ts
  apps/docs/src/app/core/component-docs/dropdown/dropdown-header/dropdown-header.component.html
  apps/docs/src/app/core/component-docs/loading-spinner-docs/loading-spinner-docs.module.ts
  apps/docs/src/app/core/component-docs/loading-spinner-docs/loading-spinner-header/loading-spinner-header.component.html
  libs/core/src/lib/badge-label/badge-label.module.ts
  libs/core/src/lib/badge-label/badge-label/badge.component.ts
  libs/core/src/lib/badge-label/label/label.component.ts
  libs/core/src/lib/badge-label/status-label/status-label.component.ts
  libs/core/src/lib/loading-spinner/loading-spinner.component.ts
  libs/core/src/lib/loading-spinner/loading-spinner.module.ts
  libs/core/src/lib/popover/popover-dropdown/popover-dropdown.component.ts
Labels: bug, v.0.16.0

#2347 docs: fix table with checkbox example
  apps/docs/src/app/core/component-docs/table/examples/table-checkboxes-example.component.html
  apps/docs/src/app/core/component-docs/table/examples/table-checkboxes-example.component.ts
Labels: documentation, v.0.16.0

#2346 docs: change product switch in Shellbar example
  apps/docs/src/app/core/component-docs/product-switch/examples/product-switch-dnd-example.component.html
  libs/core/src/lib/product-switch/product-switch-body/product-switch-body.component.scss
Labels: v.0.16.0

#2309 docs: add note about es5/RtlService to readme
  libs/core/README.md
Labels: bug, v.0.16.0

#2335 fix: rtl tokenizer
  libs/core/src/lib/token/tokenizer.component.scss
  libs/core/src/lib/token/tokenizer.component.spec.ts
  libs/core/src/lib/token/tokenizer.component.ts
Labels: RTL, bug, v.0.16.0

#2353 fix: add fix for Dialog header template close button
  libs/core/src/lib/dialog/dialog-header/dialog-header.component.html
Labels: v.0.16.0

#2356 fix: tokenizer input addon should be type transparent
  libs/core/src/lib/token/tokenizer.component.html
Labels: bug

#2360 fix: settimeout replaced by observable timer
  libs/core/src/lib/tabs/tab-list.component.ts
Labels: bug

#2361 docs: Fix sidebar
  apps/docs/src/app/documentation/core-helpers/sections-toolbar/sections-toolbar.component.scss
Labels: documentation, v.0.16.0

#2363 fix: workound added to check if tag starts with 'v'
  ci-scripts/publish.sh
Labels: tooling, v.0.16.0

#2122 feat: (platform) Radio button group component Implementation
  apps/docs/src/app/platform/api-files.ts
  apps/docs/src/app/platform/component-docs/platform-forms/radio-group/platform-radio-group-docs.component.html
  apps/docs/src/app/platform/component-docs/platform-forms/radio-group/platform-radio-group-docs.component.ts
  apps/docs/src/app/platform/component-docs/platform-forms/radio-group/platform-radio-group-examples/platform-radio-group-content-example.component.html
  apps/docs/src/app/platform/component-docs/platform-forms/radio-group/platform-radio-group-examples/platform-radio-group-content-examples.component.ts
  apps/docs/src/app/platform/component-docs/platform-forms/radio-group/platform-radio-group-examples/platform-radio-group-disabled-example.component.html
  apps/docs/src/app/platform/component-docs/platform-forms/radio-group/platform-radio-group-examples/platform-radio-group-disabled-examples.component.ts
  apps/docs/src/app/platform/component-docs/platform-forms/radio-group/platform-radio-group-examples/platform-radio-group-list-example.component.html
  apps/docs/src/app/platform/component-docs/platform-forms/radio-group/platform-radio-group-examples/platform-radio-group-list-examples.component.ts
  apps/docs/src/app/platform/component-docs/platform-forms/radio-group/platform-radio-group-examples/platform-radio-group-list-items-example.component.html
  apps/docs/src/app/platform/component-docs/platform-forms/radio-group/platform-radio-group-examples/platform-radio-group-list-items-examples.component.ts
  apps/docs/src/app/platform/component-docs/platform-forms/radio-group/platform-radio-group-header/platform-radio-group-header.component.html
  apps/docs/src/app/platform/component-docs/platform-forms/radio-group/platform-radio-group-header/platform-radio-group-header.component.ts
  apps/docs/src/app/platform/documentation/platform-documentation.component.ts
  apps/docs/src/app/platform/platform-documentation.module.ts
  apps/docs/src/app/platform/platform-documentation.routes.ts
  apps/docs/src/assets/README.md
  libs/platform/src/lib/components/form/collection-base.input.ts
  libs/platform/src/lib/components/form/radio-group/public_api.ts
  libs/platform/src/lib/components/form/radio-group/radio-group.component.html
  libs/platform/src/lib/components/form/radio-group/radio-group.component.spec.ts
  libs/platform/src/lib/components/form/radio-group/radio-group.component.ts
  libs/platform/src/lib/components/form/radio-group/radio-group.module.ts
  libs/platform/src/lib/components/form/radio-group/radio/radio.component.html
  libs/platform/src/lib/components/form/radio-group/radio/radio.component.spec.ts
  libs/platform/src/lib/components/form/radio-group/radio/radio.component.ts
  libs/platform/src/lib/platform.module.ts
Labels: platform

#2370 docs: fix sidebar squashing, add icons to shared module
  apps/docs/src/app/documentation/core-helpers/sections-toolbar/sections-toolbar.component.scss
  apps/docs/src/app/documentation/shared-core-modules.ts
Labels: documentation, v.0.16.0

#2366 fix: remove circular dependency for Nested List
  apps/docs/src/app/core/api-files.ts
  libs/core/src/lib/nested-list/nested-item/nested-item.directive.spec.ts
  libs/core/src/lib/nested-list/nested-item/nested-item.directive.ts
  libs/core/src/lib/nested-list/nested-item/nested-item.service.ts
  libs/core/src/lib/nested-list/nested-link/nested-link.directive.spec.ts
  libs/core/src/lib/nested-list/nested-link/nested-link.directive.ts
  libs/core/src/lib/nested-list/nested-list-keyboard.service.spec.ts
  libs/core/src/lib/nested-list/nested-list-keyboard.service.ts
  libs/core/src/lib/nested-list/nested-list-popover/nested-list-popover.component.ts
  libs/core/src/lib/nested-list/nested-list-popover/nested-list-popover.interface.ts
  libs/core/src/lib/nested-list/nested-list/nested-list.directive.spec.ts
  libs/core/src/lib/nested-list/nested-list/nested-list.directive.ts
  libs/core/src/lib/nested-list/nested-list/nested-list.interface.ts
  libs/core/src/lib/nested-list/prepared-nested-list/prepared-nested-list.component.ts
  libs/core/src/lib/nested-list/public_api.ts
  libs/core/src/lib/utils/decorators/apply-css-class.decorator.ts
  libs/core/src/lib/utils/decorators/apply-css-style.decorator.ts
Labels: v.0.16.0

#2373 docs: Add Tilde to angular versions, add icon module to app module
  angular.json
  apps/docs/src/app/documentation/core-helpers/toolbar/toolbar.component.html
  package.json
Labels: dependencies, documentation

#2372 docs: Remove unnecessary disabled from switch
  apps/docs/src/app/core/component-docs/switch/examples/switch-form-example/switch-forms-example.component.html
  libs/core/src/lib/switch/switch.component.html
Labels: v.0.17.0

#2388 fix: Fix alert derived class constructor bug
  libs/core/src/lib/alert/alert.component.ts
Labels: bug

#2389 fix: (popover) Fix popover performance
  libs/core/src/lib/popover/popover-directive/popover.directive.spec.ts
  libs/core/src/lib/popover/popover-directive/popover.directive.ts
Labels: v.0.13.0, v.0.14.0, v.0.15.x, v.0.17.0

#2375 chore: remove tslib from devDependencies and add repo and homepage link
  package.json
Labels: tooling

#2369 fix: (platform) Create common base class for Platform components
  apps/docs/src/app/platform/component-docs/platform-forms/radio-group/platform-radio-group-examples/platform-radio-group-content-example.component.html
  apps/docs/src/app/platform/component-docs/platform-forms/radio-group/platform-radio-group-examples/platform-radio-group-disabled-example.component.html
  apps/docs/src/app/platform/component-docs/platform-forms/radio-group/platform-radio-group-examples/platform-radio-group-list-example.component.html
  apps/docs/src/app/platform/component-docs/platform-forms/radio-group/platform-radio-group-examples/platform-radio-group-list-items-example.component.html
  libs/platform/src/lib/components/base.ts
  libs/platform/src/lib/components/form/base.input.ts
  libs/platform/src/lib/components/form/combo-box/combo-box.component.html
  libs/platform/src/lib/components/form/form-control.ts
  libs/platform/src/lib/components/form/input/input.component.html
  libs/platform/src/lib/components/form/radio-group/radio-group.component.html
  libs/platform/src/lib/components/form/radio-group/radio-group.component.spec.ts
  libs/platform/src/lib/components/form/radio-group/radio-group.component.ts
  libs/platform/src/lib/components/form/radio-group/radio/radio.component.html
  libs/platform/src/lib/components/form/radio-group/radio/radio.component.spec.ts
Labels: platform

#2412 chore: update dependencies
  package-lock.json
  package.json
Labels: dependencies

#2411 docs: update a popover example button #2106
  apps/docs/src/app/core/component-docs/popover/examples/popover-dynamic/popover-dynamic-example.component.html
Labels: documentation

#2427 fix: Checkbox check destroyed state on detect changes
  libs/core/src/lib/checkbox/checkbox/checkbox.component.ts
Labels: v.0.17.0

#2426 fix: Add RTL to popover
  libs/core/src/lib/popover/popover-directive/popover.directive.spec.ts
  libs/core/src/lib/popover/popover-directive/popover.directive.ts
  libs/core/src/lib/popover/popover.component.ts
  libs/core/src/lib/product-switch/product-switch/product-switch.component.html
  libs/core/src/lib/shellbar/product-menu/product-menu.component.html
  libs/core/src/lib/shellbar/user-menu/shellbar-user-menu.component.html
  package-lock.json
Labels: v.0.17.0

#2223 fix: (platform) Menu button As a component
  apps/docs/src/app/platform/api-files.ts
  apps/docs/src/app/platform/component-docs/platform-menu-button/platform-menu-button-docs.component.html
  apps/docs/src/app/platform/component-docs/platform-menu-button/platform-menu-button-docs.component.ts
  apps/docs/src/app/platform/component-docs/platform-menu-button/platform-menu-button-examples/platform-menu-button-compact-example.component.html
  apps/docs/src/app/platform/component-docs/platform-menu-button/platform-menu-button-examples/platform-menu-button-compact-examples.component.ts
  apps/docs/src/app/platform/component-docs/platform-menu-button/platform-menu-button-examples/platform-menu-button-cozy-example.component.html
  apps/docs/src/app/platform/component-docs/platform-menu-button/platform-menu-button-examples/platform-menu-button-cozy-examples.component.ts
  apps/docs/src/app/platform/component-docs/platform-menu-button/platform-menu-button-examples/platform-menu-button-example.component.html
  apps/docs/src/app/platform/component-docs/platform-menu-button/platform-menu-button-examples/platform-menu-button-examples.component.ts
  apps/docs/src/app/platform/component-docs/platform-menu-button/platform-menu-button-header/platform-menu-button-header.component.html
  apps/docs/src/app/platform/component-docs/platform-menu-button/platform-menu-button-header/platform-menu-button-header.component.ts
  apps/docs/src/app/platform/documentation/platform-documentation.component.ts
  apps/docs/src/app/platform/platform-documentation.module.ts
  apps/docs/src/app/platform/platform-documentation.routes.ts
  libs/platform/src/lib/components/form/radio-group/radio-group.component.spec.ts
  libs/platform/src/lib/components/menu-button/menu-button.component.html
  libs/platform/src/lib/components/menu-button/menu-button.component.scss
  libs/platform/src/lib/components/menu-button/menu-button.component.spec.ts
  libs/platform/src/lib/components/menu-button/menu-button.component.ts
  libs/platform/src/lib/components/menu-button/menu-button.module.ts
  libs/platform/src/lib/components/menu-button/public_api.ts
  libs/platform/src/lib/platform.module.ts
Labels: platform

#2425 fix: (platform) Split menu button as a component
  apps/docs/src/app/platform/api-files.ts
  apps/docs/src/app/platform/component-docs/platform-split-menu-button/platform-split-menu-button-examples/platform-split-menu-button-examples.component.html
  apps/docs/src/app/platform/component-docs/platform-split-menu-button/platform-split-menu-button-examples/platform-split-menu-button-examples.component.ts
  apps/docs/src/app/platform/component-docs/platform-split-menu-button/platform-split-menu-button-examples/platform-split-menu-button-options.component.html
  apps/docs/src/app/platform/component-docs/platform-split-menu-button/platform-split-menu-button-examples/platform-split-menu-button-options.component.ts
  apps/docs/src/app/platform/component-docs/platform-split-menu-button/platform-split-menu-button-header/platform-split-menu-button-header.component.html
  apps/docs/src/app/platform/component-docs/platform-split-menu-button/platform-split-menu-button-header/platform-split-menu-button-header.component.ts
  apps/docs/src/app/platform/component-docs/platform-split-menu-button/platform-split-menu-button.component.html
  apps/docs/src/app/platform/component-docs/platform-split-menu-button/platform-split-menu-button.component.ts
  apps/docs/src/app/platform/documentation/platform-documentation.component.ts
  apps/docs/src/app/platform/platform-documentation.module.ts
  apps/docs/src/app/platform/platform-documentation.routes.ts
  libs/platform/src/lib/components/split-menu-button/public_api.ts
  libs/platform/src/lib/components/split-menu-button/split-menu-button.component.html
  libs/platform/src/lib/components/split-menu-button/split-menu-button.component.scss
  libs/platform/src/lib/components/split-menu-button/split-menu-button.component.spec.ts
  libs/platform/src/lib/components/split-menu-button/split-menu-button.component.ts
  libs/platform/src/lib/components/split-menu-button/split-menu-button.module.ts
  libs/platform/src/lib/platform.module.ts
Labels: platform
