Repository SAP/fundamental-ngx, pull requests merged in 2021-03, with the labels that each got.

#4757 test: add alert e2e tests
  e2e/wdio/baselineScreenshot/desktop_chrome/alert-customPopup-example-0-core-chrome-mac_os_x--1920x1417.png
  e2e/wdio/baselineScreenshot/desktop_chrome/alert-customPopup-example-0-core-chrome-windows--1920x1080.png
  e2e/wdio/baselineScreenshot/desktop_chrome/alert-customPopup-example-1-core-chrome-mac_os_x--1920x1417.png
  e2e/wdio/baselineScreenshot/desktop_chrome/alert-customPopup-example-1-core-chrome-windows--1920x1080.png
  e2e/wdio/baselineScreenshot/desktop_chrome/alert-customPopup-example-2-core-chrome-mac_os_x--1920x1417.png
  e2e/wdio/baselineScreenshot/desktop_chrome/alert-customPopup-example-2-core-chrome-windows--1920x1080.png
  e2e/wdio/baselineScreenshot/desktop_chrome/alert-customPopup-example-3-core-chrome-mac_os_x--1920x1417.png
  e2e/wdio/baselineScreenshot/desktop_chrome/alert-customPopup-example-3-core-chrome-windows--1920x1080.png
  e2e/wdio/baselineScreenshot/desktop_chrome/alert-example-0-core-chrome-mac_os_x--1920x1417.png
  e2e/wdio/baselineScreenshot/desktop_chrome/alert-example-0-core-chrome-windows--1920x1080.png
  e2e/wdio/baselineScreenshot/desktop_chrome/alert-example-1-core-chrome-mac_os_x--1920x1417.png
  e2e/wdio/baselineScreenshot/desktop_chrome/alert-example-1-core-chrome-windows--1920x1080.png
  e2e/wdio/baselineScreenshot/desktop_chrome/alert-example-2-core-chrome-mac_os_x--1920x1417.png
  e2e/wdio/baselineScreenshot/desktop_chrome/alert-example-2-core-chrome-windows--1920x1080.png
  e2e/wdio/baselineScreenshot/desktop_chrome/alert-example-3-core-chrome-mac_os_x--1920x1417.png
  e2e/wdio/baselineScreenshot/desktop_chrome/alert-example-3-core-chrome-windows--1920x1080.png
  e2e/wdio/baselineScreenshot/desktop_firefox/alert-customPopup-example-0-core-firefox-mac--1920x1417.png
  e2e/wdio/baselineScreenshot/desktop_firefox/alert-customPopup-example-0-core-firefox-windows--1936x1096.png
  e2e/wdio/baselineScreenshot/desktop_firefox/alert-customPopup-example-1-core-firefox-mac--1920x1417.png
  e2e/wdio/baselineScreenshot/desktop_firefox/alert-customPopup-example-1-core-firefox-windows--1936x1096.png
  e2e/wdio/baselineScreenshot/desktop_firefox/alert-customPopup-example-2-core-firefox-mac--1920x1417.png
  e2e/wdio/baselineScreenshot/desktop_firefox/alert-customPopup-example-2-core-firefox-windows--1936x1096.png
  e2e/wdio/baselineScreenshot/desktop_firefox/alert-customPopup-example-3-core-firefox-mac--1920x1417.png
  e2e/wdio/baselineScreenshot/desktop_firefox/alert-customPopup-example-3-core-firefox-windows--1936x1096.png
  e2e/wdio/baselineScreenshot/desktop_firefox/alert-example-0-core-firefox-mac--1920x1417.png
  e2e/wdio/baselineScreenshot/desktop_firefox/alert-example-0-core-firefox-windows--1936x1096.png
  e2e/wdio/baselineScreenshot/desktop_firefox/alert-example-1-core-firefox-mac--1920x1417.png
  e2e/wdio/baselineScreenshot/desktop_firefox/alert-example-1-core-firefox-windows--1936x1096.png
  e2e/wdio/baselineScreenshot/desktop_firefox/alert-example-2-core-firefox-mac--1920x1417.png
  e2e/wdio/baselineScreenshot/desktop_firefox/alert-example-2-core-firefox-windows--1936x1096.png
  e2e/wdio/baselineScreenshot/desktop_firefox/alert-example-3-core-firefox-mac--1920x1417.png
  e2e/wdio/baselineScreenshot/desktop_firefox/alert-example-3-core-firefox-windows--1936x1096.png
  e2e/wdio/baselineScreenshot/desktop_microsoftedge/alert-customPopup-example-0-core-msedge-mac_os_x--1920x1417.png
  e2e/wdio/baselineScreenshot/desktop_microsoftedge/alert-customPopup-example-0-core-msedge-windows--1920x1080.png
  e2e/wdio/baselineScreenshot/desktop_microsoftedge/alert-customPopup-example-1-core-msedge-mac_os_x--1920x1417.png
  e2e/wdio/baselineScreenshot/desktop_microsoftedge/alert-customPopup-example-1-core-msedge-windows--1920x1080.png
  e2e/wdio/baselineScreenshot/desktop_microsoftedge/alert-customPopup-example-2-core-msedge-mac_os_x--1920x1417.png
  e2e/wdio/baselineScreenshot/desktop_microsoftedge/alert-customPopup-example-2-core-msedge-windows--1920x1080.png
  e2e/wdio/baselineScreenshot/desktop_microsoftedge/alert-customPopup-example-3-core-msedge-mac_os_x--1920x1417.png
  e2e/wdio/baselineScreenshot/desktop_microsoftedge/alert-customPopup-example-3-core-msedge-windows--1920x1080.png
  e2e/wdio/baselineScreenshot/desktop_microsoftedge/alert-example-0-core-msedge-mac_os_x--1920x1417.png
  e2e/wdio/baselineScreenshot/desktop_microsoftedge/alert-example-0-core-msedge-windows--1920x1080.png
  e2e/wdio/baselineScreenshot/desktop_microsoftedge/alert-example-1-core-msedge-mac_os_x--1920x1417.png
  e2e/wdio/baselineScreenshot/desktop_microsoftedge/alert-example-1-core-msedge-windows--1920x1080.png
  e2e/wdio/baselineScreenshot/desktop_microsoftedge/alert-example-2-core-msedge-mac_os_x--1920x1417.png
  e2e/wdio/baselineScreenshot/desktop_microsoftedge/alert-example-2-core-msedge-windows--1920x1080.png
  e2e/wdio/baselineScreenshot/desktop_microsoftedge/alert-example-3-core-msedge-mac_os_x--1920x1417.png
  e2e/wdio/baselineScreenshot/desktop_microsoftedge/alert-example-3-core-msedge-windows--1920x1080.png
  e2e/wdio/core/pages/alert.po.ts
  e2e/wdio/core/tests/alert.e2e-spec.ts
Labels: e2e

#4737 docs: (Core) Added missing cards examples
  apps/docs/src/app/core/component-docs/card/card-docs.component.html
  apps/docs/src/app/core/component-docs/card/card-docs.component.ts
  apps/docs/src/app/core/component-docs/card/card-docs.module.ts
  apps/docs/src/app/core/component-docs/card/examples/calendar-card/card-calendar-example.component.html
  apps/docs/src/app/core/component-docs/card/examples/calendar-card/card-calendar-example.component.scss
  apps/docs/src/app/core/component-docs/card/examples/calendar-card/card-calendar-example.component.ts
  apps/docs/src/app/core/component-docs/card/examples/card-compact-example.component.ts
  apps/docs/src/app/core/component-docs/card/examples/card-kpi-example.component.html
  apps/docs/src/app/core/component-docs/card/examples/link-list-card/card-link-list-example.component.html
  apps/docs/src/app/core/component-docs/card/examples/link-list-card/card-link-list-example.component.ts
  apps/docs/src/app/core/component-docs/card/examples/list-card/card-list-example.component.html
  apps/docs/src/app/core/component-docs/card/examples/list-card/card-list-example.component.ts
  apps/docs/src/app/core/component-docs/card/examples/object-card/card-object-example.component.html
  apps/docs/src/app/core/component-docs/card/examples/object-card/card-object-example.component.scss
  apps/docs/src/app/core/component-docs/card/examples/object-card/card-object-example.component.ts
  apps/docs/src/app/core/component-docs/card/examples/quick-view-card/card-quick-view-example.component.html
  apps/docs/src/app/core/component-docs/card/examples/quick-view-card/card-quick-view-example.component.ts
  apps/docs/src/app/core/component-docs/fixed-card-layout/examples/default/fixed-card-layout-examples.component.html
  apps/docs/src/app/core/component-docs/fixed-card-layout/examples/disabled-drag-drop/fixed-card-layout-disabled-drag.component.html
  apps/docs/src/app/core/component-docs/fixed-card-layout/examples/mobile/fixed-card-layout-mobile-examples.component.html
  libs/core/src/lib/card/card.component.scss
Labels: QA Approved, design_team

#4805 fix: export select option component
  libs/platform/src/lib/components/form/select/index.ts
Labels: bug, denoland

#4791 docs: (Core) Update README.md
  libs/core/README.md
Labels: documentation

#4722 feat: (Core) Introduce dynamic page
  apps/docs/src/app/core/api-files.ts
  apps/docs/src/app/core/component-docs/dynamic-page/dynamic-page-docs.component.html
  apps/docs/src/app/core/component-docs/dynamic-page/dynamic-page-docs.component.ts
  apps/docs/src/app/core/component-docs/dynamic-page/dynamic-page-docs.module.ts
  apps/docs/src/app/core/component-docs/dynamic-page/dynamic-page-examples/dynamic-page-column-layout-example/dynamic-page-column-layout-example.component.html
  apps/docs/src/app/core/component-docs/dynamic-page/dynamic-page-examples/dynamic-page-column-layout-example/dynamic-page-column-layout-example.component.ts
  apps/docs/src/app/core/component-docs/dynamic-page/dynamic-page-examples/dynamic-page-example.component.html
  apps/docs/src/app/core/component-docs/dynamic-page/dynamic-page-examples/dynamic-page-example.component.scss
  apps/docs/src/app/core/component-docs/dynamic-page/dynamic-page-examples/dynamic-page-example.component.ts
  apps/docs/src/app/core/component-docs/dynamic-page/dynamic-page-examples/dynamic-page-responsive-example/dynamic-page-responsive-example.component.html
  apps/docs/src/app/core/component-docs/dynamic-page/dynamic-page-examples/dynamic-page-responsive-example/dynamic-page-responsive-example.component.ts
  apps/docs/src/app/core/component-docs/dynamic-page/dynamic-page-examples/dynamic-page-tabs-example/dynamic-page-tabs-example.component.html
  apps/docs/src/app/core/component-docs/dynamic-page/dynamic-page-examples/dynamic-page-tabs-example/dynamic-page-tabs-example.component.ts
  apps/docs/src/app/core/component-docs/dynamic-page/dynamic-page-header/dynamic-page-docs-header.component.ts
  apps/docs/src/app/core/component-docs/dynamic-page/dynamic-page-header/dynamic-page-header.component.html
  apps/docs/src/app/core/core-documentation.routes.ts
  apps/docs/src/app/core/documentation/core-documentation.component.ts
  libs/core/src/index.ts
  libs/core/src/lib/breadcrumb/breadcrumb.component.ts
  libs/core/src/lib/dynamic-page/constants.ts
  libs/core/src/lib/dynamic-page/dynamic-page-content/dynamic-page-content.component.html
  libs/core/src/lib/dynamic-page/dynamic-page-content/dynamic-page-content.component.scss
  libs/core/src/lib/dynamic-page/dynamic-page-content/dynamic-page-content.component.ts
  libs/core/src/lib/dynamic-page/dynamic-page-footer/dynamic-page-footer.component.ts
  libs/core/src/lib/dynamic-page/dynamic-page-header/actions/dynamic-page-base-actions.ts
  libs/core/src/lib/dynamic-page/dynamic-page-header/actions/dynamic-page-global-actions.component.ts
  libs/core/src/lib/dynamic-page/dynamic-page-header/actions/dynamic-page-layout-actions.component.ts
  libs/core/src/lib/dynamic-page/dynamic-page-header/actions/dynamic-page-title-content.component.ts
  libs/core/src/lib/dynamic-page/dynamic-page-header/header/dynamic-page-header.component.html
  libs/core/src/lib/dynamic-page/dynamic-page-header/header/dynamic-page-header.component.scss
  libs/core/src/lib/dynamic-page/dynamic-page-header/header/dynamic-page-header.component.spec.ts
  libs/core/src/lib/dynamic-page/dynamic-page-header/header/dynamic-page-header.component.ts
  libs/core/src/lib/dynamic-page/dynamic-page-header/subheader/dynamic-page-subheader.component.html
  libs/core/src/lib/dynamic-page/dynamic-page-header/subheader/dynamic-page-subheader.component.spec.ts
  libs/core/src/lib/dynamic-page/dynamic-page-header/subheader/dynamic-page-subheader.component.ts
  libs/core/src/lib/dynamic-page/dynamic-page.component.html
  libs/core/src/lib/dynamic-page/dynamic-page.component.scss
  libs/core/src/lib/dynamic-page/dynamic-page.component.spec.ts
  libs/core/src/lib/dynamic-page/dynamic-page.component.ts
  libs/core/src/lib/dynamic-page/dynamic-page.config.ts
  libs/core/src/lib/dynamic-page/dynamic-page.module.ts
  libs/core/src/lib/dynamic-page/dynamic-page.service.ts
  libs/core/src/lib/dynamic-page/public_api.ts
  libs/core/src/lib/dynamic-page/utils.ts
  libs/core/src/lib/fundamental-ngx-core.module.ts
  libs/core/src/lib/toolbar/toolbar.component.html
  libs/core/src/lib/toolbar/toolbar.component.ts
Labels: Fiori 3 component, denoland

#4817 chore: Increment NGX version
  CHANGELOG.md
  package-lock.json
  package.json
Labels: dependencies

#4806 chore: add a new check in the PR template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: tooling

#4821 fix: (Core) Fix hide bug for multi input
  libs/core/src/lib/multi-input/multi-input.component.html
  libs/core/src/lib/multi-input/multi-input.component.scss
  libs/core/src/lib/multi-input/multi-input.component.spec.ts
  libs/core/src/lib/multi-input/multi-input.component.ts
Labels: core

#4799 fix: (Core) Remove small size shellbar unnecessary styles
  libs/core/src/lib/shellbar/shellbar.component.scss
Labels: bug

#4839 fix: Portal issues
  apps/docs/src/app/core/component-docs/combobox/examples/combobox-example.component.html
  apps/docs/src/app/core/component-docs/date-picker/examples/date-picker-single-example.component.ts
  apps/docs/src/app/core/component-docs/datetime-picker/examples/datetime-example/datetime-example.component.html
  apps/docs/src/app/core/component-docs/dialog/examples/dialog-complex/dialog-complex-example.component.ts
  apps/docs/src/app/core/component-docs/dialog/examples/dialog-configuration/dialog-configuration-example.component.ts
  apps/docs/src/app/core/component-docs/global-config/examples/dialog-global-config-example/dialog-global-config-example.module.ts
  apps/docs/src/app/core/component-docs/global-config/examples/message-box-global-config-example/message-box-global-config-example.module.ts
  apps/docs/src/app/core/component-docs/multi-input/examples/multi-input-example/multi-input-example.component.html
  apps/docs/src/app/core/component-docs/table/examples/table-custom-columns-example/table-custom-columns-example.component.ts
  apps/docs/src/app/core/component-docs/time-picker/examples/time-picker-example.component.html
  libs/core/src/lib/combobox/combobox.component.html
  libs/core/src/lib/combobox/combobox.component.ts
  libs/core/src/lib/date-picker/date-picker.component.html
  libs/core/src/lib/date-picker/date-picker.component.ts
  libs/core/src/lib/datetime-picker/datetime-picker.component.html
  libs/core/src/lib/datetime-picker/datetime-picker.component.ts
  libs/core/src/lib/dialog/base/dialog-config-base.class.ts
  libs/core/src/lib/dialog/dialog.component.spec.ts
  libs/core/src/lib/flexible-column-layout/flexible-column-layout.component.scss
  libs/core/src/lib/message-box/message-box.component.spec.ts
  libs/core/src/lib/multi-input/multi-input.component.html
  libs/core/src/lib/multi-input/multi-input.component.ts
  libs/core/src/lib/time-picker/time-picker.component.html
  libs/core/src/lib/time-picker/time-picker.component.ts
Labels: dxp

#4829 test: added allure to Travis CI build
  .firebaserc
  .gitignore
  .travis.yml
  deploy-to-preview-channel-core.sh
  deploy-to-preview-channel-platform-a.sh
  deploy-to-preview-channel-platform-b.sh
  firebase.json
  package-lock.json
  package.json
  wdio.conf.js
Labels: e2e

#4746 feat: (Core) introduce the status Indicator component
  apps/docs/src/app/core/api-files.ts
  apps/docs/src/app/core/component-docs/status-indicator/example/status-indicator-angled-filling.component.html
  apps/docs/src/app/core/component-docs/status-indicator/example/status-indicator-angled-filling.component.ts
  apps/docs/src/app/core/component-docs/status-indicator/example/status-indicator-cirular-fill-anti-clockwise.component.html
  apps/docs/src/app/core/component-docs/status-indicator/example/status-indicator-cirular-fill-anti-clockwise.component.ts
  apps/docs/src/app/core/component-docs/status-indicator/example/status-indicator-cirular-fill-clockwise.component.html
  apps/docs/src/app/core/component-docs/status-indicator/example/status-indicator-cirular-fill-clockwise.component.ts
  apps/docs/src/app/core/component-docs/status-indicator/example/status-indicator-clickable-type.component.html
  apps/docs/src/app/core/component-docs/status-indicator/example/status-indicator-clickable-type.component.ts
  apps/docs/src/app/core/component-docs/status-indicator/example/status-indicator-default.component.html
  apps/docs/src/app/core/component-docs/status-indicator/example/status-indicator-default.component.ts
  apps/docs/src/app/core/component-docs/status-indicator/example/status-indicator-fill-type.component.html
  apps/docs/src/app/core/component-docs/status-indicator/example/status-indicator-fill-type.component.ts
  apps/docs/src/app/core/component-docs/status-indicator/example/status-indicator-label.component.html
  apps/docs/src/app/core/component-docs/status-indicator/example/status-indicator-label.component.ts
  apps/docs/src/app/core/component-docs/status-indicator/example/status-indicator-linear-fill-type.component.html
  apps/docs/src/app/core/component-docs/status-indicator/example/status-indicator-linear-fill-type.component.ts
  apps/docs/src/app/core/component-docs/status-indicator/example/status-indicator-size.component.html
  apps/docs/src/app/core/component-docs/status-indicator/example/status-indicator-size.component.ts
  apps/docs/src/app/core/component-docs/status-indicator/status-indicator-docs.component.html
  apps/docs/src/app/core/component-docs/status-indicator/status-indicator-docs.component.scss
  apps/docs/src/app/core/component-docs/status-indicator/status-indicator-docs.component.ts
  apps/docs/src/app/core/component-docs/status-indicator/status-indicator-docs.module.ts
  apps/docs/src/app/core/component-docs/status-indicator/status-indicator-header/status-indicator-header.component.html
  apps/docs/src/app/core/component-docs/status-indicator/status-indicator-header/status-indicator-header.component.ts
  apps/docs/src/app/core/core-documentation.routes.ts
  apps/docs/src/app/core/documentation/core-documentation.component.ts
  libs/core/src/index.ts
  libs/core/src/lib/fundamental-ngx-core.module.ts
  libs/core/src/lib/status-indicator/public_api.ts
  libs/core/src/lib/status-indicator/status-indicator.component.html
  libs/core/src/lib/status-indicator/status-indicator.component.scss
  libs/core/src/lib/status-indicator/status-indicator.component.spec.ts
  libs/core/src/lib/status-indicator/status-indicator.component.ts
  libs/core/src/lib/status-indicator/status-indicator.module.ts
Labels: core

#4886 fix: (Core) Dynamic page init content resize
  libs/core/src/lib/dynamic-page/dynamic-page.component.ts
Labels: core, dxp

#4892 test: comment randomly failing slider unit test
  libs/platform/src/lib/components/slider/slider.component.spec.ts
Labels: flaky tests, unit tests

#4857 fix: (Core) updating the example for the truncation behaviour
  apps/docs/src/app/core/component-docs/object-number/examples/object-number-examples.component.scss
  apps/docs/src/app/core/component-docs/object-number/examples/object-number-examples.component.ts
  apps/docs/src/app/core/component-docs/object-number/examples/object-number-truncation-example.component.html
  apps/docs/src/app/core/component-docs/object-number/object-number-docs.component.html
  apps/docs/src/app/core/component-docs/object-number/object-number-docs.component.ts
  apps/docs/src/app/core/component-docs/object-number/object-number-docs.module.ts
  e2e/wdio/core/fixtures/appData/object-number-content.ts
  e2e/wdio/core/pages/object-number.po.ts
  e2e/wdio/core/tests/object-number.e2e-spec.ts
Labels: bug, core

#4897 test: (e2e) update thumbnail e2e tests for thumbnail phase 2
  e2e/wdio/baselineScreenshot/core/avatar/desktop_chrome/avatar-example-0-core-Chrome_Headless-darwin--1920x1417.png
  e2e/wdio/baselineScreenshot/core/avatar/desktop_chrome/avatar-example-1-core-Chrome_Headless-darwin--1920x1417.png
  e2e/wdio/baselineScreenshot/core/avatar/desktop_chrome/avatar-example-2-core-Chrome_Headless-darwin--1920x1417.png
  e2e/wdio/baselineScreenshot/core/avatar/desktop_chrome/avatar-example-3-core-Chrome_Headless-darwin--1920x1417.png
  e2e/wdio/baselineScreenshot/core/avatar/desktop_chrome/avatar-example-4-core-Chrome_Headless-darwin--1920x1417.png
  e2e/wdio/baselineScreenshot/core/avatar/desktop_chrome/avatar-example-5-core-Chrome_Headless-darwin--1920x1417.png
  e2e/wdio/baselineScreenshot/core/avatar/desktop_chrome/avatar-example-6-core-Chrome_Headless-darwin--1920x1417.png
  e2e/wdio/baselineScreenshot/core/avatar/desktop_chrome/avatar-example-7-core-Chrome_Headless-darwin--1920x1417.png
  e2e/wdio/baselineScreenshot/core/avatar/desktop_chrome/avatar-example-8-core-Chrome_Headless-darwin--1920x1417.png
  e2e/wdio/baselineScreenshot/core/avatar/desktop_chrome/avatar-example-9-core-Chrome_Headless-darwin--1920x1417.png
  e2e/wdio/baselineScreenshot/core/dynamic-side-content/desktop_chrome/dynamic-side-content-example-0-core-Chrome_Headless-darwin--1920x1417.png
  e2e/wdio/baselineScreenshot/core/dynamic-side-content/desktop_chrome/dynamic-side-content-example-1-core-Chrome_Headless-darwin--1920x1417.png
  e2e/wdio/baselineScreenshot/core/dynamic-side-content/desktop_chrome/dynamic-side-content-example-2-core-Chrome_Headless-darwin--1920x1417.png
  e2e/wdio/baselineScreenshot/core/fixed-card-layout/desktop_chrome/fixed-card-layout-example-0-core-Chrome_Headless-darwin--1920x1417.png
  e2e/wdio/baselineScreenshot/core/fixed-card-layout/desktop_chrome/fixed-card-layout-example-1-core-Chrome_Headless-darwin--1920x1417.png
  e2e/wdio/baselineScreenshot/core/fixed-card-layout/desktop_chrome/fixed-card-layout-example-2-core-Chrome_Headless-darwin--1920x1417.png
  e2e/wdio/baselineScreenshot/core/formatted-text/desktop_chrome/formatted-text-example-0-core-Chrome_Headless-darwin--1920x1417.png
  e2e/wdio/baselineScreenshot/core/formatted-text/desktop_chrome/formatted-text-example-1-core-Chrome_Headless-darwin--1920x1417.png
  e2e/wdio/baselineScreenshot/core/formatted-text/desktop_chrome/formatted-text-example-2-core-Chrome_Headless-darwin--1920x1417.png
  e2e/wdio/baselineScreenshot/platform/thumbnail/desktop_chrome/thumbnail-dialog-next-mac_os_x--1920x1417.png
  e2e/wdio/baselineScreenshot/platform/thumbnail/desktop_chrome/thumbnail-dialog-next-windows--1920x1080.png
  e2e/wdio/baselineScreenshot/platform/thumbnail/desktop_chrome/thumbnail-dialog-on-open-mac_os_x--1920x1417.png
  e2e/wdio/baselineScreenshot/platform/thumbnail/desktop_chrome/thumbnail-dialog-on-open-windows--1920x1080.png
  e2e/wdio/baselineScreenshot/platform/thumbnail/desktop_chrome/thumbnail-dialog-previous-mac_os_x--1920x1417.png
  e2e/wdio/baselineScreenshot/platform/thumbnail/desktop_chrome/thumbnail-dialog-previous-windows--1920x1080.png
  e2e/wdio/baselineScreenshot/platform/thumbnail/desktop_chrome/thumbnail-example-0-platform-chrome-mac_os_x--1920x1417.png
  e2e/wdio/baselineScreenshot/platform/thumbnail/desktop_chrome/thumbnail-example-0-platform-chrome-windows--1920x1080.png
  e2e/wdio/baselineScreenshot/platform/thumbnail/desktop_chrome/thumbnail-example-1-platform-chrome-mac_os_x--1920x1417.png
  e2e/wdio/baselineScreenshot/platform/thumbnail/desktop_chrome/thumbnail-example-1-platform-chrome-windows--1920x1080.png
  e2e/wdio/baselineScreenshot/platform/thumbnail/desktop_chrome/thumbnail-example-2-platform-chrome-mac_os_x--1920x1417.png
  e2e/wdio/baselineScreenshot/platform/thumbnail/desktop_chrome/thumbnail-example-2-platform-chrome-windows--1920x1080.png
  e2e/wdio/baselineScreenshot/platform/thumbnail/desktop_firefox/thumbnail-dialog-next-mac--1920x1417.png
  e2e/wdio/baselineScreenshot/platform/thumbnail/desktop_firefox/thumbnail-dialog-next-windows--1936x1096.png
  e2e/wdio/baselineScreenshot/platform/thumbnail/desktop_firefox/thumbnail-dialog-on-open-mac--1920x1417.png
  e2e/wdio/baselineScreenshot/platform/thumbnail/desktop_firefox/thumbnail-dialog-on-open-windows--1936x1096.png
  e2e/wdio/baselineScreenshot/platform/thumbnail/desktop_firefox/thumbnail-dialog-previous-mac--1920x1417.png
  e2e/wdio/baselineScreenshot/platform/thumbnail/desktop_firefox/thumbnail-dialog-previous-windows--1936x1096.png
  e2e/wdio/baselineScreenshot/platform/thumbnail/desktop_firefox/thumbnail-example-0-platform-firefox-mac--1920x1417.png
  e2e/wdio/baselineScreenshot/platform/thumbnail/desktop_firefox/thumbnail-example-0-platform-firefox-windows--1936x1096.png
  e2e/wdio/baselineScreenshot/platform/thumbnail/desktop_firefox/thumbnail-example-1-platform-firefox-mac--1920x1417.png
  e2e/wdio/baselineScreenshot/platform/thumbnail/desktop_firefox/thumbnail-example-1-platform-firefox-windows--1936x1096.png
  e2e/wdio/baselineScreenshot/platform/thumbnail/desktop_firefox/thumbnail-example-2-platform-firefox-mac--1920x1417.png
  e2e/wdio/baselineScreenshot/platform/thumbnail/desktop_firefox/thumbnail-example-2-platform-firefox-windows--1936x1096.png
  e2e/wdio/baselineScreenshot/platform/thumbnail/desktop_microsoftedge/thumbnail-dialog-next-mac_os_x--1920x1417.png
  e2e/wdio/baselineScreenshot/platform/thumbnail/desktop_microsoftedge/thumbnail-dialog-next-windows--1920x1080.png
  e2e/wdio/baselineScreenshot/platform/thumbnail/desktop_microsoftedge/thumbnail-dialog-on-open-mac_os_x--1920x1417.png
  e2e/wdio/baselineScreenshot/platform/thumbnail/desktop_microsoftedge/thumbnail-dialog-on-open-windows--1920x1080.png
  e2e/wdio/baselineScreenshot/platform/thumbnail/desktop_microsoftedge/thumbnail-dialog-previous-mac_os_x--1920x1417.png
  e2e/wdio/baselineScreenshot/platform/thumbnail/desktop_microsoftedge/thumbnail-dialog-previous-windows--1920x1080.png
  e2e/wdio/baselineScreenshot/platform/thumbnail/desktop_microsoftedge/thumbnail-example-0-platform-msedge-mac_os_x--1920x1417.png
  e2e/wdio/baselineScreenshot/platform/thumbnail/desktop_microsoftedge/thumbnail-example-0-platform-msedge-windows--1920x1080.png
  e2e/wdio/baselineScreenshot/platform/thumbnail/desktop_microsoftedge/thumbnail-example-1-platform-msedge-mac_os_x--1920x1417.png
  e2e/wdio/baselineScreenshot/platform/thumbnail/desktop_microsoftedge/thumbnail-example-1-platform-msedge-windows--1920x1080.png
  e2e/wdio/baselineScreenshot/platform/thumbnail/desktop_microsoftedge/thumbnail-example-2-platform-msedge-mac_os_x--1920x1417.png
  e2e/wdio/baselineScreenshot/platform/thumbnail/desktop_microsoftedge/thumbnail-example-2-platform-msedge-windows--1920x1080.png
  e2e/wdio/driver/wdio.ts
  e2e/wdio/platform/pages/thumbnail.po.ts
  e2e/wdio/platform/tests/thumbnail.e2e-spec.ts
  wdio.conf.js
Labels: e2e

#4879 feat: (Store) Store predicates
  libs/store/src/lib/infrastructure/persistence/query/grammar/predicate.spec.ts
  libs/store/src/lib/infrastructure/persistence/query/grammar/predicate.ts
  libs/store/src/lib/infrastructure/persistence/query/grammar/query-expressions.ts
Labels: state management

#4898 test: (e2e) unskip accidentally skipped tests
  e2e/wdio/core/tests/fixed-card-layout.e2e-spec.ts
  e2e/wdio/core/tests/object-marker.e2e-spec.ts
  e2e/wdio/core/tests/object-number.e2e-spec.ts
  e2e/wdio/core/tests/object-status.e2e-spec.ts
  e2e/wdio/core/tests/quick-view.e2e-spec.ts
  e2e/wdio/core/tests/slider.e2e-spec.ts
Labels: e2e

#4910 chore: bump the latest angular version
  package-lock.json
  package.json
Labels: dependencies

#4856 docs: fix playground background color
  apps/docs/src/app/documentation/core-helpers/playground/playground.components.scss
Labels: documentation

#4900 fix: (Core) Break word in every component under fixed card layout
  libs/core/src/lib/fixed-card-layout/fixed-card-layout.component.scss
Labels: dxp

#4899 fix: (Core) Add no-data mode and text wrap to table cell
  apps/docs/src/app/core/component-docs/table/examples/table-example.component.html
  apps/docs/src/app/core/component-docs/table/examples/table-example.component.ts
  apps/docs/src/app/core/component-docs/table/examples/table-toolbar-example.component.html
  libs/core/src/lib/table/directives/table-cell.directive.ts
  libs/core/src/lib/table/directives/table-text.directive.ts
  libs/core/src/lib/table/table.component.scss
Labels: dxp

#4905 fix: (Core) Add handler for real query string
  apps/docs/src/app/core/component-docs/theme-switcher/examples/theme-url-example.component.html
  apps/docs/src/app/core/component-docs/theme-switcher/examples/theme-url-example.component.ts
  apps/docs/src/app/core/component-docs/theme-switcher/theme-switcher-docs.component.html
  libs/core/src/lib/utils/services/themes.service.ts
Labels: dxp

#4922 fix: (Core) Fixed Card Layout Change focus target to header
  libs/core/src/lib/fixed-card-layout/fixed-card-layout-item/fixed-card-layout-item.component.ts
Labels: dxp

#4923 fix: Remove borders from responsvie table
  apps/docs/src/app/core/component-docs/table/examples/table-popin-example/table-popin-example.component.html
  apps/docs/src/app/core/component-docs/table/table-docs.component.html
  libs/core/src/lib/table/table.component.scss
  libs/core/src/lib/table/table.component.ts
Labels: dxp

#4901 fix: (Core) wizard step indicator stacking bugs on narrow screens
  libs/core/src/lib/action-sheet/action-sheet-item/action-sheet-item.component.html
  libs/core/src/lib/action-sheet/action-sheet-item/action-sheet-item.component.ts
  libs/core/src/lib/wizard/wizard-step-indicator/wizard-step-indicator.component.html
  libs/core/src/lib/wizard/wizard-step-indicator/wizard-step-indicator.component.ts
  libs/core/src/lib/wizard/wizard-step/wizard-step.component.html
  libs/core/src/lib/wizard/wizard-step/wizard-step.component.ts
  libs/core/src/lib/wizard/wizard.component.scss
  libs/core/src/lib/wizard/wizard.component.spec.ts
  libs/core/src/lib/wizard/wizard.component.ts
Labels: bug

#4913 chore: bump node to version 15.11.0
  .nvmrc
Labels: dependencies

#4940 test: disable card and object status e2e tests
  e2e/wdio/core/tests/card.e2e-spec.ts
  e2e/wdio/core/tests/object-status.e2e-spec.ts
  e2e/wdio/platform/tests/object-status.e2e-spec.ts
Labels: test automation

#4845 fix: (Core) fix the accessibility bug in file uploader component.
  apps/docs/src/app/core/component-docs/file-uploader/examples/file-uploader-drag-disabled-example/file-uploader-drag-disabled-example.component.html
  libs/core/src/lib/file-uploader/file-uploader.component.ts
Labels: accessibility, core

#4945 test: disable object number e2e tests with hardcoded colors
  e2e/wdio/core/tests/object-number.e2e-spec.ts
Labels: E2E automation, e2e

#4947 chore: bump @schematics/angular @types/jasmine
  package-lock.json
  package.json
Labels: dependencies

#4948 chore: bump node version to 15.11.0 for netlify
  netlify.toml
Labels: tooling

#4914 chore: bump theming-base-content version 11.1.27
  package-lock.json
  package.json
Labels: dependencies

#4944 docs: (Core) Add busy indicator to table documentation
  apps/docs/src/app/core/component-docs/table/examples/table-toolbar-example.component.html
  apps/docs/src/app/core/component-docs/table/examples/table-toolbar-example.component.ts
  apps/docs/src/app/core/component-docs/table/table-docs.module.ts
Labels: dxp

#4946 fix: (Core) Remove redundant tabbable item on multi input, remove default width limit, improve ShowAll button
  libs/core/src/lib/multi-input/multi-input.component.html
  libs/core/src/lib/multi-input/multi-input.component.scss
  libs/core/src/lib/multi-input/multi-input.component.spec.ts
  libs/core/src/lib/multi-input/multi-input.component.ts
  libs/core/src/lib/token/tokenizer.component.html
  libs/core/src/lib/token/tokenizer.component.spec.ts
  libs/core/src/lib/token/tokenizer.component.ts
  libs/platform/src/lib/components/form/multi-input/multi-input.component.html
Labels: core

#4960 fix: add fix for FCL animation and example with Dynamic Page usage and layout controls
  apps/docs/src/app/core/component-docs/flexible-column-layout/examples/dynamic-page/flexible-column-layout-dynamic-page-example.component.html
  apps/docs/src/app/core/component-docs/flexible-column-layout/examples/dynamic-page/flexible-column-layout-dynamic-page-example.component.scss
  apps/docs/src/app/core/component-docs/flexible-column-layout/examples/dynamic-page/flexible-column-layout-dynamic-page-example.component.ts
  apps/docs/src/app/core/component-docs/flexible-column-layout/flexible-column-layout-docs.component.html
  apps/docs/src/app/core/component-docs/flexible-column-layout/flexible-column-layout-docs.component.ts
  apps/docs/src/app/core/component-docs/flexible-column-layout/flexible-column-layout-docs.module.ts
  libs/core/src/lib/flexible-column-layout/flexible-column-layout.component.html
  libs/core/src/lib/flexible-column-layout/flexible-column-layout.component.scss
  libs/core/src/lib/flexible-column-layout/flexible-column-layout.component.spec.ts
Labels: denoland, dxp

#4942 fix: (Core) updating the focusable object of status indicator and adding clickable
  apps/docs/src/app/core/component-docs/status-indicator/example/status-indicator-clickable-type.component.html
  apps/docs/src/app/core/component-docs/status-indicator/example/status-indicator-clickable-type.component.ts
  apps/docs/src/app/core/component-docs/status-indicator/example/status-indicator-label.component.html
  libs/core/src/lib/status-indicator/status-indicator.component.html
  libs/core/src/lib/status-indicator/status-indicator.component.scss
  libs/core/src/lib/status-indicator/status-indicator.component.ts
Labels: QA Approved, core

#4774 feat: (Platform) approval flow adjustments
  apps/docs/src/app/platform/component-docs/platform-approval-flow/platform-approval-flow-examples/approval-flow-example-data-source.class.ts
  apps/docs/src/app/platform/component-docs/platform-approval-flow/platform-approval-flow-examples/platform-approval-flow-example.component.ts
  libs/platform/src/lib/components/approval-flow/approval-flow-node/approval-flow-node.component.scss
  libs/platform/src/lib/components/approval-flow/approval-flow.component.html
  libs/platform/src/lib/components/approval-flow/approval-flow.component.ts
Labels: QA Approved

#4999 fix: (core) added text component fixes for ie11
  libs/core/src/lib/utils/directives/line-clamp/line-clamp.directive.ts
Labels: Defect Hunting, bug, core

#5000 fix: (core) chaged text examples selectors to fix stackblitz
  apps/docs/src/app/core/component-docs/text/examples/text-basic.component.ts
  apps/docs/src/app/core/component-docs/text/examples/text-expandable.component.ts
  apps/docs/src/app/core/component-docs/text/examples/text-hyphenation.component.ts
  apps/docs/src/app/core/component-docs/text/examples/text-max-lines.component.ts
  apps/docs/src/app/core/component-docs/text/examples/text-whitespaces.component.ts
  apps/docs/src/app/core/component-docs/text/text-docs.component.html
  apps/docs/src/app/core/component-docs/text/text-docs.component.ts
Labels: Defect Hunting, bug, core

#4992 chore: upgrade to theming-base-content version 11.1.28
  package-lock.json
  package.json
Labels: dependencies

#4859 feat: (Core) Avatar Group
  apps/docs/src/app/core/api-files.ts
  apps/docs/src/app/core/component-docs/avatar-group/avatar-group-docs.component.html
  apps/docs/src/app/core/component-docs/avatar-group/avatar-group-docs.component.ts
  apps/docs/src/app/core/component-docs/avatar-group/avatar-group-docs.module.ts
  apps/docs/src/app/core/component-docs/avatar-group/avatar-group-header/avatar-group-header.component.html
  apps/docs/src/app/core/component-docs/avatar-group/avatar-group-header/avatar-group-header.component.ts
  apps/docs/src/app/core/component-docs/avatar-group/examples/avatar-group-data-example.service.ts
  apps/docs/src/app/core/component-docs/avatar-group/examples/avatar-group-group-type-example.component.html
  apps/docs/src/app/core/component-docs/avatar-group/examples/avatar-group-group-type-example.component.scss
  apps/docs/src/app/core/component-docs/avatar-group/examples/avatar-group-group-type-example.component.ts
  apps/docs/src/app/core/component-docs/avatar-group/examples/avatar-group-individual-type-example.component.html
  apps/docs/src/app/core/component-docs/avatar-group/examples/avatar-group-individual-type-example.component.scss
  apps/docs/src/app/core/component-docs/avatar-group/examples/avatar-group-individual-type-example.component.ts
  apps/docs/src/app/core/core-documentation.routes.ts
  apps/docs/src/app/core/documentation/core-documentation.component.ts
  libs/core/src/index.ts
  libs/core/src/lib/avatar-group/avatar-group.component.html
  libs/core/src/lib/avatar-group/avatar-group.component.scss
  libs/core/src/lib/avatar-group/avatar-group.component.spec.ts
  libs/core/src/lib/avatar-group/avatar-group.component.ts
  libs/core/src/lib/avatar-group/avatar-group.module.ts
  libs/core/src/lib/avatar-group/directives/avatar-group-item.directive.spec.ts
  libs/core/src/lib/avatar-group/directives/avatar-group-item.directive.ts
  libs/core/src/lib/avatar-group/directives/avatar-group-overflow-body.directive.spec.ts
  libs/core/src/lib/avatar-group/directives/avatar-group-overflow-body.directive.ts
  libs/core/src/lib/avatar-group/directives/avatar-group-overflow-button-text.directive.spec.ts
  libs/core/src/lib/avatar-group/directives/avatar-group-overflow-button-text.directive.ts
  libs/core/src/lib/avatar-group/directives/avatar-group-overflow-button.directive.spec.ts
  libs/core/src/lib/avatar-group/directives/avatar-group-overflow-button.directive.ts
  libs/core/src/lib/avatar-group/directives/avatar-group-overflow-item.directive.spec.ts
  libs/core/src/lib/avatar-group/directives/avatar-group-overflow-item.directive.ts
  libs/core/src/lib/avatar-group/public_api.ts
  libs/core/src/lib/avatar/avatar.component.ts
  libs/core/src/lib/fundamental-ngx-core.module.ts
  libs/core/src/lib/status-indicator/status-indicator.component.ts
  libs/core/src/lib/utils/datatypes/color-accent.datatype.ts
  libs/core/src/lib/utils/datatypes/index.ts
  libs/core/src/lib/utils/datatypes/size.datatype.ts
  libs/core/src/lib/utils/functions/index.ts
  libs/core/src/lib/utils/functions/random-color-accent.ts
  libs/core/src/lib/utils/public_api.ts
Labels: QA Approved, core

#5009 fix: (Core) add input for tooltip for multi-input / input group
  libs/core/src/lib/combobox/combobox.component.html
  libs/core/src/lib/combobox/combobox.component.ts
  libs/core/src/lib/input-group/input-group.component.html
  libs/core/src/lib/input-group/input-group.component.ts
  libs/core/src/lib/multi-input/multi-input.component.html
  libs/core/src/lib/multi-input/multi-input.component.ts
Labels: Defect Hunting, bug

#5020 fix: add GridListModule to the exports
  libs/core/src/lib/fundamental-ngx-core.module.ts
Labels: denoland

#4971 chore: adopt fundamental-styles version 0.17
  apps/docs/src/app/core/component-docs/table/examples/table-popin-example/table-popin-example.component.ts
  e2e/wdio/baselineScreenshot/platform/object-list-item/desktop_chrome/object-list-item-example-0-platform-chrome-mac_os_x--1920x1417.png
  e2e/wdio/baselineScreenshot/platform/object-list-item/desktop_chrome/object-list-item-example-0-platform-chrome-windows--1920x1080.png
  e2e/wdio/baselineScreenshot/platform/object-list-item/desktop_chrome/object-list-item-example-1-platform-chrome-mac_os_x--1920x1417.png
  e2e/wdio/baselineScreenshot/platform/object-list-item/desktop_chrome/object-list-item-example-1-platform-chrome-windows--1920x1080.png
  e2e/wdio/baselineScreenshot/platform/object-list-item/desktop_chrome/object-list-item-example-2-platform-chrome-mac_os_x--1920x1417.png
  e2e/wdio/baselineScreenshot/platform/object-list-item/desktop_chrome/object-list-item-example-2-platform-chrome-windows--1920x1080.png
  e2e/wdio/baselineScreenshot/platform/object-list-item/desktop_chrome/object-list-item-example-3-platform-chrome-mac_os_x--1920x1417.png
  e2e/wdio/baselineScreenshot/platform/object-list-item/desktop_chrome/object-list-item-example-3-platform-chrome-windows--1920x1080.png
  e2e/wdio/baselineScreenshot/platform/object-list-item/desktop_chrome/object-list-item-example-4-platform-chrome-mac_os_x--1920x1417.png
  e2e/wdio/baselineScreenshot/platform/object-list-item/desktop_chrome/object-list-item-example-4-platform-chrome-windows--1920x1080.png
  e2e/wdio/baselineScreenshot/platform/object-list-item/desktop_firefox/object-list-item-example-0-platform-firefox-mac--1920x1417.png
  e2e/wdio/baselineScreenshot/platform/object-list-item/desktop_firefox/object-list-item-example-0-platform-firefox-windows--1936x1096.png
  e2e/wdio/baselineScreenshot/platform/object-list-item/desktop_firefox/object-list-item-example-1-platform-firefox-mac--1920x1417.png
  e2e/wdio/baselineScreenshot/platform/object-list-item/desktop_firefox/object-list-item-example-1-platform-firefox-windows--1936x1096.png
  e2e/wdio/baselineScreenshot/platform/object-list-item/desktop_firefox/object-list-item-example-2-platform-firefox-mac--1920x1417.png
  e2e/wdio/baselineScreenshot/platform/object-list-item/desktop_firefox/object-list-item-example-2-platform-firefox-windows--1936x1096.png
  e2e/wdio/baselineScreenshot/platform/object-list-item/desktop_firefox/object-list-item-example-3-platform-firefox-mac--1920x1417.png
  e2e/wdio/baselineScreenshot/platform/object-list-item/desktop_firefox/object-list-item-example-3-platform-firefox-windows--1936x1096.png
  e2e/wdio/baselineScreenshot/platform/object-list-item/desktop_firefox/object-list-item-example-4-platform-firefox-mac--1920x1417.png
  e2e/wdio/baselineScreenshot/platform/object-list-item/desktop_firefox/object-list-item-example-4-platform-firefox-windows--1936x1096.png
  e2e/wdio/baselineScreenshot/platform/object-list-item/desktop_microsoftedge/object-list-item-example-0-platform-msedge-mac_os_x--1920x1417.png
  e2e/wdio/baselineScreenshot/platform/object-list-item/desktop_microsoftedge/object-list-item-example-0-platform-msedge-windows--1920x1080.png
  e2e/wdio/baselineScreenshot/platform/object-list-item/desktop_microsoftedge/object-list-item-example-1-platform-msedge-mac_os_x--1920x1417.png
  e2e/wdio/baselineScreenshot/platform/object-list-item/desktop_microsoftedge/object-list-item-example-1-platform-msedge-windows--1920x1080.png
  e2e/wdio/baselineScreenshot/platform/object-list-item/desktop_microsoftedge/object-list-item-example-2-platform-msedge-mac_os_x--1920x1417.png
  e2e/wdio/baselineScreenshot/platform/object-list-item/desktop_microsoftedge/object-list-item-example-2-platform-msedge-windows--1920x1080.png
  e2e/wdio/baselineScreenshot/platform/object-list-item/desktop_microsoftedge/object-list-item-example-3-platform-msedge-mac_os_x--1920x1417.png
  e2e/wdio/baselineScreenshot/platform/object-list-item/desktop_microsoftedge/object-list-item-example-3-platform-msedge-windows--1920x1080.png
  e2e/wdio/baselineScreenshot/platform/object-list-item/desktop_microsoftedge/object-list-item-example-4-platform-msedge-mac_os_x--1920x1417.png
  e2e/wdio/baselineScreenshot/platform/object-list-item/desktop_microsoftedge/object-list-item-example-4-platform-msedge-windows--1920x1080.png
  libs/core/src/lib/avatar/avatar.component.ts
  libs/core/src/lib/dynamic-page/dynamic-page.component.scss
  libs/core/src/lib/tile/directives/tile.directives.ts
  libs/platform/src/lib/components/dynamic-page/dynamic-page.component.scss
  package-lock.json
  package.json
Labels: dependencies

#4977 feat: (Core) introduce Facets component
  apps/docs/src/app/core/api-files.ts
  apps/docs/src/app/core/component-docs/facets/facet-docs.component.html
  apps/docs/src/app/core/component-docs/facets/facet-docs.component.ts
  apps/docs/src/app/core/component-docs/facets/facet-docs.module.ts
  apps/docs/src/app/core/component-docs/facets/facet-examples/custom-facet-example.component.html
  apps/docs/src/app/core/component-docs/facets/facet-examples/custom-facet-example.component.ts
  apps/docs/src/app/core/component-docs/facets/facet-examples/facet-examples.component.ts
  apps/docs/src/app/core/component-docs/facets/facet-examples/facet-group-example.component.html
  apps/docs/src/app/core/component-docs/facets/facet-examples/form-facet-example.component.html
  apps/docs/src/app/core/component-docs/facets/facet-examples/form-link-facet-example.component.html
  apps/docs/src/app/core/component-docs/facets/facet-examples/image-facet-example.component.html
  apps/docs/src/app/core/component-docs/facets/facet-examples/key-value-facet-alignment-example.component.html
  apps/docs/src/app/core/component-docs/facets/facet-examples/key-value-facet-example.component.html
  apps/docs/src/app/core/component-docs/facets/facet-examples/rating-indicator-facet-example.component.html
  apps/docs/src/app/core/component-docs/facets/facet-header/facet-docs-header.component.ts
  apps/docs/src/app/core/component-docs/facets/facet-header/facet-header.component.html
  apps/docs/src/app/core/core-documentation.routes.ts
  apps/docs/src/app/core/documentation/core-documentation.component.ts
  libs/core/src/index.ts
  libs/core/src/lib/facets/constants.ts
  libs/core/src/lib/facets/content/facet-content.component.ts
  libs/core/src/lib/facets/facet-group.component.scss
  libs/core/src/lib/facets/facet-group.component.ts
  libs/core/src/lib/facets/facet.module.ts
  libs/core/src/lib/facets/facet/facet.component.html
  libs/core/src/lib/facets/facet/facet.component.spec.ts
  libs/core/src/lib/facets/facet/facet.component.ts
  libs/core/src/lib/facets/public_api.ts
  libs/core/src/lib/facets/utils.ts
  libs/core/src/lib/fundamental-ngx-core.module.ts
Labels: QA Approved

#5019 fix: datepicker/datetimepicker/timepicker console warnings
  libs/core/src/lib/date-picker/date-picker.component.ts
  libs/core/src/lib/datetime-picker/datetime-picker.component.ts
  libs/core/src/lib/time-picker/time-picker.component.ts
Labels: Defect Hunting, bug

#5017 fix: tab index bug for single select grid list item
  libs/core/src/lib/grid-list/components/grid-list-item/grid-list-item.component.html
Labels: Defect Hunting, bug

#5018 fix: step input placeholder default value needs to be empty string
  libs/core/src/lib/step-input/step-input.component.ts
Labels: Defect Hunting, bug

#4501 test: (e2e) approval flow components phase 1/2
  e2e/wdio/baselineScreenshot/platform/approval-flow/desktop_chrome/action-bar-example-0-platform-chrome-mac_os_x--1920x1417.png
  e2e/wdio/baselineScreenshot/platform/approval-flow/desktop_chrome/action-bar-example-0-platform-chrome-windows--1920x1080.png
  e2e/wdio/baselineScreenshot/platform/approval-flow/desktop_chrome/remove-node-state-mac_os_x--1920x1417.png
  e2e/wdio/baselineScreenshot/platform/approval-flow/desktop_chrome/remove-node-state-windows--1920x1080.png
  e2e/wdio/baselineScreenshot/platform/approval-flow/desktop_firefox/action-bar-example-0-platform-firefox-mac--1920x1417.png
  e2e/wdio/baselineScreenshot/platform/approval-flow/desktop_firefox/action-bar-example-0-platform-firefox-windows--1936x1096.png
  e2e/wdio/baselineScreenshot/platform/approval-flow/desktop_firefox/remove-node-state-mac--1920x1417.png
  e2e/wdio/baselineScreenshot/platform/approval-flow/desktop_firefox/remove-node-state-windows--1936x1096.png
  e2e/wdio/baselineScreenshot/platform/approval-flow/desktop_microsoftedge/action-bar-example-0-platform-msedge-mac_os_x--1920x1417.png
  e2e/wdio/baselineScreenshot/platform/approval-flow/desktop_microsoftedge/action-bar-example-0-platform-msedge-windows--1920x1080.png
  e2e/wdio/baselineScreenshot/platform/approval-flow/desktop_microsoftedge/remove-node-state-mac_os_x--1920x1417.png
  e2e/wdio/baselineScreenshot/platform/approval-flow/desktop_microsoftedge/remove-node-state-windows--1920x1080.png
  e2e/wdio/driver/wdio.ts
  e2e/wdio/platform/fixtures/appData/approval-flow-contents.ts
  e2e/wdio/platform/pages/approval-flow.po.ts
  e2e/wdio/platform/tests/approval-flow.e2e-spec.ts
  wdio.conf.js
Labels: e2e

#4989 test: (e2e) add info label tests
  e2e/wdio/baselineScreenshot/core/info-label/desktop_chrome/info-label-example-0-core-chrome-mac_os_x--1920x1417.png
  e2e/wdio/baselineScreenshot/core/info-label/desktop_chrome/info-label-example-0-core-chrome-windows--1920x1080.png
  e2e/wdio/baselineScreenshot/core/info-label/desktop_chrome/info-label-example-1-core-chrome-mac_os_x--1920x1417.png
  e2e/wdio/baselineScreenshot/core/info-label/desktop_chrome/info-label-example-1-core-chrome-windows--1920x1080.png
  e2e/wdio/baselineScreenshot/core/info-label/desktop_chrome/info-label-example-2-core-chrome-mac_os_x--1920x1417.png
  e2e/wdio/baselineScreenshot/core/info-label/desktop_chrome/info-label-example-2-core-chrome-windows--1920x1080.png
  e2e/wdio/baselineScreenshot/core/info-label/desktop_chrome/info-label-example-3-core-chrome-mac_os_x--1920x1417.png
  e2e/wdio/baselineScreenshot/core/info-label/desktop_chrome/info-label-example-3-core-chrome-windows--1920x1080.png
  e2e/wdio/baselineScreenshot/core/info-label/desktop_firefox/info-label-example-0-core-firefox-mac--1920x1417.png
  e2e/wdio/baselineScreenshot/core/info-label/desktop_firefox/info-label-example-0-core-firefox-windows--1936x1096.png
  e2e/wdio/baselineScreenshot/core/info-label/desktop_firefox/info-label-example-1-core-firefox-mac--1920x1417.png
  e2e/wdio/baselineScreenshot/core/info-label/desktop_firefox/info-label-example-1-core-firefox-windows--1936x1096.png
  e2e/wdio/baselineScreenshot/core/info-label/desktop_firefox/info-label-example-2-core-firefox-mac--1920x1417.png
  e2e/wdio/baselineScreenshot/core/info-label/desktop_firefox/info-label-example-2-core-firefox-windows--1936x1096.png
  e2e/wdio/baselineScreenshot/core/info-label/desktop_firefox/info-label-example-3-core-firefox-mac--1920x1417.png
  e2e/wdio/baselineScreenshot/core/info-label/desktop_firefox/info-label-example-3-core-firefox-windows--1936x1096.png
  e2e/wdio/baselineScreenshot/core/info-label/desktop_microsoftedge/info-label-example-0-core-msedge-mac_os_x--1920x1417.png
  e2e/wdio/baselineScreenshot/core/info-label/desktop_microsoftedge/info-label-example-0-core-msedge-windows--1920x1080.png
  e2e/wdio/baselineScreenshot/core/info-label/desktop_microsoftedge/info-label-example-1-core-msedge-mac_os_x--1920x1417.png
  e2e/wdio/baselineScreenshot/core/info-label/desktop_microsoftedge/info-label-example-1-core-msedge-windows--1920x1080.png
  e2e/wdio/baselineScreenshot/core/info-label/desktop_microsoftedge/info-label-example-2-core-msedge-mac_os_x--1920x1417.png
  e2e/wdio/baselineScreenshot/core/info-label/desktop_microsoftedge/info-label-example-2-core-msedge-windows--1920x1080.png
  e2e/wdio/baselineScreenshot/core/info-label/desktop_microsoftedge/info-label-example-3-core-msedge-mac_os_x--1920x1417.png
  e2e/wdio/baselineScreenshot/core/info-label/desktop_microsoftedge/info-label-example-3-core-msedge-windows--1920x1080.png
  e2e/wdio/core/pages/info-label.po.ts
  e2e/wdio/core/tests/info-label.e2e-spec.ts
Labels: core, e2e

#5027 chore: remove old styling
  libs/core/src/lib/feed-list-item/components/list/feed-list.component.ts
  libs/core/src/lib/feed-list-item/original-styles.css
  libs/core/src/lib/loading-spinner/loading-spinner.component.scss
  libs/core/src/lib/modal/modal.component.scss
  libs/core/src/lib/table/table.component.scss
Labels: styling

#5006 fix: (Core) aria checked removed from native checkbox input
  e2e/wdio/platform/tests/checkbox.e2e-spec.ts
  libs/core/src/lib/checkbox/checkbox/checkbox.component.html
  libs/core/src/lib/checkbox/checkbox/checkbox.component.ts
  libs/platform/src/lib/components/form/checkbox/checkbox.component.spec.ts
Labels: ATL, Low, bug, platform

#5038 chore: bump angular, storybook and typedoc versions
  angular.json
  e2e/wdio/core/tests/action-bar.e2e-spec.ts
  e2e/wdio/core/tests/link.e2e-spec.ts
  e2e/wdio/platform/tests/link.e2e-spec.ts
  e2e/wdio/platform/tests/object-list-item.e2e-spec.ts
  package-lock.json
  package.json
  tsconfig.json
Labels: dependencies

#5013 fix: (Core) combobox minor tweaks for defect hunting
  libs/core/src/lib/combobox/combobox.component.html
  libs/core/src/lib/combobox/combobox.component.ts
Labels: Defect Hunting, bug
