Repository SAP/fundamental-ngx, pull requests merged in 2021-02, with the labels that each got.

#4525 fix: (Platform) Incapsulate input search styles
  libs/platform/src/lib/components/search-field/search-field.component.html
  libs/platform/src/lib/components/search-field/search-field.component.scss
Labels: platform

#4497 feat: (Platform) Table Page Scrolling
  apps/docs/src/app/platform/component-docs/platform-table/platform-table-docs.component.html
  apps/docs/src/app/platform/component-docs/platform-table/platform-table-docs.component.ts
  apps/docs/src/app/platform/component-docs/platform-table/platform-table-examples/platform-table-custom-column-example.component.ts
  apps/docs/src/app/platform/component-docs/platform-table/platform-table-examples/platform-table-default-example.component.ts
  apps/docs/src/app/platform/component-docs/platform-table/platform-table-examples/platform-table-filterable-example.component.ts
  apps/docs/src/app/platform/component-docs/platform-table/platform-table-examples/platform-table-freezable-example.component.html
  apps/docs/src/app/platform/component-docs/platform-table/platform-table-examples/platform-table-groupable-example.component.ts
  apps/docs/src/app/platform/component-docs/platform-table/platform-table-examples/platform-table-initial-state-example.component.ts
  apps/docs/src/app/platform/component-docs/platform-table/platform-table-examples/platform-table-multiple-row-selection-example.component.ts
  apps/docs/src/app/platform/component-docs/platform-table/platform-table-examples/platform-table-p13-columns-example.component.ts
  apps/docs/src/app/platform/component-docs/platform-table/platform-table-examples/platform-table-p13-filter-example.component.ts
  apps/docs/src/app/platform/component-docs/platform-table/platform-table-examples/platform-table-p13-group-example.component.ts
  apps/docs/src/app/platform/component-docs/platform-table/platform-table-examples/platform-table-p13-sort-example.component.ts
  apps/docs/src/app/platform/component-docs/platform-table/platform-table-examples/platform-table-page-scrolling-example.component.html
  apps/docs/src/app/platform/component-docs/platform-table/platform-table-examples/platform-table-page-scrolling-example.component.ts
  apps/docs/src/app/platform/component-docs/platform-table/platform-table-examples/platform-table-single-row-selection-example.component.ts
  apps/docs/src/app/platform/component-docs/platform-table/platform-table-examples/platform-table-sortable-example.component.ts
  apps/docs/src/app/platform/component-docs/platform-table/platform-table.module.ts
  libs/platform/src/lib/components/table/components/table-column/table-column.component.ts
  libs/platform/src/lib/components/table/constants/index.ts
  libs/platform/src/lib/components/table/directives/index.ts
  libs/platform/src/lib/components/table/directives/table-scrollable.directive.ts
  libs/platform/src/lib/components/table/directives/table-scroller.directive.ts
  libs/platform/src/lib/components/table/domain/index.ts
  libs/platform/src/lib/components/table/domain/table-data-source.ts
  libs/platform/src/lib/components/table/interfaces/collection-page.interface.ts
  libs/platform/src/lib/components/table/interfaces/collection-state.interface.ts
  libs/platform/src/lib/components/table/models/index.ts
  libs/platform/src/lib/components/table/models/page-change-event.model.ts
  libs/platform/src/lib/components/table/public_api.ts
  libs/platform/src/lib/components/table/table-scroll-dispatcher.service.ts
  libs/platform/src/lib/components/table/table.component.html
  libs/platform/src/lib/components/table/table.component.scss
  libs/platform/src/lib/components/table/table.component.spec.ts
  libs/platform/src/lib/components/table/table.component.ts
  libs/platform/src/lib/components/table/table.module.ts
  libs/platform/src/lib/components/table/table.service.ts
  libs/platform/src/lib/components/table/table.ts
  libs/platform/src/lib/components/table/utils.ts
Labels: platform, table

#4561 chore: revert typedoc version
  package-lock.json
  package.json
Labels: dependencies

#4503 chore: increase version to 0.26.1 add necessary stash to hotfix deploy script
  CHANGELOG.md
  ci-scripts/hotfix-publish.sh
  package-lock.json
  package.json
Labels: tooling

#4504 docs: Add annotation about cdk-scrollable
  apps/docs/src/app/core/component-docs/popover/popover-header/popover-header.component.html
Labels: documentation

#4509 fix: (Core) Remove double mobile menu
  libs/core/src/lib/menu/menu.component.ts
Labels: Defect Hunting, core

#4484 fix: (Platform) fix StackBlitz examples part 2
  apps/docs/src/app/platform/component-docs/platform-forms/platform-date-picker/platform-date-picker-docs.component.html
  apps/docs/src/app/platform/component-docs/platform-forms/platform-date-picker/platform-date-picker-docs.component.ts
  apps/docs/src/app/platform/component-docs/platform-forms/platform-date-picker/platform-date-picker-examples/platform-date-picker-disable-func-example.component.ts
  apps/docs/src/app/platform/component-docs/platform-forms/platform-date-picker/platform-date-picker-examples/platform-date-picker-example.component.ts
  apps/docs/src/app/platform/component-docs/platform-forms/platform-date-picker/platform-date-picker-examples/platform-date-picker-format-example.component.ts
  apps/docs/src/app/platform/component-docs/platform-forms/platform-date-picker/platform-date-picker-examples/platform-date-picker-i18n-example.component.ts
  apps/docs/src/app/platform/component-docs/platform-forms/platform-datetime-picker/platform-datetime-picker-docs.component.html
  apps/docs/src/app/platform/component-docs/platform-forms/platform-datetime-picker/platform-datetime-picker-examples/platform-datetime-picker-basic-example.component.ts
  apps/docs/src/app/platform/component-docs/platform-forms/platform-datetime-picker/platform-datetime-picker-examples/platform-datetime-picker-disable-function-example.component.ts
  apps/docs/src/app/platform/component-docs/platform-forms/platform-datetime-picker/platform-datetime-picker-examples/platform-datetime-picker-reactive-example.component.ts
  apps/docs/src/app/platform/component-docs/platform-forms/platform-datetime-picker/platform-datetime-picker-examples/platform-datetime-picker-template-example.component.ts
  apps/docs/src/app/platform/component-docs/platform-forms/platform-time-picker/examples/platform-time-picker-basic-example.component.ts
  apps/docs/src/app/platform/component-docs/platform-forms/platform-time-picker/examples/platform-time-picker-reactive-example.component.ts
  apps/docs/src/app/platform/component-docs/platform-forms/platform-time-picker/examples/platform-time-picker-template-example.component.ts
  apps/docs/src/app/platform/component-docs/platform-forms/platform-time-picker/platform-time-picker-docs.component.html
  apps/docs/src/app/platform/component-docs/platform-info-label/platform-info-label-docs.component.ts
  apps/docs/src/app/platform/component-docs/platform-info-label/platform-info-label-example/platform-info-label-example.component.scss
  apps/docs/src/app/platform/component-docs/platform-object-status/platform-object-status-docs.component.html
  apps/docs/src/app/platform/component-docs/platform-object-status/platform-object-status-docs.component.ts
  apps/docs/src/app/platform/component-docs/platform-object-status/platform-object-status-docs.module.ts
  apps/docs/src/app/platform/component-docs/platform-object-status/platform-object-status-example/platform-object-status-clickable-and-icon-example.component.scss
  apps/docs/src/app/platform/component-docs/platform-object-status/platform-object-status-example/platform-object-status-clickable-and-icon-example.component.ts
  apps/docs/src/app/platform/component-docs/platform-object-status/platform-object-status-example/platform-object-status-example.component.ts
  apps/docs/src/app/platform/component-docs/platform-object-status/platform-object-status-example/platform-object-status-large-example.component.scss
  apps/docs/src/app/platform/component-docs/platform-object-status/platform-object-status-example/platform-object-status-large-example.component.ts
  apps/docs/src/app/platform/component-docs/platform-thumbnail/platform-thumbnail-examples/platform-thumbnail-basic-example.component.ts
  apps/docs/src/app/platform/component-docs/platform-thumbnail/platform-thumbnail-examples/platform-thumbnail-horizontal-example.component.ts
  apps/docs/src/app/platform/component-docs/platform-thumbnail/platform-thumbnail-examples/platform-thumbnail-video-media-example.component.ts
  apps/docs/src/app/platform/component-docs/platform-thumbnail/platform-thumbnail.docs.component.html
  apps/docs/src/app/platform/component-docs/platform-thumbnail/platform-thumbnail.docs.component.ts
  e2e/wdio/platform/pages/thumbnail.po.ts
Labels: documentation, platform, stackblitz

#4500 fix: (Core) add fix for incorrect Shellbar overflowed counter position
  libs/core/src/lib/shellbar/shellbar-actions/shellbar-actions-mobile.component.html
  libs/core/src/lib/shellbar/shellbar-actions/shellbar-actions-mobile.component.ts
Labels: Defect Hunting

#4515 fix: (Platform) fix tabChange event not emitting in Dynamic Page
  apps/docs/src/app/platform/component-docs/platform-dynamic-page/platform-dynamic-page-examples/platform-dynamic-page-flexible-column-example.component.ts
  apps/docs/src/app/platform/component-docs/platform-dynamic-page/platform-dynamic-page-examples/platform-dynamic-page-non-collapsible-example.component.html
  apps/docs/src/app/platform/component-docs/platform-dynamic-page/platform-dynamic-page-examples/platform-dynamic-page-non-collapsible-example.component.ts
  apps/docs/src/app/platform/component-docs/platform-dynamic-page/platform-dynamic-page-examples/platform-dynamic-page-tabbed-example.component.ts
  libs/platform/src/lib/components/dynamic-page/dynamic-page-content/dynamic-page-content.component.ts
  libs/platform/src/lib/components/dynamic-page/dynamic-page.component.html
  libs/platform/src/lib/components/dynamic-page/dynamic-page.component.scss
  libs/platform/src/lib/components/dynamic-page/dynamic-page.component.ts
Labels: ariba, bug, platform

#4562 fix: (Platform) Removed dependency on click event for Radio button group
  libs/platform/src/lib/components/form/radio-group/radio-group.component.html
  libs/platform/src/lib/components/form/radio-group/radio-group.component.ts
  libs/platform/src/lib/components/form/radio-group/radio/radio.component.html
  libs/platform/src/lib/components/form/radio-group/radio/radio.component.spec.ts
  libs/platform/src/lib/components/form/radio-group/radio/radio.component.ts
Labels: Defect Hunting, platform

#4506 fix: (Core|Platform) Add missing modules in main global module
  apps/docs/src/app/documentation/core-helpers/stackblitz/stackblitz-module-wrapper.ts
  libs/core/src/lib/fundamental-ngx-core.module.ts
  libs/platform/src/lib/platform.module.ts
Labels: Defect Hunting

#4499 fix: (Core) set is-disabled class to disabled button
  libs/core/src/lib/button/base-button.ts
  libs/core/src/lib/button/button.component.spec.ts
  libs/core/src/lib/button/button.component.ts
  libs/platform/src/lib/components/menu-button/menu-button.component.spec.ts
Labels: bug, core

#4505 docs: (Core) stackblitz examples (Action Bar, Action Sheet, Avatar, Busy Indicator, Card)
  apps/docs/src/app/core/component-docs/action-bar/action-bar-docs.component.html
  apps/docs/src/app/core/component-docs/action-bar/action-bar-docs.component.ts
  apps/docs/src/app/core/component-docs/action-bar/action-bar-docs.module.ts
  apps/docs/src/app/core/component-docs/action-bar/examples/action-bar-mobile-example.component.html
  apps/docs/src/app/core/component-docs/action-bar/examples/action-bar-mobile-example.component.ts
  apps/docs/src/app/core/component-docs/action-sheet/action-sheet-docs.component.ts
  apps/docs/src/app/core/component-docs/action-sheet/examples/action-sheet-mobile/action-sheet-mobile-example.component.ts
  apps/docs/src/app/core/component-docs/avatar/avatar-docs.component.html
  apps/docs/src/app/core/component-docs/avatar/avatar-docs.component.ts
  apps/docs/src/app/core/component-docs/avatar/avatar-docs.module.ts
  apps/docs/src/app/core/component-docs/avatar/examples/avatar-accent-colors-example.component.ts
  apps/docs/src/app/core/component-docs/avatar/examples/avatar-background-image-example.component.html
  apps/docs/src/app/core/component-docs/avatar/examples/avatar-background-image-example.component.ts
  apps/docs/src/app/core/component-docs/avatar/examples/avatar-borders-example.component.ts
  apps/docs/src/app/core/component-docs/avatar/examples/avatar-circle-example.component.ts
  apps/docs/src/app/core/component-docs/avatar/examples/avatar-examples.component.scss
  apps/docs/src/app/core/component-docs/avatar/examples/avatar-examples.component.ts
  apps/docs/src/app/core/component-docs/avatar/examples/avatar-icon-example.component.ts
  apps/docs/src/app/core/component-docs/avatar/examples/avatar-initials-example.component.ts
  apps/docs/src/app/core/component-docs/avatar/examples/avatar-placeholder-example.component.ts
  apps/docs/src/app/core/component-docs/avatar/examples/avatar-tile-example.component.ts
  apps/docs/src/app/core/component-docs/avatar/examples/avatar-transparent-example.component.ts
  apps/docs/src/app/core/component-docs/avatar/examples/avatar-zoom-icon-example.component.ts
  apps/docs/src/app/core/component-docs/busy-indicator/busy-indicator-docs.component.ts
  apps/docs/src/app/core/component-docs/card/card-docs.component.ts
  apps/docs/src/app/core/component-docs/card/examples/card-kpi-example.component.ts
  apps/docs/src/app/core/component-docs/card/examples/card-kpi-google-charts.service.ts
  apps/docs/src/app/documentation/core-helpers/stackblitz/stackblitz.service.ts
Labels: core, documentation, stackblitz

#4555 fix: (Core) readable Panel title by screen readers
  libs/core/src/lib/panel/panel-title/panel-title.directive.ts
  libs/core/src/lib/panel/panel.component.scss
Labels: accessibility, bug, core

#4571 docs: Add missing version of ngx
  apps/docs/src/app/documentation/core-helpers/toolbar/toolbar.component.ts
Labels: documentation

#4566 fix: (Core) remove responsive paddings when Shellbar is used with Side Nav
  apps/docs/src/app/core/component-docs/shellbar/examples/shellbar-side-nav/shellbar-side-nav-example.component.html
  apps/docs/src/app/core/component-docs/shellbar/examples/shellbar-side-nav/shellbar-side-nav-example.component.scss
  apps/docs/src/app/core/component-docs/shellbar/shellbar-docs.component.html
  libs/core/src/lib/shellbar/shellbar.component.html
  libs/core/src/lib/shellbar/shellbar.component.scss
  libs/core/src/lib/shellbar/shellbar.component.ts
Labels: core, denoland

#4569 fix: (Platform) provide programmatic tab selection for Dynamic Page
  apps/docs/src/app/platform/component-docs/platform-dynamic-page/platform-dynamic-page-docs.component.html
  apps/docs/src/app/platform/component-docs/platform-dynamic-page/platform-dynamic-page-examples/platform-dynamic-page-tabbed-example.component.html
  apps/docs/src/app/platform/component-docs/platform-dynamic-page/platform-dynamic-page-examples/platform-dynamic-page-tabbed-example.component.ts
  libs/platform/src/lib/components/dynamic-page/dynamic-page-content/dynamic-page-content.component.ts
  libs/platform/src/lib/components/dynamic-page/dynamic-page.component.html
  libs/platform/src/lib/components/dynamic-page/dynamic-page.component.spec.ts
  libs/platform/src/lib/components/dynamic-page/dynamic-page.component.ts
Labels: ariba, enhancement, platform

#4577 fix: (Core) put back step completed on last step
  libs/core/src/lib/wizard/wizard.component.ts
Labels: bug

#4567 fix: (Platform) fix Upload Collection issues
  apps/docs/src/app/platform/component-docs/platform-upload-collection/platform-upload-collection-examples/platform-upload-collection-base-data-provider.ts
  apps/docs/src/app/platform/component-docs/platform-upload-collection/platform-upload-collection-examples/platform-upload-collection-disabled-example.component.html
  apps/docs/src/app/platform/component-docs/platform-upload-collection/platform-upload-collection-examples/platform-upload-collection-disabled-example.component.ts
  apps/docs/src/app/platform/component-docs/platform-upload-collection/platform-upload-collection-examples/platform-upload-collection-example.component.html
  apps/docs/src/app/platform/component-docs/platform-upload-collection/platform-upload-collection-examples/platform-upload-collection-example.component.ts
  apps/docs/src/app/platform/component-docs/platform-upload-collection/platform-upload-collection-examples/platform-upload-collection-readonly-example.component.html
  apps/docs/src/app/platform/component-docs/platform-upload-collection/platform-upload-collection-examples/platform-upload-collection-readonly-example.component.ts
  apps/docs/src/app/platform/component-docs/platform-upload-collection/platform-upload-collection-examples/platform-upload-collection-turn-off-example.component.html
  apps/docs/src/app/platform/component-docs/platform-upload-collection/platform-upload-collection-examples/platform-upload-collection-turn-off-example.component.ts
  libs/platform/src/lib/components/upload-collection/dialogs/move-to/move-to.component.ts
  libs/platform/src/lib/components/upload-collection/dialogs/new-folder/new-folder.component.html
  libs/platform/src/lib/components/upload-collection/dialogs/new-folder/new-folder.component.ts
  libs/platform/src/lib/components/upload-collection/models/upload-collection-events.models.ts
  libs/platform/src/lib/components/upload-collection/models/upload-collection.models.ts
  libs/platform/src/lib/components/upload-collection/upload-collection.module.ts
  libs/platform/src/lib/components/upload-collection/upload-collection/upload-collection.component.html
  libs/platform/src/lib/components/upload-collection/upload-collection/upload-collection.component.scss
  libs/platform/src/lib/components/upload-collection/upload-collection/upload-collection.component.ts
Labels: bug, platform

#4607 fix: (Core) Step Input accessibility
  apps/docs/src/app/platform/component-docs/platform-forms/step-input/platform-step-input-examples/platform-number-step-input-example.component.html
  apps/docs/src/app/platform/component-docs/platform-forms/step-input/platform-step-input-examples/platform-number-step-input-reactive-example.component.html
  apps/docs/src/app/platform/component-docs/platform-forms/step-input/platform-step-input-examples/platform-number-step-input-state-example.component.html
  apps/docs/src/app/platform/component-docs/platform-forms/step-input/platform-step-input-examples/platform-number-step-input-template-example.component.html
  libs/platform/src/lib/components/form/step-input/base.step-input.ts
  libs/platform/src/lib/components/form/step-input/number/number-step-input.component.html
Labels: accessibility, bug, platform

#4586 fix: (Core) Switch accessibility
  e2e/wdio/platform/pages/switch.po.ts
  e2e/wdio/platform/tests/switch.e2e-spec.ts
  libs/core/src/lib/switch/switch.component.html
  libs/core/src/lib/switch/switch.component.scss
  libs/core/src/lib/switch/switch.component.ts
Labels: accessibility, core

#4620 docs: (Core) Quick View title alignment
  apps/docs/src/app/core/component-docs/quick-view/examples/quick-view-dialog-example.component.html
  apps/docs/src/app/core/component-docs/quick-view/examples/quick-view-popover-example.component.html
Labels: Defect Hunting

#4628 docs: (Core) align input with unit description
  apps/docs/src/app/core/component-docs/step-input/step-input-docs.component.scss
Labels: Defect Hunting

#4627 fix: (Core) add fix for content text in Feed Tile truncation
  libs/core/src/lib/tile/tile.component.scss
Labels: Defect Hunting

#4623 fix: (Core) Add setTimeout for IE11 on InitialFocusDirective
  libs/core/src/lib/utils/directives/initial-focus/initial-focus.directive.spec.ts
  libs/core/src/lib/utils/directives/initial-focus/initial-focus.directive.ts
Labels: Defect Hunting

#4630 fix: (Platform) Step Input only numbers
  .gitignore
  e2e/wdio/baselineScreenshot/desktop_chrome/step-input-example-0-platform-chrome-mac_os_x--1920x1417.png
  e2e/wdio/baselineScreenshot/desktop_chrome/step-input-example-0-platform-chrome-windows--1920x1080.png
  e2e/wdio/baselineScreenshot/desktop_firefox/step-input-example-0-platform-firefox-mac--1920x1417.png
  e2e/wdio/baselineScreenshot/desktop_firefox/step-input-example-0-platform-firefox-windows--1936x1096.png
  e2e/wdio/baselineScreenshot/desktop_firefox/step-input-example-1-platform-firefox-mac--1920x1417.png
  e2e/wdio/baselineScreenshot/desktop_firefox/step-input-example-2-platform-firefox-mac--1920x1417.png
  e2e/wdio/baselineScreenshot/desktop_firefox/step-input-example-2-platform-firefox-windows--1936x1096.png
  e2e/wdio/baselineScreenshot/desktop_firefox/step-input-example-3-platform-firefox-mac--1920x1417.png
  e2e/wdio/baselineScreenshot/desktop_firefox/step-input-example-3-platform-firefox-windows--1936x1096.png
  e2e/wdio/baselineScreenshot/desktop_microsoftedge/step-input-example-0-platform-msedge-mac_os_x--1920x1417.png
  e2e/wdio/baselineScreenshot/desktop_microsoftedge/step-input-example-0-platform-msedge-windows--1920x1080.png
  libs/platform/src/lib/components/form/step-input/number/number-step-input.component.html
  libs/platform/src/lib/components/form/step-input/step-input.module.ts
  wdio-local.conf.js
Labels: bug, platform

#4610 fix: (Core) fix grid list
  apps/docs/src/app/core/component-docs/grid-list/examples/default/grid-list-example.component.ts
  apps/docs/src/app/core/component-docs/grid-list/examples/delete/grid-list-delete-example.component.ts
  apps/docs/src/app/core/component-docs/grid-list/examples/dnd/grid-list-dnd-example.component.ts
  apps/docs/src/app/core/component-docs/grid-list/examples/footer/grid-list-footer-example.component.ts
  apps/docs/src/app/core/component-docs/grid-list/examples/grid-list.component.scss
  apps/docs/src/app/core/component-docs/grid-list/examples/group/grid-list-group-example.component.ts
  apps/docs/src/app/core/component-docs/grid-list/examples/layout/grid-list-layout-example.component.ts
  apps/docs/src/app/core/component-docs/grid-list/examples/more/grid-list-more-example.component.ts
  apps/docs/src/app/core/component-docs/grid-list/examples/multi-select/grid-list-multi-select-example.component.ts
  apps/docs/src/app/core/component-docs/grid-list/examples/single-select-left/grid-list-single-select-left-example.component.ts
  apps/docs/src/app/core/component-docs/grid-list/examples/single-select-right/grid-list-single-select-right-example.component.ts
  apps/docs/src/app/core/component-docs/grid-list/examples/single-select/grid-list-single-select-example.component.ts
  libs/core/src/lib/grid-list/components/grid-list-item/grid-list-item.component.html
  libs/core/src/lib/grid-list/components/grid-list-item/grid-list-item.component.scss
  libs/core/src/lib/grid-list/components/grid-list-item/grid-list-item.component.ts
  libs/core/src/lib/grid-list/components/grid-list-more-btn/grid-list-more-btn.component.html
  libs/core/src/lib/grid-list/components/grid-list-more-btn/grid-list-more-btn.component.ts
Labels: Defect Hunting, bug, core

#4638 fix: expose avatar inputs as part of card header
  apps/docs/src/app/core/component-docs/card/examples/card-example.component.html
  apps/docs/src/app/core/component-docs/carousel/examples/carousel-dynamic-items-example.component.html
  apps/docs/src/app/core/component-docs/carousel/examples/carousel-multiple-active-item-example.component.html
  apps/docs/src/app/core/component-docs/fixed-card-layout/examples/default/fixed-card-layout-examples.component.html
  apps/docs/src/app/core/component-docs/fixed-card-layout/examples/disabled-drag-drop/fixed-card-layout-disabled-drag.component.html
  libs/core/src/lib/card/card-header.component.html
  libs/core/src/lib/card/card-header.component.ts
Labels: bug

#4642 fix: (Platform) Empty table filtering options
  libs/platform/src/lib/components/table/components/table-p13-dialog/filtering/filter-rule.component.html
Labels: Defect Hunting, platform

#4621 fix: (Core) Add token validate function to MultiInput
  apps/docs/src/app/core/component-docs/multi-input/examples/multi-input-new-tokens-example/multi-input-new-tokens-example.component.html
  apps/docs/src/app/core/component-docs/multi-input/examples/multi-input-new-tokens-example/multi-input-new-tokens-example.component.ts
  apps/docs/src/app/core/component-docs/multi-input/multi-input-docs.component.html
  libs/core/src/lib/multi-input/multi-input.component.ts
Labels: Defect Hunting

#4580 fix: improvements to the wizard in dialog
  apps/docs/src/app/core/component-docs/wizard/examples/wizard-branching-example.component.html
  apps/docs/src/app/core/component-docs/wizard/examples/wizard-branching-example.component.ts
  apps/docs/src/app/core/component-docs/wizard/examples/wizard-customizable-example.component.html
  apps/docs/src/app/core/component-docs/wizard/examples/wizard-customizable-example.component.ts
  apps/docs/src/app/core/component-docs/wizard/examples/wizard-dialog-example.component.html
  apps/docs/src/app/core/component-docs/wizard/examples/wizard-dialog-example.component.ts
  apps/docs/src/app/core/component-docs/wizard/examples/wizard-example.component.html
  apps/docs/src/app/core/component-docs/wizard/examples/wizard-example.component.scss
  apps/docs/src/app/core/component-docs/wizard/examples/wizard-example.component.ts
  apps/docs/src/app/core/component-docs/wizard/examples/wizard-mobile-example.component.html
  apps/docs/src/app/core/component-docs/wizard/examples/wizard-mobile-example.component.ts
  apps/docs/src/app/core/component-docs/wizard/examples/wizard-ngfor-example.component.html
  apps/docs/src/app/core/component-docs/wizard/examples/wizard-ngfor-example.component.ts
  libs/core/src/lib/dialog/dialog-body/dialog-body.component.ts
  libs/core/src/lib/wizard/wizard.component.html
  libs/core/src/lib/wizard/wizard.component.ts
Labels: bug

#4648 docs: mobile calendars should have cozy buttons
  apps/docs/src/app/core/component-docs/calendar/examples/calendar-mobile-example/calendar-mobile-example.component.html
Labels: documentation

#4631 fix: (Core) Readonly select and arrow down fix
  libs/core/src/lib/popover/popover.component.ts
  libs/core/src/lib/select/select-key-manager.service.ts
  libs/core/src/lib/select/select.component.html
  libs/core/src/lib/select/select.component.ts
Labels: Defect Hunting, core

#4626 feat: (Platform) Approval Flow - Phase 2
  apps/docs/src/app/platform/component-docs/platform-approval-flow/platform-approval-flow-docs.module.ts
  apps/docs/src/app/platform/component-docs/platform-approval-flow/platform-approval-flow-examples/approval-flow-example-data-source.class.ts
  apps/docs/src/app/platform/component-docs/platform-approval-flow/platform-approval-flow-examples/platform-approval-flow-example.component.ts
  libs/core/src/lib/menu/menu.component.ts
  libs/platform/src/lib/components/approval-flow/approval-flow-add-node/approval-flow-add-node.component.html
  libs/platform/src/lib/components/approval-flow/approval-flow-add-node/approval-flow-add-node.component.scss
  libs/platform/src/lib/components/approval-flow/approval-flow-add-node/approval-flow-add-node.component.ts
  libs/platform/src/lib/components/approval-flow/approval-flow-approver-details/approval-flow-approver-details.component.html
  libs/platform/src/lib/components/approval-flow/approval-flow-approver-details/approval-flow-approver-details.component.ts
  libs/platform/src/lib/components/approval-flow/approval-flow-node/approval-flow-drop-zone.directive.ts
  libs/platform/src/lib/components/approval-flow/approval-flow-node/approval-flow-node.component.html
  libs/platform/src/lib/components/approval-flow/approval-flow-node/approval-flow-node.component.scss
  libs/platform/src/lib/components/approval-flow/approval-flow-node/approval-flow-node.component.ts
  libs/platform/src/lib/components/approval-flow/approval-flow-team-list/approval-flow-team-list.component.html
  libs/platform/src/lib/components/approval-flow/approval-flow-team-list/approval-flow-team-list.component.scss
  libs/platform/src/lib/components/approval-flow/approval-flow-team-list/approval-flow-team-list.component.ts
  libs/platform/src/lib/components/approval-flow/approval-flow-user-details/approval-flow-user-details.component.html
  libs/platform/src/lib/components/approval-flow/approval-flow-user-details/approval-flow-user-details.component.scss
  libs/platform/src/lib/components/approval-flow/approval-flow-user-details/approval-flow-user-details.component.ts
  libs/platform/src/lib/components/approval-flow/approval-flow-user-list/approval-flow-user-list.component.html
  libs/platform/src/lib/components/approval-flow/approval-flow-user-list/approval-flow-user-list.component.scss
  libs/platform/src/lib/components/approval-flow/approval-flow-user-list/approval-flow-user-list.component.ts
  libs/platform/src/lib/components/approval-flow/approval-flow.component.html
  libs/platform/src/lib/components/approval-flow/approval-flow.component.scss
  libs/platform/src/lib/components/approval-flow/approval-flow.component.spec.ts
  libs/platform/src/lib/components/approval-flow/approval-flow.component.ts
  libs/platform/src/lib/components/approval-flow/approval-flow.module.ts
  libs/platform/src/lib/components/approval-flow/helpers/index.ts
  libs/platform/src/lib/components/approval-flow/interfaces/approval-data-source.ts
  libs/platform/src/lib/components/approval-flow/interfaces/approval-node.ts
  libs/platform/src/lib/components/approval-flow/interfaces/approval-team.ts
  libs/platform/src/lib/components/approval-flow/interfaces/index.ts
  libs/platform/src/lib/components/approval-flow/services/approval-flow-add-node-view.service.ts
  libs/platform/src/lib/components/approval-flow/styles/approval-flow-dialog.scss
  libs/platform/src/lib/components/list/list.component.ts
Labels: platform

#4652 fix: (Platform) Input Group accessibility
  apps/docs/src/app/platform/component-docs/platform-forms/input-group/platform-input-group-examples/platform-input-group-compact-example.component.html
  apps/docs/src/app/platform/component-docs/platform-forms/input-group/platform-input-group-examples/platform-input-group-disabled-example.component.html
  apps/docs/src/app/platform/component-docs/platform-forms/input-group/platform-input-group-examples/platform-input-group-form-example.component.html
  apps/docs/src/app/platform/component-docs/platform-forms/input-group/platform-input-group-examples/platform-input-group-standard-example.component.html
  e2e/wdio/baselineScreenshot/desktop_chrome/input-group-example-0-platform-chrome-mac_os_x--1920x1417.png
  e2e/wdio/baselineScreenshot/desktop_chrome/input-group-example-0-platform-chrome-windows--1920x1080.png
  e2e/wdio/baselineScreenshot/desktop_chrome/input-group-example-1-platform-chrome-mac_os_x--1920x1417.png
  e2e/wdio/baselineScreenshot/desktop_chrome/input-group-example-1-platform-chrome-windows--1920x1080.png
  e2e/wdio/baselineScreenshot/desktop_chrome/input-group-example-2-platform-chrome-mac_os_x--1920x1417.png
  e2e/wdio/baselineScreenshot/desktop_chrome/input-group-example-2-platform-chrome-windows--1920x1080.png
  e2e/wdio/baselineScreenshot/desktop_chrome/input-group-example-3-platform-chrome-windows--1920x1080.png
  e2e/wdio/baselineScreenshot/desktop_firefox/input-group-example-0-platform-firefox-mac--1920x1417.png
  e2e/wdio/baselineScreenshot/desktop_firefox/input-group-example-0-platform-firefox-windows--1936x1096.png
  e2e/wdio/baselineScreenshot/desktop_firefox/input-group-example-1-platform-firefox-mac--1920x1417.png
  e2e/wdio/baselineScreenshot/desktop_firefox/input-group-example-1-platform-firefox-windows--1936x1096.png
  e2e/wdio/baselineScreenshot/desktop_firefox/input-group-example-2-platform-firefox-mac--1920x1417.png
  e2e/wdio/baselineScreenshot/desktop_firefox/input-group-example-2-platform-firefox-windows--1936x1096.png
  e2e/wdio/baselineScreenshot/desktop_firefox/input-group-example-3-platform-firefox-mac--1920x1417.png
  e2e/wdio/baselineScreenshot/desktop_firefox/input-group-example-3-platform-firefox-windows--1936x1096.png
  e2e/wdio/baselineScreenshot/desktop_microsoftedge/input-group-example-0-platform-msedge-mac_os_x--1920x1417.png
  e2e/wdio/baselineScreenshot/desktop_microsoftedge/input-group-example-0-platform-msedge-windows--1920x1080.png
  e2e/wdio/baselineScreenshot/desktop_microsoftedge/input-group-example-1-platform-msedge-mac_os_x--1920x1417.png
  e2e/wdio/baselineScreenshot/desktop_microsoftedge/input-group-example-1-platform-msedge-windows--1920x1080.png
  e2e/wdio/baselineScreenshot/desktop_microsoftedge/input-group-example-2-platform-msedge-mac_os_x--1920x1417.png
  e2e/wdio/baselineScreenshot/desktop_microsoftedge/input-group-example-2-platform-msedge-windows--1920x1080.png
  e2e/wdio/baselineScreenshot/desktop_microsoftedge/input-group-example-3-platform-msedge-windows--1920x1080.png
  e2e/wdio/platform/pages/input-group.po.ts
  libs/platform/src/lib/components/form/input-group/input-group.component.html
Labels: accessibility, bug

#4691 fix: (Core) proper alignment of the Split Button text
  libs/core/src/lib/split-button/split-button.component.scss
Labels: Defect Hunting

#4701 fix: (Core) remove Popover Directive
  apps/docs/src/app/core/api-files.ts
  apps/docs/src/app/core/component-docs/popover-directive/examples/popover-directive-example/popover-directive-example.component.html
  apps/docs/src/app/core/component-docs/popover-directive/examples/popover-directive-example/popover-directive-example.component.scss
  apps/docs/src/app/core/component-docs/popover-directive/examples/popover-directive-example/popover-directive-example.component.ts
  apps/docs/src/app/core/component-docs/popover-directive/examples/popover-fill/popover-fill.component.html
  apps/docs/src/app/core/component-docs/popover-directive/examples/popover-fill/popover-fill.component.scss
  apps/docs/src/app/core/component-docs/popover-directive/examples/popover-fill/popover-fill.component.ts
  apps/docs/src/app/core/component-docs/popover-directive/examples/popover-programmatic/popover-programmatic.component.html
  apps/docs/src/app/core/component-docs/popover-directive/examples/popover-programmatic/popover-programmatic.component.scss
  apps/docs/src/app/core/component-docs/popover-directive/examples/popover-programmatic/popover-programmatic.component.ts
  apps/docs/src/app/core/component-docs/popover-directive/examples/popover-triggers/popover-triggers.component.html
  apps/docs/src/app/core/component-docs/popover-directive/examples/popover-triggers/popover-triggers.component.scss
  apps/docs/src/app/core/component-docs/popover-directive/examples/popover-triggers/popover-triggers.component.ts
  apps/docs/src/app/core/component-docs/popover-directive/popover-directive-docs.component.html
  apps/docs/src/app/core/component-docs/popover-directive/popover-directive-docs.component.scss
  apps/docs/src/app/core/component-docs/popover-directive/popover-directive-docs.component.ts
  apps/docs/src/app/core/component-docs/popover-directive/popover-directive-docs.module.ts
  apps/docs/src/app/core/component-docs/popover-directive/popover-directive-header/popover-directive-header.component.html
  apps/docs/src/app/core/component-docs/popover-directive/popover-directive-header/popover-directive-header.component.scss
  apps/docs/src/app/core/component-docs/popover-directive/popover-directive-header/popover-directive-header.component.ts
  apps/docs/src/app/core/core-documentation.routes.ts
  apps/docs/src/app/core/documentation/core-documentation.component.ts
  libs/core/src/lib/popover/popover-directive/popover-container.scss
  libs/core/src/lib/popover/popover-directive/popover-container.ts
  libs/core/src/lib/popover/popover-directive/popover.directive.spec.ts
  libs/core/src/lib/popover/popover-directive/popover.directive.ts
  libs/core/src/lib/popover/popover.module.ts
  libs/core/src/lib/popover/public_api.ts
Labels: Defect Hunting

#4700 fix: (Core) add fix for checkbox focus inside Multi Input
  libs/core/src/lib/multi-input/multi-input.component.scss
Labels: Defect Hunting, denoland

#4708 fix: (Platform) accessibility fixes for Table
  libs/platform/src/lib/components/table/table.component.html
Labels: accessibility, platform

#4655 fix: (Core) hide Shellbar custom elements in mobile mode
  libs/core/src/lib/shellbar/shellbar-actions/shellbar-actions.component.html
Labels: denoland

#4633 docs: (Platform) adding password example for the input component
  apps/docs/src/app/platform/component-docs/platform-forms/platform-input/platform-input-example/platform-input-auto-complete-validation-example.component.html
  apps/docs/src/app/platform/component-docs/platform-forms/platform-input/platform-input-example/platform-input-example.component.html
  apps/docs/src/app/platform/component-docs/platform-forms/platform-input/platform-input-example/platform-input-reactive-validation-example.component.html
  e2e/wdio/baselineScreenshot/desktop_chrome/input-example-0-platform-chrome-mac_os_x--1920x1417.png
  e2e/wdio/baselineScreenshot/desktop_chrome/input-example-0-platform-chrome-windows--1920x1080.png
  e2e/wdio/baselineScreenshot/desktop_firefox/input-example-0-platform-firefox-mac--1920x1417.png
  e2e/wdio/baselineScreenshot/desktop_firefox/input-example-0-platform-firefox-windows--1936x1096.png
  e2e/wdio/baselineScreenshot/desktop_firefox/input-example-1-platform-firefox-mac--1920x1417.png
  e2e/wdio/baselineScreenshot/desktop_firefox/input-example-1-platform-firefox-windows--1936x1096.png
  e2e/wdio/baselineScreenshot/desktop_microsoftedge/input-example-0-platform-msedge-mac_os_x--1920x1417.png
  e2e/wdio/baselineScreenshot/desktop_microsoftedge/input-example-0-platform-msedge-windows--1920x1080.png
  e2e/wdio/platform/fixtures/appData/input-page-contents.ts
  e2e/wdio/platform/pages/input.po.ts
  e2e/wdio/platform/tests/input.e2e-spec.ts
Labels: bug

#4687 test: (e2e) refactor e2e test imports
  e2e/wdio/core/fixtures/appData/card-content.ts
  e2e/wdio/core/pages/object-marker.po.ts
  e2e/wdio/core/tests/card.e2e-spec.ts
  e2e/wdio/core/tests/fixed-card-layout.e2e-spec.ts
  e2e/wdio/core/tests/object-marker.e2e-spec.ts
  e2e/wdio/platform/fixtures/appData/input-page-contents.ts
  e2e/wdio/platform/pages/date-time-picker.po.ts
  e2e/wdio/platform/pages/input.po.ts
  e2e/wdio/platform/pages/link.po.ts
  e2e/wdio/platform/pages/list.po.ts
  e2e/wdio/platform/pages/menu-button.po.ts
  e2e/wdio/platform/pages/menu.po.ts
  e2e/wdio/platform/pages/multi-input.po.ts
  e2e/wdio/platform/pages/switch.po.ts
  e2e/wdio/platform/tests/action-list-item.e2e-spec.ts
  e2e/wdio/platform/tests/checkbox-group.e2e-spec.ts
  e2e/wdio/platform/tests/combobox.e2e-spec.ts
  e2e/wdio/platform/tests/date-picker.e2e-spec.ts
  e2e/wdio/platform/tests/display-list-item.e2e-spec.ts
  e2e/wdio/platform/tests/file-uploader.e2e-spec.ts
  e2e/wdio/platform/tests/input-group.e2e-spec.ts
  e2e/wdio/platform/tests/input.e2e-spec.ts
  e2e/wdio/platform/tests/link.e2e-spec.ts
  e2e/wdio/platform/tests/list.e2e-spec.ts
  e2e/wdio/platform/tests/menu-button.e2e-spec.ts
  e2e/wdio/platform/tests/menu.e2e-spec.ts
  e2e/wdio/platform/tests/multi-input.e2e-spec.ts
  e2e/wdio/platform/tests/object-list-item.e2e-spec.ts
  e2e/wdio/platform/tests/panel.e2e-spec.ts
  e2e/wdio/platform/tests/split-menu-button.e2e-spec.ts
  e2e/wdio/platform/tests/standard-list-item.e2e-spec.ts
  e2e/wdio/platform/tests/step-input.e2e-spec.ts
  e2e/wdio/platform/tests/switch.e2e-spec.ts
  e2e/wdio/platform/tests/textarea.e2e-spec.ts
  e2e/wdio/platform/tests/thumbnail.e2e-spec.ts
Labels: e2e

#4715 fix: (Platform) fix combobox list compact
  libs/platform/src/lib/components/form/combobox/combobox/combobox.component.html
Labels: QA Approved, bug, platform

#4739 docs: Add new versions of NGX
  apps/docs/src/app/documentation/core-helpers/toolbar/toolbar.component.ts
Labels: 0.28.0

#4724 test: (e2e) add object attribute e2e tests
  e2e/wdio/baselineScreenshot/desktop_chrome/object-attribute-example-0-platform-chrome-mac_os_x--1920x1417.png
  e2e/wdio/baselineScreenshot/desktop_chrome/object-attribute-example-0-platform-chrome-windows--1920x1080.png
  e2e/wdio/baselineScreenshot/desktop_chrome/object-attribute-example-1-platform-chrome-mac_os_x--1920x1417.png
  e2e/wdio/baselineScreenshot/desktop_chrome/object-attribute-example-1-platform-chrome-windows--1920x1080.png
  e2e/wdio/baselineScreenshot/desktop_chrome/object-attribute-example-2-platform-chrome-mac_os_x--1920x1417.png
  e2e/wdio/baselineScreenshot/desktop_chrome/object-attribute-example-2-platform-chrome-windows--1920x1080.png
  e2e/wdio/baselineScreenshot/desktop_firefox/object-attribute-example-0-platform-firefox-mac--1920x1417.png
  e2e/wdio/baselineScreenshot/desktop_firefox/object-attribute-example-0-platform-firefox-windows--1936x1096.png
  e2e/wdio/baselineScreenshot/desktop_firefox/object-attribute-example-1-platform-firefox-mac--1920x1417.png
  e2e/wdio/baselineScreenshot/desktop_firefox/object-attribute-example-1-platform-firefox-windows--1936x1096.png
  e2e/wdio/baselineScreenshot/desktop_firefox/object-attribute-example-2-platform-firefox-mac--1920x1417.png
  e2e/wdio/baselineScreenshot/desktop_firefox/object-attribute-example-2-platform-firefox-windows--1936x1096.png
  e2e/wdio/baselineScreenshot/desktop_microsoftedge/object-attribute-example-0-platform-msedge-mac_os_x--1920x1417.png
  e2e/wdio/baselineScreenshot/desktop_microsoftedge/object-attribute-example-0-platform-msedge-windows--1920x1080.png
  e2e/wdio/baselineScreenshot/desktop_microsoftedge/object-attribute-example-1-platform-msedge-mac_os_x--1920x1417.png
  e2e/wdio/baselineScreenshot/desktop_microsoftedge/object-attribute-example-1-platform-msedge-windows--1920x1080.png
  e2e/wdio/baselineScreenshot/desktop_microsoftedge/object-attribute-example-2-platform-msedge-mac_os_x--1920x1417.png
  e2e/wdio/baselineScreenshot/desktop_microsoftedge/object-attribute-example-2-platform-msedge-windows--1920x1080.png
  e2e/wdio/platform/fixtures/appData/object-attribute-contents.ts
  e2e/wdio/platform/pages/object-attribute.po.ts
  e2e/wdio/platform/tests/object-attribute.e2e-spec.ts
  wdio.conf.js
Labels: e2e

#4579 feat: (Core) introduce ControlValueAccessor to SegmentedButton
  apps/docs/src/app/core/component-docs/calendar/examples/calendar--i18n-moment-example.component.ts
  apps/docs/src/app/core/component-docs/carousel/examples/carousel-dynamic-items-example.component.html
  apps/docs/src/app/core/component-docs/carousel/examples/carousel-dynamic-items-example.component.ts
  apps/docs/src/app/core/component-docs/date-picker/examples/date-picker-complex-i18n-example/date-picker-complex-i18n-example.component.html
  apps/docs/src/app/core/component-docs/date-picker/examples/date-picker-complex-i18n-example/date-picker-complex-i18n-example.component.ts
  apps/docs/src/app/core/component-docs/fixed-card-layout/examples/default/fixed-card-layout-examples.component.html
  apps/docs/src/app/core/component-docs/fixed-card-layout/examples/default/fixed-card-layout-examples.component.ts
  apps/docs/src/app/core/component-docs/pagination/examples/pagination-per-page-example.component.html
  apps/docs/src/app/core/component-docs/pagination/examples/pagination-per-page-example.component.ts
  apps/docs/src/app/core/component-docs/popover/examples/popover-new-placement/popover-cdk-placement-example.component.html
  apps/docs/src/app/core/component-docs/schemas.ts
  apps/docs/src/app/core/component-docs/segmented-button/examples/segmented-button-complex-example/segmented-button-complex-example.component.html
  apps/docs/src/app/core/component-docs/segmented-button/examples/segmented-button-complex-example/segmented-button-complex-example.component.ts
  apps/docs/src/app/core/component-docs/segmented-button/examples/segmented-button-default-example.component.html
  apps/docs/src/app/core/component-docs/segmented-button/examples/segmented-button-default-example.component.ts
  apps/docs/src/app/core/component-docs/segmented-button/examples/segmented-button-form-example/segmented-button-form-example.component.html
  apps/docs/src/app/core/component-docs/segmented-button/examples/segmented-button-form-example/segmented-button-form-example.component.ts
  apps/docs/src/app/core/component-docs/segmented-button/examples/segmented-button-toggle-example.component.html
  apps/docs/src/app/core/component-docs/segmented-button/examples/segmented-button-toggle-example.component.ts
  apps/docs/src/app/core/component-docs/segmented-button/segmented-button-docs.component.html
  apps/docs/src/app/core/component-docs/segmented-button/segmented-button-docs.component.ts
  apps/docs/src/app/core/component-docs/segmented-button/segmented-button-docs.module.ts
  apps/docs/src/app/core/component-docs/shellbar/examples/shellbar-collapsible-example.component.html
  apps/docs/src/app/core/component-docs/shellbar/examples/shellbar-collapsible-example.component.ts
  apps/docs/src/app/core/component-docs/tabs/examples/tab-selection-example/tab-selection-example.component.html
  apps/docs/src/app/core/component-docs/tabs/examples/tab-selection-example/tab-selection-example.component.scss
  apps/docs/src/app/core/component-docs/time-picker/examples/time-picker-allow-null-example.component.html
  apps/docs/src/app/platform/component-docs/platform-forms/platform-date-picker/platform-date-picker-examples/platform-date-picker-i18n-example.component.html
  apps/docs/src/app/platform/component-docs/platform-forms/platform-time-picker/examples/platform-time-picker-basic-example.component.html
  apps/docs/src/app/platform/component-docs/platform-forms/platform-time-picker/examples/platform-time-picker-template-example.component.html
  libs/core/src/lib/segmented-button/segmented-button.component.scss
  libs/core/src/lib/segmented-button/segmented-button.component.spec.ts
  libs/core/src/lib/segmented-button/segmented-button.component.ts
Labels: enhancement

#4721 test: (e2e) add object status e2e tests platform
  e2e/wdio/baselineScreenshot/desktop_chrome/platform-object-status-example-0-platform-chrome-mac_os_x--1920x1417.png
  e2e/wdio/baselineScreenshot/desktop_chrome/platform-object-status-example-0-platform-chrome-windows--1920x1080.png
  e2e/wdio/baselineScreenshot/desktop_chrome/platform-object-status-example-1-platform-chrome-mac_os_x--1920x1417.png
  e2e/wdio/baselineScreenshot/desktop_chrome/platform-object-status-example-1-platform-chrome-windows--1920x1080.png
  e2e/wdio/baselineScreenshot/desktop_chrome/platform-object-status-example-2-platform-chrome-mac_os_x--1920x1417.png
  e2e/wdio/baselineScreenshot/desktop_chrome/platform-object-status-example-2-platform-chrome-windows--1920x1080.png
  e2e/wdio/baselineScreenshot/desktop_chrome/platform-object-status-example-3-platform-chrome-mac_os_x--1920x1417.png
  e2e/wdio/baselineScreenshot/desktop_chrome/platform-object-status-example-3-platform-chrome-windows--1920x1080.png
  e2e/wdio/baselineScreenshot/desktop_chrome/platform-object-status-example-4-platform-chrome-mac_os_x--1920x1417.png
  e2e/wdio/baselineScreenshot/desktop_chrome/platform-object-status-example-4-platform-chrome-windows--1920x1080.png
  e2e/wdio/baselineScreenshot/desktop_chrome/platform-object-status-example-5-platform-chrome-mac_os_x--1920x1417.png
  e2e/wdio/baselineScreenshot/desktop_chrome/platform-object-status-example-5-platform-chrome-windows--1920x1080.png
  e2e/wdio/baselineScreenshot/desktop_chrome/platform-object-status-example-6-platform-chrome-mac_os_x--1920x1417.png
  e2e/wdio/baselineScreenshot/desktop_chrome/platform-object-status-example-6-platform-chrome-windows--1920x1080.png
  e2e/wdio/baselineScreenshot/desktop_chrome/platform-object-status-example-7-platform-chrome-mac_os_x--1920x1417.png
  e2e/wdio/baselineScreenshot/desktop_chrome/platform-object-status-example-7-platform-chrome-windows--1920x1080.png
  e2e/wdio/baselineScreenshot/desktop_firefox/platform-object-status-example-0-platform-firefox-mac--1920x1417.png
  e2e/wdio/baselineScreenshot/desktop_firefox/platform-object-status-example-0-platform-firefox-windows--1936x1096.png
  e2e/wdio/baselineScreenshot/desktop_firefox/platform-object-status-example-1-platform-firefox-mac--1920x1417.png
  e2e/wdio/baselineScreenshot/desktop_firefox/platform-object-status-example-1-platform-firefox-windows--1936x1096.png
  e2e/wdio/baselineScreenshot/desktop_firefox/platform-object-status-example-2-platform-firefox-mac--1920x1417.png
  e2e/wdio/baselineScreenshot/desktop_firefox/platform-object-status-example-2-platform-firefox-windows--1936x1096.png
  e2e/wdio/baselineScreenshot/desktop_firefox/platform-object-status-example-3-platform-firefox-mac--1920x1417.png
  e2e/wdio/baselineScreenshot/desktop_firefox/platform-object-status-example-3-platform-firefox-windows--1936x1096.png
  e2e/wdio/baselineScreenshot/desktop_firefox/platform-object-status-example-4-platform-firefox-mac--1920x1417.png
  e2e/wdio/baselineScreenshot/desktop_firefox/platform-object-status-example-4-platform-firefox-windows--1936x1096.png
  e2e/wdio/baselineScreenshot/desktop_firefox/platform-object-status-example-5-platform-firefox-mac--1920x1417.png
  e2e/wdio/baselineScreenshot/desktop_firefox/platform-object-status-example-5-platform-firefox-windows--1936x1096.png
  e2e/wdio/baselineScreenshot/desktop_firefox/platform-object-status-example-6-platform-firefox-mac--1920x1417.png
  e2e/wdio/baselineScreenshot/desktop_firefox/platform-object-status-example-6-platform-firefox-windows--1936x1096.png
  e2e/wdio/baselineScreenshot/desktop_firefox/platform-object-status-example-7-platform-firefox-mac--1920x1417.png
  e2e/wdio/baselineScreenshot/desktop_firefox/platform-object-status-example-7-platform-firefox-windows--1936x1096.png
  e2e/wdio/baselineScreenshot/desktop_microsoftedge/platform-object-status-example-0-platform-msedge-mac_os_x--1920x1417.png
  e2e/wdio/baselineScreenshot/desktop_microsoftedge/platform-object-status-example-0-platform-msedge-windows--1920x1080.png
  e2e/wdio/baselineScreenshot/desktop_microsoftedge/platform-object-status-example-1-platform-msedge-mac_os_x--1920x1417.png
  e2e/wdio/baselineScreenshot/desktop_microsoftedge/platform-object-status-example-1-platform-msedge-windows--1920x1080.png
  e2e/wdio/baselineScreenshot/desktop_microsoftedge/platform-object-status-example-2-platform-msedge-mac_os_x--1920x1417.png
  e2e/wdio/baselineScreenshot/desktop_microsoftedge/platform-object-status-example-2-platform-msedge-windows--1920x1080.png
  e2e/wdio/baselineScreenshot/desktop_microsoftedge/platform-object-status-example-3-platform-msedge-mac_os_x--1920x1417.png
  e2e/wdio/baselineScreenshot/desktop_microsoftedge/platform-object-status-example-3-platform-msedge-windows--1920x1080.png
  e2e/wdio/baselineScreenshot/desktop_microsoftedge/platform-object-status-example-4-platform-msedge-mac_os_x--1920x1417.png
  e2e/wdio/baselineScreenshot/desktop_microsoftedge/platform-object-status-example-4-platform-msedge-windows--1920x1080.png
  e2e/wdio/baselineScreenshot/desktop_microsoftedge/platform-object-status-example-5-platform-msedge-mac_os_x--1920x1417.png
  e2e/wdio/baselineScreenshot/desktop_microsoftedge/platform-object-status-example-5-platform-msedge-windows--1920x1080.png
  e2e/wdio/baselineScreenshot/desktop_microsoftedge/platform-object-status-example-6-platform-msedge-mac_os_x--1920x1417.png
  e2e/wdio/baselineScreenshot/desktop_microsoftedge/platform-object-status-example-6-platform-msedge-windows--1920x1080.png
  e2e/wdio/baselineScreenshot/desktop_microsoftedge/platform-object-status-example-7-platform-msedge-mac_os_x--1920x1417.png
  e2e/wdio/baselineScreenshot/desktop_microsoftedge/platform-object-status-example-7-platform-msedge-windows--1920x1080.png
  e2e/wdio/platform/fixtures/appData/object-status-contents.ts
  e2e/wdio/platform/pages/object-status.po.ts
  e2e/wdio/platform/tests/object-status.e2e-spec.ts
  wdio.conf.js
Labels: e2e

#4654 feat: (Core) introduce text component
  apps/docs/src/app/core/api-files.ts
  apps/docs/src/app/core/component-docs/text/examples/text-basic.component.html
  apps/docs/src/app/core/component-docs/text/examples/text-basic.component.ts
  apps/docs/src/app/core/component-docs/text/examples/text-expandable.component.html
  apps/docs/src/app/core/component-docs/text/examples/text-expandable.component.ts
  apps/docs/src/app/core/component-docs/text/examples/text-hyphenation.component.html
  apps/docs/src/app/core/component-docs/text/examples/text-hyphenation.component.scss
  apps/docs/src/app/core/component-docs/text/examples/text-hyphenation.component.ts
  apps/docs/src/app/core/component-docs/text/examples/text-max-lines.component.html
  apps/docs/src/app/core/component-docs/text/examples/text-max-lines.component.ts
  apps/docs/src/app/core/component-docs/text/examples/text-whitespaces.component.html
  apps/docs/src/app/core/component-docs/text/examples/text-whitespaces.component.ts
  apps/docs/src/app/core/component-docs/text/text-docs.component.html
  apps/docs/src/app/core/component-docs/text/text-docs.component.ts
  apps/docs/src/app/core/component-docs/text/text-docs.module.ts
  apps/docs/src/app/core/component-docs/text/text-header/text-header.component.html
  apps/docs/src/app/core/component-docs/text/text-header/text-header.component.ts
  apps/docs/src/app/core/core-documentation.routes.ts
  apps/docs/src/app/core/documentation/core-documentation.component.ts
  libs/core/src/index.ts
  libs/core/src/lib/fundamental-ngx-core.module.ts
  libs/core/src/lib/text/public_api.ts
  libs/core/src/lib/text/text.component.html
  libs/core/src/lib/text/text.component.scss
  libs/core/src/lib/text/text.component.spec.ts
  libs/core/src/lib/text/text.component.ts
  libs/core/src/lib/text/text.module.ts
  libs/core/src/lib/utils/directives/line-clamp/line-clamp.directive.ts
Labels: core

#4753 fix: (Platform) defect hunting issues in approval flow
  libs/platform/src/lib/components/approval-flow/approval-flow-add-node/approval-flow-add-node.component.html
  libs/platform/src/lib/components/approval-flow/approval-flow-add-node/approval-flow-add-node.component.ts
  libs/platform/src/lib/components/approval-flow/approval-flow-node/approval-flow-node.component.html
  libs/platform/src/lib/components/approval-flow/approval-flow-user-details/approval-flow-user-details.component.scss
  libs/platform/src/lib/components/approval-flow/approval-flow.component.html
  libs/platform/src/lib/components/approval-flow/approval-flow.component.ts
  libs/platform/src/lib/components/approval-flow/styles/approval-flow-dialog.scss
Labels: Defect Hunting

#4720 fix: (Core) change touched state on focus for Datepickers
  libs/core/src/lib/date-picker/date-picker.component.html
  libs/core/src/lib/datetime-picker/datetime-picker.component.html
Labels: Defect Hunting

#4702 feat: (Platform)Thumbnail component v2 enhancements
  apps/docs/src/app/platform/component-docs/platform-thumbnail/platform-thumbnail-examples/platform-thumbnail-basic-example.component.html
  apps/docs/src/app/platform/component-docs/platform-thumbnail/platform-thumbnail-examples/platform-thumbnail-basic-example.component.ts
  apps/docs/src/app/platform/component-docs/platform-thumbnail/platform-thumbnail-examples/platform-thumbnail-horizontal-example.component.ts
  apps/docs/src/app/platform/component-docs/platform-thumbnail/platform-thumbnail-examples/platform-thumbnail-video-media-example.component.ts
  libs/platform/src/lib/components/thumbnail/thumbnail-details/thumbnail-details.component.html
  libs/platform/src/lib/components/thumbnail/thumbnail-details/thumbnail-details.component.scss
  libs/platform/src/lib/components/thumbnail/thumbnail-details/thumbnail-details.component.spec.ts
  libs/platform/src/lib/components/thumbnail/thumbnail-details/thumbnail-details.component.ts
  libs/platform/src/lib/components/thumbnail/thumbnail-image/thumbnail-image.component.html
  libs/platform/src/lib/components/thumbnail/thumbnail-image/thumbnail-image.component.scss
  libs/platform/src/lib/components/thumbnail/thumbnail-image/thumbnail-image.component.spec.ts
  libs/platform/src/lib/components/thumbnail/thumbnail-image/thumbnail-image.component.ts
  libs/platform/src/lib/components/thumbnail/thumbnail.component.html
  libs/platform/src/lib/components/thumbnail/thumbnail.component.scss
  libs/platform/src/lib/components/thumbnail/thumbnail.component.spec.ts
  libs/platform/src/lib/components/thumbnail/thumbnail.component.ts
  libs/platform/src/lib/components/thumbnail/thumbnail.module.ts
  wdio.conf.js
Labels: platform

#4709 feat: (Core) add custom item template option to Multi Input
  apps/docs/src/app/core/component-docs/multi-input/examples/multi-input-custom-item-example/multi-input-custom-item-example.component.html
  apps/docs/src/app/core/component-docs/multi-input/examples/multi-input-custom-item-example/multi-input-custom-item-example.component.ts
  apps/docs/src/app/core/component-docs/multi-input/multi-input-docs.component.html
  apps/docs/src/app/core/component-docs/multi-input/multi-input-docs.component.ts
  apps/docs/src/app/core/component-docs/multi-input/multi-input-docs.module.ts
  libs/core/src/lib/multi-input/multi-input.component.html
  libs/core/src/lib/multi-input/multi-input.component.ts
Labels: enhancement

#4758 feat(store): Entity Query Interface
  angular.json
  libs/store/karma.conf.js
  libs/store/src/lib/persistence/query/grammer/predicate.ts
  libs/store/src/lib/persistence/query/grammer/query-expressions.ts
  libs/store/src/lib/persistence/query/query-adapter.spec.ts
  libs/store/src/lib/persistence/query/query-adapter.ts
  libs/store/src/lib/persistence/query/query-builder.ts
  libs/store/src/lib/persistence/query/query.service.ts
  libs/store/src/lib/persistence/query/query.spec.ts
  libs/store/src/lib/persistence/query/query.ts
  libs/store/src/test-setup.ts
  libs/store/src/test.ts
  libs/store/tsconfig.spec.json
  package-lock.json
  package.json
Labels: state management

#4768 fix: (Core) Split Buton 0.16.1 migration
  libs/core/src/lib/split-button/split-button.component.html
  libs/core/src/lib/split-button/split-button.component.scss
  libs/core/src/lib/split-button/split-button.component.spec.ts
  libs/core/src/lib/split-button/split-button.component.ts
Labels: denoland

#4743 fix: (Core) fix Slider tooltip RTL
  libs/core/src/lib/slider/slider.component.scss
Labels: Defect Hunting, core

#4704 fix: (Core) accessibility fixes for fixed card layout
  apps/docs/src/app/core/api-files.ts
  apps/docs/src/app/core/component-docs/fixed-card-layout/examples/default/fixed-card-layout-examples.component.html
  apps/docs/src/app/core/component-docs/fixed-card-layout/examples/default/fixed-card-layout-examples.component.ts
  libs/core/src/lib/fixed-card-layout/fixed-card-layout-item/fixed-card-layout-item.component.ts
  libs/core/src/lib/fixed-card-layout/fixed-card-layout.component.html
  libs/core/src/lib/fixed-card-layout/fixed-card-layout.component.ts
  libs/core/src/lib/fixed-card-layout/fixed-card-layout.module.ts
Labels: accessibility, core

#4776 fix(store): Fixing spelling "grammer" -> "grammar"
  libs/store/src/lib/infrastructure/persistence/query/grammar/predicate.ts
  libs/store/src/lib/infrastructure/persistence/query/grammar/query-expressions.ts
  libs/store/src/lib/infrastructure/persistence/query/query-adapter.spec.ts
  libs/store/src/lib/infrastructure/persistence/query/query-adapter.ts
  libs/store/src/lib/infrastructure/persistence/query/query-builder.ts
  libs/store/src/lib/infrastructure/persistence/query/query.spec.ts
  libs/store/src/lib/infrastructure/persistence/query/query.ts
Labels: state management

#4749 fix: selecting multi-input option should clear search term
  libs/core/src/lib/multi-input/multi-input.component.spec.ts
  libs/core/src/lib/multi-input/multi-input.component.ts
Labels: bug

#4719 fix: (Core) add grab cursor to drag and drop Grid List items
  libs/core/src/lib/utils/drag-and-drop/drag-and-drop.scss
Labels: Defect Hunting

#4693 docs: (Core) refactor dialog example to remove box shadow issue
  apps/docs/src/app/core/component-docs/wizard/examples/wizard-dialog-example.component.html
  apps/docs/src/app/core/component-docs/wizard/examples/wizard-example.component.scss
Labels: documentation

#4775 fix: (Core|Docs) Defect hunting issues
  apps/docs/src/app/documentation/core-helpers/toolbar/toolbar.component.html
  apps/docs/src/app/documentation/core-helpers/toolbar/toolbar.component.scss
  apps/docs/src/app/documentation/core-helpers/toolbar/toolbar.component.ts
  apps/docs/src/styles.scss
  libs/core/src/lib/datetime-picker/datetime-picker.component.ts
  libs/core/src/lib/table/table.component.scss
  package-lock.json
Labels: 0.28.0

#4744 docs: (Core) updating programmatic select example as requested by QA for testing
  apps/docs/src/app/core/component-docs/select/examples/select-programmatic-example/select-programmatic-example.component.ts
Labels: QA Approved

#4769 fix: (Platform) table enhancements
  apps/docs/src/app/platform/component-docs/platform-table/platform-table-docs.component.html
  apps/docs/src/app/platform/component-docs/platform-table/platform-table-examples/platform-table-page-scrolling-example.component.ts
  libs/platform/src/lib/components/table/components/table-p13-dialog/table-p13-dialog.component.ts
  libs/platform/src/lib/components/table/directives/index.ts
  libs/platform/src/lib/components/table/directives/table-cell-selectable.directive.ts
  libs/platform/src/lib/components/table/table.component.html
  libs/platform/src/lib/components/table/table.component.scss
  libs/platform/src/lib/components/table/table.component.ts
  libs/platform/src/lib/components/table/table.module.ts
Labels: Defect Hunting, platform

#4741 fix: (Platform) fix combobox resize
  apps/docs/src/app/platform/component-docs/platform-combobox/examples/combobox-columns/combobox-columns-example.component.html
  apps/docs/src/app/platform/component-docs/platform-combobox/examples/combobox-datasource/combobox-datasource-example.component.html
  apps/docs/src/app/platform/component-docs/platform-combobox/examples/combobox-forms/combobox-forms-example.component.html
  apps/docs/src/app/platform/component-docs/platform-combobox/examples/combobox-group/combobox-group-example.component.html
  apps/docs/src/app/platform/component-docs/platform-combobox/examples/combobox-mobile/combobox-mobile-example.component.html
  apps/docs/src/app/platform/component-docs/platform-combobox/examples/combobox-standard/combobox-standard.component.html
  apps/docs/src/app/platform/component-docs/platform-combobox/examples/combobox-states/combobox-states-example.component.html
  apps/docs/src/app/platform/component-docs/platform-combobox/examples/combobox-templates/combobox-templates-example.component.html
  e2e/wdio/baselineScreenshot/desktop_chrome/combobox-example-0-platform-chrome-mac_os_x--1920x1417.png
  e2e/wdio/baselineScreenshot/desktop_chrome/combobox-example-0-platform-chrome-windows--1920x1080.png
  e2e/wdio/baselineScreenshot/desktop_chrome/combobox-example-1-platform-chrome-mac_os_x--1920x1417.png
  e2e/wdio/baselineScreenshot/desktop_chrome/combobox-example-1-platform-chrome-windows--1920x1080.png
  e2e/wdio/baselineScreenshot/desktop_chrome/combobox-example-2-platform-chrome-mac_os_x--1920x1417.png
  e2e/wdio/baselineScreenshot/desktop_chrome/combobox-example-2-platform-chrome-windows--1920x1080.png
  e2e/wdio/baselineScreenshot/desktop_chrome/combobox-example-3-platform-chrome-mac_os_x--1920x1417.png
  e2e/wdio/baselineScreenshot/desktop_chrome/combobox-example-3-platform-chrome-windows--1920x1080.png
  e2e/wdio/baselineScreenshot/desktop_chrome/combobox-example-4-platform-chrome-mac_os_x--1920x1417.png
  e2e/wdio/baselineScreenshot/desktop_chrome/combobox-example-4-platform-chrome-windows--1920x1080.png
  e2e/wdio/baselineScreenshot/desktop_chrome/combobox-example-5-platform-chrome-mac_os_x--1920x1417.png
  e2e/wdio/baselineScreenshot/desktop_chrome/combobox-example-5-platform-chrome-windows--1920x1080.png
  e2e/wdio/baselineScreenshot/desktop_chrome/combobox-example-6-platform-chrome-mac_os_x--1920x1417.png
  e2e/wdio/baselineScreenshot/desktop_chrome/combobox-example-6-platform-chrome-windows--1920x1080.png
  e2e/wdio/baselineScreenshot/desktop_chrome/combobox-example-7-platform-chrome-mac_os_x--1920x1417.png
  e2e/wdio/baselineScreenshot/desktop_chrome/combobox-example-7-platform-chrome-windows--1920x1080.png
  e2e/wdio/baselineScreenshot/desktop_firefox/combobox-example-0-platform-firefox-mac--1920x1417.png
  e2e/wdio/baselineScreenshot/desktop_firefox/combobox-example-0-platform-firefox-windows--1936x1096.png
  e2e/wdio/baselineScreenshot/desktop_firefox/combobox-example-1-platform-firefox-mac--1920x1417.png
  e2e/wdio/baselineScreenshot/desktop_firefox/combobox-example-1-platform-firefox-windows--1936x1096.png
  e2e/wdio/baselineScreenshot/desktop_firefox/combobox-example-2-platform-firefox-mac--1920x1417.png
  e2e/wdio/baselineScreenshot/desktop_firefox/combobox-example-2-platform-firefox-windows--1936x1096.png
  e2e/wdio/baselineScreenshot/desktop_firefox/combobox-example-3-platform-firefox-mac--1920x1417.png
  e2e/wdio/baselineScreenshot/desktop_firefox/combobox-example-3-platform-firefox-windows--1936x1096.png
  e2e/wdio/baselineScreenshot/desktop_firefox/combobox-example-4-platform-firefox-mac--1920x1417.png
  e2e/wdio/baselineScreenshot/desktop_firefox/combobox-example-4-platform-firefox-windows--1936x1096.png
  e2e/wdio/baselineScreenshot/desktop_firefox/combobox-example-5-platform-firefox-mac--1920x1417.png
  e2e/wdio/baselineScreenshot/desktop_firefox/combobox-example-5-platform-firefox-windows--1936x1096.png
  e2e/wdio/baselineScreenshot/desktop_firefox/combobox-example-6-platform-firefox-mac--1920x1417.png
  e2e/wdio/baselineScreenshot/desktop_firefox/combobox-example-6-platform-firefox-windows--1936x1096.png
  e2e/wdio/baselineScreenshot/desktop_firefox/combobox-example-7-platform-firefox-mac--1920x1417.png
  e2e/wdio/baselineScreenshot/desktop_firefox/combobox-example-7-platform-firefox-windows--1936x1096.png
  e2e/wdio/baselineScreenshot/desktop_microsoftedge/combobox-example-0-platform-msedge-mac_os_x--1920x1417.png
  e2e/wdio/baselineScreenshot/desktop_microsoftedge/combobox-example-0-platform-msedge-windows--1920x1080.png
  e2e/wdio/baselineScreenshot/desktop_microsoftedge/combobox-example-1-platform-msedge-mac_os_x--1920x1417.png
  e2e/wdio/baselineScreenshot/desktop_microsoftedge/combobox-example-1-platform-msedge-windows--1920x1080.png
  e2e/wdio/baselineScreenshot/desktop_microsoftedge/combobox-example-2-platform-msedge-mac_os_x--1920x1417.png
  e2e/wdio/baselineScreenshot/desktop_microsoftedge/combobox-example-2-platform-msedge-windows--1920x1080.png
  e2e/wdio/baselineScreenshot/desktop_microsoftedge/combobox-example-3-platform-msedge-mac_os_x--1920x1417.png
  e2e/wdio/baselineScreenshot/desktop_microsoftedge/combobox-example-3-platform-msedge-windows--1920x1080.png
  e2e/wdio/baselineScreenshot/desktop_microsoftedge/combobox-example-4-platform-msedge-mac_os_x--1920x1417.png
  e2e/wdio/baselineScreenshot/desktop_microsoftedge/combobox-example-4-platform-msedge-windows--1920x1080.png
  e2e/wdio/baselineScreenshot/desktop_microsoftedge/combobox-example-5-platform-msedge-mac_os_x--1920x1417.png
  e2e/wdio/baselineScreenshot/desktop_microsoftedge/combobox-example-5-platform-msedge-windows--1920x1080.png
  e2e/wdio/baselineScreenshot/desktop_microsoftedge/combobox-example-6-platform-msedge-mac_os_x--1920x1417.png
  e2e/wdio/baselineScreenshot/desktop_microsoftedge/combobox-example-6-platform-msedge-windows--1920x1080.png
  e2e/wdio/baselineScreenshot/desktop_microsoftedge/combobox-example-7-platform-msedge-mac_os_x--1920x1417.png
  e2e/wdio/baselineScreenshot/desktop_microsoftedge/combobox-example-7-platform-msedge-windows--1920x1080.png
  libs/platform/src/lib/components/form/combobox/combobox/combobox.component.html
  libs/platform/src/lib/components/form/combobox/combobox/combobox.component.scss
  libs/platform/src/lib/components/form/combobox/commons/base-combobox.ts
Labels: QA Approved, bug, platform

#4488 fix: (Core | Platform) feed input accessibility issues
  apps/docs/src/app/platform/component-docs/platform-feed-input/platform-feed-input-examples/platform-feed-input-example/platform-feed-input-example.component.html
  e2e/wdio/platform/tests/feed-input.e2e-spec.ts
  libs/core/src/lib/feed-input/directives/feed-input-button.directive.ts
  libs/core/src/lib/feed-input/feed-input.component.spec.ts
  libs/platform/src/lib/components/button/button.component.html
  libs/platform/src/lib/components/feed-input/feed-input.component.html
  libs/platform/src/lib/components/feed-input/feed-input.component.spec.ts
  libs/platform/src/lib/components/feed-input/feed-input.component.ts
Labels: QA Approved, accessibility
