Repository SAP/fundamental-ngx, pull requests merged in 2022-12, with the labels that each got.

#9018 chore(core,platform): styles bump to 0.26.0-rc.37 and BC processing
  libs/core/src/lib/file-uploader/file-uploader.component.html
  libs/core/src/lib/file-uploader/file-uploader.component.scss
  libs/core/src/lib/file-uploader/file-uploader.component.ts
  libs/core/src/lib/popover/popover-body/popover-body.component.ts
  package.json
  yarn.lock
Labels: core, 0.37

#9017 feat(platform): wizard generator group hint
  libs/docs/platform/wizard-generator/examples/wizard-generator-default-example.component.ts
  libs/platform/src/lib/wizard-generator/components/wizard-generator-step/wizard-generator-step.component.html
  libs/platform/src/lib/wizard-generator/interfaces/wizard-generator-form-group.interface.ts
Labels: dxp, 0.37

#9016 fix(platform): dynamic page tabs padding
  libs/core/src/lib/tabs/tab-list.component.scss
  libs/platform/src/lib/dynamic-page/dynamic-page.component.ts
Labels: dxp, 0.37

#9023 fix(core): vertical nav regression
  libs/core/src/lib/vertical-navigation/vertical-navigation.component.scss
Labels: bug, core, 0.37

#9019 feat(platform): custom load more content on lists
  libs/docs/platform/list/examples/platform-list-with-more-button-example.component.html
  libs/platform/src/lib/list/list.component.html
  libs/platform/src/lib/list/list.component.scss
  libs/platform/src/lib/list/list.component.ts
  libs/platform/src/lib/list/list.module.ts
  libs/platform/src/lib/list/load-more-content.directive.ts
  libs/platform/src/lib/list/public_api.ts
Labels: enhancement

#9014 fix(platform): fixed data source limitation of 5 items in the list
  libs/docs/platform/list/examples/platform-list-border-less-example.component.html
  libs/docs/platform/list/examples/platform-list-border-less-example.component.ts
  libs/platform/src/lib/list/list.component.ts
  libs/platform/src/lib/shared/domain/data-source.ts
Labels: bug, dxp

#9022 chore(deps): bump theming-base-content version 11.1.47
  package.json
  yarn.lock
Labels: tooling, dependencies, theming

#9033 fix(platform): fixed list item change detection latency
  libs/docs/platform/approval-flow/e2e/approval-flow.e2e-spec.ts
  libs/platform/src/lib/list/base-list-item.ts
  libs/platform/src/lib/list/fdpListComponent.token.ts
  libs/platform/src/lib/list/list.component.ts
  libs/platform/src/lib/list/public_api.ts
Labels: bug, planned, 0.37

#9044 fix(platform,docs): added missing export of PlatformMultiComboboxModule
  libs/platform/src/lib/fundamental-ngx.module.ts
Labels: bug, documentation, platform, quick fix, 0.37

#9032 feat(platform): add toggling search button in search-field
  libs/platform/src/lib/search-field/search-field.component.html
  libs/platform/src/lib/search-field/search-field.component.ts
Labels: enhancement, dxp

#9008 fix(core): select custom width & refactoring
  libs/core/src/lib/select/option/option.component.html
  libs/core/src/lib/select/select.component.html
  libs/core/src/lib/select/select.component.scss
  libs/core/src/lib/select/select.component.spec.ts
  libs/core/src/lib/select/select.component.ts
  libs/docs/core/select/select-docs.module.ts
Labels: code refactoring, core, dxp, 0.37

#9010 fix(core,platform): button toggled state
  libs/core/src/lib/button/base-button.ts
  libs/core/src/lib/dynamic-page/dynamic-page-header/subheader/dynamic-page-subheader.component.html
  libs/core/src/lib/utils/interfaces/module-deprecation.interface.ts
  libs/docs/core/button/button-docs.component.html
  libs/docs/core/button/examples/button-state-example.component.html
  libs/docs/core/dynamic-page/e2e/dynamic-page.e2e-spec.ts
  libs/docs/core/flexible-column-layout/e2e/flexible-column-layout.e2e-spec.ts
  libs/docs/core/resizable-card-layout/e2e/resizable-card-layout.e2e-spec.ts
  libs/docs/platform/button/platform-button.module.ts
  libs/docs/shared/src/lib/core-helpers/deprecated-alerts/deprecated-alerts.component.html
  libs/platform/src/lib/button/button.component.html
  libs/platform/src/lib/button/button.component.ts
  libs/platform/src/lib/form/select/select/select.component.ts
Labels: dxp, 0.37

#9053 fix(platform): select multi column options
  libs/core/src/lib/select/option/option.component.html
  libs/platform/src/lib/form/select/select/select.component.html
  libs/platform/src/lib/form/select/select/select.component.spec.ts
  libs/platform/src/lib/form/select/select/select.component.ts
Labels: bug, platform, 0.37

#9052 chore(deps-dev): removed wdio-html-format-reporter from dependencies
  package.json
  yarn.lock
Labels: dependencies, 0.37

#9055 chore(docs): fixed documentation page errors
  libs/docs/core/calendar/calendar-docs.component.ts
  libs/docs/platform/file-uploader/examples/platform-file-uploader-example.component.html
Labels: documentation, 0.37

#9057 feat(docs): added pure example file type
  libs/docs/shared/src/lib/core-helpers/code-example/example-file.ts
  libs/docs/shared/src/lib/core-helpers/stackblitz/stackblitz.service.ts
  libs/docs/shared/src/lib/getAsset.ts
Labels: enhancement, documentation, nice to have, Low

#9061 fix(core): fixed deprecated tab list compact directive
  libs/core/src/lib/tabs/deprecated-tabs-compact.directive.ts
Labels: bug, core, quick fix

#9083 feat(core): split schematics into separate steps
  libs/core/schematics/add-animations/index.ts
  libs/core/schematics/add-animations/schema.json
  libs/core/schematics/add-dependencies/index.ts
  libs/core/schematics/add-dependencies/schema.json
  libs/core/schematics/add-styles/index.ts
  libs/core/schematics/add-styles/schema.json
  libs/core/schematics/add-theming/index.ts
  libs/core/schematics/add-theming/schema.json
  libs/core/schematics/collection.json
  libs/core/schematics/models/schema.ts
  libs/core/schematics/ng-add/index.ts
  libs/core/schematics/utils/package-utils.ts
Labels: enhancement

#8983 fix(docs): removing of hardcoded density
  libs/docs/core/action-bar/examples/action-bar-back-example.component.html
  libs/docs/core/action-bar/examples/action-bar-contextual-menu-example.component.html
  libs/docs/core/action-bar/examples/action-bar-long-string-title-truncation-example.component.html
  libs/docs/core/action-bar/examples/action-bar-mobile-example.component.html
  libs/docs/core/action-bar/examples/action-bar-no-back-example.component.html
  libs/docs/core/calendar/examples/calendar-mobile-example/calendar-mobile-example.component.html
  libs/docs/core/list/examples/list-data-example/list-data-example.component.html
  libs/docs/core/radio/examples/radio-example.component.html
  libs/docs/core/table/examples/table-toolbar-example.component.html
  libs/docs/core/textarea/examples/textarea-state-example.component.html
  libs/docs/core/toolbar/e2e/toolbar.po.ts
  libs/docs/core/toolbar/examples/toolbar-overflow-example.component.html
  libs/docs/core/toolbar/examples/toolbar-overflow-grouping-example.component.html
  libs/docs/core/toolbar/examples/toolbar-overflow-priority-example.component.html
Labels: enhancement, documentation

#8962 feat(core): apply fiori scrollbar to components
  libs/core/src/lib/combobox/combobox.component.html
  libs/core/src/lib/combobox/combobox.component.scss
  libs/core/src/lib/datetime-picker/datetime-picker.component.scss
  libs/core/src/lib/dialog/dialog-body/dialog-body.component.html
  libs/core/src/lib/dialog/dialog.component.scss
  libs/core/src/lib/dialog/dialog.module.ts
  libs/core/src/lib/dynamic-page/dynamic-page.component.html
  libs/core/src/lib/dynamic-page/dynamic-page.module.ts
  libs/core/src/lib/multi-input/multi-input.component.scss
  libs/core/src/lib/popover/popover-body/popover-body.component.html
  libs/core/src/lib/product-switch/product-switch/product-switch.component.html
  libs/core/src/lib/tabs/tab-list.component.html
  libs/core/src/lib/tabs/tabs.module.ts
  libs/core/src/lib/wizard/wizard.component.html
  libs/core/src/lib/wizard/wizard.component.scss
  libs/core/src/lib/wizard/wizard.component.spec.ts
  libs/core/src/lib/wizard/wizard.component.ts
  libs/core/src/lib/wizard/wizard.module.ts
  libs/docs/core/fixed-card-layout/examples/custom-column-width/fixed-card-layout-custom-column-width-example.component.html
  libs/docs/core/fixed-card-layout/examples/custom-width/fixed-card-layout-custom-width-example.component.html
  libs/docs/core/fixed-card-layout/examples/default/fixed-card-layout-examples.component.html
  libs/docs/core/fixed-card-layout/examples/disabled-drag-drop/fixed-card-layout-disabled-drag.component.html
  libs/docs/core/fixed-card-layout/examples/max-columns/fixed-card-layout-max-columns-example.component.html
  libs/docs/core/fixed-card-layout/fixed-card-layout-docs.module.ts
  libs/docs/core/scroll-spy/examples/scroll-spy-custom-example/scroll-spy-custom-example.component.html
  libs/docs/core/scroll-spy/examples/scroll-spy-custom-offset/scroll-spy-offset-example.component.html
  libs/docs/core/scroll-spy/examples/scroll-spy-example/scroll-spy-example.component.html
  libs/docs/core/scroll-spy/scroll-spy-docs.module.ts
  libs/docs/core/timeline/examples/timeline-template-example.component.html
  libs/docs/core/timeline/timeline-docs.module.ts
  libs/platform/src/lib/approval-flow/approval-flow.component.html
  libs/platform/src/lib/approval-flow/approval-flow.component.scss
  libs/platform/src/lib/form/combobox/combobox/combobox.component.scss
  libs/platform/src/lib/icon-tab-bar/icon-tab-bar.component.scss
  libs/platform/src/lib/search-field/search-field.component.html
  libs/platform/src/lib/value-help-dialog/components/select-tab/select-tab.component.html
  libs/platform/src/lib/value-help-dialog/value-help-dialog.module.ts
  libs/platform/src/lib/value-help-dialog/value-help-dialog/value-help-dialog.component.html
Labels: dxp

#9096 chore(docs): update versions.json
  versions.json
Labels: enhancement, documentation

#9097 fix(docs): fixed asset urls so now links work properly
  apps/docs/src/index.html
  e2e/wdio/core-base-component.po.ts
  e2e/wdio/platform-base-component.po.ts
  libs/docs/platform/approval-flow/e2e/approval-flow.e2e-spec.ts
  libs/docs/shared/src/lib/getAsset.ts
  package.json
Labels: bug, enhancement

#9099 fix(docs): add live announcer for sidebar search
  libs/docs/shared/src/lib/core-helpers/sections-toolbar/sections-toolbar.component.ts
Labels: documentation, accessibility

#9094 feat(core,platform): add unread indicator
  libs/core/src/lib/list/list-component.token.ts
  libs/core/src/lib/list/list-item/list-item.component.html
  libs/core/src/lib/list/list-item/list-item.component.ts
  libs/core/src/lib/list/list-navigation-item/list-navigation-item.component.ts
  libs/core/src/lib/list/list-unread-indicator.interface.ts
  libs/core/src/lib/list/list.component.spec.ts
  libs/core/src/lib/list/list.component.ts
  libs/core/src/lib/list/public_api.ts
  libs/docs/core/list-byline/examples/list-byline-unread-example/list-byline-unread-example.component.html
  libs/docs/core/list-byline/examples/list-byline-unread-example/list-byline-unread-example.component.ts
  libs/docs/core/list-byline/list-byline-docs.component.html
  libs/docs/core/list-byline/list-byline-docs.component.ts
  libs/docs/core/list-byline/list-byline-docs.module.ts
  libs/docs/platform/standard-list-item/examples/platform-standard-list-unread-example.component.html
  libs/docs/platform/standard-list-item/examples/platform-standard-list-unread-example.component.ts
  libs/docs/platform/standard-list-item/platform-standard-list-item-docs.component.html
  libs/docs/platform/standard-list-item/platform-standard-list-item-docs.component.ts
  libs/docs/platform/standard-list-item/platform-standard-list-item-docs.module.ts
  libs/platform/src/lib/list/base-list-item.ts
  libs/platform/src/lib/list/list.component.html
  libs/platform/src/lib/list/list.component.ts
  libs/platform/src/lib/list/standard-list-item/standard-list-item.component.html
  package.json
  yarn.lock
Labels: enhancement, platform, core, list

#9111 fix: invalidate nx cache on package.json change
  libs/docs/core/flexible-column-layout/e2e/flexible-column-layout.e2e-spec.ts
  nx.json
Labels: bug

#9112 fix(ci): npm publish always set to public and added gh publish for hotfix latest
  .github/actions/npm-publish/index.js
  .github/workflows/create-hotfix.yml
Labels: bug, High, High priority

#9009 chore(core,platform): update packages
  apps/docs/project.json
  e2e/tsconfig.json
  e2e/wdio/driver/wdio.ts
  libs/docs/shared/src/lib/core-helpers/code-snippet/code-snippet.component.ts
  package.json
  yarn.lock
Labels: dependencies

#9116 fix: wizard scroll on top after step change
  libs/core/src/lib/scrollbar/scrollbar.component.ts
  libs/core/src/lib/wizard/wizard.component.ts
  libs/docs/platform/approval-flow/e2e/approval-flow.e2e-spec.ts
Labels: quick fix

#9113 feat(core): multi input dropdown width
  libs/core/src/lib/multi-input/multi-input.component.html
  libs/core/src/lib/multi-input/multi-input.component.ts
  libs/docs/core/multi-input/examples/multi-input-dropdown-width-example/multi-input-dropdown-width-example.component.html
  libs/docs/core/multi-input/examples/multi-input-dropdown-width-example/multi-input-dropdown-width-example.component.ts
  libs/docs/core/multi-input/multi-input-docs.component.html
  libs/docs/core/multi-input/multi-input-docs.component.ts
  libs/docs/core/multi-input/multi-input-docs.module.ts
Labels: core, multi input

#9117 fix(core): removed forbidden aria-selected attribute from div
  libs/core/src/lib/tabs/tab-list.component.html
  libs/docs/core/tabs/e2e/tabs.e2e-spec.ts
  libs/docs/platform/dynamic-page/e2e/dynamic-page.e2e-spec.ts
Labels: quick fix

#9120 fix: component generator fix
  tools/generators/sap-component/index.ts
  tools/generators/utils/ast-utils.ts
  tools/generators/utils/linting.ts
Labels: bug

#9119 fix(core): fix missing popover arrow
  libs/core/src/lib/popover/popover-body/popover-body.component.html
Labels: bug, Defect Hunting

#9092 feat(core): custom icon placement on core button
  libs/core/src/lib/button/button.component.html
Labels: enhancement, core

#9140 fix(core): breadcrumb overflow icon
  libs/core/src/lib/breadcrumb/breadcrumb.component.html
Labels: enhancement, core

#9142 fix(core,fn,docs): fixed incorrect import paths from styles
  libs/core/src/lib/popover/popover-body/popover-body.component.scss
  libs/docs/core/calendar/e2e/calendar.e2e-spec.ts
  libs/docs/shared/src/lib/core-helpers/stackblitz/code-example-stack/styles.scss
  libs/fn/src/lib/avatar/avatar.component.scss
  libs/fn/src/lib/button/button.component.scss
  libs/fn/src/lib/checkbox/checkbox/checkbox.component.scss
  libs/fn/src/lib/form/form-control/form-control.component.scss
  libs/fn/src/lib/form/form-label/form-label.component.scss
  libs/fn/src/lib/generic-tag/generic-tag.component.scss
  libs/fn/src/lib/info-label/info-label.component.scss
  libs/fn/src/lib/input/input.component.scss
  libs/fn/src/lib/message-strip/message-strip.component.scss
  libs/fn/src/lib/message-toast/message-toast.component.scss
  libs/fn/src/lib/notification/notification.component.scss
  libs/fn/src/lib/object-status/object-status.component.scss
  libs/fn/src/lib/progress-bar/progress-bar.component.scss
  libs/fn/src/lib/radio/radio-button/radio-button.component.scss
  libs/fn/src/lib/search/search.component.scss
  libs/fn/src/lib/select/select.component.scss
  libs/fn/src/lib/slider/slider.component.scss
  libs/fn/src/lib/switch/switch.component.scss
  libs/fn/src/lib/tabs/tabs/tabs.component.scss
  libs/platform/src/lib/menu/menu.component.scss
Labels: quick fix

#9141 fix: removed not recommended aria attribute on `div`
  libs/core/src/lib/select/select.component.html
  libs/docs/platform/select/e2e/select.e2e-spec.ts
Labels: accessibility, quick fix, 0.38.2

#9144 fix(core): added i18n package installation in core's ng-add
  libs/core/schematics/add-dependencies/index.ts
Labels: bug, 0.38.2

#9139 fix(core): submenu visibility
  libs/core/src/lib/menu/menu.component.html
  package.json
  yarn.lock
Labels: bug, core, Defect Hunting, 0.38.2

#9145 fix(ci): fixed versions of our 3rd party dependencies
  tools/executors/prepare-library/utils/sync-versions.ts
Labels: 0.38.2

#9146 fix: fixed i18n package dependencies
  libs/i18n/project.json
Labels: bug, quick fix, 0.38.2
