Repository SAP/fundamental-ngx, pull requests merged in 2022-04, with the labels that each got.

#7935 chore(deps): fix ngx versions
  CHANGELOG.md
  package.json
Labels: dependencies

#7934 feat(core): added ignore click on selection directive
  libs/core/src/lib/dynamic-page/dynamic-page-header/header/dynamic-page-header.component.html
  libs/core/src/lib/dynamic-page/dynamic-page.module.ts
  libs/core/src/lib/utils/directives/ignore-click-on-selection/ignore-click-on-selection.directive.ts
  libs/core/src/lib/utils/directives/ignore-click-on-selection/ignore-click-on-selection.module.ts
  libs/core/src/lib/utils/directives/ignore-click-on-selection/tokens.ts
  libs/core/src/lib/utils/public_api.ts
Labels: bug, enhancement, dxp

#7936 chore(ci): fix release version
  CHANGELOG.md
  package.json
Labels: tooling, dependencies

#7937 chore(ci): fix release script for hotfixes
  .github/workflows/on-push-or-pull.yml
Labels: tooling

#7938 chore(ci): try to fix the hotfix script v2
  .github/workflows/on-push-or-pull.yml
Labels: tooling

#7939 chore(ci): test ci
  ci-scripts/hotfix-publish.sh
Labels: tooling

#7940 chore(ci): fix hotfix script
  .github/workflows/on-push-or-pull.yml
  ci-scripts/hotfix-publish.sh
Labels: tooling

#7905 fix(platform,core): form mis-alignments
  e2e/wdio/platform/fixtures/appData/input-page-contents.ts
  e2e/wdio/platform/fixtures/appData/textarea-page-content.ts
  e2e/wdio/platform/tests/form-container.e2e-spec.ts
  libs/core/src/lib/form/form-label/form-label.component.scss
  libs/core/src/lib/form/form-label/form-label.component.ts
  libs/platform/src/lib/form/form-group/form-field/form-field.component.html
  libs/platform/src/lib/form/form-group/form-field/form-field.component.ts
  libs/platform/src/lib/form/form-group/form-group.component.html
  libs/platform/src/lib/form/form-group/services/form-field-layout.service.ts
Labels: stale

#7927 docs(core): form message update
  apps/docs/src/app/core/component-docs/form-message/examples/state-message/form-messaging-state-example.component.html
  apps/docs/src/app/core/component-docs/form-message/examples/state-message/form-messaging-state-example.component.ts
  apps/docs/src/app/core/component-docs/form-message/form-message-docs.component.html
  apps/docs/src/app/core/component-docs/form-message/form-message-docs.component.ts
  apps/docs/src/app/core/component-docs/form-message/form-message-docs.module.ts
  apps/docs/src/app/core/component-docs/form-message/form-message-header/form-message-header.component.html
Labels: documentation, stale

#7884 feat(core): handle dynamic container height
  apps/docs/src/app/core/component-docs/popover/examples/popover-dynamic-container-height/popover-dynamic-container-height-example.component.html
  apps/docs/src/app/core/component-docs/popover/examples/popover-dynamic-container-height/popover-dynamic-container-height-example.component.ts
  apps/docs/src/app/core/component-docs/popover/popover-docs.component.html
  apps/docs/src/app/core/component-docs/popover/popover-docs.component.ts
  apps/docs/src/app/core/component-docs/popover/popover-docs.module.ts
  e2e/wdio/core/pages/popover.po.ts
  e2e/wdio/core/tests/popover.e2e-spec.ts
  libs/core/src/lib/popover/popover-container/popover-container.directive.ts
  libs/core/src/lib/popover/popover-service/popover.service.ts
  libs/core/src/lib/popover/popover.module.ts
  libs/core/src/lib/popover/public_api.ts
Labels: enhancement

#7961 chore(deps): update to theming-base-content v 11.1.38
  package-lock.json
  package.json
Labels: dependencies, theming

#7962 fix(core, platform): dynamic page spacer
  libs/core/src/lib/dynamic-page/dynamic-page-content/dynamic-page-content.component.html
  libs/core/src/lib/dynamic-page/dynamic-page-content/dynamic-page-content.component.ts
  libs/core/src/lib/dynamic-page/dynamic-page.component.html
  libs/core/src/lib/dynamic-page/dynamic-page.component.ts
Labels: bug, platform, core, dxp

#7954 fix(platform): rename input property
  apps/docs/src/app/platform/component-docs/platform-smart-filter-bar/platform-smart-filter-bar-docs.component.html
  apps/docs/src/app/platform/component-docs/platform-smart-filter-bar/platform-smart-filter-bar-examples/platform-smart-filter-bar-basic-example.component.html
  apps/docs/src/app/platform/component-docs/platform-smart-filter-bar/platform-smart-filter-bar-examples/platform-smart-filter-bar-custom-filter-example.component.html
  apps/docs/src/app/platform/component-docs/platform-smart-filter-bar/platform-smart-filter-bar-examples/platform-smart-filter-bar-custom-labels-example.component.html
  apps/docs/src/app/platform/component-docs/platform-smart-filter-bar/platform-smart-filter-bar-examples/platform-smart-filter-bar-dynamic-page-example.component.html
  apps/docs/src/app/platform/component-docs/platform-smart-filter-bar/platform-smart-filter-bar-examples/platform-smart-filter-bar-observable-example.component.html
  e2e/wdio/platform/tests/form-generator.e2e-spec.ts
  libs/platform/src/lib/form/form-group/form-group.component.scss
  libs/platform/src/lib/smart-filter-bar/components/smart-filter-bar-conditions-dialog/smart-filter-bar-conditions-dialog.component.html
  libs/platform/src/lib/smart-filter-bar/directives/smart-filter-bar-field-definition.directive.spec.ts
  libs/platform/src/lib/smart-filter-bar/directives/smart-filter-bar-field-definition.directive.ts
  libs/platform/src/lib/smart-filter-bar/directives/smart-filter-bar-subject.directive.spec.ts
  libs/platform/src/lib/smart-filter-bar/directives/smart-filter-bar-subject.directive.ts
  libs/platform/src/lib/smart-filter-bar/smart-filter-bar.component.scss
  libs/platform/src/lib/smart-filter-bar/smart-filter-bar.component.spec.ts
Labels: bug

#7949 fix(core): add auto slides calculation
  apps/docs/src/app/core/component-docs/carousel/carousel-docs.component.html
  apps/docs/src/app/core/component-docs/carousel/carousel-docs.module.ts
  apps/docs/src/app/core/component-docs/carousel/examples/carousel-auto-slides-example.component.html
  apps/docs/src/app/core/component-docs/carousel/examples/carousel-auto-slides-example.component.ts
  apps/docs/src/app/core/component-docs/carousel/examples/carousel-example.component.scss
  libs/core/src/lib/carousel/carousel.component.ts
Labels: enhancement, stale

#7971 fix(core): clicking on tabs in overflow menu produced errors
  libs/core/src/lib/menu/services/menu.service.ts
Labels: bug, High priority

#7973 fix(core): added missing column numbers sequence
  libs/core/src/lib/grid-list/helpers/parse-layout-pattern.ts
Labels: bug, stale

#7970 fix(core, platform): dynamic page spacer fix, update for tabs
  libs/core/src/lib/dynamic-page/dynamic-page-content/dynamic-page-content.component.html
  libs/core/src/lib/dynamic-page/dynamic-page-content/dynamic-page-content.component.ts
  libs/core/src/lib/dynamic-page/dynamic-page.component.spec.ts
  libs/core/src/lib/dynamic-page/dynamic-page.component.ts
  libs/core/src/lib/dynamic-page/tsconfig.json
Labels: bug, platform, core, stale

#7964 feat(platform): enhancement of form generator and form container
  apps/docs/src/app/platform/component-docs/platform-forms/platform-form-generator/platform-form-generator-examples/platform-form-generator-custom-component-example.component.ts
  apps/docs/src/app/platform/component-docs/platform-forms/platform-form-generator/platform-form-generator-examples/platform-form-generator-custom-error-example.component.ts
  apps/docs/src/app/platform/component-docs/platform-forms/platform-form-generator/platform-form-generator-examples/platform-form-generator-custom-field-layout-example.component.ts
  apps/docs/src/app/platform/component-docs/platform-forms/platform-form-generator/platform-form-generator-examples/platform-form-generator-example.component.ts
  apps/docs/src/app/platform/component-docs/platform-forms/platform-form-generator/platform-form-generator-examples/platform-form-generator-field-layout-example.component.ts
  apps/docs/src/app/platform/component-docs/platform-forms/platform-form-generator/platform-form-generator-examples/platform-form-generator-grouping-example.component.ts
  apps/docs/src/app/platform/component-docs/platform-forms/platform-form-generator/platform-form-generator-examples/platform-form-generator-inline-help-example.component.ts
  apps/docs/src/app/platform/component-docs/platform-forms/platform-form-generator/platform-form-generator-examples/platform-form-generator-no-colons-example.component.ts
  apps/docs/src/app/platform/component-docs/platform-forms/platform-form-generator/platform-form-generator-examples/platform-form-generator-observable-example.component.ts
  apps/docs/src/app/platform/component-docs/platform-forms/platform-form-generator/platform-form-generator-examples/platform-form-generator-programatic-submit.component.ts
  e2e/wdio/platform/fixtures/appData/input-page-contents.ts
  e2e/wdio/platform/fixtures/appData/textarea-page-content.ts
  e2e/wdio/platform/pages/form-container.po.ts
  e2e/wdio/platform/pages/form-generator.po.ts
  e2e/wdio/platform/pages/input-group.po.ts
  e2e/wdio/platform/pages/input.po.ts
  e2e/wdio/platform/tests/form-container.e2e-spec.ts
  e2e/wdio/platform/tests/form-generator.e2e-spec.ts
  e2e/wdio/platform/tests/input-group.e2e-spec.ts
  libs/core/src/lib/form/form-label/form-label.component.html
  libs/core/src/lib/form/form-label/form-label.component.scss
  libs/core/src/lib/form/form-label/form-label.module.ts
  libs/core/src/lib/link/link.component.scss
  libs/core/src/lib/link/link.component.ts
  libs/platform/src/lib/form/form-generator/config/default-form-generator-hint-options.ts
  libs/platform/src/lib/form/form-group/config/default-form-field-hint-options.ts
  libs/platform/src/lib/form/form-group/fdp-form.module.ts
  libs/platform/src/lib/form/form-group/form-field/form-field.component.html
  libs/platform/src/lib/form/form-group/form-field/form-field.component.scss
  libs/platform/src/lib/form/form-group/form-group-header/form-group-header.component.html
  libs/platform/src/lib/form/form-group/form-group.component.html
Labels: enhancement, dxp

#7956 fix(core): time picker locale change incorrect behavior
  libs/core/src/lib/time-picker/time-picker.component.ts
Labels: bug, stale

#7933 fix(core): datetime picker - mobile mode switcher
  libs/core/src/lib/datetime-picker/datetime-picker.component.html
  libs/core/src/lib/datetime-picker/datetime-picker.component.scss
  libs/core/src/lib/datetime-picker/datetime-picker.component.ts
  libs/core/src/lib/datetime-picker/datetime-picker.module.ts
Labels: core

#7979 fix(core): pagination announcement, examples
  apps/docs/src/app/core/component-docs/pagination/examples/pagination-example.component.ts
  apps/docs/src/app/documentation/core-helpers/stackblitz/code-example-stack/styles.scss
  libs/core/src/lib/pagination/pagination.component.html
  libs/core/src/lib/pagination/pagination.component.ts
Labels: bug, core, stale

#7982 fix(core): fixed time picker drag end on last array element
  libs/core/src/lib/time/time-column/time-column.component.ts
Labels: bug, stale

#7999 fix(docs): fixed missing variables file in stackblitz examples
  apps/docs/src/app/documentation/core-helpers/stackblitz/stackblitz.service.ts
Labels: bug

#8002 feat(core): maxColumns feature for fixed grid layout
  apps/docs/src/app/core/component-docs/fixed-card-layout/examples/max-columns/fixed-card-layout-max-columns-example.component.html
  apps/docs/src/app/core/component-docs/fixed-card-layout/examples/max-columns/fixed-card-layout-max-columns-example.component.ts
  apps/docs/src/app/core/component-docs/fixed-card-layout/fixed-card-layout-docs.component.html
  apps/docs/src/app/core/component-docs/fixed-card-layout/fixed-card-layout-docs.component.ts
  apps/docs/src/app/core/component-docs/fixed-card-layout/fixed-card-layout-docs.module.ts
  libs/core/src/lib/fixed-card-layout/fixed-card-layout.component.spec.ts
  libs/core/src/lib/fixed-card-layout/fixed-card-layout.component.ts
Labels: enhancement, core

#8023 chore(deps): update dependabot.yml
  .github/dependabot.yml
Labels: tooling, dependencies

#8024 chore(ci): update CODEOWNERS
  .github/CODEOWNERS
Labels: tooling

#8034 fix(core,platform): missing class on split button
  libs/core/src/lib/split-button/split-button.component.html
  libs/core/src/lib/split-button/split-button.component.scss
  libs/core/src/lib/split-button/split-button.component.ts
  libs/platform/src/lib/split-menu-button/split-menu-button.component.html
  libs/platform/src/lib/split-menu-button/split-menu-button.component.ts
Labels: bug, platform, core, theming

#8006 fix(platform): icon tab bar horizon theme - removed unnecessary more(extra) button directive
  e2e/wdio/core/pages/product-switch.po.ts
  libs/platform/src/lib/icon-tab-bar/components/icon-tab-bar-base.class.ts
  libs/platform/src/lib/icon-tab-bar/components/icon-tab-bar-filter-type/icon-tab-bar-filter-type.component.html
  libs/platform/src/lib/icon-tab-bar/components/icon-tab-bar-icon-type/icon-tab-bar-icon-type.component.html
  libs/platform/src/lib/icon-tab-bar/components/icon-tab-bar-process-type/icon-tab-bar-process-type.component.html
  libs/platform/src/lib/icon-tab-bar/components/icon-tab-bar-process-type/icon-tab-bar-process-type.component.ts
  libs/platform/src/lib/icon-tab-bar/components/icon-tab-bar-text-type/icon-tab-bar-text-type.component.html
  libs/platform/src/lib/icon-tab-bar/directives/extra-button/extra-button.directive.spec.ts
  libs/platform/src/lib/icon-tab-bar/directives/extra-button/extra-button.directive.ts
  libs/platform/src/lib/icon-tab-bar/icon-tab-bar.component.spec.ts
  libs/platform/src/lib/icon-tab-bar/icon-tab-bar.module.ts
  libs/platform/src/lib/icon-tab-bar/public_api.ts
Labels: platform
