Repository SAP/fundamental-ngx, pull requests merged in 2023-06, with the labels that each got.

#9968 chore(deps): theming-base-content version 11.4.2
  package.json
  yarn.lock
Labels: dependencies, theming

#9969 fix(core): select focus on page load bug
  libs/core/src/lib/select/select.component.ts
Labels: bug

#9961 fix(core): multi input, various fixes and doc updates
  libs/core/src/lib/multi-input/multi-input.component.ts
  libs/docs/core/multi-input/examples/multi-input-displaywith-example/multi-input-displaywith-example.component.html
  libs/docs/core/multi-input/examples/multi-input-displaywith-example/multi-input-displaywith-example.component.ts
  libs/docs/core/multi-input/multi-input-docs.component.html
Labels: bug, documentation

#9962 fix(core): escape key when using focusable grid closes dialog
  libs/core/src/lib/dialog/base/dialog-base.class.ts
  libs/core/src/lib/dialog/dialog.component.spec.ts
  libs/core/src/lib/message-box/message-box.component.spec.ts
Labels: bug

#9946 fix(core): fixed popover arrow placement
  libs/core/src/lib/popover/popover-body/popover-body.component.ts
Labels: bug, core

#9951 chore: removed alert styles and tests. replaced usage to message-strip
  libs/core/src/lib/alert/alert-service/alert.service.spec.ts
  libs/core/src/lib/alert/alert.component.html
  libs/core/src/lib/alert/alert.component.scss
  libs/core/src/lib/alert/alert.component.spec.ts
  libs/core/src/lib/alert/alert.component.ts
  libs/core/src/lib/alert/alert.module.ts
  libs/core/src/lib/alert/jest.config.ts
  libs/core/src/lib/alert/project.json
  libs/core/src/lib/alert/src/test-setup.ts
  libs/core/src/lib/alert/tsconfig.json
  libs/core/src/lib/alert/tsconfig.spec.json
  libs/core/src/lib/message-strip/message-strip.component.ts
  libs/docs/core/alert/e2e/alert.e2e-spec.ts
  libs/docs/core/alert/e2e/alert.po.ts
  libs/docs/core/alert/e2e/tsconfig.json
  libs/docs/core/alert/project.json
Labels: code refactoring, core

#9922 chore(core): partial jest migrations of formatted-text and feed-list-item
  libs/core/src/lib/feed-list-item/components/item/feed-list-item.component.spec.ts
  libs/core/src/lib/feed-list-item/jest.config.ts
  libs/core/src/lib/feed-list-item/karma.conf.js
  libs/core/src/lib/feed-list-item/project.json
  libs/core/src/lib/feed-list-item/src/test-setup.ts
  libs/core/src/lib/feed-list-item/test.ts
  libs/core/src/lib/feed-list-item/tsconfig.spec.json
  libs/core/src/lib/formatted-text/formatted-text.component.spec.ts
  libs/core/src/lib/formatted-text/jest.config.ts
  libs/core/src/lib/formatted-text/karma.conf.js
  libs/core/src/lib/formatted-text/project.json
  libs/core/src/lib/formatted-text/src/test-setup.ts
  libs/core/src/lib/formatted-text/test.ts
  libs/core/src/lib/formatted-text/tsconfig.spec.json
  package.json
Labels: testing, unit tests

#9948 fix(core): added blocking of the document scroll when dialog is open
  libs/core/src/lib/dialog/dialog-service/dialog.service.ts
Labels: core, quick fix

#9987 fix(platform): do not use fdkClicked
  libs/platform/src/lib/table/table.component.html
  libs/platform/src/lib/table/table.module.ts
Labels: bug

#9985 fix(core): template based inline help was not setting screenreader element
  libs/core/src/lib/inline-help/inline-help.directive.ts
Labels: bug, accessibility

#10007 fix(platform): do not set aria-expanded for table cells that do not expand
  libs/docs/platform/table/platform-table-docs.component.html
  libs/platform/src/lib/table/table.component.html
Labels: bug, accessibility

#10006 fix(docs): sidebar container css bug
  libs/docs/shared/src/lib/core-helpers/sections-toolbar/sections-toolbar.component.scss
  libs/docs/shared/src/lib/documentation-base.component.scss
Labels: bug, documentation

#10005 fix(docs): remove display none spans from inline help docs
  libs/docs/core/inline-help/examples/inline-help-template-example/inline-help-template-example.component.html
  libs/docs/core/inline-help/examples/inline-help-trigger-example.component.html
Labels: bug

#9972 fix(core): add label for multi input
  libs/core/src/lib/multi-input/multi-input.component.ts
  libs/i18n/src/lib/languages/albanian.ts
  libs/i18n/src/lib/languages/arabic.ts
  libs/i18n/src/lib/languages/belarusian.ts
  libs/i18n/src/lib/languages/bulgarian.ts
  libs/i18n/src/lib/languages/chinese.ts
  libs/i18n/src/lib/languages/croatian.ts
  libs/i18n/src/lib/languages/czech.ts
  libs/i18n/src/lib/languages/english.ts
  libs/i18n/src/lib/languages/french.ts
  libs/i18n/src/lib/languages/georgian.ts
  libs/i18n/src/lib/languages/german.ts
  libs/i18n/src/lib/languages/hebrew.ts
  libs/i18n/src/lib/languages/hindi.ts
  libs/i18n/src/lib/languages/italian.ts
  libs/i18n/src/lib/languages/polish.ts
  libs/i18n/src/lib/languages/portuguese.ts
  libs/i18n/src/lib/languages/romanian.ts
  libs/i18n/src/lib/languages/russian.ts
  libs/i18n/src/lib/languages/sinhala.ts
  libs/i18n/src/lib/languages/spanish.ts
  libs/i18n/src/lib/languages/turkish.ts
  libs/i18n/src/lib/languages/ukrainian.ts
  libs/i18n/src/lib/models/lang.ts
Labels: accessibility

#9986 fix(core): select should have listbox role
  libs/core/src/lib/select/select.component.html
Labels: bug, accessibility

#10033 fix(core): localize combobox addon button
  libs/core/src/lib/combobox/combobox.component.html
  libs/core/src/lib/combobox/combobox.module.ts
Labels: bug

#10054 fix(core): tokenizer bug when removing tokens
  libs/core/src/lib/token/tokenizer.component.html
  libs/core/src/lib/token/tokenizer.component.ts
Labels: bug

#9989 feat(core): message strip alert implementation
  libs/cdk/src/lib/utils/index.ts
  libs/core/src/lib/alert/alert.module.ts
  libs/core/src/lib/message-strip/alert/default-config.ts
  libs/core/src/lib/message-strip/alert/index.ts
  libs/core/src/lib/message-strip/alert/message-strip-alert-container-footer/message-strip-alert-container-footer.component.ts
  libs/core/src/lib/message-strip/alert/message-strip-alert-container/message-strip-alert-container.component.scss
  libs/core/src/lib/message-strip/alert/message-strip-alert-container/message-strip-alert-container.component.ts
  libs/core/src/lib/message-strip/alert/message-strip-alert.position.ts
  libs/core/src/lib/message-strip/alert/message-strip-alert.ref.ts
  libs/core/src/lib/message-strip/alert/message-strip-alert.service.ts
  libs/core/src/lib/message-strip/alert/message-strip-alert/message-strip-alert.component.html
  libs/core/src/lib/message-strip/alert/message-strip-alert/message-strip-alert.component.ts
  libs/core/src/lib/message-strip/alert/message-strip-configuration-type.ts
  libs/core/src/lib/message-strip/alert/open-message-strip-alert.config.ts
  libs/core/src/lib/message-strip/alert/tokens.ts
  libs/core/src/lib/message-strip/auto-dismiss-message-strip.directive.ts
  libs/core/src/lib/message-strip/index.ts
  libs/core/src/lib/message-strip/message-strip-type.ts
  libs/core/src/lib/message-strip/message-strip.component.spec.ts
  libs/core/src/lib/message-strip/message-strip.component.ts
  libs/core/src/lib/message-strip/message-strip.module.ts
  libs/core/src/lib/message-strip/ng-package.json
  libs/core/src/lib/message-strip/public_api.ts
  libs/docs/core/message-strip/examples/message-strip-alert-example.component.ts
  libs/docs/core/message-strip/message-strip-docs.component.html
  libs/docs/core/message-strip/message-strip-docs.component.ts
  libs/docs/core/message-strip/message-strip-docs.module.ts
  libs/docs/shared/src/lib/core-helpers/code-example/code-example.component.ts
Labels: enhancement, core

#10038 fix(core): new checkbox hidden element for a11y
  libs/core/src/lib/checkbox/checkbox/checkbox.component.html
  libs/core/src/lib/grid-list/components/grid-list-item/grid-list-item.component.html
  libs/docs/core/grid-list/e2e/grid-list.po.ts
  libs/docs/platform/approval-flow/e2e/approval-flow.po.ts
Labels: accessibility

#10056 fix(core): bug where token would not be removed from mobile mode
  libs/core/src/lib/multi-combobox/multi-combobox.component.html
  libs/core/src/lib/multi-combobox/multi-combobox.component.ts
  libs/core/src/lib/multi-input/multi-input.component.ts
  libs/docs/core/multi-input/examples/multi-input-mobile-example/multi-input-mobile-example.component.html
Labels: bug

#10060 docs(core,platform): add link to the playground examples
  libs/docs/core/alert/alert-docs.component.html
  libs/docs/core/button/button-docs.component.html
  libs/docs/core/dialog/dialog-docs.component.html
  libs/docs/core/input-group/input-group-docs.component.html
  libs/docs/core/pagination/pagination-docs.component.html
  libs/docs/core/slider/slider-docs.component.html
  libs/docs/core/switch/switch-docs.component.html
  libs/docs/core/tabs/tabs-docs.component.html
  libs/docs/platform/slider/slider-docs.component.html
  libs/docs/platform/table/platform-table-docs.component.html
  libs/docs/shared/src/lib/core-helpers/playground/playground.component.html
Labels: documentation

#10087 docs(core,platform): minor doc updates
  README.md
  apps/docs/src/index.html
  libs/core/src/lib/README.md
  libs/platform/src/lib/README.md
Labels: documentation

#10084 fix(platform): preserved state fixes
  libs/docs/platform/table/examples/preserved-state/platform-table-preserved-state-example.component.html
  libs/docs/platform/table/examples/preserved-state/platform-table-preserved-state-example.component.ts
  libs/platform/src/lib/table-helpers/helpers.ts
Labels: bug, platform, table

#10072 feat(platform): table children lazy load
  apps/docs/src/app/platform/documentation/platform-documentation-data.ts
  libs/cdk/src/lib/data-source/data-source.directive.spec.ts
  libs/cdk/src/lib/data-source/data-source.directive.ts
  libs/cdk/src/lib/utils/directives/index.ts
  libs/cdk/src/lib/utils/directives/intersection-spy/intersection-spy.directive.ts
  libs/cdk/src/lib/utils/utils.module.ts
  libs/docs/platform/table/child-docs/advanced/advanced-examples-docs.component.html
  libs/docs/platform/table/child-docs/advanced/advanced-examples-docs.component.ts
  libs/docs/platform/table/examples/advanced-scrolling/advanced-scrolling-example.component.html
  libs/docs/platform/table/examples/advanced-scrolling/advanced-scrolling-example.component.ts
  libs/docs/platform/table/index.ts
  libs/docs/platform/table/platform-table.module.ts
  libs/platform/src/lib/shared/domain/data-source.ts
  libs/platform/src/lib/table-helpers/directives/table-data-source.directive.ts
  libs/platform/src/lib/table-helpers/directives/table-draggable.directive.ts
  libs/platform/src/lib/table-helpers/directives/table-initial-state.directive.ts
  libs/platform/src/lib/table-helpers/domain/table-data-provider.ts
  libs/platform/src/lib/table-helpers/domain/table-data-source.ts
  libs/platform/src/lib/table-helpers/helpers.ts
  libs/platform/src/lib/table-helpers/models/index.ts
  libs/platform/src/lib/table-helpers/models/table-item.model.ts
  libs/platform/src/lib/table-helpers/models/table-row.model.ts
  libs/platform/src/lib/table-helpers/services/table-row.service.ts
  libs/platform/src/lib/table-helpers/table.ts
  libs/platform/src/lib/table/components/table-row/table-row.component.ts
  libs/platform/src/lib/table/index.ts
  libs/platform/src/lib/table/table.component.html
  libs/platform/src/lib/table/table.component.scss
  libs/platform/src/lib/table/table.component.spec.ts
  libs/platform/src/lib/table/table.component.ts
  libs/platform/src/lib/table/table.module.ts
  libs/platform/src/lib/table/tests/helpers.ts
  libs/platform/src/lib/table/tests/table.component-host.spec.ts
  libs/platform/src/lib/table/tests/table.component-initial-state.spec.ts
  libs/platform/src/lib/table/tests/table.component-internal.spec.ts
  libs/platform/src/lib/table/tests/table.component-page-scrolling.spec.ts
  libs/platform/src/lib/table/tests/table.component-tree-lazy-loading.spec.ts
  libs/platform/src/lib/table/tests/table.component-tree.spec.ts
  libs/platform/src/lib/table/tsconfig.lib.json
  libs/platform/src/lib/table/tsconfig.spec.json
Labels: platform, sourcing, table

#10092 fix(core): add the correct styling for Select placeholder
  libs/core/src/lib/select/select.component.html
  libs/core/src/lib/select/select.component.scss
Labels: bug

#10097 fix(platform): fix expand all functionality
  libs/platform/src/lib/table-helpers/models/table-row.model.ts
  libs/platform/src/lib/table/table.component.ts
Labels: bug, platform, table

#10096 fix: dayjs adapter was enforcing double digits for month and day
  libs/datetime-adapter/src/lib/dayjs-datetime-formats.ts
Labels: bug

#10102 fix(platform): table tbody focus
  libs/docs/platform/table/examples/platform-table-freezable-example.component.html
  libs/platform/src/lib/table/table.component.html
  libs/platform/src/lib/table/table.component.scss
Labels: bug, platform, table

#10061 fix(docs): placeimg is shutting down so new placeholder site
  libs/docs/core/avatar-group/examples/avatar-group-data-example.service.ts
  libs/docs/core/card/examples/card-example.component.html
  libs/docs/core/card/examples/link-list-card/card-link-list-example.component.html
  libs/docs/core/card/examples/list-card/card-list-example.component.html
  libs/docs/core/card/examples/quick-view-card/card-quick-view-example.component.ts
  libs/docs/core/carousel/examples/carousel-content-navigation-example.component.html
  libs/docs/core/carousel/examples/carousel-dynamic-items-example.component.html
  libs/docs/core/carousel/examples/carousel-hidden-navigation-example.component.html
  libs/docs/core/carousel/examples/carousel-loading-content-example.component.html
  libs/docs/core/carousel/examples/carousel-looped-navigation-example.component.html
  libs/docs/core/carousel/examples/carousel-multiple-active-item-example.component.html
  libs/docs/core/carousel/examples/carousel-no-page-indicator-example.component.html
  libs/docs/core/carousel/examples/carousel-one-active-item-example.component.html
  libs/docs/core/carousel/examples/carousel-vertical-direction-example.component.html
  libs/docs/core/overflow-layout/examples/complex/avatar-generator-example.service.ts
  libs/docs/core/quick-view/examples/quick-view-base-example.component.ts
  libs/docs/core/quick-view/examples/quick-view-dialog-example.component.ts
  libs/docs/core/quick-view/examples/quick-view-popover-example.component.ts
  libs/docs/platform/multi-input/examples/platform-multi-input-complex-example.component.ts
  libs/docs/platform/multi-input/examples/platform-multi-input-mobile-example.component.ts
  libs/docs/platform/standard-list-item/examples/platform-standard-list-item-border-less-example.component.ts
  libs/docs/platform/standard-list-item/examples/platform-standard-list-item-example.component.html
  libs/docs/platform/standard-list-item/examples/platform-standard-list-item-with-footer-example.component.html
  libs/docs/platform/standard-list-item/examples/platform-standard-list-item-with-group-header-example.component.html
  libs/docs/platform/standard-list-item/examples/platform-standard-list-item-with-inverted-secondary-type-example.component.html
  libs/docs/platform/standard-list-item/examples/platform-standard-list-item-with-navigation-example.component.html
  libs/docs/platform/standard-list-item/examples/platform-standard-list-item-with-secondary-type-example.component.html
  libs/docs/platform/standard-list-item/examples/platform-standard-list-item-with-selection-example.component.ts
  libs/docs/platform/standard-list-item/examples/platform-standard-list-item-with-single-selection-example.component.ts
  libs/docs/platform/standard-list-item/examples/platform-standard-list-unread-example.component.html
Labels: documentation

#10065 feat(platform,core): custom title and subtitle template for dynamic page
  libs/core/src/lib/dynamic-page/directives/dynamic-page-header-subtitle.directive.ts
  libs/core/src/lib/dynamic-page/directives/dynamic-page-header-title.directive.ts
  libs/core/src/lib/dynamic-page/dynamic-page-header/header/dynamic-page-header.component.html
  libs/core/src/lib/dynamic-page/dynamic-page-header/header/dynamic-page-header.component.spec.ts
  libs/core/src/lib/dynamic-page/dynamic-page-header/header/dynamic-page-header.component.ts
  libs/core/src/lib/dynamic-page/dynamic-page.module.ts
  libs/core/src/lib/dynamic-page/index.ts
  libs/core/src/lib/dynamic-page/models/title-directive-context.ts
  libs/docs/core/dynamic-page/dynamic-page-docs.component.html
  libs/docs/core/dynamic-page/examples/dynamic-page-facets-example/dynamic-page-facets-example.component.html
  libs/docs/core/dynamic-page/examples/dynamic-page-facets-example/dynamic-page-facets-example.component.ts
  libs/docs/platform/dynamic-page/examples/platform-dynamic-page-facets-example/platform-dynamic-page-facets-example.component.html
  libs/docs/platform/dynamic-page/examples/platform-dynamic-page-facets-example/platform-dynamic-page-facets-example.component.scss
  libs/platform/src/lib/dynamic-page/directives/dynamic-page-header-subtitle.directive.ts
  libs/platform/src/lib/dynamic-page/directives/dynamic-page-header-title.directive.ts
  libs/platform/src/lib/dynamic-page/dynamic-page-header/title/dynamic-page-title.component.ts
  libs/platform/src/lib/dynamic-page/dynamic-page.component.html
  libs/platform/src/lib/dynamic-page/dynamic-page.module.ts
  libs/platform/src/lib/dynamic-page/index.ts
Labels: sourcing
