Repository SAP/fundamental-ngx, pull requests merged in 2023-01, with the labels that each got.

#9158 fix(core): feed list item more el tabindex
  libs/core/src/lib/feed-list-item/components/item/feed-list-item.component.html
Labels: bug, core, Defect Hunting

#9159 fix(core): remove timeline node tab index
  libs/core/src/lib/timeline/components/timeline-node/timeline-node.component.html
Labels: bug

#9156 fix(core): dynamic footer z-index must be higher than that of fd-scrollbar
  libs/core/src/lib/dynamic-page/dynamic-page.component.scss
Labels: bug

#9183 feat(core): added illustrated message dot type
  apps/docs/src/assets/images/sapIllus-Spot-NoMail.svg
  libs/core/src/lib/illustrated-message/illustrated-message.component.html
  libs/core/src/lib/illustrated-message/illustrated-message.component.ts
  libs/docs/core/calendar/e2e/calendar.e2e-spec.ts
  libs/docs/core/illustrated-message/examples/illustrated-message-dot-example.component.html
  libs/docs/core/illustrated-message/examples/illustrated-message-dot-example.component.ts
  libs/docs/core/illustrated-message/examples/illustrated-message-inline-example.component.ts
  libs/docs/core/illustrated-message/illustrated-message-docs.component.html
  libs/docs/core/illustrated-message/illustrated-message-docs.component.ts
  libs/docs/core/illustrated-message/illustrated-message-docs.module.ts
  package.json
  yarn.lock
Labels: enhancement, 0.38.3

#9206 fix: update release badge for correct workflow
  libs/cdk/src/lib/README.md
  libs/core/src/lib/README.md
  libs/cx/src/lib/README.md
  libs/platform/src/lib/README.md
Labels: quick fix

#9198 fix(core): correct null validation
  libs/core/src/lib/datetime-picker/datetime-picker.component.spec.ts
  libs/core/src/lib/datetime-picker/datetime-picker.component.ts
Labels: bug, datepicker, core

#9182 fix(core,platform,docs): build warnings
  libs/core/src/lib/combobox/combobox-mobile/combobox-mobile.component.html
  libs/core/src/lib/combobox/combobox.component.html
  libs/core/src/lib/combobox/combobox.component.ts
  libs/core/src/lib/dialog/dialog-default/dialog-default.component.html
  libs/core/src/lib/dialog/dialog-default/dialog-default.component.ts
  libs/core/src/lib/dialog/dialog.component.html
  libs/core/src/lib/multi-input/multi-input-mobile/multi-input-mobile.component.html
  libs/core/src/lib/nested-list/prepared-nested-list/prepared-nested-list.component.ts
  libs/core/src/lib/overflow-layout/overflow-layout.component.ts
  libs/core/src/lib/panel/panel.component.ts
  libs/core/src/lib/select/select.component.html
  libs/core/src/lib/side-navigation/side-navigation.component.ts
  libs/core/src/lib/time/time-column/time-column.component.ts
  libs/core/src/lib/wizard/wizard-step-indicator/wizard-step-indicator.component.html
  libs/core/src/lib/wizard/wizard-step-indicator/wizard-step-indicator.component.ts
  libs/cx/src/lib/nested-list/prepared-nested-list/prepared-nested-list.component.ts
  libs/cx/src/lib/side-navigation/side-navigation.component.ts
  libs/docs/core/date-picker/examples/date-picker-allow-null-example.component.ts
  libs/docs/core/date-picker/examples/date-picker-disable-focus-scroll-example.component.ts
  libs/docs/core/date-picker/examples/date-picker-disabled-example.component.ts
  libs/docs/core/date-picker/examples/date-picker-format-example.component.ts
  libs/docs/core/date-picker/examples/date-picker-position-example.component.ts
  libs/docs/core/date-picker/examples/date-picker-range-example.component.ts
  libs/docs/core/date-picker/examples/date-picker-single-example.component.ts
  libs/docs/core/date-picker/examples/date-picker-today-button-example.component.ts
  libs/docs/core/date-picker/examples/date-picker-update-on-blur-example.component.ts
  libs/docs/core/segmented-button/examples/segmented-button-form-example/segmented-button-form-example.component.html
  libs/docs/core/time-picker/examples/time-picker-allow-null-example.component.html
  libs/docs/core/time-picker/examples/time-picker-form-example.component.html
  libs/docs/platform/checkbox-group/examples/platform-checkbox-group-content-checkbox.component.html
  libs/docs/platform/checkbox-group/examples/platform-checkbox-group-example.component.html
  libs/docs/platform/checkbox-group/examples/platform-checkbox-group-list-object.component.html
  libs/docs/platform/checkbox-group/examples/platform-checkbox-group-list.component.html
  libs/docs/platform/date-picker/examples/platform-date-picker-example.component.html
  libs/docs/platform/date-picker/examples/platform-date-picker-format-example.component.html
  libs/docs/platform/date-picker/examples/platform-date-picker-update-on-blur-example.component.ts
  libs/docs/platform/datetime-picker/examples/platform-datetime-picker-reactive-example.component.html
  libs/docs/platform/radio-group/examples/platform-radio-group-content-example.component.html
  libs/docs/platform/radio-group/examples/platform-radio-group-list-example.component.html
  libs/docs/platform/radio-group/examples/platform-radio-group-list-items-example.component.html
  libs/docs/platform/standard-list-item/examples/platform-standard-list-item-with-single-selection-example.component.html
  libs/docs/platform/standard-list-item/examples/platform-standard-list-item-with-single-selection-example.component.ts
  libs/docs/platform/time-picker/examples/platform-time-picker-reactive-example.component.html
  libs/docs/platform/vhd/examples/platform-vhd-mobile-example.component.ts
  libs/platform/src/lib/approval-flow/approval-flow-add-node/approval-flow-add-node.component.ts
  libs/platform/src/lib/approval-flow/approval-flow-node/approval-flow-node.component.html
  libs/platform/src/lib/form/form-generator/form-generator-field/form-generator-field.component.html
  libs/platform/src/lib/list/list.component.ts
  libs/platform/src/lib/panel/panel.component.ts
  libs/platform/src/lib/table/table.component.html
  libs/platform/src/lib/upload-collection/upload-collection/upload-collection.component.html
  libs/platform/src/lib/value-help-dialog/components/define-tab/define-tab.component.html
Labels: bug, documentation, platform, core

#9207 feat(platform): change and apply smart filter bar events
  libs/docs/platform/smart-filter-bar/examples/platform-smart-filter-bar-basic-example.component.html
  libs/docs/platform/smart-filter-bar/examples/platform-smart-filter-bar-basic-example.component.ts
  libs/platform/src/lib/smart-filter-bar/smart-filter-bar.class.ts
  libs/platform/src/lib/smart-filter-bar/smart-filter-bar.component.ts
Labels: enhancement

#9208 feat(ci): cdk scope for commits
  commitlint.config.js
Labels: enhancement

#9210 fix(core): pagination mobile displaying total items count instead of total pages
  libs/core/src/lib/pagination/pagination.component.html
  libs/core/src/lib/pagination/pagination.component.ts
Labels: bug

#9211 fix(core,cx): nested list icon should extend fd-icon
  libs/core/src/lib/nested-list/nested-list-directives.spec.ts
  libs/core/src/lib/nested-list/nested-list-directives.ts
  libs/core/src/lib/nested-list/nested-list.module.ts
  libs/cx/src/lib/nested-list/nested-list-directives.spec.ts
  libs/cx/src/lib/nested-list/nested-list-directives.ts
  libs/cx/src/lib/nested-list/nested-list.module.ts
  libs/docs/core/shared/src/lib/api-files.ts
Labels: enhancement

#9243 fix(platform): allow for shift+arrow key column resize when header is focused
  libs/platform/src/lib/table/directives/table-cell-resizable.directive.ts
  libs/platform/src/lib/table/table-column-resize.service.ts
  libs/platform/src/lib/table/table.component.html
  libs/platform/src/lib/table/table.component.ts
Labels: bug, accessibility

#9275 docs(core,platform): add support info in README.md
  README.md
Labels: documentation

#9237 fix(platform): add fix for Search Field suggestions menu overflow
  libs/docs/platform/search-field/e2e/search-field.e2e-spec.ts
  libs/docs/platform/search-field/examples/platform-search-field-basic-example.component.ts
  libs/platform/src/lib/search-field/search-field.component.html
  libs/platform/src/lib/search-field/search-field.component.scss
  wdio_docs.conf.js
Labels: bug, dxp

#9284 fix(ci): fixed agents timeout when running e2e tests on local
  .github/workflows/on-pull-request.yml
Labels: quick fix

#9195 fix(core): date-picker respects closeOnDateChoose input now
  libs/core/src/lib/calendar/calendar-views/calendar-day-view/calendar-day-view.component.ts
  libs/core/src/lib/calendar/calendar.component.spec.ts
  libs/core/src/lib/calendar/calendar.component.ts
  libs/core/src/lib/date-picker/date-picker.component.ts
Labels: core, 0.39

#9270 fix(platform): unable to enter numeric values using numeric keypad in combobox
  libs/cdk/src/lib/utils/functions/key-util.ts
  libs/platform/src/lib/form/combobox/commons/base-combobox.ts
Labels: accessibility, platform

#9282 fix(platform): fix form generator inline help open/close issue
  libs/core/src/lib/form/form-label/form-label.component.ts
  libs/core/src/lib/inline-help/inline-help.directive.ts
  libs/platform/src/lib/form/form-generator/config/default-form-generator-hint-options.ts
  libs/platform/src/lib/form/form-group/config/default-form-field-hint-options.ts
  libs/platform/src/lib/shared/form/hint-options.ts
Labels: bug

#9302 fix(platform): more clear typedoc for checkbox component
  libs/platform/src/lib/form/checkbox/checkbox.component.ts
Labels: documentation

#9274 fix(core,cx): error when no linkItem provided
  libs/core/src/lib/nested-list/nested-list/nested-list.directive.ts
  libs/cx/src/lib/nested-list/nested-list/nested-list.component.ts
Labels: bug

#9265 chore(deps,deps-dev): updated dependencies
  libs/cx/src/lib/nested-list/nested-list/nested-list.component.ts
  libs/plugins/wdio/executors/utils/get-projects.ts
  libs/plugins/wdio/executors/utils/spec-files.ts
  migrations.json
  package.json
  tools/executors/compile-typedoc/index.ts
  tools/executors/prepare-library/index.ts
  yarn.lock
Labels: dependencies

#9290 fix(platform): add public function for checking of rows
  libs/platform/src/lib/table/table.component.ts
Labels: bug, enhancement

#9310 fix(core): schematics type incompatibility
  libs/core/schematics/add-theming/index.ts
Labels: quick fix
