Repository SAP/fundamental-ngx, pull requests merged in 2023-12, with the labels that each got.

#11018 fix(platform): list accessibility issues
  libs/core/src/lib/list/list-item/list-item.component.ts
  libs/docs/platform/list/examples/platform-list-with-group-header-example.component.html
  libs/docs/platform/list/examples/platform-list-with-infinite-scroll-example.component.ts
  libs/docs/platform/list/examples/platform-list-with-more-button-example.component.ts
  libs/docs/platform/list/examples/platform-list-with-selection-example.component.html
  libs/docs/platform/list/examples/platform-list-with-single-selection-example.component.html
  libs/platform/src/lib/list/action-list-item/action-list-item.component.html
  libs/platform/src/lib/list/action-list-item/action-list-item.component.spec.ts
  libs/platform/src/lib/list/action-list-item/action-list-item.component.ts
  libs/platform/src/lib/list/base-list-item.ts
  libs/platform/src/lib/list/display-list-item/display-list-item.component.html
  libs/platform/src/lib/list/display-list-item/display-list-item.component.spec.ts
  libs/platform/src/lib/list/display-list-item/display-list-item.component.ts
  libs/platform/src/lib/list/free-content-list-item/free-content-list-item.component.html
  libs/platform/src/lib/list/free-content-list-item/free-content-list-item.component.ts
  libs/platform/src/lib/list/list-group-footer.component.ts
  libs/platform/src/lib/list/list-group-header.component.ts
  libs/platform/src/lib/list/list.component.html
  libs/platform/src/lib/list/list.component.ts
  libs/platform/src/lib/list/object-list-item/object-list-item.component.html
  libs/platform/src/lib/list/object-list-item/object-list-item.component.spec.ts
  libs/platform/src/lib/list/object-list-item/object-list-item.component.ts
  libs/platform/src/lib/list/standard-list-item/standard-list-item.component.html
  libs/platform/src/lib/list/standard-list-item/standard-list-item.component.ts
  libs/platform/src/lib/shared/domain/data-source.ts
Labels: accessibility, platform, list, ng15

#11033 docs: update versions.json
  versions.json
Labels: documentation

#11034 docs: add version selector
  libs/docs/shared/src/lib/core-helpers/toolbar/toolbar.component.html
Labels: documentation

#11026 feat(core): ng-add is compatible with the standalone applications
  apps/docs/src/app.component.ts
  apps/docs/src/app.config.ts
  libs/core/schematics/add-animations/index.ts
  libs/core/schematics/add-styles/index.ts
  libs/core/schematics/add-styles/schema.json
  libs/core/schematics/add-theming/index.ts
  libs/core/schematics/add-theming/schema.json
  libs/core/schematics/ng-add/index.ts
  libs/core/schematics/utils/angular-json-utils.ts
  libs/core/schematics/utils/calls-providers-function.ts
  libs/core/schematics/utils/main-ts-file-path.ts
  libs/core/schematics/utils/package-utils.ts
  libs/core/schematics/utils/workspace.ts
  libs/core/src/lib/styles/fundamental-ngx-core.css
  libs/core/src/lib/theming/index.ts
  libs/core/src/lib/theming/theming-initializer.ts
Labels: tooling, core

#11047 fix(platform): do not select parent row if tristate is disabled
  libs/platform/src/lib/table-helpers/helpers.ts
  libs/platform/src/lib/table/table.component.ts
Labels: platform, table, ng15

#11053 fix(core): allow dev to pass disableScrollbar to menu
  libs/core/src/lib/menu/menu.component.spec.ts
  libs/core/src/lib/menu/menu.component.ts
Labels: bug

#11051 fix(cdk): ensure stable zone before applying autocomplete
  libs/cdk/utils/directives/auto-complete/auto-complete.directive.spec.ts
  libs/cdk/utils/directives/auto-complete/auto-complete.directive.ts
Labels: bug

#11058 fix(platform): reset table rows before new rows emitted
  libs/platform/table-helpers/directives/table-data-source.directive.ts
  libs/platform/table-helpers/table.ts
  libs/platform/table/table.component.ts
Labels: bug, platform, table

#11060 fix(platform): reset pagination when ds changed
  libs/platform/table/table.component.ts
Labels: bug, platform, table

#11078 fix(platform): correct list markup
  libs/docs/platform/action-list-item/e2e/action-list-item.po.ts
  libs/docs/platform/approval-flow/e2e/approval-flow.po.ts
  libs/docs/platform/display-list-item/e2e/display-list-item.po.ts
  libs/docs/platform/list/e2e/list.po.ts
  libs/docs/platform/object-list-item/e2e/object-list-item.po.ts
  libs/platform/list/action-list-item/action-list-item.component.html
  libs/platform/list/action-list-item/action-list-item.component.spec.ts
  libs/platform/list/base-list-item.ts
  libs/platform/list/display-list-item/display-list-item.component.html
  libs/platform/list/display-list-item/display-list-item.component.spec.ts
  libs/platform/list/free-content-list-item/free-content-list-item.component.html
  libs/platform/list/free-content-list-item/free-content-list-item.component.spec.ts
  libs/platform/list/list-group-footer.component.ts
  libs/platform/list/list-group-header.component.ts
  libs/platform/list/list.component.html
  libs/platform/list/list.component.spec.ts
  libs/platform/list/list.component.ts
  libs/platform/list/object-list-item/object-list-item.component.html
  libs/platform/list/object-list-item/object-list-item.component.spec.ts
  libs/platform/list/standard-list-item/standard-list-item.component.html
  libs/platform/list/standard-list-item/standard-list-item.component.spec.ts
Labels: platform, list

#11064 fix(core,platform): button should not set aria-pressed by default
  libs/core/src/lib/button/base-button.ts
  libs/core/src/lib/segmented-button/segmented-button.component.ts
  libs/platform/src/lib/button/button.component.html
  libs/platform/src/lib/button/button.component.spec.ts
  wdio_docs-core-multi-input.conf.js
  wdio_docs-core-notification.conf.js
  wdio_docs-core-time-picker.conf.js
Labels: bug, accessibility, ng15

#11065 fix(core,platform): button should not set aria-pressed by default
  libs/core/button/base-button.ts
  libs/core/segmented-button/segmented-button.component.ts
  libs/platform/button/button.component.html
  libs/platform/button/button.component.spec.ts
Labels: ariba

#11063 fix(core): allow for programmatic change of pane size
  libs/core/splitter/splitter-pane-container/splitter-pane-container.component.ts
  libs/core/splitter/splitter-split-pane/splitter-split-pane.component.ts
  libs/docs/core/splitter/examples/api/splitter-api-example.component.html
  libs/docs/core/splitter/examples/api/splitter-api-example.component.ts
Labels: bug

#11087 fix(core): segmented button improvements
  libs/core/src/lib/button/button.component.ts
  libs/core/src/lib/segmented-button/segmented-button.component.ts
Labels: ng15

#11088 chore: remove greeting action
  .github/workflows/greetings.yml
Labels: ng15

#11093 feat(i18n): translation delivery
  libs/i18n/src/lib/languages/albanian.ts
  libs/i18n/src/lib/languages/arabic.ts
  libs/i18n/src/lib/languages/bulgarian.ts
  libs/i18n/src/lib/languages/chinese.ts
  libs/i18n/src/lib/languages/chinese_traditional.ts
  libs/i18n/src/lib/languages/croatian.ts
  libs/i18n/src/lib/languages/czech.ts
  libs/i18n/src/lib/languages/danish.ts
  libs/i18n/src/lib/languages/dutch.ts
  libs/i18n/src/lib/languages/english.ts
  libs/i18n/src/lib/languages/finnish.ts
  libs/i18n/src/lib/languages/french.ts
  libs/i18n/src/lib/languages/georgian.ts
  libs/i18n/src/lib/languages/german.ts
  libs/i18n/src/lib/languages/greek.ts
  libs/i18n/src/lib/languages/hebrew.ts
  libs/i18n/src/lib/languages/hindi.ts
  libs/i18n/src/lib/languages/hungarian.ts
  libs/i18n/src/lib/languages/index.ts
  libs/i18n/src/lib/languages/italian.ts
  libs/i18n/src/lib/languages/japanese.ts
  libs/i18n/src/lib/languages/kazakh.ts
  libs/i18n/src/lib/languages/korean.ts
  libs/i18n/src/lib/languages/malay.ts
  libs/i18n/src/lib/languages/norwegian.ts
  libs/i18n/src/lib/languages/polish.ts
  libs/i18n/src/lib/languages/portuguese.ts
  libs/i18n/src/lib/languages/romanian.ts
  libs/i18n/src/lib/languages/russian.ts
  libs/i18n/src/lib/languages/serbian.ts
  libs/i18n/src/lib/languages/slovak.ts
  libs/i18n/src/lib/languages/slovenian.ts
  libs/i18n/src/lib/languages/spanish.ts
  libs/i18n/src/lib/languages/swedish.ts
  libs/i18n/src/lib/languages/thai.ts
  libs/i18n/src/lib/languages/turkish.ts
  libs/i18n/src/lib/languages/ukrainian.ts
  libs/nx-plugin/generators.json
  libs/nx-plugin/src/generators/downport-translations/generator.ts
  libs/nx-plugin/src/generators/downport-translations/schema.d.ts
  libs/nx-plugin/src/generators/downport-translations/schema.json
  libs/nx-plugin/src/generators/downport-translations/utils/flatten-object.ts
  libs/nx-plugin/src/generators/downport-translations/utils/get-original-translations.ts
  libs/nx-plugin/src/generators/downport-translations/utils/load-json.ts
  libs/nx-plugin/src/generators/downport-translations/utils/load-properties.ts
  package.json
  yarn.lock
Labels: enhancement, tooling, sourcing, i18n, ng15

#11081 fix(platform): fdp-combobox selection issues
  libs/platform/form/combobox/combobox/combobox.component.ts
Labels: bug

#11082 fix(platform): fdp-combobox selection issues
  libs/platform/src/lib/form/combobox/combobox/combobox.component.ts
Labels: bug

#11097 docs: add more languages to the doc's language selector
  libs/docs/shared/src/lib/core-helpers/toolbar/toolbar.component.ts
Labels: documentation, ng15

#11127 feat(platform): allow disabling select all in vhd
  libs/platform/value-help-dialog/components/select-tab/select-tab.component.html
  libs/platform/value-help-dialog/components/select-tab/select-tab.component.ts
  libs/platform/value-help-dialog/value-help-dialog/value-help-dialog.component.html
  libs/platform/value-help-dialog/value-help-dialog/value-help-dialog.component.ts
Labels: enhancement, platform

#11128 feat(platform): allow disabling select all in vhd
  libs/core/src/lib/multi-combobox/multi-announcer/multi-announcer.directive.ts
  libs/platform/src/lib/value-help-dialog/components/select-tab/select-tab.component.html
  libs/platform/src/lib/value-help-dialog/components/select-tab/select-tab.component.ts
  libs/platform/src/lib/value-help-dialog/value-help-dialog/value-help-dialog.component.html
  libs/platform/src/lib/value-help-dialog/value-help-dialog/value-help-dialog.component.ts
Labels: enhancement, platform, ng15

#11141 fix(core): first forced item case
  libs/core/overflow-layout/overflow-layout.service.ts
Labels: bug, core

#11111 fix(core): scroll spy emit issue
  libs/core/src/lib/tabs/tab-list.component.ts
Labels: bug
