Repository SAP/fundamental-ngx, pull requests merged in 2023-08, with the labels that each got.

#10294 fix: removed `deprecated-decorator`
  libs/cdk/src/lib/package.json
  libs/cdk/src/lib/utils/services/themes.service.ts
  libs/core/schematics/add-dependencies/index.ts
  libs/core/src/lib/action-bar/action-bar.component.ts
  libs/core/src/lib/alert/alert-service/alert.service.ts
  libs/core/src/lib/alert/alert-utils/alert-config.ts
  libs/core/src/lib/alert/alert-utils/alert-container.component.ts
  libs/core/src/lib/alert/alert-utils/alert-ref.ts
  libs/core/src/lib/alert/alert.component.ts
  libs/core/src/lib/alert/alert.module.ts
  libs/core/src/lib/package.json
  libs/core/src/lib/side-navigation/side-navigation.component.ts
  libs/core/src/lib/splitter/splitter-pagination/splitter-pagination.component.ts
  libs/fn/src/lib/form/form-label/form-label.component.ts
  libs/moment-adapter/package.json
  libs/moment-adapter/src/lib/moment-datetime-adapter.ts
  libs/moment-adapter/src/lib/moment-datetime.module.ts
  libs/platform/src/lib/action-bar/action-bar.component.ts
  libs/platform/src/lib/approval-flow/approval-flow.component.ts
  libs/platform/src/lib/form/select/commons/base-select.ts
  libs/platform/src/lib/package.json
  libs/platform/src/lib/page-footer/page-footer.component.ts
  libs/platform/src/lib/thumbnail/thumbnail-details/thumbnail-details.component.ts
  libs/platform/src/lib/thumbnail/thumbnail-image/thumbnail-image.component.ts
  libs/platform/src/lib/thumbnail/thumbnail.component.ts
  libs/platform/src/lib/upload-collection/upload-collection/upload-collection.component.ts
  package.json
  yarn.lock
Labels: quick fix

#10282 feat(cdk): focusable item interface
  libs/cdk/src/lib/utils/directives/focusable-grid/focusable-grid.directive.ts
  libs/cdk/src/lib/utils/directives/focusable-item/focusable-item.directive.ts
  libs/cdk/src/lib/utils/directives/focusable-item/focusable-list.position.ts
  libs/cdk/src/lib/utils/directives/focusable-item/focusable.item.ts
  libs/cdk/src/lib/utils/directives/focusable-item/get-item-element.ts
  libs/cdk/src/lib/utils/directives/focusable-item/index.ts
  libs/cdk/src/lib/utils/directives/focusable-item/is-item-focusable.ts
  libs/cdk/src/lib/utils/directives/focusable-list/focusable-list.directive.ts
  libs/core/src/lib/table/directives/table-cell.directive.ts
Labels: enhancement, nice to have

#10318 chore(docs): added example of the auto dismiss to the message strip docs
  libs/docs/core/message-strip/examples/message-strip-auto-dismiss-example.component.ts
  libs/docs/core/message-strip/message-strip-docs.component.html
  libs/docs/core/message-strip/message-strip-docs.component.ts
  libs/docs/core/message-strip/message-strip-docs.module.ts
  libs/docs/core/shared/src/lib/api-files.ts
Labels: documentation

#10314 feat(core): toolbar horizon update
  libs/cdk/src/lib/utils/components/dynamic-portal/dynamic-portal.component.ts
  libs/core/src/lib/toolbar/deprecated-toolbar-size.directive.ts
  libs/core/src/lib/toolbar/toolbar-form-label.directive.ts
  libs/core/src/lib/toolbar/toolbar-item.directive.ts
  libs/core/src/lib/toolbar/toolbar-label.directive.ts
  libs/core/src/lib/toolbar/toolbar-overflow-button-menu.directive.ts
  libs/core/src/lib/toolbar/toolbar-overflow-button.directive.ts
  libs/core/src/lib/toolbar/toolbar-separator.component.ts
  libs/core/src/lib/toolbar/toolbar-spacer.directive.ts
  libs/core/src/lib/toolbar/toolbar.component.html
  libs/core/src/lib/toolbar/toolbar.component.spec.ts
  libs/core/src/lib/toolbar/toolbar.component.ts
  libs/core/src/lib/toolbar/toolbar.module.ts
  libs/docs/core/toolbar/examples/toolbar-overflow-grouping-example.component.html
  libs/docs/core/toolbar/examples/toolbar-overflow-priority-example.component.html
  libs/docs/core/toolbar/examples/toolbar-separator-example.component.html
  libs/docs/core/toolbar/examples/toolbar-size-example.component.html
  package.json
  yarn.lock
Labels: core, Horizon 2023

#10317 feat(platform): message popover horizon update
  libs/docs/platform/message-popover/examples/default/message-popover-default-example.component.html
  libs/docs/platform/message-popover/examples/default/message-popover-default-example.component.ts
  libs/docs/platform/message-popover/examples/form-generator/form-generator-component-example.component.ts
  libs/platform/src/lib/message-popover/components/message-popover-form-wrapper/message-popover-form-wrapper.component.ts
  libs/platform/src/lib/message-popover/components/message-view/message-view.component.ts
  libs/platform/src/lib/message-popover/directives/message-popover-form-item.directive.ts
  libs/platform/src/lib/message-popover/message-popover.component.spec.ts
  libs/platform/src/lib/message-popover/message-popover.component.ts
  libs/platform/src/lib/message-popover/models/message-popover.interface.ts
  libs/platform/src/lib/message-popover/platform-message-popover.module.ts
  libs/platform/src/lib/message-popover/utils.ts
Labels: Horizon 2023

#10268 fix(core): no initial aria-pressed value for buttons
  libs/core/src/lib/button/base-button.ts
Labels: accessibility

#10265 fix(platform): announce row index
  libs/platform/src/lib/table/components/table-header-row/table-header-row.component.html
  libs/platform/src/lib/table/components/table-row/table-row.component.html
Labels: accessibility

#10264 fix(core): dialog bar cozy issue
  libs/core/src/lib/bar/bar.component.ts
Labels: bug

#10322 docs(core): updated new component readme
  libs/docs/shared/NEW_COMPONENT.md
Labels: documentation

#10273 docs(core): added feed input example
  libs/docs/core/feed-input/examples/feed-input-circle-avatar-example/feed-input-circle-avatar-example.component.html
  libs/docs/core/feed-input/examples/feed-input-circle-avatar-example/feed-input-circle-avatar-example.component.ts
  libs/docs/core/feed-input/feed-input-docs.component.html
  libs/docs/core/feed-input/feed-input-docs.component.ts
  libs/docs/core/feed-input/feed-input-docs.module.ts
Labels: documentation

#10354 fix(docs): fixed docs current version value
  apps/docs/src/app/app.module.ts
  libs/docs/shared/src/index.ts
  libs/docs/shared/src/lib/core-helpers/toolbar/toolbar.component.html
  libs/docs/shared/src/lib/core-helpers/toolbar/toolbar.component.ts
  libs/docs/shared/src/lib/services/docs.service.ts
  libs/docs/shared/src/lib/shared-documentation.module.ts
  libs/docs/shared/src/lib/tokens/lerna-json.token.ts
  libs/docs/shared/src/lib/utilities/libraries.ts
Labels: documentation, quick fix

#10368 feat(platform): form generator dynamic controls
  libs/docs/platform/form-generator/examples/advanced/platform-form-generator-advanced-example.component.html
  libs/docs/platform/form-generator/examples/advanced/platform-form-generator-advanced-example.component.ts
  libs/docs/platform/form-generator/platform-form-generator-docs.component.html
  libs/docs/platform/form-generator/platform-form-generator-docs.module.ts
  libs/platform/src/lib/form/form-generator/controls/dynamic-form-generator-checkbox/dynamic-form-generator-checkbox.component.ts
  libs/platform/src/lib/form/form-generator/controls/dynamic-form-generator-datepicker/dynamic-form-generator-datepicker.component.ts
  libs/platform/src/lib/form/form-generator/controls/dynamic-form-generator-editor/dynamic-form-generator-editor.component.ts
  libs/platform/src/lib/form/form-generator/controls/dynamic-form-generator-input/dynamic-form-generator-input.component.ts
  libs/platform/src/lib/form/form-generator/controls/dynamic-form-generator-multi-input/dynamic-form-generator-multi-input.component.ts
  libs/platform/src/lib/form/form-generator/controls/dynamic-form-generator-object-status/dynamic-form-generator-object-status.component.ts
  libs/platform/src/lib/form/form-generator/controls/dynamic-form-generator-radio/dynamic-form-generator-radio.component.ts
  libs/platform/src/lib/form/form-generator/controls/dynamic-form-generator-select/dynamic-form-generator-select.component.ts
  libs/platform/src/lib/form/form-generator/controls/dynamic-form-generator-switch/dynamic-form-generator-switch.component.ts
  libs/platform/src/lib/form/form-generator/dynamic-form-control-field.directive.spec.ts
  libs/platform/src/lib/form/form-generator/dynamic-form-control-field.directive.ts
  libs/platform/src/lib/form/form-generator/dynamic-form-control.directive.ts
  libs/platform/src/lib/form/form-generator/dynamic-form-control.ts
  libs/platform/src/lib/form/form-generator/fdp-form-generator.module.ts
  libs/platform/src/lib/form/form-generator/form-generator-field/form-generator-field.component.html
  libs/platform/src/lib/form/form-generator/form-generator-field/form-generator-field.component.ts
  libs/platform/src/lib/form/form-generator/form-generator.service.spec.ts
  libs/platform/src/lib/form/form-generator/form-generator.service.ts
  libs/platform/src/lib/form/form-generator/form-generator/form-generator.component.html
  libs/platform/src/lib/form/form-generator/form-generator/form-generator.component.spec.ts
  libs/platform/src/lib/form/form-generator/form-generator/form-generator.component.ts
  libs/platform/src/lib/form/form-generator/helpers.ts
  libs/platform/src/lib/form/form-generator/interfaces/dynamic-form-item.ts
  libs/platform/src/lib/form/form-generator/pipes/get-hint-options.pipe.ts
  libs/platform/src/lib/form/form-generator/pipes/get-ordered-form-controls.pipe.ts
  libs/platform/src/lib/form/form-generator/providers/providers.ts
  libs/platform/src/lib/form/form-group/form-group-header/form-group-header.component.ts
  libs/platform/src/lib/form/form-group/form-group.component.ts
  libs/platform/src/lib/form/form-group/pipes/field-group-row-value.pipe.ts
  libs/platform/src/lib/form/form-helpers.ts
  libs/platform/src/lib/form/index.ts
  libs/platform/src/lib/form/input-message-group-with-template/input-message-group-with-template.component.html
  libs/platform/src/lib/form/input-message-group-with-template/input-message-group-with-template.component.ts
  libs/platform/src/lib/form/models/field.model.ts
  libs/platform/src/lib/shared/form/base.input.ts
Labels: enhancement, platform

#10370 fix(docs): update contributing docs
  CONTRIBUTING.md
Labels: documentation

#10376 fix(core,platform): fix csp style-src
  libs/core/src/lib/avatar/avatar.component.html
  libs/core/src/lib/carousel/carousel.component.html
  libs/core/src/lib/date-picker/date-picker.component.html
  libs/core/src/lib/illustrated-message/illustrated-message.component.html
  libs/core/src/lib/scrollbar/scrollbar.directive.ts
  libs/core/src/lib/time-picker/time-picker.component.html
  libs/core/src/lib/upload-collection/upload-collection-form-item/upload-collection-form-item.component.html
  libs/core/src/lib/wizard/wizard-step-indicator/wizard-step-indicator.component.html
  libs/platform/src/lib/approval-flow/approval-flow.component.html
  libs/platform/src/lib/form/form-generator/form-generator/form-generator.component.html
  libs/platform/src/lib/form/form-group/form-field/form-field.component.html
  libs/platform/src/lib/list/list.component.html
  libs/platform/src/lib/settings-generator/layouts/settings-generator-sidebar-layout/settings-generator-sidebar-layout.component.html
  libs/platform/src/lib/settings-generator/settings-generator-content/settings-generator-content.component.html
  libs/platform/src/lib/smart-filter-bar/components/smart-filter-bar-conditions-dialog/smart-filter-bar-conditions-dialog.component.html
  libs/platform/src/lib/smart-filter-bar/components/smart-filter-bar-settings-dialog/smart-filter-bar-settings-dialog.component.html
  libs/platform/src/lib/split-menu-button/split-menu-button.component.html
  libs/platform/src/lib/table/components/table-cell-header-popover/table-cell-header-popover.component.html
  libs/platform/src/lib/table/components/table-row/table-row.component.html
  libs/platform/src/lib/table/components/table-toolbar/table-toolbar.component.html
  libs/platform/src/lib/table/table.component.html
  libs/platform/src/lib/upload-collection/upload-collection/upload-collection.component.html
  libs/platform/src/lib/value-help-dialog/components/select-tab/select-tab.component.html
  libs/platform/src/lib/wizard-generator/components/wizard-summary-step/wizard-summary-section/wizard-summary-section.component.html
Labels: security

#10319 fix(docs): cdk doc problems
  libs/docs/cdk/clicked/clicked-docs.module.ts
  libs/docs/cdk/initial-focus/initial-focus-docs.module.ts
  libs/docs/cdk/shared/src/lib/api-files.ts
Labels: documentation

#10380 fix(core): correct aria-label for rating-indicator
  libs/core/src/lib/rating-indicator/components/rating-indicator.component.html
  libs/docs/core/rating-indicator/e2e/rating-indicator.po.ts
Labels: accessibility

#10396 fix(core): datepicker outer focustrap
  libs/core/src/lib/date-picker/date-picker.component.ts
  libs/core/src/lib/datetime-picker/datetime-picker.component.ts
Labels: bug, core

#10439 fix(platform): custom row height
  libs/platform/src/lib/table/table.component.ts
Labels: bug, platform, ng15

#10440 fix(platform): cell height instead of tbody
  libs/platform/src/lib/table/table.component.html
Labels: bug, table, ng15

#10444 feat(core): removed addon button on mobile mode in multi-input
  libs/core/src/lib/multi-input/multi-input-mobile/multi-input-mobile.component.html
  libs/core/src/lib/multi-input/multi-input.component.html
  libs/core/src/lib/multi-input/multi-input.component.ts
Labels: core, ariba, quick fix, ng15

#10447 feat(platform): added aria-labelledby to the table
  libs/platform/src/lib/table/components/table-toolbar/table-toolbar.component.ts
  libs/platform/src/lib/table/components/table-toolbar/table-toolbar.ts
  libs/platform/src/lib/table/table.component.html
  libs/platform/src/lib/table/table.component.ts
Labels: accessibility, platform, ariba, quick fix, ng15

#10443 feat(core): removed addon button on mobile mode in multi-input
  libs/core/src/lib/multi-input/multi-input-mobile/multi-input-mobile.component.html
  libs/core/src/lib/multi-input/multi-input.component.html
  libs/core/src/lib/multi-input/multi-input.component.ts
Labels: ariba, quick fix
