Repository SAP/fundamental-ngx, pull requests merged in 2023-05, with the labels that each got.

#9756 fix(core,platform): refocus select element on option select
  libs/core/src/lib/select/select.component.ts
  libs/platform/src/lib/form/combobox/commons/base-combobox.ts
Labels: bug, accessibility

#9790 fix(platform): failing combobox unit test
  libs/platform/src/lib/form/combobox/combobox/combobox.component.spec.ts
Labels: testing, flaky tests

#9788 fix(core,platform): table toolbar responsiveness
  .eslintrc.json
  libs/cdk/src/lib/utils/components/dynamic-portal/dynamic-portal.component.ts
  libs/cdk/src/lib/utils/components/index.ts
  libs/cdk/src/lib/utils/index.ts
  libs/core/src/lib/grid-list/components/grid-list-title-bar-spacer/grid-list-title-bar-spacer.component.ts
  libs/core/src/lib/table/table.module.ts
  libs/core/src/lib/toolbar/abstract-toolbar-item.class.ts
  libs/core/src/lib/toolbar/public_api.ts
  libs/core/src/lib/toolbar/toolbar-item.directive.ts
  libs/core/src/lib/toolbar/toolbar-overflow-group.directive.ts
  libs/core/src/lib/toolbar/toolbar-overflow-priority.directive.ts
  libs/core/src/lib/toolbar/toolbar-spacer.directive.ts
  libs/core/src/lib/toolbar/toolbar.component.html
  libs/core/src/lib/toolbar/toolbar.component.scss
  libs/core/src/lib/toolbar/toolbar.component.spec.ts
  libs/core/src/lib/toolbar/toolbar.component.ts
  libs/core/src/lib/toolbar/toolbar.module.ts
  libs/docs/platform/table/examples/platform-table-default-example.component.html
  libs/docs/platform/table/examples/platform-table-freezable-example.component.ts
  libs/docs/platform/table/examples/platform-table-tree-example.component.ts
  libs/docs/platform/table/platform-table-docs.component.html
  libs/docs/platform/table/platform-table.module.ts
  libs/platform/src/lib/panel/panel-actions.component.ts
  libs/platform/src/lib/panel/panel-actions/panel-actions.component.html
  libs/platform/src/lib/panel/panel-actions/panel-actions.component.ts
  libs/platform/src/lib/panel/panel.component.html
  libs/platform/src/lib/panel/panel.component.spec.ts
  libs/platform/src/lib/panel/panel.component.ts
  libs/platform/src/lib/panel/panel.module.ts
  libs/platform/src/lib/panel/public_api.ts
  libs/platform/src/lib/table/components/table-toolbar/table-toolbar.component.html
  libs/platform/src/lib/table/components/table-toolbar/table-toolbar.component.ts
  libs/platform/src/lib/table/table.component.scss
Labels: bug, enhancement, code refactoring, performance

#9808 fix(core,platform): multi combobox with numpad input
  libs/core/src/lib/multi-combobox/multi-combobox.component.ts
  libs/docs/platform/multi-combobox/examples/multi-combobox-datasource/multi-combobox-datasource-example.component.ts
  libs/platform/src/lib/form/multi-combobox/commons/base-multi-combobox.ts
Labels: bug, platform, core

#9784 fix: scrollbar should stop immediate propagation
  libs/core/src/lib/scrollbar/scrollbar.directive.ts
Labels: bug

#9785 fix(core): inline help needs tooltip role
  libs/core/src/lib/inline-help/inline-help.directive.ts
  libs/core/src/lib/popover/base/base-popover.class.ts
  libs/core/src/lib/popover/popover-body/popover-body.component.html
  libs/core/src/lib/popover/popover-body/popover-body.component.ts
  libs/core/src/lib/popover/popover-service/popover.service.ts
  libs/docs/core/inline-help/examples/inline-help-example.component.html
  libs/docs/core/inline-help/examples/inline-help-template-example/inline-help-template-example.component.html
  libs/docs/core/inline-help/examples/inline-help-trigger-example.component.html
Labels: bug, accessibility

#9819 fix(core,platform): remove unnecessary innerText usage
  libs/core/src/lib/feed-list-item/components/item/feed-list-item.component.html
  libs/core/src/lib/grid-list/components/grid-list-item/grid-list-item.component.html
  libs/core/src/lib/grid-list/components/grid-list-item/grid-list-item.component.spec.ts
  libs/core/src/lib/grid-list/components/grid-list-more-btn/grid-list-more-btn.component.html
  libs/core/src/lib/grid-list/components/grid-list/grid-list.component.spec.ts
  libs/core/src/lib/multi-combobox/mobile/mobile-multi-combobox.component.html
  libs/core/src/lib/quick-view/quick-view/quick-view.component.spec.ts
  libs/core/src/lib/slider/slider.component.html
  libs/core/src/lib/text/text.component.html
  libs/docs/core/avatar-group/examples/avatar-group-group-type-example.component.html
  libs/docs/core/avatar-group/examples/avatar-group-individual-type-example.component.html
  libs/docs/core/card/examples/quick-view-card/card-quick-view-example.component.html
  libs/docs/core/formatted-text/examples/base/formatted-text-example.component.html
  libs/docs/core/formatted-text/examples/links/formatted-text-links-example.component.html
  libs/docs/core/formatted-text/examples/script/formatted-text-script-example.component.html
  libs/docs/core/grid-list/examples/default/grid-list-example.component.html
  libs/docs/core/grid-list/examples/delete/grid-list-delete-example.component.html
  libs/docs/core/grid-list/examples/dnd/grid-list-dnd-example.component.html
  libs/docs/core/grid-list/examples/focusing/grid-list-focusing-example.component.html
  libs/docs/core/grid-list/examples/footer/grid-list-footer-example.component.html
  libs/docs/core/grid-list/examples/group/grid-list-group-example.component.html
  libs/docs/core/grid-list/examples/layout/grid-list-layout-example.component.html
  libs/docs/core/grid-list/examples/multi-select/grid-list-multi-select-example.component.html
  libs/docs/core/grid-list/examples/single-select-left/grid-list-single-select-left-example.component.html
  libs/docs/core/grid-list/examples/single-select-right/grid-list-single-select-right-example.component.html
  libs/docs/core/grid-list/examples/single-select/grid-list-single-select-example.component.html
  libs/docs/core/message-box/examples/custom-position/message-box-position-example.component.html
  libs/docs/core/message-box/examples/mobile-mode/message-box-mobile-example.component.html
  libs/docs/core/message-box/examples/object-based/object-based-message-box-example.component.html
  libs/docs/core/message-box/examples/semantic-types/semantic-types-example.component.html
  libs/docs/core/overflow-layout/examples/complex/overflow-layout-complex-example.component.html
  libs/docs/core/quick-view/examples/quick-view-base-example.component.html
  libs/docs/core/quick-view/examples/quick-view-dialog-example.component.html
  libs/docs/core/quick-view/examples/quick-view-popover-example.component.html
  libs/docs/platform/combobox/examples/combobox-templates/combobox-templates-example.component.html
  libs/platform/src/lib/form/combobox/combobox-mobile/combobox/combobox-mobile.component.html
  libs/platform/src/lib/form/multi-combobox/multi-combobox-mobile/multi-combobox/multi-combobox-mobile.component.html
  libs/platform/src/lib/form/multi-input/multi-input-mobile/multi-input-mobile.component.html
  libs/platform/src/lib/form/multi-input/multi-input.component.html
  libs/platform/src/lib/slider/slider.component.spec.ts
  libs/platform/src/lib/table/components/table-view-settings-dialog/sorting/sorting.component.html
  libs/platform/src/lib/table/table.component.html
  libs/platform/src/lib/upload-collection/dialogs/move-to/move-to.component.html
  libs/platform/src/lib/upload-collection/upload-collection/upload-collection.component.html
Labels: enhancement

#9762 fix(platform): checkbox focus/keyboard nav issue in platform table
  libs/platform/src/lib/table/table.component.html
  libs/platform/src/lib/table/table.component.ts
  libs/platform/src/lib/table/table.module.ts
Labels: bug

#9818 fix(core,platform,cx): navigation components had missing/incorrect roles
  libs/core/src/lib/list/list-navigation-item/list-navigation-item.component.ts
  libs/core/src/lib/nested-list/nested-item/nested-item.directive.ts
  libs/core/src/lib/side-navigation/side-navigation.component.ts
  libs/core/src/lib/vertical-navigation/vertical-navigation-main-navigation.component.ts
  libs/core/src/lib/vertical-navigation/vertical-navigation.component.html
  libs/core/src/lib/vertical-navigation/vertical-navigation.module.ts
  libs/cx/src/lib/nested-list/nested-item/nested-item.component.ts
  libs/cx/src/lib/side-navigation/side-navigation.component.html
  libs/cx/src/lib/side-navigation/side-navigation.module.ts
  libs/i18n/src/lib/languages/albanian.ts
  libs/i18n/src/lib/languages/arabic.ts
  libs/i18n/src/lib/languages/belarusian.ts
  libs/i18n/src/lib/languages/bulgarian.ts
  libs/i18n/src/lib/languages/chinese.ts
  libs/i18n/src/lib/languages/croatian.ts
  libs/i18n/src/lib/languages/czech.ts
  libs/i18n/src/lib/languages/english.ts
  libs/i18n/src/lib/languages/french.ts
  libs/i18n/src/lib/languages/georgian.ts
  libs/i18n/src/lib/languages/german.ts
  libs/i18n/src/lib/languages/hebrew.ts
  libs/i18n/src/lib/languages/hindi.ts
  libs/i18n/src/lib/languages/italian.ts
  libs/i18n/src/lib/languages/polish.ts
  libs/i18n/src/lib/languages/portuguese.ts
  libs/i18n/src/lib/languages/romanian.ts
  libs/i18n/src/lib/languages/russian.ts
  libs/i18n/src/lib/languages/sinhala.ts
  libs/i18n/src/lib/languages/spanish.ts
  libs/i18n/src/lib/languages/turkish.ts
  libs/i18n/src/lib/languages/ukrainian.ts
  libs/i18n/src/lib/models/lang.ts
Labels: bug, accessibility

#9910 feat(core): message toast bound to element
  libs/cdk/src/lib/utils/toast/base-toast-positions.ts
  libs/cdk/src/lib/utils/toast/base-toast.service.ts
  libs/cdk/src/lib/utils/toast/classes/base-toast-ref.ts
  libs/docs/core/message-toast/examples/message-toast-position-example.component.html
  libs/docs/core/message-toast/examples/message-toast-position-example.component.ts
Labels: enhancement

#9895 fix(platform): bug where combobox selection event fires twice
  libs/platform/src/lib/form/combobox/combobox/combobox.component.ts
Labels: bug

#9888 fix(core,cdk): markForCheck after attaching portal
  libs/cdk/src/lib/utils/dynamic-component/dynamic-component-container.ts
  libs/core/src/lib/dialog/dialog-container/dialog-container.component.ts
  libs/core/src/lib/message-box/message-box-container/message-box-container.component.ts
Labels: bug

#9907 feat(platform,docs): table preserved state
  apps/docs/src/app/platform/documentation/platform-documentation-data.ts
  libs/docs/platform/table/child-docs/preserving-state/preserved-state-docs.component.html
  libs/docs/platform/table/child-docs/preserving-state/preserved-state-docs.component.ts
  libs/docs/platform/table/examples/platform-table-p13-group-example.component.ts
  libs/docs/platform/table/examples/preserved-state/platform-table-preserved-state-example.component.html
  libs/docs/platform/table/examples/preserved-state/platform-table-preserved-state-example.component.ts
  libs/docs/platform/table/platform-table.module.ts
  libs/platform/src/lib/table/components/table-p13-dialog/filtering/filter-rule.component.html
  libs/platform/src/lib/table/table.component.ts
Labels: enhancement, documentation, platform, table

#9822 fix(core): inline help hidden element for screenreaders
  libs/core/src/lib/icon/icon.component.ts
  libs/core/src/lib/inline-help/inline-help.directive.ts
  libs/docs/core/icon/icon-docs.component.html
  libs/docs/core/input/e2e/input.e2e-spec.ts
Labels: accessibility

#9930 chore(cdk,core): partial jest migration
  libs/cdk/src/lib/utils/directives/auto-complete/auto-complete.directive.spec.ts
  libs/cdk/src/lib/utils/directives/focus-key-manager/focus-key-manager-list.directive.spec.ts
  libs/cdk/src/lib/utils/directives/initial-focus/initial-focus.directive.spec.ts
  libs/cdk/src/lib/utils/directives/initial-focus/initial-focus.directive.ts
  libs/cdk/src/lib/utils/directives/overflow-list/overflow-list.directive.spec.ts
  libs/cdk/src/lib/utils/directives/overflow-list/overflow-list.directive.ts
  libs/cdk/src/lib/utils/directives/selectable-list/selection.service.spec.ts
  libs/cdk/src/lib/utils/drag-and-drop/dnd-item/dnd-item.directive.spec.ts
  libs/cdk/src/lib/utils/drag-and-drop/dnd-list/dnd-list.directive.spec.ts
  libs/cdk/src/lib/utils/dynamic-component/dynamic-component-container.ts
  libs/cdk/src/lib/utils/functions/intersection-observable.spec.ts
  libs/cdk/src/lib/utils/functions/resize-observable.spec.ts
  libs/cdk/src/lib/utils/helpers/range-selector.spec.ts
  libs/cdk/src/lib/utils/jest.config.ts
  libs/cdk/src/lib/utils/karma.conf.js
  libs/cdk/src/lib/utils/pipes/async-or-sync.pipe.spec.ts
  libs/cdk/src/lib/utils/pipes/make-async.pipe.spec.ts
  libs/cdk/src/lib/utils/project.json
  libs/cdk/src/lib/utils/services/keyboard-support/keyboard-support.service.spec.ts
  libs/cdk/src/lib/utils/src/test-setup.ts
  libs/cdk/src/lib/utils/test.ts
  libs/cdk/src/lib/utils/tsconfig.spec.json
  libs/core/src/lib/dialog/base/dialog-base.class.ts
  libs/core/src/lib/dialog/tokens.ts
  libs/core/src/lib/message-box/jest.config.ts
  libs/core/src/lib/message-box/karma.conf.js
  libs/core/src/lib/message-box/message-box-body/message-box-body.component.spec.ts
  libs/core/src/lib/message-box/message-box-container/message-box-container.component.spec.ts
  libs/core/src/lib/message-box/message-box-default/message-box-default.component.spec.ts
  libs/core/src/lib/message-box/message-box-footer/message-box-footer.component.spec.ts
  libs/core/src/lib/message-box/message-box-header/message-box-header.component.spec.ts
  libs/core/src/lib/message-box/message-box.component.spec.ts
  libs/core/src/lib/message-box/project.json
  libs/core/src/lib/message-box/services/message-box.service.spec.ts
  libs/core/src/lib/message-box/src/test-setup.ts
  libs/core/src/lib/message-box/test.ts
  libs/core/src/lib/message-box/tsconfig.spec.json
  libs/core/src/lib/nested-list/jest.config.ts
  libs/core/src/lib/nested-list/karma.conf.js
  libs/core/src/lib/nested-list/nested-item/nested-item.directive.spec.ts
  libs/core/src/lib/nested-list/nested-list-directives.spec.ts
  libs/core/src/lib/nested-list/nested-list-keyboard.service.spec.ts
  libs/core/src/lib/nested-list/prepared-nested-list/prepared-nested-list.component.spec.ts
  libs/core/src/lib/nested-list/project.json
  libs/core/src/lib/nested-list/src/test-setup.ts
  libs/core/src/lib/nested-list/test.ts
  libs/core/src/lib/nested-list/tsconfig.spec.json
  package.json
Labels: testing, unit tests

#9953 docs(core,platform): show the current version on the doc
  libs/docs/shared/src/lib/core-helpers/toolbar/toolbar.component.html
Labels: documentation
