Repository SAP/fundamental-ngx, pull requests merged in 2023-04, with the labels that each got.

#9603 fix(platform): semantic borderless example
  libs/platform/src/lib/table/components/table-p13-dialog/filtering/filtering.component.scss
  libs/platform/src/lib/table/table.component.scss
Labels: bug, platform, table

#9610 fix(core): no tooltip for breadcrumb when overflow dots are shown
  libs/core/src/lib/breadcrumb/breadcrumb.component.html
  libs/core/src/lib/breadcrumb/breadcrumb.component.spec.ts
  libs/core/src/lib/breadcrumb/breadcrumb.module.ts
  libs/i18n/src/lib/languages/albanian.ts
  libs/i18n/src/lib/languages/arabic.ts
  libs/i18n/src/lib/languages/belarusian.ts
  libs/i18n/src/lib/languages/bulgarian.ts
  libs/i18n/src/lib/languages/chinese.ts
  libs/i18n/src/lib/languages/croatian.ts
  libs/i18n/src/lib/languages/czech.ts
  libs/i18n/src/lib/languages/english.ts
  libs/i18n/src/lib/languages/french.ts
  libs/i18n/src/lib/languages/georgian.ts
  libs/i18n/src/lib/languages/german.ts
  libs/i18n/src/lib/languages/hebrew.ts
  libs/i18n/src/lib/languages/hindi.ts
  libs/i18n/src/lib/languages/italian.ts
  libs/i18n/src/lib/languages/polish.ts
  libs/i18n/src/lib/languages/portuguese.ts
  libs/i18n/src/lib/languages/romanian.ts
  libs/i18n/src/lib/languages/russian.ts
  libs/i18n/src/lib/languages/sinhala.ts
  libs/i18n/src/lib/languages/spanish.ts
  libs/i18n/src/lib/languages/turkish.ts
  libs/i18n/src/lib/languages/ukrainian.ts
  libs/i18n/src/lib/models/lang.ts
Labels: accessibility

#9613 chore(core,platform): deprecate unmaintained Ariba specific components
  libs/core/src/lib/action-bar/action-bar.component.ts
  libs/docs/core/action-bar/action-bar-header/action-bar-header.component.html
  libs/docs/platform/action-bar/platform-action-bar-header/platform-action-bar-header.component.html
  libs/docs/platform/approval-flow/platform-approval-flow-header/platform-approval-flow-header.component.html
  libs/docs/platform/page-footer/platform-page-footer-header/platform-page-footer-header.component.html
  libs/docs/platform/thumbnail/platform-thumbnail-header/platform-thumbnail-header.component.html
  libs/docs/platform/upload-collection/platform-upload-collection-header/platform-upload-collection-header.component.html
  libs/platform/src/lib/action-bar/action-bar.component.ts
  libs/platform/src/lib/approval-flow/approval-flow-add-node/approval-flow-add-node.component.ts
  libs/platform/src/lib/approval-flow/approval-flow-approver-details/approval-flow-approver-details.component.ts
  libs/platform/src/lib/approval-flow/approval-flow-messages/approval-flow-messages.component.ts
  libs/platform/src/lib/approval-flow/approval-flow-node/approval-flow-node.component.ts
  libs/platform/src/lib/approval-flow/approval-flow-select-type/approval-flow-select-type.component.ts
  libs/platform/src/lib/approval-flow/approval-flow-team-list/approval-flow-team-list.component.ts
  libs/platform/src/lib/approval-flow/approval-flow-toolbar-actions/approval-flow-toolbar-actions.component.ts
  libs/platform/src/lib/approval-flow/approval-flow-user-details/approval-flow-user-details.component.ts
  libs/platform/src/lib/approval-flow/approval-flow-user-list/approval-flow-user-list.component.ts
  libs/platform/src/lib/approval-flow/approval-flow.component.ts
  libs/platform/src/lib/page-footer/page-footer.component.ts
  libs/platform/src/lib/thumbnail/thumbnail-details/thumbnail-details.component.ts
  libs/platform/src/lib/thumbnail/thumbnail-image/thumbnail-image.component.ts
  libs/platform/src/lib/thumbnail/thumbnail.component.ts
  libs/platform/src/lib/upload-collection/upload-collection/upload-collection.component.ts
Labels: ariba

#9626 feat(platform, cdk): Drag & drop auto detect mode
  angular.json
  apps/docs/src/app/cdk/cdk-documentation.routes.ts
  apps/docs/src/app/cdk/documentation/cdk-documentation-data.ts
  apps/docs/src/app/platform/documentation/platform-documentation-data.ts
  libs/cdk/src/lib/utils/drag-and-drop/dnd-list/dnd-list.directive.spec.ts
  libs/cdk/src/lib/utils/drag-and-drop/dnd-list/dnd-list.directive.ts
  libs/cdk/src/lib/utils/drag-and-drop/dnd.interfaces.ts
  libs/cdk/src/lib/utils/drag-and-drop/drag-and-drop.scss
  libs/docs/cdk/drag-n-drop/dnd-docs.component.html
  libs/docs/cdk/drag-n-drop/dnd-docs.component.ts
  libs/docs/cdk/drag-n-drop/dnd-docs.module.ts
  libs/docs/cdk/drag-n-drop/dnd-header/dnd-header.component.html
  libs/docs/cdk/drag-n-drop/dnd-header/dnd-header.component.ts
  libs/docs/cdk/drag-n-drop/examples/default-example/default-example.component.html
  libs/docs/cdk/drag-n-drop/examples/default-example/default-example.component.ts
  libs/docs/cdk/drag-n-drop/index.ts
  libs/docs/cdk/drag-n-drop/project.json
  libs/docs/cdk/drag-n-drop/tsconfig.json
  libs/docs/core/list/examples/list-dnd-example/list-dnd-example.component.ts
  libs/docs/platform/table/child-docs/clickable-rows/clickable-rows-docs.component.html
  libs/docs/platform/table/child-docs/clickable-rows/clickable-rows-docs.component.ts
  libs/docs/platform/table/child-docs/p13-dialog/p13-dialog-docs.component.html
  libs/docs/platform/table/child-docs/p13-dialog/p13-dialog-docs.component.ts
  libs/docs/platform/table/child-docs/row-selection/row-selection-docs.component.html
  libs/docs/platform/table/child-docs/row-selection/row-selection-docs.component.ts
  libs/docs/platform/table/child-docs/scrolling/table-scrolling-docs.component.html
  libs/docs/platform/table/child-docs/scrolling/table-scrolling-docs.component.ts
  libs/docs/platform/table/child-docs/settings-dialog/settings-dialog-docs.component.html
  libs/docs/platform/table/child-docs/settings-dialog/settings-dialog-docs.component.ts
  libs/docs/platform/table/e2e/table-clickable-rows.e2e-spec.ts
  libs/docs/platform/table/e2e/table-common-tests.ts
  libs/docs/platform/table/e2e/table-p13-dialog.e2e-spec.ts
  libs/docs/platform/table/e2e/table-row-selection.e2e-spec.ts
  libs/docs/platform/table/e2e/table-scrolling.e2e-spec.ts
  libs/docs/platform/table/e2e/table-settings-dialog.e2e-spec.ts
  libs/docs/platform/table/e2e/table.e2e-spec.ts
  libs/docs/platform/table/e2e/table.po.ts
  libs/docs/platform/table/platform-table-docs.component.html
  libs/docs/platform/table/platform-table-docs.component.ts
  libs/docs/platform/table/platform-table.module.ts
  libs/docs/shared/src/index.ts
  libs/docs/shared/src/lib/core-helpers/header-tabs/header-tabs.component.html
  libs/docs/shared/src/lib/core-helpers/header-tabs/header-tabs.component.ts
  libs/docs/shared/src/lib/services/example-child.service.ts
  libs/platform/src/lib/table/table.component.html
  libs/platform/src/lib/table/table.component.scss
  libs/platform/src/lib/table/table.component.spec.ts
  libs/platform/src/lib/table/table.component.ts
  tsconfig.base.json
Labels: enhancement, documentation, platform, e2e, table

#9631 chore: update fundamental-styles
  package.json
  yarn.lock
Labels: theming

#9594 feat(cdk): created breakpoint directive
  apps/docs/src/app/cdk/cdk-documentation.routes.ts
  apps/docs/src/app/cdk/documentation/cdk-documentation-data.ts
  libs/cdk/src/lib/forms/cva/cva-control.class.ts
  libs/cdk/src/lib/utils/directives/breakpoints/breakpoint.directive.spec.ts
  libs/cdk/src/lib/utils/directives/breakpoints/breakpoint.directive.ts
  libs/cdk/src/lib/utils/directives/breakpoints/responsive-breakpoints.ts
  libs/cdk/src/lib/utils/directives/index.ts
  libs/cdk/src/lib/utils/index.ts
  libs/cdk/src/lib/utils/services/resize-observer.service.ts
  libs/cdk/src/lib/utils/tokens/viewport-size.observable.ts
  libs/docs/cdk/breakpoint/breakpoint-docs.component.html
  libs/docs/cdk/breakpoint/breakpoint-docs.component.ts
  libs/docs/cdk/breakpoint/breakpoint-docs.module.ts
  libs/docs/cdk/breakpoint/breakpoint-header/breakpoint-header.component.html
  libs/docs/cdk/breakpoint/breakpoint-header/breakpoint-header.component.ts
  libs/docs/cdk/breakpoint/examples/alias-names-example/alias-names-example.component.ts
  libs/docs/cdk/breakpoint/examples/basic-example/basic-example.component.html
  libs/docs/cdk/breakpoint/examples/basic-example/basic-example.component.ts
  libs/docs/cdk/breakpoint/examples/different-observe-target-example.component.ts
  libs/docs/cdk/breakpoint/index.ts
  libs/docs/cdk/breakpoint/project.json
  libs/docs/cdk/breakpoint/tsconfig.json
  libs/docs/cdk/forms/examples/default/forms-default-example.component.ts
  libs/docs/cdk/shared/src/lib/api-files.ts
  libs/docs/platform/table/examples/platform-table-default-example.component.html
  libs/docs/platform/table/examples/platform-table-default-example.component.ts
  libs/docs/platform/table/platform-table-docs.component.html
  libs/docs/platform/table/platform-table.module.ts
  tsconfig.base.json
Labels: enhancement

#9638 fix(core): simplify change detection for segmented button
  libs/core/src/lib/button/base-button.ts
  libs/core/src/lib/segmented-button/segmented-button.component.spec.ts
  libs/core/src/lib/segmented-button/segmented-button.component.ts
Labels: bug, core

#9654 docs(platform): fix a type in settings generator
  libs/docs/platform/settings-generator/examples/default/settings-generator-default-example.component.ts
  libs/docs/platform/settings-generator/examples/dialog/settings-generator-dialog-example.component.ts
  libs/docs/platform/settings-generator/examples/message-popover/settings-generator-message-popover-example.component.ts
Labels: documentation

#9570 fix(cx): side nav updates
  libs/core/src/lib/shellbar/shellbar.component.html
  libs/core/src/lib/shellbar/shellbar.component.scss
  libs/core/src/lib/shellbar/shellbar.component.ts
  libs/core/src/lib/side-navigation/public_api.ts
  libs/core/src/lib/side-navigation/side-navigation.component.ts
  libs/core/src/lib/side-navigation/side-navigation.interface.ts
  libs/cx/src/lib/side-navigation/side-navigation.component.html
  libs/cx/src/lib/side-navigation/side-navigation.component.scss
  libs/cx/src/lib/side-navigation/side-navigation.component.ts
  libs/cx/src/lib/side-navigation/side-navigation.module.ts
  libs/docs/cx/side-navigation/examples/side-navigation-mobile-example.component.html
  libs/docs/cx/side-navigation/examples/side-navigation-mobile-example.component.ts
  libs/docs/cx/side-navigation/examples/side-navigation-shellbar-example.component.html
  libs/docs/cx/side-navigation/examples/side-navigation-shellbar-example.component.ts
  libs/docs/cx/side-navigation/side-navigation-docs.component.html
  libs/docs/cx/side-navigation/side-navigation-docs.component.ts
  libs/docs/cx/side-navigation/side-navigation-docs.module.ts
Labels: enhancement

#9673 fix(platform): extend TableRowsRearrangeEvent with new data
  libs/platform/src/lib/table/models/table-rows-rearrange-event.model.ts
  libs/platform/src/lib/table/table.component.ts
Labels: platform, table

#9684 fix(platform): automatically sticky table header
  libs/platform/src/lib/table/table.component.ts
Labels: bug

#9689 fix(cx): updated styles version and fixed side nav content density
  libs/cx/src/lib/side-navigation/side-navigation.component.scss
  libs/docs/platform/link/e2e/link.e2e-spec.ts
  package.json
  yarn.lock
Labels: dependencies, cx, quick fix

#9685 fix(platform): add input to disable drag and drop
  libs/docs/platform/table/platform-table-docs.component.html
  libs/platform/src/lib/table/table.component.html
  libs/platform/src/lib/table/table.component.scss
  libs/platform/src/lib/table/table.component.ts
Labels: enhancement

#9659 feat(platform): custom table popover renderer
  libs/core/src/lib/list/directives/list-link.directive.ts
  libs/core/src/lib/list/list-item/list-item.component.ts
  libs/core/src/lib/popover/popover-service/popover.service.ts
  libs/core/src/lib/popover/popover.component.ts
  libs/core/src/lib/timeline/timeline.component.spec.ts
  libs/docs/platform/settings-generator/examples/custom-layout/settings-generator-custom-layout-example.component.ts
  libs/docs/platform/table/e2e/table.po.ts
  libs/docs/platform/table/examples/platform-table-custom-column-example.component.html
  libs/docs/platform/table/examples/platform-table-custom-column-example.component.ts
  libs/docs/platform/table/platform-table-docs.component.html
  libs/docs/platform/table/platform-table.module.ts
  libs/docs/platform/upload-collection/e2e/upload-collection.e2e-spec.ts
  libs/platform/src/lib/list/free-content-list-item/free-content-list-item.component.spec.ts
  libs/platform/src/lib/list/list.component.ts
  libs/platform/src/lib/list/standard-list-item/standard-list-item.component.spec.ts
  libs/platform/src/lib/table/components/index.ts
  libs/platform/src/lib/table/components/table-cell-content/table-cell-content.component.html
  libs/platform/src/lib/table/components/table-cell-content/table-cell-content.component.ts
  libs/platform/src/lib/table/components/table-cell-header-popover/table-cell-header-popover.component.html
  libs/platform/src/lib/table/components/table-cell-header-popover/table-cell-header-popover.component.spec.ts
  libs/platform/src/lib/table/components/table-cell-header-popover/table-cell-header-popover.component.ts
  libs/platform/src/lib/table/components/table-column/table-column.component.ts
  libs/platform/src/lib/table/components/table-column/table-column.ts
  libs/platform/src/lib/table/components/table-header-cell-content/table-header-cell-content.component.html
  libs/platform/src/lib/table/components/table-header-cell-content/table-header-cell-content.component.spec.ts
  libs/platform/src/lib/table/components/table-header-cell-content/table-header-cell-content.component.ts
  libs/platform/src/lib/table/directives/table-cell-header-popover.directive.ts
  libs/platform/src/lib/table/directives/table-header.directive.ts
  libs/platform/src/lib/table/public_api.ts
  libs/platform/src/lib/table/table.component.html
  libs/platform/src/lib/table/table.component.ts
  libs/platform/src/lib/table/table.module.ts
Labels: enhancement, platform, table

#9612 fix(platform): tooltip for column size shrink
  libs/platform/src/lib/table/components/table-column/table-column.component.ts
  libs/platform/src/lib/table/components/table-column/table-column.ts
  libs/platform/src/lib/table/table-column-resize.service.spec.ts
  libs/platform/src/lib/table/table-column-resize.service.ts
  libs/platform/src/lib/table/table.component.html
  libs/platform/src/lib/table/table.component.scss
  libs/platform/src/lib/table/table.ts
Labels: platform

#9657 fix(platform): only scroll freezable cells when using l/r keyboard buttons, freezable column width not updating on table data load
  libs/platform/src/lib/table/table.component.html
  libs/platform/src/lib/table/table.component.ts
Labels: bug

#9694 fix(core,platform): multi combobox/input keyboard behaviour
  libs/core/src/lib/combobox/combobox.component.html
  libs/core/src/lib/combobox/combobox.component.ts
  libs/core/src/lib/input-group/input-group-directives.ts
  libs/core/src/lib/input-group/input-group.component.html
  libs/core/src/lib/input-group/input-group.component.ts
  libs/core/src/lib/input-group/input-group.module.ts
  libs/core/src/lib/multi-combobox/base-multi-combobox.class.ts
  libs/core/src/lib/multi-combobox/multi-combobox.component.scss
  libs/core/src/lib/multi-combobox/multi-combobox.component.ts
  libs/core/src/lib/multi-input/multi-input.component.scss
  libs/core/src/lib/multi-input/multi-input.component.ts
  libs/core/src/lib/token/tokenizer.component.scss
  libs/docs/core/combobox/combobox-docs.component.html
  libs/docs/core/multi-combobox/multi-combobox-docs.component.html
  libs/docs/core/multi-input/multi-input-docs.component.html
  libs/docs/platform/combobox/platform-combobox-docs.component.html
  libs/docs/platform/multi-combobox/platform-multi-combobox-docs.component.html
  libs/docs/platform/multi-input/platform-multi-input-docs.component.html
  libs/platform/src/lib/form/combobox/commons/base-combobox.ts
  libs/platform/src/lib/form/multi-combobox/commons/base-multi-combobox.ts
  libs/platform/src/lib/form/multi-input/base-multi-input.ts
  libs/platform/src/lib/form/multi-input/multi-input.component.html
  libs/platform/src/lib/form/multi-input/multi-input.component.ts
Labels: accessibility, platform, core

#9670 fix(core): allow shrinking groups
  libs/core/src/lib/shellbar/shellbar-actions/shellbar-actions.component.spec.ts
  libs/core/src/lib/shellbar/shellbar-actions/shellbar-actions.component.ts
  libs/core/src/lib/shellbar/shellbar.component.html
  libs/core/src/lib/shellbar/shellbar.component.spec.ts
  libs/core/src/lib/shellbar/shellbar.component.ts
  libs/docs/core/shellbar/examples/shellbar-growing-group-example/shellbar-growing-group-example.component.html
  libs/docs/core/shellbar/examples/shellbar-growing-group-example/shellbar-growing-group-example.component.ts
  libs/docs/core/shellbar/index.ts
  libs/docs/core/shellbar/shellbar-docs.component.html
  libs/docs/core/shellbar/shellbar-docs.module.ts
  package.json
  yarn.lock
Labels: core

#9696 fix(core): fd-scrollbar should prevent scroll event from bubbling
  libs/core/src/lib/scrollbar/scrollbar.directive.ts
Labels: bug

#9687 fix(core): fix overflow layout calculation
  libs/core/src/lib/overflow-layout/directives/overflow-item-ref.directive.ts
  libs/core/src/lib/overflow-layout/directives/overflow-layout-item.directive.ts
  libs/core/src/lib/overflow-layout/interfaces/overflow-item-ref.interface.ts
  libs/core/src/lib/overflow-layout/overflow-layout.service.ts
Labels: bug, core

#9693 fix(platform): enable keydown events also for the non-tree rows
  libs/platform/src/lib/table/table.component.html
  libs/platform/src/lib/table/table.component.ts
  versions.json
Labels: bug, platform

#9717 fix: testing translation_v2
  translation_v2.json
Labels: i18n

#9713 fix(platform): minor table visual issues
  libs/platform/src/lib/table/components/table-cell-content/table-cell-content.component.html
  libs/platform/src/lib/table/components/table-cell-content/table-cell-content.component.ts
  libs/platform/src/lib/table/table.component.html
Labels: bug

#9720 fix(cdk): resize observer cleanup and breakpoint directive export absence
  libs/cdk/src/lib/utils/services/resize-observer.service.ts
  libs/cdk/src/lib/utils/utils.module.ts
Labels: quick fix

#9590 fix(platform): exclude columns from p13n dialog
  libs/docs/platform/table/child-docs/p13-dialog/p13-dialog-docs.component.html
  libs/docs/platform/table/e2e/table-contents.ts
  libs/docs/platform/table/examples/platform-table-p13-columns-example.component.html
  libs/platform/src/lib/table/components/table-column/table-column.component.ts
  libs/platform/src/lib/table/components/table-column/table-column.ts
  libs/platform/src/lib/table/components/table-p13-dialog/table-p13-dialog.component.spec.ts
  libs/platform/src/lib/table/components/table-p13-dialog/table-p13-dialog.component.ts
Labels: platform

#9726 chore(deps): upgrade theming-base-content version 11.3.2
  package.json
  yarn.lock
Labels: dependencies, theming

#9729 fix(docs): api absence in prod builds
  apps/docs/project.json
Labels: documentation, quick fix

#9741 fix(platform): enables correct behavior for buttons when used as acti…
  libs/platform/src/lib/table/table.component.ts
Labels: platform

#9712 fix(platform): open up drag and drop to sorting/filtering/etc
  libs/docs/platform/table/platform-table-docs.component.html
  libs/platform/src/lib/table/models/table-rows-rearrange-event.model.ts
  libs/platform/src/lib/table/table.component.html
  libs/platform/src/lib/table/table.component.ts
Labels: bug, enhancement

#9748 fix(platform): fix table indentation
  libs/platform/src/lib/table/table.component.scss
Labels: bug, platform, table

#9770 fix: various dialog fixes
  libs/core/src/lib/bar/bar.component.ts
  libs/core/src/lib/combobox/combobox-mobile/combobox-mobile.component.ts
  libs/core/src/lib/dialog/dialog.component.ts
  libs/core/src/lib/input-group/input-group.component.scss
  libs/core/src/lib/menu/menu-mobile/menu-mobile.component.ts
  libs/core/src/lib/multi-combobox/mobile/mobile-multi-combobox.component.ts
  libs/core/src/lib/multi-input/multi-input-mobile/multi-input-mobile.component.ts
  libs/core/src/lib/select/select-mobile/select-mobile.component.ts
  libs/platform/src/lib/form/combobox/combobox-mobile/combobox/combobox-mobile.component.ts
  libs/platform/src/lib/form/multi-combobox/multi-combobox-mobile/multi-combobox/multi-combobox-mobile.component.ts
  libs/platform/src/lib/form/multi-input/multi-input-mobile/multi-input-mobile.component.ts
  libs/platform/src/lib/search-field/search-field-mobile/search-field/search-field-mobile.component.ts
  libs/platform/src/lib/smart-filter-bar/smart-filter-bar.component.ts
  libs/platform/src/lib/table/components/table-p13-dialog/table-p13-dialog.component.ts
Labels: bug
