Repository SAP/fundamental-ngx, pull requests merged in 2023-07, with the labels that each got.

#10100 fix(platform): add aria-description for select all checkbox
  libs/i18n/src/lib/languages/albanian.ts
  libs/i18n/src/lib/languages/arabic.ts
  libs/i18n/src/lib/languages/belarusian.ts
  libs/i18n/src/lib/languages/bulgarian.ts
  libs/i18n/src/lib/languages/chinese.ts
  libs/i18n/src/lib/languages/croatian.ts
  libs/i18n/src/lib/languages/czech.ts
  libs/i18n/src/lib/languages/english.ts
  libs/i18n/src/lib/languages/french.ts
  libs/i18n/src/lib/languages/georgian.ts
  libs/i18n/src/lib/languages/german.ts
  libs/i18n/src/lib/languages/hebrew.ts
  libs/i18n/src/lib/languages/hindi.ts
  libs/i18n/src/lib/languages/italian.ts
  libs/i18n/src/lib/languages/polish.ts
  libs/i18n/src/lib/languages/portuguese.ts
  libs/i18n/src/lib/languages/romanian.ts
  libs/i18n/src/lib/languages/russian.ts
  libs/i18n/src/lib/languages/sinhala.ts
  libs/i18n/src/lib/languages/spanish.ts
  libs/i18n/src/lib/languages/turkish.ts
  libs/i18n/src/lib/languages/ukrainian.ts
  libs/i18n/src/lib/models/lang.ts
  libs/platform/src/lib/table/components/table-header-row/table-header-row.component.html
Labels: bug

#9876 feat(core): added select all toggler to the multi combo box
  libs/core/src/lib/multi-combobox/multi-combobox.component.html
  libs/core/src/lib/multi-combobox/multi-combobox.component.ts
  libs/core/src/lib/multi-combobox/multi-combobox.module.ts
  libs/core/src/lib/multi-combobox/multi-combobox.token.ts
  libs/core/src/lib/multi-combobox/select-all-toggler/select-all-toggler.component.scss
  libs/core/src/lib/multi-combobox/select-all-toggler/select-all-toggler.component.ts
  libs/datetime-adapter/src/lib/dayjs-datetime-adapter.spec.ts
  libs/docs/core/multi-combobox/examples/multi-combobox-datasource/multi-combobox-datasource-example.component.html
  libs/i18n/src/lib/languages/albanian.ts
  libs/i18n/src/lib/languages/arabic.ts
  libs/i18n/src/lib/languages/belarusian.ts
  libs/i18n/src/lib/languages/bulgarian.ts
  libs/i18n/src/lib/languages/chinese.ts
  libs/i18n/src/lib/languages/croatian.ts
  libs/i18n/src/lib/languages/czech.ts
  libs/i18n/src/lib/languages/english.ts
  libs/i18n/src/lib/languages/french.ts
  libs/i18n/src/lib/languages/georgian.ts
  libs/i18n/src/lib/languages/german.ts
  libs/i18n/src/lib/languages/hebrew.ts
  libs/i18n/src/lib/languages/hindi.ts
  libs/i18n/src/lib/languages/italian.ts
  libs/i18n/src/lib/languages/polish.ts
  libs/i18n/src/lib/languages/portuguese.ts
  libs/i18n/src/lib/languages/romanian.ts
  libs/i18n/src/lib/languages/russian.ts
  libs/i18n/src/lib/languages/sinhala.ts
  libs/i18n/src/lib/languages/spanish.ts
  libs/i18n/src/lib/languages/turkish.ts
  libs/i18n/src/lib/languages/ukrainian.ts
  libs/i18n/src/lib/models/lang.ts
  package.json
  yarn.lock
Labels: enhancement, core

#10091 feat(core): added wrapping to the checkbox label
  libs/core/src/lib/checkbox/checkbox/checkbox.component.html
  libs/core/src/lib/checkbox/checkbox/checkbox.component.ts
  libs/docs/core/checkbox/checkbox-docs.component.html
  libs/docs/core/checkbox/checkbox-docs.component.ts
  libs/docs/core/checkbox/examples/checkbox-label-wrapping-example.component.ts
  libs/docs/core/checkbox/examples/index.ts
Labels: enhancement

#10066 feat(core): busy indicator horizon
  libs/cdk/src/lib/utils/components/dynamic-portal/dynamic-portal.component.ts
  libs/core/src/lib/busy-indicator/busy-indicator-extended/busy-indicator-extended.directive.spec.ts
  libs/core/src/lib/busy-indicator/busy-indicator-extended/busy-indicator-extended.directive.ts
  libs/core/src/lib/busy-indicator/busy-indicator.component.spec.ts
  libs/core/src/lib/busy-indicator/busy-indicator.component.ts
  libs/core/src/lib/busy-indicator/busy-indicator.module.ts
  libs/core/src/lib/dialog/dialog-body/dialog-body.component.html
  libs/core/src/lib/dialog/dialog.module.ts
  libs/core/src/lib/dialog/utils/dialog-ref.class.ts
  libs/core/src/lib/link/link.component.spec.ts
  libs/core/src/lib/link/link.component.ts
  libs/core/src/lib/link/link.module.ts
  libs/core/src/lib/object-identifier/object-identifier.component.spec.ts
  libs/core/src/lib/text/text.component.spec.ts
  libs/core/src/lib/text/text.component.ts
  libs/core/src/lib/text/text.module.ts
  libs/core/src/lib/vertical-navigation/vertical-navigation.component.spec.ts
  libs/docs/core/dialog/examples/dialog-state/dialog-state-example.component.ts
  libs/i18n/src/lib/directives/patch-language.directive.ts
  libs/i18n/src/lib/i18n.module.ts
  libs/i18n/src/lib/pipes/fd-translate.pipe.ts
Labels: Horizon 2023

#10129 fix(platform): table checkbox space scroll bug
  libs/platform/src/lib/table/table.component.html
  libs/platform/src/lib/table/table.component.ts
Labels: bug

#10120 chore(deps): update theming-base-content v.11.5.0
  libs/docs/core/icon/examples/icon-businessSuiteInAppSymbols-example.component.ts
  libs/docs/core/icon/examples/icon-example.component.ts
  libs/docs/shared/src/lib/utilities/icons.ts
  package.json
  yarn.lock
Labels: dependencies, theming

#10150 chore(tooling): fixed sap-component generator
  libs/nx-plugin/src/generators/sap-component/files/docs/project.json.template
  libs/nx-plugin/src/generators/sap-component/generator.ts
Labels: tooling

#10063 fix(core): redundant popover open/close/event things
  libs/core/src/lib/popover/popover-mobile/popover-mobile.component.html
  libs/core/src/lib/popover/popover-service/popover.service.ts
  libs/core/src/lib/popover/popover.component.spec.ts
  libs/core/src/lib/popover/popover.component.ts
  libs/docs/core/popover/e2e/popover.e2e-spec.ts
  libs/docs/core/popover/e2e/popover.po.ts
  libs/docs/core/popover/examples/popover-mobile/popover-mobile-example.component.html
Labels: bug

#10151 chore(deps): update to theming-base-content v.11.6.1
  package.json
  yarn.lock
Labels: theming

#10158 chore(tooling): introduced new release creation ci workflow
  .github/actions/bump-version/action.yml
  .github/actions/bump-version/index.js
  .github/actions/generate-conventional-release-notes/closest-version.js
  .github/actions/get-version/action.yml
  .github/actions/get-version/index.js
  .github/actions/helpers/angular-version.js
  .github/actions/helpers/bumped-release.js
  .github/actions/helpers/current-version.js
  .github/actions/helpers/get-file-contents.js
  .github/actions/helpers/get-release-tag.js
  .github/actions/helpers/get-release-tag.spec.js
  .github/actions/helpers/get-version.js
  .github/actions/helpers/git-semver-tags.js
  .github/actions/npm-publish/index.js
  .github/actions/release-tags/action.yml
  .github/actions/release-tags/index.js
  .github/jest.config.js
  .github/workflows/create-hotfix.yml
  .github/workflows/create-release.yml
  lerna.json
  libs/nx-plugin/src/executors/prepare-library/utils/sync-versions.ts
  nx.json
  package.json
  scripts/hotfix-publish-release.sh
  scripts/release-hotfix.js
  yarn.lock
Labels: tooling

#10161 chore: synchronized versions
  lerna.json
  libs/cdk/src/lib/package.json
  libs/core/src/lib/package.json
  libs/cx/src/lib/package.json
  libs/datetime-adapter/package.json
  libs/fn/src/lib/package.json
  libs/i18n/package.json
  libs/moment-adapter/package.json
  libs/platform/src/lib/package.json
Labels: tooling

#10162 chore: removed hardcoded dry-run from publish script
  .github/actions/npm-publish/index.js
Labels: tooling

#10153 fix(core): carousel not updating when slide count changes
  libs/core/src/lib/carousel/carousel.component.spec.ts
  libs/core/src/lib/carousel/carousel.component.ts
Labels: bug

#10167 fix(platform): fixed table sort rules update
  libs/platform/src/lib/table-helpers/services/table.service.ts
Labels: bug, platform, table

#10168 fix(docs,core,platform): various fixes from deffect hunt
  libs/cdk/src/lib/utils/directives/initial-focus/initial-focus.directive.ts
  libs/core/src/lib/combobox/combobox-mobile/combobox-mobile.component.html
  libs/core/src/lib/dialog/dialog-default/dialog-default.component.html
  libs/core/src/lib/list/list-item/list-item.component.ts
  libs/core/src/lib/menu/menu-mobile/menu-mobile.component.html
  libs/core/src/lib/message-box/message-box-default/message-box-default.component.html
  libs/core/src/lib/select/select.component.html
  libs/docs/cdk/clicked/clicked-header/clicked-header.component.html
  libs/docs/cdk/disabled/disabled-header/disabled-header.component.html
  libs/docs/cdk/focusable-grid/focusable-grid-header/focusable-grid-header.component.html
  libs/docs/cdk/focusable-list/focusable-list-header/focusable-list-header.component.html
  libs/docs/cdk/initial-focus/examples/default/initial-focus-default-example.component.html
  libs/docs/cdk/initial-focus/examples/nested-elements-example/nested-elements-example.component.html
  libs/docs/cdk/initial-focus/initial-focus-docs.component.html
  libs/docs/cdk/selectable-list/selectable-list-header/selectable-list-header.component.html
  libs/docs/core/dialog/dialog-docs.component.html
  libs/docs/core/illustrated-message/examples/illustrated-message-dialog-example.component.html
  libs/docs/core/message-box/examples/template-based/template-based-message-box-example.component.html
  libs/docs/core/message-box/message-box-docs.component.html
  libs/docs/core/popover/examples/popover-dialog/popover-dialog-example.component.html
  libs/docs/core/tabs/e2e/tabs.po.ts
  libs/docs/core/wizard/examples/wizard-branching-example.component.html
  libs/docs/platform/icon-tab-bar/platform-icon-tab-bar-header/platform-icon-tab-bar-header.component.html
  libs/docs/platform/wizard-generator/examples/wizard-generator-customizable-example.component.html
  libs/platform/src/lib/approval-flow/approval-flow-add-node/approval-flow-add-node.component.html
  libs/platform/src/lib/approval-flow/approval-flow-approver-details/approval-flow-approver-details.component.html
  libs/platform/src/lib/approval-flow/approval-flow-select-type/approval-flow-select-type.component.html
  libs/platform/src/lib/form/form-generator/form-generator/form-generator.component.html
  libs/platform/src/lib/message-popover/components/message-view/message-view.component.html
  libs/platform/src/lib/search-field/search-field-mobile/search-field/search-field-mobile.component.html
  libs/platform/src/lib/upload-collection/dialogs/new-folder/new-folder.component.html
  libs/platform/src/lib/wizard-generator/components/dialog-wizard-generator/dialog-wizard-generator.component.html
Labels: bug

#10163 fix(platform): table console error
  libs/platform/src/lib/table/table.component.ts
Labels: bug

#10157 fix(platform): remove aria-labelledby from platform table header cells
  libs/platform/src/lib/table/components/table-header-row/table-header-row.component.html
Labels: bug, accessibility

#10164 fix(platform): various fixes for platform table
  libs/docs/platform/table/e2e/table-p13-dialog.e2e-spec.ts
  libs/i18n/src/lib/languages/albanian.ts
  libs/i18n/src/lib/languages/arabic.ts
  libs/i18n/src/lib/languages/belarusian.ts
  libs/i18n/src/lib/languages/bulgarian.ts
  libs/i18n/src/lib/languages/chinese.ts
  libs/i18n/src/lib/languages/croatian.ts
  libs/i18n/src/lib/languages/czech.ts
  libs/i18n/src/lib/languages/english.ts
  libs/i18n/src/lib/languages/french.ts
  libs/i18n/src/lib/languages/georgian.ts
  libs/i18n/src/lib/languages/german.ts
  libs/i18n/src/lib/languages/hebrew.ts
  libs/i18n/src/lib/languages/hindi.ts
  libs/i18n/src/lib/languages/italian.ts
  libs/i18n/src/lib/languages/polish.ts
  libs/i18n/src/lib/languages/portuguese.ts
  libs/i18n/src/lib/languages/romanian.ts
  libs/i18n/src/lib/languages/russian.ts
  libs/i18n/src/lib/languages/sinhala.ts
  libs/i18n/src/lib/languages/spanish.ts
  libs/i18n/src/lib/languages/turkish.ts
  libs/i18n/src/lib/languages/ukrainian.ts
  libs/i18n/src/lib/models/lang.ts
  libs/platform/src/lib/table/components/table-cell-header-popover/table-cell-header-popover.component.html
  libs/platform/src/lib/table/components/table-header-row/table-header-row.component.html
  libs/platform/src/lib/table/components/table-header-row/table-header-row.component.ts
  libs/platform/src/lib/table/components/table-p13-dialog/sorting/sorting.component.html
  libs/platform/src/lib/table/table.component.html
  libs/platform/src/lib/table/table.component.ts
Labels: bug

#10170 fix(core): remove manual change detection from dialog container
  libs/core/src/lib/dialog/dialog-container/dialog-container.component.ts
  libs/core/src/lib/message-box/message-box-container/message-box-container.component.ts
Labels: bug

#10193 fix(core): add option to focus first focusable element in tab panel when using stacked tabs
  libs/core/src/lib/tabs/tab-list.component.ts
  libs/core/src/lib/tabs/tab-panel/tab-panel.component.ts
Labels: enhancement

#10098 fix(platform): preserves scrolling position
  libs/docs/platform/table/child-docs/scrolling/table-scrolling-docs.component.html
  libs/docs/platform/table/examples/virtual-scroll/platform-table-virtual-scroll-example.component.html
  libs/docs/platform/table/examples/virtual-scroll/platform-table-virtual-scroll-example.component.ts
  libs/platform/src/lib/table-helpers/constants/index.ts
  libs/platform/src/lib/table-helpers/directives/table-scrollable.directive.ts
  libs/platform/src/lib/table-helpers/directives/table-virtual-scroll.directive.ts
  libs/platform/src/lib/table-helpers/interfaces/table-state.interface.ts
  libs/platform/src/lib/table-helpers/services/table-scroll-dispatcher.service.ts
  libs/platform/src/lib/table-helpers/services/table.service.ts
  libs/platform/src/lib/table/table.component.ts
  libs/platform/src/lib/table/tests/table.component-page-scrolling.spec.ts
Labels: platform

#10191 fix(platform): update tablerows index
  libs/platform/src/lib/table/table.component.ts
Labels: platform, sourcing, table

#10195 fix(core): only stop propagation of scroll in the popover
  libs/core/src/lib/dynamic-page/dynamic-page.component.spec.ts
  libs/core/src/lib/popover/popover-body/popover-body.component.ts
  libs/core/src/lib/popover/popover.component.spec.ts
  libs/core/src/lib/popover/popover.component.ts
  libs/core/src/lib/scrollbar/scrollbar.directive.ts
Labels: bug

#10220 fix(docs): dayjs datetime adapter docs
  libs/datetime-adapter/src/lib/dayjs-datetime-adapter.ts
  libs/docs/core/dayjs-datetime-adapter/examples/date-picker-dayjs-adapter-example.component.ts
  libs/docs/core/dayjs-datetime-adapter/examples/dayjs-adapter-options-example.component.ts
Labels: bug, documentation

#10225 fix(core,platform): remove the i18n files for not translated languages
  libs/docs/shared/src/lib/core-helpers/toolbar/toolbar.component.ts
  libs/i18n/src/lib/languages/arabic.ts
  libs/i18n/src/lib/languages/belarusian.ts
  libs/i18n/src/lib/languages/croatian.ts
  libs/i18n/src/lib/languages/german.ts
  libs/i18n/src/lib/languages/hebrew.ts
  libs/i18n/src/lib/languages/index.ts
  libs/i18n/src/lib/languages/portuguese.ts
  libs/i18n/src/lib/languages/romanian.ts
  libs/i18n/src/lib/languages/sinhala.ts
  libs/i18n/src/lib/languages/spanish.ts
Labels: tooling

#10226 fix: add focusAutoCapture to table popover
  libs/docs/core/table/examples/table-column-sorting-example.component.html
Labels: documentation

#10223 fix(platform): line break in template adding whitespace to table text
  libs/platform/src/lib/table/components/table-row/table-row.component.html
Labels: bug

#10200 fix(core): only apply the animation/transition to the switch when the…
  libs/core/src/lib/switch/switch.component.html
  libs/core/src/lib/switch/switch.component.scss
  libs/core/src/lib/switch/switch.component.spec.ts
  libs/core/src/lib/switch/switch.component.ts
  libs/docs/core/switch/e2e/switch.e2e-spec.ts
Labels: bug

#10228 fix(core): correct icon placement
  libs/core/src/lib/button/button.component.html
Labels: bug, core

#10227 fix(docs): highlight async content
  libs/docs/shared/src/lib/core-helpers/code-snippet/code-snippet.component.ts
Labels: bug, documentation

#10229 fix(platform): add missing labels
  libs/i18n/src/lib/languages/albanian.ts
  libs/i18n/src/lib/languages/bulgarian.ts
  libs/i18n/src/lib/languages/chinese.ts
  libs/i18n/src/lib/languages/czech.ts
  libs/i18n/src/lib/languages/english.ts
  libs/i18n/src/lib/languages/french.ts
  libs/i18n/src/lib/languages/georgian.ts
  libs/i18n/src/lib/languages/hindi.ts
  libs/i18n/src/lib/languages/italian.ts
  libs/i18n/src/lib/languages/polish.ts
  libs/i18n/src/lib/languages/russian.ts
  libs/i18n/src/lib/languages/turkish.ts
  libs/i18n/src/lib/languages/ukrainian.ts
  libs/i18n/src/lib/models/lang.ts
  libs/platform/src/lib/form/multi-input/multi-input.component.html
  libs/platform/src/lib/form/multi-input/multi-input.component.ts
  libs/platform/src/lib/smart-filter-bar/components/smart-filter-bar-condition-field/smart-filter-bar-condition-field.component.html
  libs/platform/src/lib/smart-filter-bar/smart-filter-bar.component.html
Labels: bug, accessibility, platform

#10232 fix(docs): i18n example sources
  apps/docs/project.json
  libs/docs/i18n/examples/i18n-translation-customization-example/i18n-translation-customization-example.component.html
  libs/docs/i18n/platform-i18n-docs.component.ts
Labels: bug, documentation

#10233 fix(core): provided wizard service
  libs/core/src/lib/wizard/wizard.module.ts
  libs/docs/core/wizard/examples/loading/wizard-loading-example.component.ts
  libs/docs/core/wizard/examples/wizard-branching-example.component.ts
  libs/docs/core/wizard/examples/wizard-customizable-example.component.ts
  libs/docs/core/wizard/examples/wizard-dialog-example.component.ts
  libs/docs/core/wizard/examples/wizard-example.component.ts
  libs/docs/core/wizard/examples/wizard-mobile-example.component.ts
  libs/docs/core/wizard/examples/wizard-ngfor-example.component.ts
  libs/docs/core/wizard/examples/wizard-visible-summary-example.component.ts
Labels: core

#10231 feat(core): form message popover placement
  libs/core/src/lib/form/form-input-message-group/form-input-message-group.component.html
  libs/core/src/lib/form/form-input-message-group/form-input-message-group.component.scss
  libs/core/src/lib/form/form-input-message-group/form-input-message-group.component.ts
  libs/core/src/lib/popover/base/base-popover.class.ts
  libs/core/src/lib/popover/popover-service/popover.service.ts
  libs/docs/core/form-message/examples/form-message-example.component.html
  libs/docs/core/form-message/examples/form-message-example.component.ts
  libs/docs/core/list/examples/list-example.component.html
  libs/docs/core/list/examples/list-examples.component.ts
  libs/docs/core/list/list-docs.module.ts
Labels: enhancement, core

#10235 fix(platform): add new strings for platform table single selection cells
  libs/i18n/src/lib/languages/albanian.ts
  libs/i18n/src/lib/languages/bulgarian.ts
  libs/i18n/src/lib/languages/chinese.ts
  libs/i18n/src/lib/languages/czech.ts
  libs/i18n/src/lib/languages/english.ts
  libs/i18n/src/lib/languages/french.ts
  libs/i18n/src/lib/languages/georgian.ts
  libs/i18n/src/lib/languages/hindi.ts
  libs/i18n/src/lib/languages/italian.ts
  libs/i18n/src/lib/languages/polish.ts
  libs/i18n/src/lib/languages/russian.ts
  libs/i18n/src/lib/languages/turkish.ts
  libs/i18n/src/lib/languages/ukrainian.ts
  libs/i18n/src/lib/models/lang.ts
  libs/platform/src/lib/table/components/table-row/table-row.component.html
Labels: accessibility
