Repository SAP/fundamental-ngx, pull requests merged in 2023-10, with the labels that each got.

#10650 docs: bring the latest icons in the docs
  libs/docs/core/icon/examples/icon-businessSuiteInAppSymbols-example.component.ts
  libs/docs/core/icon/examples/icon-example.component.ts
  libs/docs/core/icon/examples/icon-tnt-example.component.ts
Labels: Horizon 2023

#10609 fix(core): update token total count properly
  libs/core/src/lib/token/token.component.ts
Labels: bug, accessibility

#10634 fix(core): some improvements to using labels with block busy indicator
  libs/core/src/lib/busy-indicator/busy-indicator.component.spec.ts
Labels: enhancement, core

#10662 feat: downport german i18n
  libs/docs/shared/src/lib/core-helpers/toolbar/toolbar.component.ts
  libs/i18n/src/lib/languages/german.ts
  libs/i18n/src/lib/languages/index.ts
Labels: enhancement, i18n, ng15

#10635 fix(core): some improvements to using labels with block busy indicator
  libs/core/src/lib/busy-indicator/busy-indicator.component.html
  libs/core/src/lib/busy-indicator/busy-indicator.component.scss
  libs/core/src/lib/busy-indicator/busy-indicator.component.spec.ts
Labels: enhancement, core, ng15

#10655 fix(docs,core): various defect hunt issues
  libs/core/src/lib/micro-process-flow/components/micro-process-flow-item/micro-process-flow-item.component.ts
  libs/docs/core/breadcrumb/examples/breadcrumb-routerLink-example.component.html
  libs/docs/core/illustrated-message/examples/illustrated-message-inline-example.component.ts
  libs/docs/core/panel/panel-docs.component.html
  libs/docs/platform/smart-filter-bar/examples/platform-smart-filter-bar-custom-filter-example.component.ts
  libs/platform/src/lib/upload-collection/upload-collection/upload-collection.component.html
Labels: documentation, core, Defect Hunting

#10653 fix(core): tokenizer more button focus issue
  libs/core/src/lib/token/tokenizer.component.html
Labels: ng15

#10660 feat: add German language support
  libs/docs/shared/src/lib/core-helpers/toolbar/toolbar.component.ts
  libs/i18n/src/lib/languages/german.ts
  libs/i18n/src/lib/languages/index.ts
  libs/i18n/src/lib/translations/translations_de-DE.json
Labels: tooling, i18n

#10671 docs: update CONTRIBUTING.md with local setup steps
  CONTRIBUTING.md
Labels: documentation

#10672 fix(core): tab list tabindex fix
  libs/core/src/lib/tabs/tab-list.component.html
Labels: accessibility

#10657 fix(core): add role to show all button
  libs/core/src/lib/multi-input/multi-input.component.html
Labels: ng15

#10651 fix(core): inline help screenreader bug when using template
  libs/core/src/lib/inline-help/inline-help.directive.ts
Labels: bug

#10675 fix(platform): fdp multi combobox fires multiple times after value is…
  libs/platform/src/lib/form/multi-combobox/multi-combobox/multi-combobox.component.ts
Labels: ng15

#10679 fix(core): add aria-label to tokenizer
  libs/core/src/lib/token/tokenizer.component.html
  libs/i18n/src/lib/languages/albanian.ts
  libs/i18n/src/lib/languages/bulgarian.ts
  libs/i18n/src/lib/languages/chinese.ts
  libs/i18n/src/lib/languages/czech.ts
  libs/i18n/src/lib/languages/english.ts
  libs/i18n/src/lib/languages/french.ts
  libs/i18n/src/lib/languages/georgian.ts
  libs/i18n/src/lib/languages/german.ts
  libs/i18n/src/lib/languages/hindi.ts
  libs/i18n/src/lib/languages/italian.ts
  libs/i18n/src/lib/languages/polish.ts
  libs/i18n/src/lib/languages/russian.ts
  libs/i18n/src/lib/languages/turkish.ts
  libs/i18n/src/lib/languages/ukrainian.ts
  libs/i18n/src/lib/models/lang.ts
Labels: ng15

#10663 chore(docs): popover examples
  libs/docs/core/popover/e2e/popover-contents.ts
  libs/docs/core/popover/e2e/popover.e2e-spec.ts
  libs/docs/core/popover/examples/popover-complex-example/popover-complex-example.component.html
  libs/docs/core/popover/examples/popover-complex-example/popover-complex-example.component.ts
  libs/docs/core/popover/examples/popover-simple/popover-example.component.html
  libs/docs/core/popover/examples/popover-simple/popover-example.component.ts
Labels: documentation, Horizon 2023

#10696 chore(deps): fixed i18n dependency and updated fundamental-styles
  libs/i18n/ng-package.json
  libs/i18n/package.json
  libs/nx-plugin/src/executors/prepare-library/utils/sync-versions.ts
  package.json
  yarn.lock
Labels: bug, dependencies

#10699 feat: add Portuguese language support
  libs/docs/shared/src/lib/core-helpers/toolbar/toolbar.component.ts
  libs/i18n/src/lib/languages/index.ts
  libs/i18n/src/lib/languages/portuguese.ts
  libs/i18n/src/lib/translations/translations_pt-BR.json
Labels: tooling

#10702 docs: add Portuguese brazil in doc
  libs/docs/shared/src/lib/core-helpers/toolbar/toolbar.component.ts
Labels: documentation

#10684 fix(core): add full labels to time component for screenreader
  libs/core/src/lib/time/i18n/time-i18n.ts
  libs/core/src/lib/time/time-column/time-column-config.ts
  libs/core/src/lib/time/time-column/time-column.component.html
  libs/core/src/lib/time/time-column/time-column.component.ts
  libs/core/src/lib/time/time.component.ts
  libs/i18n/src/lib/languages/albanian.ts
  libs/i18n/src/lib/languages/bulgarian.ts
  libs/i18n/src/lib/languages/chinese.ts
  libs/i18n/src/lib/languages/czech.ts
  libs/i18n/src/lib/languages/english.ts
  libs/i18n/src/lib/languages/french.ts
  libs/i18n/src/lib/languages/georgian.ts
  libs/i18n/src/lib/languages/german.ts
  libs/i18n/src/lib/languages/hindi.ts
  libs/i18n/src/lib/languages/italian.ts
  libs/i18n/src/lib/languages/polish.ts
  libs/i18n/src/lib/languages/portuguese.ts
  libs/i18n/src/lib/languages/russian.ts
  libs/i18n/src/lib/languages/turkish.ts
  libs/i18n/src/lib/languages/ukrainian.ts
  libs/i18n/src/lib/models/lang.ts
Labels: ng15

#10683 fix(core): add full labels to time component for screenreader
  libs/core/src/lib/time/time-column/time-column-config.ts
  libs/core/src/lib/time/time-column/time-column.component.html
  libs/core/src/lib/time/time-column/time-column.component.ts
  libs/i18n/src/lib/models/lang.ts
  libs/i18n/src/lib/translations/translations_bg-BG.json
  libs/i18n/src/lib/translations/translations_cs-CZ.json
  libs/i18n/src/lib/translations/translations_de-DE.json
  libs/i18n/src/lib/translations/translations_en-US.json
  libs/i18n/src/lib/translations/translations_fr-FR.json
  libs/i18n/src/lib/translations/translations_hi-IN.json
  libs/i18n/src/lib/translations/translations_it-IT.json
  libs/i18n/src/lib/translations/translations_ka-GE.json
  libs/i18n/src/lib/translations/translations_pl-PL.json
  libs/i18n/src/lib/translations/translations_pt-BR.json
  libs/i18n/src/lib/translations/translations_ru-RU.json
  libs/i18n/src/lib/translations/translations_sq-AL.json
  libs/i18n/src/lib/translations/translations_tr-TR.json
  libs/i18n/src/lib/translations/translations_uk-UA.json
  libs/i18n/src/lib/translations/translations_zh-CN.json
Labels: accessibility

#10677 fix(core): improved multi-input a11y
  libs/core/src/lib/multi-input/multi-input.component.html
  libs/core/src/lib/multi-input/multi-input.component.ts
  libs/i18n/src/lib/languages/albanian.ts
  libs/i18n/src/lib/languages/bulgarian.ts
  libs/i18n/src/lib/languages/chinese.ts
  libs/i18n/src/lib/languages/czech.ts
  libs/i18n/src/lib/languages/english.ts
  libs/i18n/src/lib/languages/french.ts
  libs/i18n/src/lib/languages/georgian.ts
  libs/i18n/src/lib/languages/german.ts
  libs/i18n/src/lib/languages/hindi.ts
  libs/i18n/src/lib/languages/italian.ts
  libs/i18n/src/lib/languages/polish.ts
  libs/i18n/src/lib/languages/portuguese.ts
  libs/i18n/src/lib/languages/russian.ts
  libs/i18n/src/lib/languages/turkish.ts
  libs/i18n/src/lib/languages/ukrainian.ts
  libs/i18n/src/lib/models/lang.ts
Labels: ng15

#10703 docs(core): remove hardcoded fdCozy from popover examples
  libs/docs/core/popover/examples/popover-focus-example/popover-focus-example.component.html
  libs/docs/core/popover/examples/popover-simple/popover-example.component.html
Labels: documentation

#10716 fix(btp): vertical navigation ui bug fixes
  libs/btp/index.ts
  libs/btp/jest.config.ts
  libs/btp/navigation/.eslintrc.json
  libs/btp/navigation/jest.config.ts
  libs/btp/navigation/navigation-list-item-component.token.ts
  libs/btp/navigation/navigation-list/navigation-list-item.component.html
  libs/btp/navigation/navigation-list/navigation-list-item.component.ts
  libs/btp/navigation/navigation.component.scss
  libs/btp/navigation/ng-package.json
  libs/btp/navigation/project.json
  libs/btp/navigation/src/index.ts
  libs/btp/navigation/src/test-setup.ts
  libs/btp/navigation/tsconfig.json
  libs/btp/navigation/tsconfig.lib.json
  libs/btp/navigation/tsconfig.spec.json
  libs/btp/ng-package.json
  libs/btp/project.json
  libs/btp/test-setup.ts
  libs/btp/tsconfig.lib.json
  tsconfig.base.json
Labels: quick fix, BTP

#10717 fix(btp): fixed z-index of the home list item when expanded or popup
  libs/btp/navigation/navigation.component.scss
Labels: BTP

#10712 fix(core): some multi-combobox fixes
  libs/core/src/lib/dialog/dialog.component.scss
  libs/core/src/lib/list/list.component.scss
  libs/core/src/lib/multi-combobox/multi-combobox.component.ts
  libs/core/src/lib/token/tokenizer.component.html
Labels: bug

#10731 fix(core,btp): various dh fixes
  libs/btp/navigation/directives/navigation-list-spacer.directive.ts
  libs/btp/navigation/index.ts
  libs/btp/navigation/navigation-component.token.ts
  libs/btp/navigation/navigation-content-end.component.ts
  libs/btp/navigation/navigation-content-start.component.html
  libs/btp/navigation/navigation-content-start.component.ts
  libs/btp/navigation/navigation-list-item-component.token.ts
  libs/btp/navigation/navigation-list/navigation-list-item.component.ts
  libs/btp/navigation/navigation-list/navigation-list-overflow-item.component.html
  libs/btp/navigation/navigation-list/navigation-list-overflow-item.component.ts
  libs/btp/navigation/navigation.component.scss
  libs/btp/navigation/navigation.component.ts
  libs/btp/navigation/navigation.types.ts
  libs/core/src/lib/popover/popover-body/popover-body.component.scss
  libs/core/src/lib/theming/theming.service.ts
  libs/docs/btp/navigation/examples/basic-example/navigation-basic-example.component.html
  libs/docs/btp/navigation/examples/basic-example/navigation-basic-example.component.ts
  libs/docs/btp/navigation/navigation-docs.component.html
Labels: Defect Hunting

#10738 fix(btp): snapped functionality for ungrouped items
  libs/btp/navigation/navigation-content-start.component.ts
  libs/btp/navigation/navigation-link.component.ts
  libs/btp/navigation/navigation-list-component.token.ts
  libs/btp/navigation/navigation-list-item-component.token.ts
  libs/btp/navigation/navigation-list/navigation-list-item.component.html
  libs/btp/navigation/navigation-list/navigation-list-item.component.ts
  libs/btp/navigation/navigation-list/navigation-list.component.ts
  libs/btp/navigation/navigation.component.scss
  libs/btp/navigation/navigation.component.ts
  libs/docs/btp/navigation/examples/basic-example/navigation-basic-example.component.html
Labels: bug, BTP

#10743 fix(platform): approval flow e2e
  libs/docs/platform/approval-flow/e2e/approval-flow.e2e-spec.ts
Labels: e2e

#10742 fix(core,platform): fixed shellbar search outline and hover jumping
  libs/core/src/lib/shellbar/shellbar.component.scss
  libs/platform/src/lib/search-field/search-field.component.scss
  package.json
  yarn.lock
Labels: Defect Hunting

#10740 feat(core): avatar glyph font family
  libs/core/src/lib/avatar/avatar.component.html
  libs/core/src/lib/avatar/avatar.component.ts
Labels: core

#10734 fix(core): time picker hour/minute/seconds being read twice on JAWS
  libs/core/src/lib/time/time-column/time-column.component.html
Labels: ng15

#10744 fix(btp): custom vertical nav home
  libs/btp/navigation/directives/navigation-home.directive.ts
  libs/btp/navigation/navigation-component.token.ts
  libs/btp/navigation/navigation-link.component.ts
  libs/btp/navigation/navigation-list-item-component.token.ts
  libs/btp/navigation/navigation-list/navigation-list-item.component.html
  libs/btp/navigation/navigation-list/navigation-list-item.component.ts
  libs/btp/navigation/navigation-list/navigation-list.component.html
  libs/btp/navigation/navigation.component.scss
  libs/btp/navigation/navigation.component.ts
  libs/docs/btp/navigation/examples/basic-example/navigation-basic-example.component.html
Labels: Horizon 2023

#10745 fix(core): dynamic stacked tabs
  libs/core/src/lib/scroll-spy/scroll-spy.directive.ts
  libs/core/src/lib/tabs/tab-list.component.ts
  libs/docs/core/popover/e2e/popover.e2e-spec.ts
  libs/docs/core/tabs/examples/tab-stacked-content-example/tab-stacked-content-example.component.html
  libs/docs/core/tabs/examples/tab-stacked-content-example/tab-stacked-content-example.component.ts
Labels: bug, core

#10746 fix(core): dynamic stacked tabs
  libs/core/src/lib/scroll-spy/scroll-spy.directive.ts
  libs/core/src/lib/tabs/tab-list.component.ts
  libs/docs/core/tabs/examples/tab-stacked-content-example/tab-stacked-content-example.component.html
  libs/docs/core/tabs/examples/tab-stacked-content-example/tab-stacked-content-example.component.ts
Labels: ng15

#10752 docs: bring fundamental-styles 0.30.2 and theming-base-content 11.7.0
  libs/docs/core/icon/examples/icon-example.component.ts
  libs/docs/core/icon/examples/icon-tnt-example.component.ts
  libs/docs/shared/src/lib/utilities/icons.ts
  package.json
  yarn.lock
Labels: dependencies, theming

#10760 fix(btp): incorrect import of the styling of tool-header
  libs/btp/tool-header/src/components/tool-header/tool-header.component.scss
Labels: High, quick fix, BTP

#10763 fix(e2e): temporary do a full page refresh
  e2e/wdio/driver/wdio.ts
Labels: e2e

#10759 fix(core): multi input new token
  libs/core/src/lib/multi-input/multi-input.component.ts
Labels: bug

#10756 chore(platform): added approval flow missing translations
  libs/i18n/src/lib/models/lang.ts
  libs/i18n/src/lib/translations/translations_bg-BG.json
  libs/i18n/src/lib/translations/translations_cs-CZ.json
  libs/i18n/src/lib/translations/translations_de-DE.json
  libs/i18n/src/lib/translations/translations_en-US.json
  libs/i18n/src/lib/translations/translations_fr-FR.json
  libs/i18n/src/lib/translations/translations_hi-IN.json
  libs/i18n/src/lib/translations/translations_it-IT.json
  libs/i18n/src/lib/translations/translations_ka-GE.json
  libs/i18n/src/lib/translations/translations_pl-PL.json
  libs/i18n/src/lib/translations/translations_pt-BR.json
  libs/i18n/src/lib/translations/translations_ru-RU.json
  libs/i18n/src/lib/translations/translations_sq-AL.json
  libs/i18n/src/lib/translations/translations_tr-TR.json
  libs/i18n/src/lib/translations/translations_uk-UA.json
  libs/i18n/src/lib/translations/translations_zh-CN.json
  libs/platform/src/lib/approval-flow/approval-flow-node/approval-flow-node.component.html
Labels: platform, sourcing, i18n

#10779 fix(core): popover close strategy fix
  libs/core/src/lib/popover/popover-service/popover.service.ts
Labels: bug, core

#10780 fix(docs): illustrated message async data example
  libs/docs/core/illustrated-message/examples/illustrated-message-inline-example.component.html
  libs/docs/core/illustrated-message/examples/illustrated-message-inline-example.component.ts
Labels: bug, documentation

#10766 fix(core): reactive condensed state
  libs/core/src/lib/list/list-navigation-item/list-navigation-item.component.html
  libs/core/src/lib/list/list-navigation-item/list-navigation-item.component.ts
  libs/core/src/lib/vertical-navigation/vertical-navigation.component.ts
  libs/docs/core/vertical-navigation/examples/vertical-navigation-condensed-example.component.html
  libs/docs/core/vertical-navigation/examples/vertical-navigation-condensed-example.component.ts
Labels: bug, core

#10767 fix(core): various carousel fixes
  libs/core/src/lib/carousel/carousel-item/carousel-item.component.html
  libs/core/src/lib/carousel/carousel-item/carousel-item.component.ts
  libs/core/src/lib/carousel/carousel.component.scss
  libs/core/src/lib/carousel/carousel.component.ts
Labels: core, Defect Hunting, quick fix

#10768 fix(core): wizard scroll and focus fixes
  libs/core/src/lib/wizard/wizard.component.spec.ts
  libs/core/src/lib/wizard/wizard.component.ts
Labels: bug

#10788 fix(e2e): core calendar fix
  libs/docs/core/calendar/e2e/calendar.e2e-spec.ts
Labels: bug, e2e

#10748 feat(core): calendar now uses i18n package for translating labels
  libs/core/src/lib/calendar/calendar-directives.ts
  libs/core/src/lib/calendar/calendar-header/calendar-header.component.html
  libs/core/src/lib/calendar/calendar-header/calendar-header.component.ts
  libs/core/src/lib/calendar/calendar-views/calendar-aggregated-year-view/calendar-aggregated-year-view.component.html
  libs/core/src/lib/calendar/calendar-views/calendar-aggregated-year-view/calendar-aggregated-year-view.component.ts
  libs/core/src/lib/calendar/calendar-views/calendar-day-view/calendar-day-view.component.html
  libs/core/src/lib/calendar/calendar-views/calendar-day-view/calendar-day-view.component.ts
  libs/core/src/lib/calendar/calendar-views/calendar-month-view/calendar-month-view.component.html
  libs/core/src/lib/calendar/calendar-views/calendar-month-view/calendar-month-view.component.ts
  libs/core/src/lib/calendar/calendar-views/calendar-year-view/calendar-year-view.component.html
  libs/core/src/lib/calendar/calendar-views/calendar-year-view/calendar-year-view.component.ts
  libs/core/src/lib/calendar/calendar.component.ts
  libs/core/src/lib/calendar/i18n/calendar-i18n-labels.ts
  libs/core/src/lib/calendar/patch-deprecated-i18n-labels.ts
  libs/docs/core/calendar/examples/calendar-i18n-example.component.ts
  libs/docs/core/date-picker/examples/date-picker-i18n-example.component.ts
  libs/docs/platform/date-picker/examples/platform-date-picker-i18n-example.component.ts
  libs/i18n/src/lib/models/lang.ts
  libs/i18n/src/lib/translations/translations_bg-BG.json
  libs/i18n/src/lib/translations/translations_cs-CZ.json
  libs/i18n/src/lib/translations/translations_de-DE.json
  libs/i18n/src/lib/translations/translations_en-US.json
  libs/i18n/src/lib/translations/translations_fr-FR.json
  libs/i18n/src/lib/translations/translations_hi-IN.json
  libs/i18n/src/lib/translations/translations_it-IT.json
  libs/i18n/src/lib/translations/translations_ka-GE.json
  libs/i18n/src/lib/translations/translations_pl-PL.json
  libs/i18n/src/lib/translations/translations_pt-BR.json
  libs/i18n/src/lib/translations/translations_ru-RU.json
  libs/i18n/src/lib/translations/translations_sq-AL.json
  libs/i18n/src/lib/translations/translations_tr-TR.json
  libs/i18n/src/lib/translations/translations_uk-UA.json
  libs/i18n/src/lib/translations/translations_zh-CN.json
Labels: enhancement, code refactoring, core, sourcing, i18n

#10787 fix(core): multi input more button dropdown values
  libs/core/src/lib/multi-input/multi-input.component.html
  libs/core/src/lib/multi-input/multi-input.component.ts
  libs/docs/shared/src/lib/core-helpers/sections-toolbar/sections-toolbar.component.html
  libs/docs/shared/src/lib/core-helpers/sections-toolbar/sections-toolbar.component.ts
Labels: bug, documentation, core

#10791 feat(core): icon component text and background color
  libs/core/src/lib/icon/icon.component.ts
  libs/docs/core/icon/examples/icon-color-example.component.ts
  libs/docs/core/icon/icon-docs.component.html
  libs/docs/core/icon/icon-docs.component.ts
Labels: enhancement, core

#10789 fix(platform): special characters escape
  libs/platform/src/lib/shared/domain/data-source.ts
Labels: bug, platform

#10790 fix(platform): special characters escape
  libs/platform/src/lib/shared/domain/data-source.ts
Labels: bug, platform, ng15

#10785 feat(core,platform): combobox custom templates
  libs/core/src/lib/combobox/combobox-item.directive.ts
  libs/core/src/lib/combobox/combobox.component.html
  libs/core/src/lib/combobox/combobox.component.ts
  libs/core/src/lib/combobox/combobox.interface.ts
  libs/core/src/lib/combobox/combobox.module.ts
  libs/core/src/lib/combobox/index.ts
  libs/docs/core/combobox/combobox-docs.component.html
  libs/docs/core/combobox/examples/combobox-template-example.component.html
  libs/docs/core/combobox/examples/combobox-template-example.component.ts
  libs/docs/platform/combobox/examples/combobox-templates/combobox-templates-example.component.html
  libs/docs/platform/combobox/examples/combobox-templates/combobox-templates-example.component.ts
  libs/platform/src/lib/form/combobox/combobox.module.ts
  libs/platform/src/lib/form/combobox/combobox/combobox.component.html
  libs/platform/src/lib/form/combobox/commons/base-combobox.ts
  libs/platform/src/lib/form/combobox/directives/combobox-item.directive.ts
  libs/platform/src/lib/form/combobox/index.ts
  libs/platform/src/lib/form/index.ts
Labels: enhancement, platform, core

#10754 fix: table cell focus issue
  libs/core/src/lib/table/table.component.scss
  libs/platform/src/lib/table/table.component.scss
Labels: ng15

#10676 fix(core): improved multi-input a11y
  libs/core/src/lib/multi-combobox/index.ts
  libs/core/src/lib/multi-combobox/multi-announcer/multi-announcer.directive.spec.ts
  libs/core/src/lib/multi-combobox/multi-announcer/multi-announcer.directive.ts
  libs/core/src/lib/multi-combobox/multi-combobox.component.html
  libs/core/src/lib/multi-combobox/multi-combobox.component.ts
  libs/core/src/lib/multi-combobox/multi-combobox.module.ts
  libs/core/src/lib/multi-input/multi-input.component.html
  libs/core/src/lib/multi-input/multi-input.component.ts
  libs/i18n/src/lib/models/lang.ts
  libs/i18n/src/lib/translations/translations_bg-BG.json
  libs/i18n/src/lib/translations/translations_cs-CZ.json
  libs/i18n/src/lib/translations/translations_de-DE.json
  libs/i18n/src/lib/translations/translations_en-US.json
  libs/i18n/src/lib/translations/translations_fr-FR.json
  libs/i18n/src/lib/translations/translations_hi-IN.json
  libs/i18n/src/lib/translations/translations_it-IT.json
  libs/i18n/src/lib/translations/translations_ka-GE.json
  libs/i18n/src/lib/translations/translations_pl-PL.json
  libs/i18n/src/lib/translations/translations_pt-BR.json
  libs/i18n/src/lib/translations/translations_ru-RU.json
  libs/i18n/src/lib/translations/translations_sq-AL.json
  libs/i18n/src/lib/translations/translations_tr-TR.json
  libs/i18n/src/lib/translations/translations_uk-UA.json
  libs/i18n/src/lib/translations/translations_zh-CN.json
  libs/platform/src/lib/form/multi-combobox/multi-combobox/multi-combobox.component.html
  libs/platform/src/lib/form/multi-combobox/multi-combobox/multi-combobox.component.ts
  libs/platform/src/lib/form/multi-input/multi-input.component.html
  libs/platform/src/lib/form/multi-input/multi-input.component.ts
Labels: accessibility

#10798 fix(core): rating indicator missing display types
  libs/core/src/lib/rating-indicator/components/rating-indicator.component.html
  libs/core/src/lib/rating-indicator/components/rating-indicator.component.ts
  libs/docs/core/rating-indicator/e2e/rating-indicator.e2e-spec.ts
  libs/docs/core/rating-indicator/examples/ri-dynamic-example.component.html
  libs/docs/core/rating-indicator/examples/ri-dynamic-example.component.ts
  libs/docs/core/rating-indicator/rating-indicator-docs.component.html
  libs/docs/core/rating-indicator/rating-indicator-docs.component.ts
  libs/docs/core/schema/src/index.ts
  libs/docs/core/schema/src/lib/rating-indicator.schema.ts
  libs/docs/core/schema/src/lib/schemas.ts
  package.json
  yarn.lock
Labels: documentation, core

#10749 feat(core): calendar now uses i18n package for translating labels
  libs/core/src/lib/calendar/calendar-directives.ts
  libs/core/src/lib/calendar/calendar-header/calendar-header.component.html
  libs/core/src/lib/calendar/calendar-header/calendar-header.component.spec.ts
  libs/core/src/lib/calendar/calendar-header/calendar-header.component.ts
  libs/core/src/lib/calendar/calendar-views/calendar-aggregated-year-view/calendar-aggregated-year-view.component.html
  libs/core/src/lib/calendar/calendar-views/calendar-aggregated-year-view/calendar-aggregated-year-view.component.spec.ts
  libs/core/src/lib/calendar/calendar-views/calendar-aggregated-year-view/calendar-aggregated-year-view.component.ts
  libs/core/src/lib/calendar/calendar-views/calendar-day-view/calendar-day-view.component.html
  libs/core/src/lib/calendar/calendar-views/calendar-day-view/calendar-day-view.component.spec.ts
  libs/core/src/lib/calendar/calendar-views/calendar-day-view/calendar-day-view.component.ts
  libs/core/src/lib/calendar/calendar-views/calendar-month-view/calendar-month-view.component.html
  libs/core/src/lib/calendar/calendar-views/calendar-month-view/calendar-month-view.component.spec.ts
  libs/core/src/lib/calendar/calendar-views/calendar-month-view/calendar-month-view.component.ts
  libs/core/src/lib/calendar/calendar-views/calendar-year-view/calendar-year-view.component.html
  libs/core/src/lib/calendar/calendar-views/calendar-year-view/calendar-year-view.component.spec.ts
  libs/core/src/lib/calendar/calendar-views/calendar-year-view/calendar-year-view.component.ts
  libs/core/src/lib/calendar/calendar.component.ts
  libs/core/src/lib/calendar/calendar.module.ts
  libs/core/src/lib/calendar/i18n/calendar-i18n-labels.ts
  libs/core/src/lib/calendar/patch-deprecated-i18n-labels.ts
  libs/docs/core/calendar/examples/calendar-i18n-example.component.ts
  libs/docs/core/date-picker/examples/date-picker-i18n-example.component.ts
  libs/docs/platform/date-picker/examples/platform-date-picker-i18n-example.component.ts
  libs/i18n/src/lib/languages/albanian.ts
  libs/i18n/src/lib/languages/bulgarian.ts
  libs/i18n/src/lib/languages/chinese.ts
  libs/i18n/src/lib/languages/czech.ts
  libs/i18n/src/lib/languages/english.ts
  libs/i18n/src/lib/languages/french.ts
  libs/i18n/src/lib/languages/georgian.ts
  libs/i18n/src/lib/languages/german.ts
  libs/i18n/src/lib/languages/hindi.ts
  libs/i18n/src/lib/languages/italian.ts
  libs/i18n/src/lib/languages/polish.ts
  libs/i18n/src/lib/languages/portuguese.ts
  libs/i18n/src/lib/languages/russian.ts
  libs/i18n/src/lib/languages/turkish.ts
  libs/i18n/src/lib/languages/ukrainian.ts
  libs/i18n/src/lib/models/lang.ts
Labels: enhancement, core, sourcing, i18n, ng15

#10804 chore(deps): update to fundamental-styles 0.31 and change common-css …
  libs/core/src/lib/avatar-group/avatar-group.component.scss
  libs/core/src/lib/multi-combobox/select-all-toggler/select-all-toggler.component.scss
  package.json
  yarn.lock
Labels: tooling, dependencies

#10808 fix(core): busy indicator overlay z-index
  libs/core/src/lib/busy-indicator/busy-indicator.component.scss
Labels: bug, core

#10538 fix(core): swap icon files along the theme switch
  apps/docs/src/theming/sap_fiori_3_fonts.css
  apps/docs/src/theming/sap_horizon_fonts.css
  libs/docs/shared/src/lib/core-helpers/stackblitz/code-example-stack/theming/sap_fiori_3_fonts.css
  libs/docs/shared/src/lib/core-helpers/stackblitz/code-example-stack/theming/sap_horizon_fonts.css
Labels: documentation

#10845 fix: add 72-SemiboldDuplex font
  apps/docs/src/styles.scss
  libs/cx/schematics/ng-add/styles.ts
  libs/docs/shared/src/lib/core-helpers/stackblitz/code-example-stack/styles.scss
Labels: tooling, theming

#10833 fix(core): link icon position
  libs/core/src/lib/link/link.component.html
  libs/core/src/lib/link/link.component.scss
  libs/docs/core/calendar/e2e/calendar.e2e-spec.ts
  libs/docs/core/link/e2e/link.e2e-spec.ts
  libs/docs/core/link/examples/link-example.component.html
Labels: bug, core

#10850 fix(core): multi input close dropdown when item selected
  apps/docs/src/styles.scss
  libs/core/src/lib/multi-input/multi-input.component.html
  libs/core/src/lib/multi-input/multi-input.component.ts
  libs/docs/shared/src/lib/core-helpers/stackblitz/code-example-stack/styles.scss
Labels: bug

#10851 fix(core): close dropdown item when keyboard is used
  libs/core/src/lib/multi-input/multi-input.component.html
  libs/core/src/lib/multi-input/multi-input.component.ts
  libs/docs/core/calendar/e2e/calendar.e2e-spec.ts
Labels: bug, ng15
