Repository SAP/fundamental-ngx, pull requests merged in 2023-11, with the labels that each got.

#10855 feat(core): dialog typechecks
  libs/core/src/lib/combobox/combobox-mobile/combobox-mobile.component.html
  libs/core/src/lib/date-picker/date-picker-mobile/date-picker-mobile.component.html
  libs/core/src/lib/datetime-picker/datetime-picker-mobile/datetime-picker-mobile.component.html
  libs/core/src/lib/dialog/dialog-container/dialog-container.component.ts
  libs/core/src/lib/dialog/dialog.module.ts
  libs/core/src/lib/dialog/directives/dialog-template.directive.ts
  libs/core/src/lib/dialog/index.ts
  libs/core/src/lib/dialog/utils/dialog-config.class.ts
  libs/core/src/lib/menu/menu-mobile/menu-mobile.component.html
  libs/core/src/lib/message-box/directives/message-box-template.directive.ts
  libs/core/src/lib/message-box/index.ts
  libs/core/src/lib/message-box/message-box.module.ts
  libs/core/src/lib/message-box/services/message-box.service.spec.ts
  libs/core/src/lib/message-toast/message-toast.service.spec.ts
  libs/core/src/lib/multi-combobox/mobile/mobile-multi-combobox.component.html
  libs/core/src/lib/multi-input/multi-input-mobile/multi-input-mobile.component.html
  libs/core/src/lib/popover/popover-mobile/popover-mobile.component.html
  libs/core/src/lib/select/select-mobile/select-mobile.component.html
  libs/docs/core/calendar/examples/calendar-mobile-example/calendar-mobile-example.component.html
  libs/docs/core/dialog/dialog-docs.component.html
  libs/docs/core/dialog/dialog-docs.component.ts
  libs/docs/core/dialog/examples/auto-label/auto-label-dialog-example.component.html
  libs/docs/core/dialog/examples/dialog-backdrop-container/dialog-backdrop-container-example.component.html
  libs/docs/core/dialog/examples/dialog-complex/dialog-complex-example.component.html
  libs/docs/core/dialog/examples/dialog-configuration/dialog-configuration-example.component.html
  libs/docs/core/dialog/examples/dialog-form/form-dialog-example.component.html
  libs/docs/core/dialog/examples/dialog-full-screen/dialog-full-screen-example.component.html
  libs/docs/core/dialog/examples/dialog-mobile/dialog-mobile-example.component.html
  libs/docs/core/dialog/examples/dialog-position/dialog-position-example.component.html
  libs/docs/core/dialog/examples/dialog-state/dialog-state-example.component.html
  libs/docs/core/dialog/examples/template-based/template-based-dialog-example.component.html
  libs/docs/core/fixed-card-layout/examples/mobile/fixed-card-layout-mobile-examples.component.html
  libs/docs/core/illustrated-message/examples/illustrated-message-dialog-example.component.html
  libs/docs/core/message-box/examples/template-based/template-based-message-box-example.component.html
  libs/docs/core/message-toast/examples/message-toast-example.component.html
  libs/docs/core/popover/examples/popover-dialog/popover-dialog-example.component.html
  libs/docs/core/quick-view/examples/quick-view-dialog-example.component.html
  libs/docs/core/table/examples/table-toolbar-example.component.html
  libs/docs/core/upload-collection/examples/upload-collection-complex-example.component.html
  libs/docs/core/wizard/examples/wizard-branching-example.component.html
  libs/docs/core/wizard/examples/wizard-dialog-example.component.html
  libs/docs/core/wizard/examples/wizard-visible-summary-example.component.html
  libs/docs/platform/settings-generator/examples/dialog/settings-generator-dialog-example.component.html
  libs/docs/platform/wizard-generator/examples/wizard-generator-customizable-example.component.html
  libs/platform/src/lib/form/combobox/combobox-mobile/combobox/combobox-mobile.component.html
  libs/platform/src/lib/form/multi-combobox/multi-combobox-mobile/multi-combobox/multi-combobox-mobile.component.html
  libs/platform/src/lib/form/multi-input/multi-input-mobile/multi-input-mobile.component.html
  libs/platform/src/lib/search-field/search-field-mobile/search-field/search-field-mobile.component.html
  libs/platform/src/lib/value-help-dialog/value-help-dialog/value-help-dialog.component.html
  libs/platform/src/lib/wizard-generator/components/dialog-wizard-generator/dialog-wizard-generator.component.html
Labels: enhancement, core

#10859 fix(platform): remove selected duplicates
  libs/platform/src/lib/form/multi-combobox/commons/base-multi-combobox.ts
  libs/platform/src/lib/form/multi-combobox/multi-combobox/multi-combobox.component.spec.ts
Labels: ng15

#10862 fix(core): disable autocomplete if includes enabled
  libs/core/src/lib/multi-input/multi-input.component.html
  libs/docs/platform/multi-input/platform-multi-input-docs.component.html
Labels: core

#10863 fix(core): disable autocomplete if includes enabled
  libs/core/src/lib/multi-input/multi-input.component.html
  libs/docs/platform/multi-input/platform-multi-input-docs.component.html
Labels: ng15

#10861 fix(core): token position in set
  libs/core/src/lib/token/token.component.html
  libs/core/src/lib/token/token.component.ts
  libs/core/src/lib/token/tokenizer.component.ts
Labels: bug, accessibility, core, ng15

#10860 fix(core): token position in set
  libs/core/src/lib/token/token.component.html
  libs/core/src/lib/token/token.component.ts
  libs/core/src/lib/token/tokenizer.component.ts
Labels: bug, accessibility, core

#10867 chore(ci): fixed long-standing problem of the volta action
  .github/workflows/create-release.yml
  .github/workflows/on-pull-request.yml
  .github/workflows/on-schedule.yml
Labels: nice to have, quick fix

#10864 fix(core,platform): multi combobox blur behaviour
  libs/core/src/lib/multi-combobox/multi-combobox.component.spec.ts
  libs/core/src/lib/multi-combobox/multi-combobox.component.ts
  libs/platform/src/lib/form/multi-combobox/multi-combobox-cva.spec.ts
  libs/platform/src/lib/form/multi-combobox/multi-combobox/multi-combobox.component.html
  libs/platform/src/lib/form/multi-combobox/multi-combobox/multi-combobox.component.spec.ts
  libs/platform/src/lib/form/multi-combobox/multi-combobox/multi-combobox.component.ts
Labels: bug, accessibility, platform, core

#10865 fix(core,platform): multi combobox blur behaviour
  libs/core/src/lib/multi-combobox/multi-combobox.component.spec.ts
  libs/core/src/lib/multi-combobox/multi-combobox.component.ts
  libs/core/src/lib/token/token.component.ts
  libs/core/src/lib/token/tokenizer.component.ts
  libs/platform/src/lib/form/multi-combobox/multi-combobox-cva.spec.ts
  libs/platform/src/lib/form/multi-combobox/multi-combobox/multi-combobox.component.html
  libs/platform/src/lib/form/multi-combobox/multi-combobox/multi-combobox.component.spec.ts
  libs/platform/src/lib/form/multi-combobox/multi-combobox/multi-combobox.component.ts
Labels: ng15

#10728 feat(core,btp): updated button with new features from styles
  libs/btp/button/button-type-guard.ts
  libs/btp/button/index.ts
  libs/btp/button/nested-button.directive.ts
  libs/btp/button/ng-package.json
  libs/btp/button/project.json
  libs/btp/button/tool-header-button.directive.ts
  libs/btp/navigation/navigation-list/navigation-list-item.component.html
  libs/btp/navigation/navigation-list/navigation-list-item.component.ts
  libs/btp/search-field/src/search-field.component.html
  libs/btp/search-field/src/search-field.component.ts
  libs/btp/tool-header/src/components/tool-header-product-switch.component.ts
  libs/btp/tool-header/src/components/tool-header/tool-header.component.ts
  libs/btp/tool-header/src/directives/tool-header-button.directive.ts
  libs/btp/tool-header/src/index.ts
  libs/core/src/lib/button/button-badge.directive.ts
  libs/core/src/lib/button/button.component.html
  libs/core/src/lib/button/index.ts
  libs/core/src/lib/segmented-button/segmented-button.component.ts
  libs/docs/btp/api-files.ts
  libs/docs/btp/button/button-docs.component.html
  libs/docs/btp/button/button-docs.component.ts
  libs/docs/btp/button/button-header/button-header.component.html
  libs/docs/btp/button/button-header/button-header.component.ts
  libs/docs/btp/button/examples/nested-example.component.ts
  libs/docs/btp/button/examples/tool-header-example.component.ts
  libs/docs/btp/button/index.ts
  libs/docs/btp/button/project.json
  libs/docs/btp/button/tsconfig.json
  libs/docs/btp/docs-data.ts
  libs/docs/btp/docs-routes.ts
  libs/docs/btp/search-field/search-field-docs.component.ts
  libs/docs/btp/tool-header/examples/basic-example/tool-header-basic-example.component.html
  libs/docs/btp/tool-header/examples/basic-example/tool-header-basic-example.component.ts
  libs/docs/btp/tool-header/examples/custom-logo-example/custom-logo-example.component.ts
  libs/docs/core/button/button-docs.component.html
  libs/docs/core/button/button-docs.component.ts
  libs/docs/core/button/examples/button-badge-example.component.ts
  libs/docs/core/segmented-button/examples/segmented-button-default-example.component.html
  package.json
  tsconfig.base.json
  yarn.lock
Labels: Horizon 2023, BTP

#10853 fix(core,platform): inputs with dropdowns ignore tab key
  libs/core/src/lib/combobox/combobox.component.html
  libs/core/src/lib/combobox/combobox.component.ts
  libs/core/src/lib/multi-combobox/multi-combobox.component.html
  libs/core/src/lib/multi-combobox/multi-combobox.component.ts
  libs/core/src/lib/multi-input/multi-input.component.html
  libs/core/src/lib/multi-input/multi-input.component.ts
  libs/core/src/lib/token/token.component.ts
  libs/platform/src/lib/form/combobox/combobox/combobox.component.html
  libs/platform/src/lib/form/combobox/combobox/combobox.component.ts
  libs/platform/src/lib/form/combobox/commons/base-combobox.ts
  libs/platform/src/lib/form/multi-combobox/multi-combobox/multi-combobox.component.html
  libs/platform/src/lib/form/multi-combobox/multi-combobox/multi-combobox.component.ts
  libs/platform/src/lib/form/multi-input/base-multi-input.ts
  libs/platform/src/lib/form/multi-input/multi-input.component.html
  libs/platform/src/lib/list/list.component.ts
Labels: ng15

#10877 fix(i18n): comments 116-248
  libs/i18n/src/lib/translations/translations_en-US.properties
Labels: i18n

#10879 fix(i18n): denis comments part 2
  libs/i18n/src/lib/translations/translations_en-US.properties
Labels: i18n

#10880 fix(i18n): added comments on the translations properties
  libs/i18n/src/lib/models/lang.ts
  libs/i18n/src/lib/translations/translations_bg-BG.json
  libs/i18n/src/lib/translations/translations_bg-BG.properties
  libs/i18n/src/lib/translations/translations_cs-CZ.json
  libs/i18n/src/lib/translations/translations_cs-CZ.properties
  libs/i18n/src/lib/translations/translations_de-DE.json
  libs/i18n/src/lib/translations/translations_de-DE.properties
  libs/i18n/src/lib/translations/translations_en-US.json
  libs/i18n/src/lib/translations/translations_en-US.properties
  libs/i18n/src/lib/translations/translations_fr-FR.json
  libs/i18n/src/lib/translations/translations_fr-FR.properties
  libs/i18n/src/lib/translations/translations_hi-IN.json
  libs/i18n/src/lib/translations/translations_hi-IN.properties
  libs/i18n/src/lib/translations/translations_it-IT.json
  libs/i18n/src/lib/translations/translations_it-IT.properties
  libs/i18n/src/lib/translations/translations_ka-GE.json
  libs/i18n/src/lib/translations/translations_ka-GE.properties
  libs/i18n/src/lib/translations/translations_pl-PL.json
  libs/i18n/src/lib/translations/translations_pl-PL.properties
  libs/i18n/src/lib/translations/translations_pt-BR.json
  libs/i18n/src/lib/translations/translations_pt-BR.properties
  libs/i18n/src/lib/translations/translations_ru-RU.json
  libs/i18n/src/lib/translations/translations_ru-RU.properties
  libs/i18n/src/lib/translations/translations_sq-AL.json
  libs/i18n/src/lib/translations/translations_sq-AL.properties
  libs/i18n/src/lib/translations/translations_tr-TR.json
  libs/i18n/src/lib/translations/translations_tr-TR.properties
  libs/i18n/src/lib/translations/translations_uk-UA.json
  libs/i18n/src/lib/translations/translations_uk-UA.properties
  libs/i18n/src/lib/translations/translations_zh-CN.json
  libs/i18n/src/lib/translations/translations_zh-CN.properties
  libs/platform/src/lib/table/components/table-p13-dialog/filtering/filtering.component.html
Labels: i18n

#10884 fix(i18n): add comments for translations lines 249 through 323
  libs/i18n/src/lib/translations/translations_en-US.properties
Labels: i18n

#10881 fix(platform): keyboard improvements for search field
  libs/platform/src/lib/search-field/search-field.component.html
Labels: ng15

#10909 fix(core,platform): add aria-label for multi combobox
  libs/core/src/lib/multi-combobox/multi-combobox.component.html
  libs/i18n/src/lib/languages/albanian.ts
  libs/i18n/src/lib/languages/bulgarian.ts
  libs/i18n/src/lib/languages/chinese.ts
  libs/i18n/src/lib/languages/czech.ts
  libs/i18n/src/lib/languages/english.ts
  libs/i18n/src/lib/languages/french.ts
  libs/i18n/src/lib/languages/georgian.ts
  libs/i18n/src/lib/languages/german.ts
  libs/i18n/src/lib/languages/hindi.ts
  libs/i18n/src/lib/languages/italian.ts
  libs/i18n/src/lib/languages/polish.ts
  libs/i18n/src/lib/languages/portuguese.ts
  libs/i18n/src/lib/languages/russian.ts
  libs/i18n/src/lib/languages/turkish.ts
  libs/i18n/src/lib/languages/ukrainian.ts
  libs/i18n/src/lib/models/lang.ts
  libs/platform/src/lib/form/multi-combobox/multi-combobox/multi-combobox.component.html
Labels: ng15

#10908 fix(platform): remove title tooltip from table checkbox
  libs/i18n/src/lib/languages/albanian.ts
  libs/i18n/src/lib/languages/bulgarian.ts
  libs/i18n/src/lib/languages/chinese.ts
  libs/i18n/src/lib/languages/czech.ts
  libs/i18n/src/lib/languages/english.ts
  libs/i18n/src/lib/languages/french.ts
  libs/i18n/src/lib/languages/georgian.ts
  libs/i18n/src/lib/languages/german.ts
  libs/i18n/src/lib/languages/hindi.ts
  libs/i18n/src/lib/languages/italian.ts
  libs/i18n/src/lib/languages/polish.ts
  libs/i18n/src/lib/languages/portuguese.ts
  libs/i18n/src/lib/languages/russian.ts
  libs/i18n/src/lib/languages/turkish.ts
  libs/i18n/src/lib/languages/ukrainian.ts
  libs/i18n/src/lib/models/lang.ts
  libs/platform/src/lib/table/components/table-row/table-row.component.html
Labels: ng15

#10904 fix(btp): tool header styles discrepancy and updated overflows
  apps/docs/src/app.config.ts
  libs/btp/navigation-menu/src/lib/navigation-menu-item.component.ts
  libs/btp/navigation-menu/src/lib/navigation-menu-popover.component.scss
  libs/btp/navigation-menu/src/lib/navigation-menu-popover.component.ts
  libs/btp/navigation-menu/src/lib/navigation-menu.component.ts
  libs/btp/tool-header/src/components/tool-header-action-separator.component.ts
  libs/btp/tool-header/src/components/tool-header/tool-header.component.html
  libs/btp/tool-header/src/components/tool-header/tool-header.component.scss
  libs/btp/tool-header/src/components/tool-header/tool-header.component.ts
  libs/btp/tool-header/src/directives/tool-header-action-button.directive.ts
  libs/btp/tool-header/src/directives/tool-header-action.directive.ts
  libs/btp/tool-header/src/directives/tool-header-actions.directive.ts
  libs/btp/tool-header/src/directives/tool-header-auto-mode.directive.ts
  libs/btp/tool-header/src/directives/tool-header-group.directive.ts
  libs/btp/tool-header/src/index.ts
  libs/btp/tool-header/src/tool-header-action.class.ts
  libs/btp/tool-header/src/tool-header-component.class.ts
  libs/cdk/src/lib/utils/datatypes/can-be-observable.type.ts
  libs/cdk/src/lib/utils/directives/clicked/clicked-behavior.module.ts
  libs/cdk/src/lib/utils/directives/clicked/clicked-event.plugin.ts
  libs/cdk/src/lib/utils/directives/clicked/clicked.directive.ts
  libs/cdk/src/lib/utils/directives/clicked/provide-fdk-clicked.ts
  libs/cdk/src/lib/utils/directives/focusable-item/get-item-element.ts
  libs/cdk/src/lib/utils/directives/focusable-item/index.ts
  libs/cdk/src/lib/utils/directives/focusable-item/indirect-focusable-item.directive.ts
  libs/cdk/src/lib/utils/directives/focusable-list/focusable-list.directive.ts
  libs/cdk/src/lib/utils/directives/focusable-list/index.ts
  libs/cdk/src/lib/utils/directives/focusable-list/indirect-focusable-list.directive.ts
  libs/cdk/src/lib/utils/utils.module.ts
  libs/core/src/lib/overflow-layout/overflow-layout.component.html
  libs/core/src/lib/overflow-layout/overflow-layout.component.ts
  libs/core/src/lib/overflow-layout/overflow-layout.service.ts
  libs/core/src/lib/tree/components/tree-item/tree-item.component.spec.ts
  libs/core/src/lib/tree/components/tree-item/tree-item.component.ts
  libs/core/src/lib/tree/tree.component.spec.ts
  libs/docs/btp/api-files.ts
  libs/docs/btp/tool-header/examples/auto-mode-example/auto-mode-example.component.html
  libs/docs/btp/tool-header/examples/auto-mode-example/auto-mode-example.component.ts
  libs/docs/btp/tool-header/examples/basic-example/tool-header-basic-example.component.html
  libs/docs/btp/tool-header/examples/basic-example/tool-header-basic-example.component.ts
  libs/docs/btp/tool-header/examples/custom-logo-example/custom-logo-example.component.ts
  libs/docs/btp/tool-header/examples/menu-button-example/menu-button-example.component.ts
  libs/docs/btp/tool-header/examples/usage-with-layout-example/usage-with-layout-example.component.html
  libs/docs/btp/tool-header/examples/usage-with-layout-example/usage-with-layout-example.component.ts
  libs/docs/cdk/clicked/examples/basic-example/basic-example.component.ts
  libs/docs/cdk/disabled/examples/di-example/di-example.component.ts
  libs/platform/src/lib/settings-generator/controls/theme-selector-list/theme-selector-list.component.ts
  libs/platform/src/lib/settings-generator/settings-generator.module.ts
Labels: core, BTP

#10914 fix(core): multi input addon aria hidden
  libs/core/src/lib/input-group/input-group.component.html
  libs/core/src/lib/input-group/input-group.component.ts
  libs/core/src/lib/multi-input/multi-input.component.html
Labels: enhancement, accessibility, core, ariba, sourcing, quick fix

#10915 fix(core): multi input addon aria hidden
  libs/core/src/lib/input-group/input-group.component.html
  libs/core/src/lib/input-group/input-group.component.ts
  libs/core/src/lib/multi-input/multi-input.component.html
Labels: enhancement, accessibility, core, ariba, sourcing, quick fix, ng15

#10916 fix(platform): aria-labelledby for select
  libs/docs/platform/vhd/e2e/vhd.po.ts
  libs/platform/src/lib/form/select/select/select.component.html
  libs/platform/src/lib/shared/form/base.input.ts
Labels: bug, accessibility

#10920 fix(platform): aria sort attribute
  libs/platform/src/lib/table-helpers/pipes/column-sorting-direction.pipe.spec.ts
  libs/platform/src/lib/table-helpers/pipes/column-sorting-direction.pipe.ts
  libs/platform/src/lib/table-helpers/pipes/index.ts
  libs/platform/src/lib/table/components/table-header-cell-content/table-header-cell-content.component.html
  libs/platform/src/lib/table/components/table-header-row/table-header-row.component.html
  libs/platform/src/lib/table/components/table-header-row/table-header-row.component.ts
Labels: accessibility

#10918 fix(platform): aria-labelledby for select
  libs/platform/src/lib/form/select/select/select.component.html
  libs/platform/src/lib/shared/form/base.input.ts
Labels: ng15

#10922 fix(platform): aria sort attribute
  .gitignore
  libs/platform/src/lib/table-helpers/pipes/column-sorting-direction.pipe.spec.ts
  libs/platform/src/lib/table-helpers/pipes/column-sorting-direction.pipe.ts
  libs/platform/src/lib/table-helpers/pipes/index.ts
  libs/platform/src/lib/table-helpers/table-helpers.module.ts
  libs/platform/src/lib/table/components/table-header-cell-content/table-header-cell-content.component.html
  libs/platform/src/lib/table/components/table-header-row/table-header-row.component.html
  libs/platform/src/lib/table/components/table-header-row/table-header-row.component.ts
Labels: ng15

#10913 fix(core): select aria attributes
  libs/core/src/lib/select/select.component.html
Labels: accessibility, core

#10925 fix(core,platform): multi announcer improvements
  libs/core/src/lib/multi-combobox/multi-announcer/multi-announcer.directive.ts
  libs/core/src/lib/multi-combobox/multi-combobox.component.html
  libs/core/src/lib/multi-input/multi-input.component.html
  libs/platform/src/lib/form/multi-combobox/multi-combobox/multi-combobox.component.html
  libs/platform/src/lib/form/multi-input/multi-input.component.html
Labels: bug

#10927 fix(core): tokenizer listbox label
  libs/core/src/lib/token/tokenizer.component.html
Labels: accessibility, core

#10937 fix(core): tokenizer listbox label
  libs/core/src/lib/token/tokenizer.component.html
Labels: ng15

#10936 fix(i18n): fixed increased bundle size because of the json formats
  .github/workflows/create-release.yml
  .github/workflows/on-pull-request.yml
  libs/i18n/project.json
  libs/i18n/src/lib/languages/albanian.ts
  libs/i18n/src/lib/languages/bulgarian.ts
  libs/i18n/src/lib/languages/chinese.ts
  libs/i18n/src/lib/languages/czech.ts
  libs/i18n/src/lib/languages/english.ts
  libs/i18n/src/lib/languages/french.ts
  libs/i18n/src/lib/languages/georgian.ts
  libs/i18n/src/lib/languages/german.ts
  libs/i18n/src/lib/languages/hindi.ts
  libs/i18n/src/lib/languages/italian.ts
  libs/i18n/src/lib/languages/polish.ts
  libs/i18n/src/lib/languages/portuguese.ts
  libs/i18n/src/lib/languages/russian.ts
  libs/i18n/src/lib/languages/turkish.ts
  libs/i18n/src/lib/languages/ukrainian.ts
  libs/i18n/src/lib/translations/translations_bg-BG.json
  libs/i18n/src/lib/translations/translations_bg-BG.ts
  libs/i18n/src/lib/translations/translations_cs-CZ.json
  libs/i18n/src/lib/translations/translations_cs-CZ.ts
  libs/i18n/src/lib/translations/translations_de-DE.json
  libs/i18n/src/lib/translations/translations_de-DE.ts
  libs/i18n/src/lib/translations/translations_en-US.json
  libs/i18n/src/lib/translations/translations_en-US.ts
  libs/i18n/src/lib/translations/translations_fr-FR.json
  libs/i18n/src/lib/translations/translations_fr-FR.ts
  libs/i18n/src/lib/translations/translations_hi-IN.json
  libs/i18n/src/lib/translations/translations_hi-IN.ts
  libs/i18n/src/lib/translations/translations_it-IT.json
  libs/i18n/src/lib/translations/translations_it-IT.ts
  libs/i18n/src/lib/translations/translations_ka-GE.json
  libs/i18n/src/lib/translations/translations_ka-GE.ts
  libs/i18n/src/lib/translations/translations_pl-PL.json
  libs/i18n/src/lib/translations/translations_pl-PL.ts
  libs/i18n/src/lib/translations/translations_pt-BR.json
  libs/i18n/src/lib/translations/translations_pt-BR.ts
  libs/i18n/src/lib/translations/translations_ru-RU.json
  libs/i18n/src/lib/translations/translations_ru-RU.ts
  libs/i18n/src/lib/translations/translations_sq-AL.json
  libs/i18n/src/lib/translations/translations_sq-AL.ts
  libs/i18n/src/lib/translations/translations_tr-TR.json
  libs/i18n/src/lib/translations/translations_tr-TR.ts
  libs/i18n/src/lib/translations/translations_uk-UA.json
  libs/i18n/src/lib/translations/translations_uk-UA.ts
  libs/i18n/src/lib/translations/translations_zh-CN.json
  libs/i18n/src/lib/translations/translations_zh-CN.ts
  libs/nx-plugin/src/executors/transform-translations/executor.ts
Labels: i18n

#10926 fix(core): select aria attributes
  libs/core/src/lib/select/select.component.html
Labels: ng15

#10952 fix(core): fixed group item selections and deselections
  libs/core/src/lib/multi-combobox/multi-combobox.component.ts
Labels: core, quick fix

#10951 fix(core): downport of 10715 (remove link role from list item)
  libs/core/src/lib/list/list-item/list-item.component.ts
Labels: bug

#10955 chore(docs): added missing languages on prod build
  apps/docs/src/environments/translations.prod.ts
Labels: documentation, i18n

#10963 feat: updated styles and adopted changes
  apps/docs/src/environments/translations.ts
  libs/cdk/src/lib/utils/directives/focusable-list/indirect-focusable-list.directive.ts
  libs/core/src/lib/switch/switch.component.html
  libs/docs/core/icon/examples/icon-tnt-example.component.ts
  package.json
  yarn.lock
Labels: dependencies

#10973 fix(platform): move initial focus to search input on p13
  libs/platform/src/lib/table/components/table-p13-dialog/columns/columns.component.html
Labels: ng15

#10970 chore(docs): added search page of the icons
  libs/cdk/src/lib/utils/pipes/search-highlight.pipe.ts
  libs/docs/core/icon/icon-header/icon-header.component.html
  libs/docs/core/icon/icon-header/icon-header.component.ts
  libs/docs/core/icon/index.ts
  libs/docs/core/icon/search-icons/available-sap-icons.ts
  libs/docs/core/icon/search-icons/search-icons.component.html
  libs/docs/core/icon/search-icons/search-icons.component.ts
  libs/docs/shared/src/lib/core-helpers/header-tabs/header-tabs.component.html
  libs/docs/shared/src/lib/core-helpers/header-tabs/header-tabs.component.ts
  libs/platform/src/lib/table-helpers/directives/table-cell.directive.ts
  package.json
  yarn.lock
Labels: enhancement, documentation, nice to have

#10924 fix(core,platform): multi announcer improvements
  libs/cdk/src/lib/utils/directives/index.ts
  libs/core/src/lib/multi-combobox/index.ts
  libs/core/src/lib/multi-combobox/multi-announcer/multi-announcer.directive.ts
  libs/core/src/lib/multi-combobox/multi-combobox.component.html
  libs/core/src/lib/multi-combobox/multi-combobox.module.ts
  libs/core/src/lib/multi-input/multi-input.component.html
  libs/core/src/lib/multi-input/multi-input.module.ts
  libs/platform/src/lib/form/multi-combobox/multi-combobox.module.ts
  libs/platform/src/lib/form/multi-combobox/multi-combobox/multi-combobox.component.html
  libs/platform/src/lib/form/multi-input/multi-input.component.html
  libs/platform/src/lib/form/multi-input/multi-input.module.ts
Labels: ng15

#10976 fix(core): fixed switch default off icon
  libs/core/src/lib/switch/switch.component.html
Labels: core, design-discrepancy

#10917 fix(core): fd-shellbar user menu showing dot for customized user menu…
  libs/core/src/lib/shellbar/user-menu/shellbar-user-menu.component.html
Labels: ng15

#10928 feat(core,platform): dropdown control tabout strategy
  libs/cdk/src/lib/forms/index.ts
  libs/cdk/src/lib/forms/models/control-type.model.ts
  libs/core/src/lib/combobox/combobox.component.html
  libs/core/src/lib/combobox/combobox.component.ts
  libs/core/src/lib/list/list-focus-item.model.ts
  libs/core/src/lib/list/list-item/list-item.component.ts
  libs/core/src/lib/list/list.component.ts
  libs/core/src/lib/select/select-key-manager.service.ts
  libs/core/src/lib/select/select.component.ts
  libs/core/src/lib/select/select.interface.ts
  libs/platform/src/lib/form/combobox/combobox/combobox.component.html
  libs/platform/src/lib/form/combobox/commons/base-combobox.ts
  libs/platform/src/lib/form/form-generator/controls/dynamic-form-generator-select/dynamic-form-generator-select.component.ts
  libs/platform/src/lib/form/index.ts
  libs/platform/src/lib/form/select/commons/base-select.ts
  libs/platform/src/lib/form/select/index.ts
  libs/platform/src/lib/form/select/option/option.component.ts
  libs/platform/src/lib/form/select/select.module.ts
  libs/platform/src/lib/form/select/select/select.component.html
Labels: accessibility, platform, core

#10966 fix(platform): add cellFocused event and focusCell method to platform table
  libs/docs/platform/table/examples/preserved-state/platform-table-preserved-state-example.component.html
  libs/docs/platform/table/examples/preserved-state/platform-table-preserved-state-example.component.ts
  libs/platform/src/lib/table/table.component.ts
Labels: ng15

#10965 fix(platform): add cellFocused event and focusCell method to platform table
  libs/docs/platform/table/examples/preserved-state/platform-table-preserved-state-example.component.html
  libs/docs/platform/table/examples/preserved-state/platform-table-preserved-state-example.component.ts
  libs/platform/src/lib/table/table.component.ts
Labels: enhancement

#10991 feat(core,platform): dropdown control tabout strategy
  libs/cdk/src/lib/forms/index.ts
  libs/cdk/src/lib/forms/models/control-type.model.ts
  libs/core/src/lib/combobox/combobox.component.html
  libs/core/src/lib/combobox/combobox.component.ts
  libs/core/src/lib/list/list-focus-item.model.ts
  libs/core/src/lib/list/list-item/list-item.component.ts
  libs/core/src/lib/list/list.component.ts
  libs/core/src/lib/select/select-key-manager.service.ts
  libs/core/src/lib/select/select.component.ts
  libs/core/src/lib/select/select.interface.ts
  libs/platform/src/lib/form/combobox/combobox/combobox.component.html
  libs/platform/src/lib/form/combobox/commons/base-combobox.ts
  libs/platform/src/lib/form/select/commons/base-select.ts
  libs/platform/src/lib/form/select/index.ts
  libs/platform/src/lib/form/select/select/select.component.html
Labels: ng15

#10930 fix(platform): list accessibility issues
  libs/core/src/lib/list/list-item/list-item.component.ts
  libs/docs/platform/list/examples/platform-list-with-group-header-example.component.html
  libs/docs/platform/list/examples/platform-list-with-infinite-scroll-example.component.ts
  libs/docs/platform/list/examples/platform-list-with-more-button-example.component.ts
  libs/docs/platform/list/examples/platform-list-with-selection-example.component.html
  libs/docs/platform/list/examples/platform-list-with-single-selection-example.component.html
  libs/platform/src/lib/list/action-list-item/action-list-item.component.html
  libs/platform/src/lib/list/action-list-item/action-list-item.component.spec.ts
  libs/platform/src/lib/list/action-list-item/action-list-item.component.ts
  libs/platform/src/lib/list/base-list-item.ts
  libs/platform/src/lib/list/display-list-item/display-list-item.component.html
  libs/platform/src/lib/list/display-list-item/display-list-item.component.spec.ts
  libs/platform/src/lib/list/display-list-item/display-list-item.component.ts
  libs/platform/src/lib/list/free-content-list-item/free-content-list-item.component.html
  libs/platform/src/lib/list/free-content-list-item/free-content-list-item.component.ts
  libs/platform/src/lib/list/list-group-footer.component.ts
  libs/platform/src/lib/list/list-group-header.component.ts
  libs/platform/src/lib/list/list.component.html
  libs/platform/src/lib/list/list.component.ts
  libs/platform/src/lib/list/object-list-item/object-list-item.component.html
  libs/platform/src/lib/list/object-list-item/object-list-item.component.spec.ts
  libs/platform/src/lib/list/object-list-item/object-list-item.component.ts
  libs/platform/src/lib/list/standard-list-item/standard-list-item.component.html
  libs/platform/src/lib/list/standard-list-item/standard-list-item.component.ts
  libs/platform/src/lib/shared/domain/data-source.ts
Labels: accessibility, platform

#11000 fix(platform): fixed table row excessive focus and toggle handling
  libs/platform/src/lib/table/components/table-row/table-row.component.html
  libs/platform/src/lib/table/components/table-row/table-row.component.ts
  libs/platform/src/lib/table/table.component.html
Labels: accessibility, platform, ariba, table

#11015 fix(platform): fixed table row excessive focus and toggle handling (#11000)
  libs/platform/src/lib/table/components/table-row/table-row.component.html
  libs/platform/src/lib/table/components/table-row/table-row.component.ts
  libs/platform/src/lib/table/table.component.html
Labels: accessibility, platform, ariba, sourcing, ng15

#11019 fix(platform): clear table rows on data source changes
  libs/platform/src/lib/table/table.component.ts
Labels: platform, sourcing, table

#11022 chore: remove greetings workflow
  .github/workflows/greetings.yml
Labels: tooling

#10999 fix(core,platform): added missing translations for the dynamic page
  libs/core/src/lib/dynamic-page/dynamic-page-header/header/dynamic-page-header.component.ts
  libs/core/src/lib/dynamic-page/dynamic-page-header/subheader/dynamic-page-subheader.component.html
  libs/core/src/lib/dynamic-page/dynamic-page-header/subheader/dynamic-page-subheader.component.ts
  libs/core/src/lib/dynamic-page/dynamic-page.config.ts
  libs/core/src/lib/dynamic-page/index.ts
  libs/core/src/lib/dynamic-page/patch-header-i18n-texts.ts
  libs/docs/core/dynamic-page/index.ts
  libs/docs/platform/dynamic-page/index.ts
  libs/i18n/src/lib/models/lang.ts
  libs/i18n/src/lib/translations/translations.properties
  libs/i18n/src/lib/translations/translations.ts
  libs/i18n/src/lib/translations/translations_bg.properties
  libs/i18n/src/lib/translations/translations_bg.ts
  libs/i18n/src/lib/translations/translations_cs.properties
  libs/i18n/src/lib/translations/translations_cs.ts
  libs/i18n/src/lib/translations/translations_de.properties
  libs/i18n/src/lib/translations/translations_de.ts
  libs/i18n/src/lib/translations/translations_fr.properties
  libs/i18n/src/lib/translations/translations_fr.ts
  libs/i18n/src/lib/translations/translations_hi.properties
  libs/i18n/src/lib/translations/translations_hi.ts
  libs/i18n/src/lib/translations/translations_it.properties
  libs/i18n/src/lib/translations/translations_it.ts
  libs/i18n/src/lib/translations/translations_ka.properties
  libs/i18n/src/lib/translations/translations_ka.ts
  libs/i18n/src/lib/translations/translations_pl.properties
  libs/i18n/src/lib/translations/translations_pl.ts
  libs/i18n/src/lib/translations/translations_pt.properties
  libs/i18n/src/lib/translations/translations_pt.ts
  libs/i18n/src/lib/translations/translations_ru.properties
  libs/i18n/src/lib/translations/translations_ru.ts
  libs/i18n/src/lib/translations/translations_sq.properties
  libs/i18n/src/lib/translations/translations_sq.ts
  libs/i18n/src/lib/translations/translations_tr.properties
  libs/i18n/src/lib/translations/translations_tr.ts
  libs/i18n/src/lib/translations/translations_uk.properties
  libs/i18n/src/lib/translations/translations_uk.ts
  libs/i18n/src/lib/translations/translations_zh_CN.properties
  libs/i18n/src/lib/translations/translations_zh_CN.ts
  libs/platform/src/lib/dynamic-page/dynamic-page-header/header/dynamic-page-header.component.ts
  libs/platform/src/lib/dynamic-page/dynamic-page.component.ts
  libs/platform/src/lib/dynamic-page/dynamic-page.config.ts
Labels: accessibility, platform, core, ariba, i18n

#11020 fix(core): bug where datetime picker cannot be opened a 2nd time
  libs/core/src/lib/datetime-picker/datetime-picker.component.ts
Labels: bug, ng15

#11021 fix(platform): clear table rows on data source changes (#11019)
  libs/platform/src/lib/table/table.component.ts
Labels: platform, sourcing, table, ng15

#11028 fix(core): file uploader buttonAriaLabel is not working
  libs/core/src/lib/file-uploader/file-uploader.component.html
Labels: ng15
