Repository SAP/fundamental-ngx, pull requests merged in 2024-05, with the labels that each got.

#11867 docs(platform): wizard generator sb
  libs/docs/platform/wizard-generator/examples/wizard-generator-condition-example.component.ts
  libs/docs/platform/wizard-generator/examples/wizard-generator-customizable-example.component.ts
  libs/docs/platform/wizard-generator/examples/wizard-generator-dialog-example.component.ts
  libs/docs/platform/wizard-generator/examples/wizard-generator-responsive-dialog-example.component.ts
  libs/docs/platform/wizard-generator/examples/wizard-generator-visibility-between-steps-example.component.ts
  libs/docs/platform/wizard-generator/examples/wizard-generator-visible-summary-branching-example.component.ts
  libs/docs/platform/wizard-generator/platform-wizard-generator-docs.component.ts
Labels: stackblitz

#11868 docs(core): list stackblitz
  libs/docs/core/list-byline/examples/list-byline-unread-example/list-byline-unread-example.component.html
  libs/docs/core/list/examples/list-data-example/list-data-example.component.ts
  libs/docs/core/list/examples/list-data-example/sort.pipe.ts
  libs/docs/core/list/list-docs.component.ts
Labels: stackblitz

#11869 docs(core): table stackblitz
  libs/docs/core/table/examples/table-column-sorting-example.component.ts
  libs/docs/core/table/examples/table-custom-columns-example/table-custom-dialog.component.ts
  libs/docs/core/table/table-docs.component.ts
Labels: stackblitz

#11870 docs(core): content density sb
  libs/docs/core/content-density/content-density-docs.component.ts
  libs/docs/core/content-density/examples/content-density-example.component.ts
Labels: stackblitz

#11878 fix(platform): check validator before open Filtering Settings Dialog
  libs/platform/src/lib/table/components/table-p13-dialog/table-p13-dialog.component.ts
Labels: ng15

#11818 fix(core): remove tabindex from dynamic page header
  libs/core/src/lib/dynamic-page/dynamic-page-header/header/dynamic-page-header.component.ts
  libs/platform/src/lib/dynamic-page/dynamic-page-header/title/dynamic-page-title.component.spec.ts
Labels: ng15

#11860 fix(platform): setting generator allow rendering avatar if only label…
  libs/platform/settings-generator/layouts/settings-generator-sidebar-layout/settings-generator-sidebar-icon/settings-generator-sidebar-icon.component.html
Labels: bug

#11822 fix(platform): some improvements to platform table header popover
  libs/core/src/lib/list/directives/list-icon.directive.ts
  libs/core/src/lib/popover/popover-body/popover-body.component.scss
  libs/docs/platform/list/examples/platform-list-free-content-example.component.html
  libs/docs/platform/table/examples/platform-table-custom-column-example.component.html
  libs/platform/src/lib/list/free-content-list-item/free-content-list-item.component.html
  libs/platform/src/lib/list/free-content-list-item/free-content-list-item.component.spec.ts
  libs/platform/src/lib/list/free-content-list-item/free-content-list-item.component.ts
  libs/platform/src/lib/list/list.component.ts
  libs/platform/src/lib/table/components/table-cell-header-popover/table-cell-header-popover.component.html
  libs/platform/src/lib/table/components/table-cell-header-popover/table-cell-header-popover.component.ts
Labels: ng15

#11851 fix(platform): table header popover a11y improvements
  libs/core/list/directives/list-icon.directive.ts
  libs/core/popover/popover-body/popover-body.component.scss
  libs/docs/platform/list/examples/platform-list-free-content-example.component.html
  libs/docs/platform/table/examples/platform-table-custom-column-example.component.html
  libs/platform/list/free-content-list-item/free-content-list-item.component.spec.ts
  libs/platform/list/free-content-list-item/free-content-list-item.component.ts
  libs/platform/list/list.component.ts
  libs/platform/table/components/table-cell-header-popover/table-cell-header-popover.component.html
  libs/platform/table/components/table-cell-header-popover/table-cell-header-popover.component.ts
Labels: accessibility

#11852 fix(platform): remove tabindex from scrollable containers in VHD
  libs/platform/src/lib/value-help-dialog/components/select-tab/select-tab.component.html
  libs/platform/src/lib/value-help-dialog/value-help-dialog/value-help-dialog.component.html
Labels: ng15

#11875 fix(platform): add cellActivate event to platform table
  libs/docs/platform/table/child-docs/clickable-rows/clickable-rows-docs.component.html
  libs/docs/platform/table/examples/platform-table-activable-example.component.html
  libs/docs/platform/table/examples/platform-table-activable-example.component.ts
  libs/platform/table-helpers/models/index.ts
  libs/platform/table-helpers/models/table-cell-activate-event.model.ts
  libs/platform/table-helpers/models/table-row-activate-event.model.ts
  libs/platform/table-helpers/services/table-row.service.ts
  libs/platform/table/components/table-row/table-row.component.html
  libs/platform/table/table.component.ts
Labels: accessibility

#11876 fix(platform): add cellActivate event to platform table
  libs/docs/platform/table/child-docs/clickable-rows/clickable-rows-docs.component.html
  libs/docs/platform/table/examples/platform-table-activable-example.component.html
  libs/docs/platform/table/examples/platform-table-activable-example.component.ts
  libs/platform/src/lib/table-helpers/models/index.ts
  libs/platform/src/lib/table-helpers/models/table-cell-activate-event.model.ts
  libs/platform/src/lib/table-helpers/services/table-row.service.ts
  libs/platform/src/lib/table/components/table-row/table-row.component.html
  libs/platform/src/lib/table/table.component.ts
Labels: ng15

#11897 test(platform): remove menu button e2e
  libs/docs/platform/menu-button/e2e/menu-button-contents.ts
  libs/docs/platform/menu-button/e2e/menu-button.e2e-spec.ts
  libs/docs/platform/menu-button/e2e/menu-button.po.ts
  libs/docs/platform/menu-button/e2e/tsconfig.json
Labels: test automation, e2e

#11896 chore(release): publish 0.50.0-rc.91
  CHANGELOG.md
  lerna.json
  libs/btp/CHANGELOG.md
  libs/btp/package.json
  libs/cdk/CHANGELOG.md
  libs/cdk/package.json
  libs/core/CHANGELOG.md
  libs/core/package.json
  libs/cx/CHANGELOG.md
  libs/cx/package.json
  libs/datetime-adapter/CHANGELOG.md
  libs/datetime-adapter/package.json
  libs/i18n/CHANGELOG.md
  libs/i18n/package.json
  libs/moment-adapter/CHANGELOG.md
  libs/moment-adapter/package.json
  libs/nx-plugin/CHANGELOG.md
  libs/nx-plugin/package.json
  libs/platform/CHANGELOG.md
  libs/platform/package.json
Labels: tooling

#11935 fix(deps): align common-css version with fundamental-styles 0.36
  package.json
  yarn.lock
Labels: dependencies

#11923 docs(btp,i18n): add license link in i18n and btp packages' README.md
  libs/btp/README.md
  libs/i18n/README.md
Labels: documentation

#11947 fix(platform): add fix for incorrect border in Platform table
  libs/docs/platform/table/examples/platform-table-no-outer-borders-example.component.html
  libs/docs/platform/table/examples/platform-table-no-outer-borders-example.component.ts
  libs/docs/platform/table/platform-table-docs.component.html
  libs/platform/table/table.component.scss
Labels: table

#11961 fix(core): remove padding when subheader is empty
  libs/core/dynamic-page/dynamic-page.component.scss
Labels: bug

#11962 fix(core): remove redundant popoverFormMessage assignments
  libs/core/datetime-picker/datetime-picker.component.ts
Labels: bug

#11924 fix(core): show clear button in any combobox
  libs/core/combobox/combobox.component.html
  libs/core/combobox/combobox.component.ts
  libs/docs/core/combobox/combobox-docs.component.html
  libs/docs/core/combobox/examples/combobox-search-field-example.component.html
  libs/docs/core/combobox/examples/combobox-search-field-example.component.ts
Labels: enhancement
