Repository SAP/fundamental-ngx, pull requests merged in 2024-02, with the labels that each got.

#11344 fix(btp): fix splitter style import
  libs/btp/splitter/splitter.component.scss
Labels: bug

#11351 chore(deps): update theming-base-content v11.11.0
  package.json
  yarn.lock
Labels: tooling, theming

#11349 fix(core,platform): tabs programmatic overflow item open
  libs/core/tabs/tab-list.component.ts
  libs/platform/icon-tab-bar/components/icon-tab-bar-base.class.ts
  libs/platform/icon-tab-bar/icon-tab-bar.component.ts
Labels: bug, platform, core

#11338 feat(docs,core): icon tab bar navigation improvements
  libs/docs/platform/icon-tab-bar/platform-icon-tab-bar-header/platform-icon-tab-bar-header.component.html
  libs/platform/icon-tab-bar/components/closable-icon-tab-bar.class.ts
  libs/platform/icon-tab-bar/components/icon-tab-bar-base.class.ts
  libs/platform/icon-tab-bar/components/icon-tab-bar-filter-type/icon-tab-bar-filter-type.component.html
  libs/platform/icon-tab-bar/components/icon-tab-bar-icon-type/icon-tab-bar-icon-type.component.html
  libs/platform/icon-tab-bar/components/icon-tab-bar-process-type/icon-tab-bar-process-type.component.html
  libs/platform/icon-tab-bar/components/icon-tab-bar-text-type/icon-tab-bar-text-type.component.html
  libs/platform/icon-tab-bar/components/icon-tab-bar-text-type/icon-tab-bar-text-type.component.ts
  libs/platform/icon-tab-bar/components/popovers/icon-tab-bar-popover-base.class.ts
  libs/platform/icon-tab-bar/components/popovers/icon-tab-bar-popover/icon-tab-bar-popover.component.html
  libs/platform/icon-tab-bar/components/popovers/text-type-popover/text-type-popover.component.html
  libs/platform/icon-tab-bar/components/popovers/text-type-popover/text-type-popover.component.ts
Labels: enhancement, documentation, platform

#11347 fix(core,platform): multi input and combobox placeholder behavior
  libs/core/multi-combobox/multi-combobox.component.html
  libs/core/multi-input/multi-input.component.html
  libs/docs/core/multi-input/e2e/multi-input.e2e-spec.ts
  libs/docs/platform/multi-input/e2e/multi-input.e2e-spec.ts
  libs/platform/form/multi-combobox/multi-combobox/multi-combobox.component.html
  libs/platform/form/multi-input/multi-input.component.html
Labels: bug, platform, core

#11367 fix(core): dialog dismiss reason
  libs/core/dialog/base/dialog-base.class.ts
  libs/core/dialog/base/dialog-ref-base.class.ts
Labels: core

#11379 fix(platform): disallow select all for single select
  libs/platform/src/lib/table/components/table-header-row/table-header-row.component.html
Labels: ng15

#11378 fix(platform): disallow select all for single select
  libs/platform/table/components/table-header-row/table-header-row.component.html
Labels: bug, platform, table

#11381 feat(core,docs): multi input combobox byline example
  libs/core/multi-combobox/multi-combobox.component.html
  libs/core/multi-combobox/multi-combobox.component.ts
  libs/docs/core/multi-combobox/e2e/multi-combobox.e2e-spec.ts
  libs/docs/core/multi-combobox/examples/multi-combobox-byline/multi-combobox-byline-example.component.html
  libs/docs/core/multi-combobox/examples/multi-combobox-byline/multi-combobox-byline-example.component.ts
  libs/docs/core/multi-combobox/multi-combobox-docs.component.html
  libs/docs/core/multi-combobox/multi-combobox-docs.component.ts
  libs/docs/core/multi-input/examples/multi-input-dropdown-width-example/multi-input-dropdown-width-example.component.html
  libs/docs/core/multi-input/examples/multi-input-dropdown-width-example/multi-input-dropdown-width-example.component.ts
Labels: enhancement, documentation, core

#11382 chore(ci): clean up unused ci and update versions of some ghactions
  .github/actions/bump-styles-version/action.yml
  .github/actions/bump-styles-version/index.js
  .github/actions/nodejs/action.yml
  .github/actions/npm-publish/index.js
  .github/actions/parallel-commands/action.yml
  .github/actions/update-versions/action.yml
  .github/actions/update-versions/index.js
  .github/actions/wait-for-netlify/action.yml
  .github/actions/wait-for-netlify/index.js
  .github/workflows/bump-styles.yml
  .github/workflows/create-release.yml
  .github/workflows/on-pull-request.yml
  .github/workflows/on-schedule.yml
  .github/workflows/update-versions.yml
  package.json
  yarn.lock
Labels: tooling

#11383 fix(docs): vhd value comparator fix
  libs/docs/platform/vhd/examples/platform-vhd-multi-input-example.component.html
  libs/docs/platform/vhd/examples/platform-vhd-multi-input-example.component.ts
Labels: documentation

#11397 fix(core,platform): detect changes when control value being updated
  libs/cdk/src/lib/forms/cva/cva.directive.ts
  libs/core/src/lib/combobox/combobox.component.ts
  libs/core/src/lib/input-group/input-group.component.ts
  libs/core/src/lib/multi-input/multi-input.component.ts
  libs/core/src/lib/rating-indicator/components/rating-indicator.component.ts
  libs/core/src/lib/select/select.component.ts
  libs/core/src/lib/slider/slider.component.ts
  libs/core/src/lib/time-picker/time-picker.component.ts
  libs/docs/core/select/e2e/select.e2e-spec.ts
  libs/docs/core/table/e2e/table.e2e-spec.ts
  libs/docs/platform/select/e2e/select.e2e-spec.ts
  libs/platform/src/lib/form/date-picker/date-picker.component.ts
  libs/platform/src/lib/form/datetime-picker/datetime-picker.component.ts
  libs/platform/src/lib/form/multi-combobox/commons/base-multi-combobox.ts
  libs/platform/src/lib/form/step-input/base.step-input.ts
  libs/platform/src/lib/list/base-list-item.ts
  libs/platform/src/lib/list/list.component.html
  libs/platform/src/lib/shared/form/base.input.ts
Labels: bug, ng15

#11384 fix(docs): vhd value comparator fix
  libs/docs/platform/vhd/examples/platform-vhd-multi-input-example.component.html
  libs/docs/platform/vhd/examples/platform-vhd-multi-input-example.component.ts
Labels: ng15

#11342 fix(platform): p13 dialog active issue
  libs/docs/platform/table/e2e/table.po.ts
  libs/platform/table/components/table-p13-dialog/columns/columns.component.html
  libs/platform/table/components/table-p13-dialog/columns/columns.component.ts
Labels: bug

#11341 fix(platform): p13 dialog active issue
  libs/docs/platform/table/e2e/table.po.ts
  libs/platform/src/lib/table/components/table-p13-dialog/columns/columns.component.html
  libs/platform/src/lib/table/components/table-p13-dialog/columns/columns.component.ts
Labels: bug

#11402 fix(docs): use direct object assignment to trigger correct detection
  libs/docs/platform/vhd/examples/platform-vhd-multi-input-example.component.ts
Labels: ng15

#11403 fix(docs): use direct object assignment to trigger correct detection
  libs/docs/platform/vhd/examples/platform-vhd-multi-input-example.component.ts
Labels: documentation

#11407 fix(core): add fix for broken list height in Multi Combobox
  libs/core/multi-combobox/multi-combobox.component.html
Labels: bug

#11417 chore(deps): tbc v11.12.0
  package.json
  yarn.lock
Labels: dependencies, theming

#11429 fix(platform): search field simplification
  libs/platform/search-field/search-field.component.html
  libs/platform/search-field/search-field.component.scss
  libs/platform/search-field/search-field.component.spec.ts
  libs/platform/search-field/search-field.component.ts
Labels: bug, enhancement, platform

#11411 feat(platform,docs): table growing button
  libs/docs/platform/docs-data.ts
  libs/docs/platform/table/child-docs/pagination/table-pagination-docs.component.html
  libs/docs/platform/table/child-docs/pagination/table-pagination-docs.component.ts
  libs/docs/platform/table/examples/custom-pagination/table-custom-pagination-example.component.html
  libs/docs/platform/table/examples/custom-pagination/table-custom-pagination-example.component.ts
  libs/docs/platform/table/examples/standard-pagination/platform-table-standard-pagination-example.component.html
  libs/docs/platform/table/examples/standard-pagination/platform-table-standard-pagination-example.component.ts
  libs/docs/platform/table/index.ts
  libs/i18n/src/lib/models/fd-language-key-identifier.ts
  libs/i18n/src/lib/translations/translations.properties
  libs/i18n/src/lib/translations/translations.ts
  libs/platform/table-helpers/services/table.service.ts
  libs/platform/table-helpers/table.ts
  libs/platform/table/components/growing-button/table-growing-button.component.html
  libs/platform/table/components/growing-button/table-growing-button.component.ts
  libs/platform/table/index.ts
  libs/platform/table/table.component.html
  libs/platform/table/table.component.scss
  libs/platform/table/table.component.ts
  libs/platform/table/table.module.ts
Labels: enhancement, documentation, platform

#11434 fix(cdk): data source package tsconfig
  libs/cdk/data-source/tsconfig.json
  libs/cdk/data-source/tsconfig.lib.json
Labels: bug

#11441 fix(platform): smart filter bar service scope fix
  libs/platform/smart-filter-bar/smart-filter-bar.component.ts
Labels: bug, platform

#11466 docs(core,platform): update the state icons for Object Status
  libs/docs/core/object-status/examples/object-status-clickable-and-icon-example.component.html
  libs/docs/core/object-status/examples/object-status-default-example.component.html
  libs/docs/core/object-status/examples/object-status-icon-text-example.component.html
  libs/docs/core/object-status/examples/object-status-inverted-example.component.html
  libs/docs/core/object-status/examples/object-status-large-example.component.html
  libs/docs/platform/object-status/examples/platform-object-status-clickable-and-icon-example.component.html
  libs/docs/platform/object-status/examples/platform-object-status-icon-text-example.component.html
  libs/docs/platform/object-status/examples/platform-object-status-inverted-example.component.html
  libs/docs/platform/object-status/examples/platform-object-status-large-example.component.html
Labels: documentation

#11477 fix(core): update displayed calendar date
  libs/core/date-picker/date-picker.component.ts
Labels: bug, datepicker, core

#11473 feat(cx): side nav update
  libs/cx/nested-list/nested-item/nested-item.component.ts
  libs/cx/side-navigation/side-navigation-main.component.ts
  libs/cx/side-navigation/side-navigation.component.html
  libs/cx/side-navigation/side-navigation.component.scss
  libs/cx/side-navigation/side-navigation.component.spec.ts
  libs/cx/side-navigation/side-navigation.component.ts
  libs/docs/cx/side-navigation/examples/side-navigation-shellbar-example.component.html
  package.json
  yarn.lock
Labels: enhancement, cx

#11475 fix(platform): simplify vhd styles
  libs/platform/value-help-dialog/components/define-tab/define-tab.component.html
  libs/platform/value-help-dialog/components/define-tab/define-tab.component.scss
Labels: bug, platform

#11487 fix(platform): optimize icon tab bar
  libs/platform/icon-tab-bar/components/icon-tab-bar-base.class.ts
Labels: bug, platform
