Repository SAP/fundamental-ngx, pull requests merged in 2024-09, with the labels that each got.

#12300 feat(platform): move the column reordering button in the list item representing the column
  libs/platform/table/components/table-p13-dialog/columns/columns.component.html
  libs/platform/table/components/table-p13-dialog/columns/columns.component.ts
Labels: table

#12358 fix(core): add proper styling for Select placeholder
  libs/core/select/select.component.html
  libs/core/select/select.component.scss
Labels: bug

#12359 docs(core): remove deprecate from action bar
  libs/docs/core/action-bar/action-bar-header/action-bar-header.component.html
Labels: documentation

#12356 fix(platform): table grouping spanning
  libs/platform/table/table.component.ts
Labels: table

#12365 fix(platform): broken _getNumberOfRowsToDisplay() function
  libs/platform/src/lib/table-helpers/directives/table-virtual-scroll.directive.ts
  libs/platform/src/lib/table/tests/table.component-virtual-scrolling.spec.ts
Labels: ng15

#12394 docs: update README.md
  README.md
Labels: documentation

#12375 fix(platform): more specific targeting of blocking wheel event when using scrollWholeRows
  libs/core/src/lib/busy-indicator/busy-indicator.component.ts
  libs/platform/src/lib/table-helpers/directives/table-virtual-scroll.directive.ts
  libs/platform/src/lib/table/table.component.html
Labels: ng15

#12392 fix(platform): update Valiant Management list item state on select event
  libs/platform/variant-management/variant-management.component.html
Labels: bug

#12301 fix(core): call endClose on dialog close method to handle right seque…
  libs/core/dialog/base/dialog-ref-base.class.ts
  libs/docs/core/menu/e2e/menu.e2e-spec.ts
  libs/docs/core/message-box/e2e/message-box.e2e-spec.ts
  libs/docs/core/multi-combobox/e2e/multi-combobox.e2e-spec.ts
  libs/docs/platform/multi-combobox/e2e/multi-combobox.e2e-spec.ts
Labels: bug

#12414 test(platform): add more time for smart filter bar unit test
  libs/platform/smart-filter-bar/directives/smart-filter-bar-subject.directive.spec.ts
Labels: testing, unit tests

#12413 fix(platform): add border to Toolbar in all types of Platfrm table
  libs/platform/table/components/table-toolbar/table-toolbar.component.html
  libs/platform/table/table.component.scss
Labels: bug

#12288 fix(core): grid list keyboard support
  libs/cdk/utils/functions/key-util.ts
  libs/core/grid-list/components/grid-list-item/grid-list-item.component.html
  libs/core/grid-list/components/grid-list-item/grid-list-item.component.ts
  libs/core/grid-list/components/grid-list/grid-list.component.spec.ts
  libs/core/grid-list/components/grid-list/grid-list.component.ts
  libs/core/grid-list/models/grid-list-selection.models.ts
  libs/docs/core/grid-list/e2e/grid-list.e2e-spec.ts
  libs/docs/core/grid-list/examples/combo-select/grid-list-combo-select-example.component.html
  libs/docs/core/grid-list/examples/combo-select/grid-list-combo-select-example.component.ts
  libs/docs/core/wizard/e2e/wizard.e2e-spec.ts
Labels: accessibility

#12303 fix(platform): fix fdp-table popover alignment
  libs/core/shared/interfaces/popover-position.ts
  libs/platform/table/components/table-cell-header-popover/table-cell-header-popover.component.html
  libs/platform/table/components/table-cell-header-popover/table-cell-header-popover.component.ts
  libs/platform/table/components/table-header-cell-content/table-header-cell-content.component.html
  libs/platform/table/components/table-header-cell-content/table-header-cell-content.component.ts
Labels: table

#12415 fix: datetime adapter passing date format, not dateTime
  libs/core/datetime-picker/datetime-picker.component.ts
Labels: bug

#12431 fix(platform): icon-tab-bar check for selectedUid
  libs/platform/icon-tab-bar/components/icon-tab-bar-base.class.ts
Labels: bug

#12433 fix(core): handle invalid date inputs gracefully
  libs/core/datetime-picker/datetime-picker.component.ts
Labels: bug

#12410 fix(core,platform): provide translation for multi-combobox Invalid En…
  libs/core/src/lib/multi-combobox/base-multi-combobox.class.ts
  libs/core/src/lib/multi-combobox/multi-combobox.component.ts
  libs/i18n/src/lib/languages/albanian.ts
  libs/i18n/src/lib/languages/arabic.ts
  libs/i18n/src/lib/languages/bulgarian.ts
  libs/i18n/src/lib/languages/chinese.ts
  libs/i18n/src/lib/languages/chinese_traditional.ts
  libs/i18n/src/lib/languages/croatian.ts
  libs/i18n/src/lib/languages/czech.ts
  libs/i18n/src/lib/languages/danish.ts
  libs/i18n/src/lib/languages/dutch.ts
  libs/i18n/src/lib/languages/english.ts
  libs/i18n/src/lib/languages/finnish.ts
  libs/i18n/src/lib/languages/french.ts
  libs/i18n/src/lib/languages/georgian.ts
  libs/i18n/src/lib/languages/german.ts
  libs/i18n/src/lib/languages/greek.ts
  libs/i18n/src/lib/languages/hebrew.ts
  libs/i18n/src/lib/languages/hindi.ts
  libs/i18n/src/lib/languages/hungarian.ts
  libs/i18n/src/lib/languages/italian.ts
  libs/i18n/src/lib/languages/japanese.ts
  libs/i18n/src/lib/languages/kazakh.ts
  libs/i18n/src/lib/languages/korean.ts
  libs/i18n/src/lib/languages/malay.ts
  libs/i18n/src/lib/languages/norwegian.ts
  libs/i18n/src/lib/languages/polish.ts
  libs/i18n/src/lib/languages/portuguese.ts
  libs/i18n/src/lib/languages/romanian.ts
  libs/i18n/src/lib/languages/russian.ts
  libs/i18n/src/lib/languages/serbian.ts
  libs/i18n/src/lib/languages/slovak.ts
  libs/i18n/src/lib/languages/slovenian.ts
  libs/i18n/src/lib/languages/spanish.ts
  libs/i18n/src/lib/languages/swedish.ts
  libs/i18n/src/lib/languages/thai.ts
  libs/i18n/src/lib/languages/turkish.ts
  libs/i18n/src/lib/languages/ukrainian.ts
  libs/i18n/src/lib/models/lang.ts
  libs/platform/src/lib/form/multi-combobox/commons/base-multi-combobox.ts
  libs/platform/src/lib/form/multi-combobox/multi-combobox/multi-combobox.component.ts
Labels: ng15

#12367 fix(platform): prevent filter input from losing focus when entering s…
  libs/platform/table/components/table-cell-header-popover/table-cell-header-popover.component.html
Labels: bug

#12398 fix(core): Refactor calendar day view component to use signal version of inputs. add special day rules example for DatePicker
  libs/core/calendar/calendar-views/calendar-day-view/calendar-day-view.component.html
  libs/core/calendar/calendar-views/calendar-day-view/calendar-day-view.component.spec.ts
  libs/core/calendar/calendar-views/calendar-day-view/calendar-day-view.component.ts
  libs/docs/core/date-picker/date-picker-docs.component.html
  libs/docs/core/date-picker/date-picker-docs.component.ts
  libs/docs/core/date-picker/examples/date-picker-special-day-example/date-picker-special-day-example.component.html
  libs/docs/core/date-picker/examples/date-picker-special-day-example/date-picker-special-day-example.component.scss
  libs/docs/core/date-picker/examples/date-picker-special-day-example/date-picker-special-day-example.component.ts
Labels: bug, code refactoring

#12443 fix(core): address some Dynamic Page header issues
  libs/core/dynamic-page/dynamic-page-header/subheader/dynamic-page-subheader.component.html
  libs/core/dynamic-page/dynamic-page.component.scss
  libs/docs/core/dynamic-page/examples/dynamic-page-routing/dynamic-page-routing-example.component.html
  libs/docs/core/dynamic-page/examples/dynamic-page-routing/dynamic-page-routing-example.component.ts
Labels: bug

#12445 fix(cx): Add ariaHidden input property and set it default false
  libs/cx/nested-list/nested-item/nested-item.component.ts
Labels: bug

#12341 feat(core): add a feature to pick date range in month year format
  libs/core/calendar/calendar-header/calendar-header.component.html
  libs/core/calendar/calendar-views/calendar-aggregated-year-view/calendar-aggregated-year-view.component.ts
  libs/core/calendar/calendar-views/calendar-day-view/calendar-day-view.component.ts
  libs/core/calendar/calendar-views/calendar-month-view/calendar-month-view.component.html
  libs/core/calendar/calendar-views/calendar-month-view/calendar-month-view.component.spec.ts
  libs/core/calendar/calendar-views/calendar-month-view/calendar-month-view.component.ts
  libs/core/calendar/calendar-views/calendar-year-view/calendar-year-view.component.html
  libs/core/calendar/calendar-views/calendar-year-view/calendar-year-view.component.spec.ts
  libs/core/calendar/calendar-views/calendar-year-view/calendar-year-view.component.ts
  libs/core/calendar/calendar.component.html
  libs/core/calendar/calendar.component.ts
  libs/core/calendar/calendar.service.spec.ts
  libs/core/calendar/calendar.service.ts
  libs/core/calendar/models/calendar-month.ts
  libs/core/calendar/models/calendar-year-grid.ts
  libs/core/date-picker/date-picker.component.html
  libs/core/date-picker/date-picker.component.ts
  libs/docs/core/date-picker/date-picker-docs.component.html
  libs/docs/core/date-picker/examples/date-picker-range-example.component.ts
  libs/docs/core/datetime-picker/e2e/date-time-picker.e2e-spec.ts
Labels: datepicker

#12430 fix(platform): fdp-table Enhance the <fdp-table-p13-dialog [table]="table"> component to emit an event with the selected column
  libs/docs/platform/table/examples/platform-table-p13-columns-example.component.html
  libs/docs/platform/table/examples/platform-table-p13-columns-example.component.ts
  libs/platform/table/components/table-p13-dialog/table-p13-dialog.component.ts
Labels: table

#12452 fix: downport translations
  libs/i18n/src/lib/languages/arabic.ts
  libs/i18n/src/lib/languages/bulgarian.ts
  libs/i18n/src/lib/languages/chinese.ts
  libs/i18n/src/lib/languages/chinese_traditional.ts
  libs/i18n/src/lib/languages/croatian.ts
  libs/i18n/src/lib/languages/czech.ts
  libs/i18n/src/lib/languages/danish.ts
  libs/i18n/src/lib/languages/dutch.ts
  libs/i18n/src/lib/languages/finnish.ts
  libs/i18n/src/lib/languages/french.ts
  libs/i18n/src/lib/languages/georgian.ts
  libs/i18n/src/lib/languages/german.ts
  libs/i18n/src/lib/languages/greek.ts
  libs/i18n/src/lib/languages/hebrew.ts
  libs/i18n/src/lib/languages/hungarian.ts
  libs/i18n/src/lib/languages/italian.ts
  libs/i18n/src/lib/languages/japanese.ts
  libs/i18n/src/lib/languages/kazakh.ts
  libs/i18n/src/lib/languages/korean.ts
  libs/i18n/src/lib/languages/malay.ts
  libs/i18n/src/lib/languages/norwegian.ts
  libs/i18n/src/lib/languages/polish.ts
  libs/i18n/src/lib/languages/portuguese.ts
  libs/i18n/src/lib/languages/romanian.ts
  libs/i18n/src/lib/languages/serbian.ts
  libs/i18n/src/lib/languages/slovak.ts
  libs/i18n/src/lib/languages/slovenian.ts
  libs/i18n/src/lib/languages/spanish.ts
  libs/i18n/src/lib/languages/swedish.ts
  libs/i18n/src/lib/languages/thai.ts
  libs/i18n/src/lib/languages/turkish.ts
Labels: i18n, ng15

#12439 fix(cx): fix cx side bar keyboard navigation
  libs/cx/nested-list/nested-list/nested-list.component.ts
Labels: cx

#12438 fix(core): more customization of aria attributes for multi-input
  libs/core/src/lib/multi-input/multi-input.component.html
  libs/core/src/lib/multi-input/multi-input.component.ts
Labels: ng15

#12437 fix(core): more customization of aria attributes for multi-input
  libs/core/multi-input/multi-input.component.html
  libs/core/multi-input/multi-input.component.ts
Labels: accessibility

#12429 fix(platform): fdp-table sorting visible columns state get lost
  libs/platform/table/components/table-p13-dialog/columns/columns.component.ts
Labels: table

#12370 feat(core): implement ContentDensity to handle all type of themes on demand.
  libs/core/dialog/base/dialog-config-base.class.ts
  libs/core/dialog/dialog-footer/dialog-footer.component.html
  libs/core/dialog/dialog-footer/dialog-footer.component.spec.ts
  libs/core/dialog/dialog-header/dialog-header.component.html
  libs/core/dialog/dialog-header/dialog-header.component.spec.ts
  libs/docs/core/dialog/dialog-docs.component.ts
  libs/docs/core/dialog/examples/dialog-mobile/dialog-mobile-example.component.ts
  libs/docs/core/schema/src/lib/dialog.schema.ts
Labels: nice to have

#12477 fix(core): wizard steps - anchors should have role="navigation"
  libs/core/wizard/wizard-step/wizard-step.component.html
  libs/core/wizard/wizard-step/wizard-step.component.ts
Labels: accessibility

#12470 refactor(core): replaced outputs and inputs with signals, prevent ful…
  libs/core/dialog/dialog-close-button/dialog-close-button.component.ts
  libs/core/dialog/dialog-full-screen-toggler-button/dialog-full-screen-toggler-button.component.ts
  libs/core/dialog/dialog-header/dialog-header.component.html
  libs/core/dialog/dialog.component.html
  libs/core/dialog/dialog.component.ts
  libs/core/dialog/directives/dialog-template.directive.ts
  libs/core/dialog/directives/dialog-title.directive.ts
Labels: bug, code refactoring
