Repository SAP/fundamental-ngx, pull requests merged in 2024-04, with the labels that each got.

#11656 fix(core): pagination accessibility improvements
  libs/cdk/src/lib/utils/directives/only-digits/only-digits.directive.ts
  libs/core/src/lib/pagination/pagination.component.html
  libs/core/src/lib/pagination/pagination.component.ts
Labels: bug, accessibility, ng15

#11650 fix(platform): dialog aria-labelledBy for vhd
  libs/docs/platform/vhd/examples/platform-vhd-basic-example.component.html
  libs/platform/value-help-dialog/value-help-dialog/value-help-dialog.component.ts
Labels: bug

#11662 fix(platform): focus menu button trigger when closed
  libs/platform/menu-button/menu-button.component.ts
  libs/platform/menu/menu-trigger.directive.ts
Labels: bug

#11681 fix(core): a11y fix for Shellbar component
  libs/core/shellbar/product-menu/product-menu.component.html
  libs/core/shellbar/product-menu/product-menu.component.scss
  libs/core/shellbar/product-menu/product-menu.component.ts
  libs/core/shellbar/shellbar-title/shellbar-title.component.html
Labels: accessibility, sourcing

#11661 fix(platform): focus menu button trigger when closed
  libs/platform/src/lib/menu/menu-trigger.directive.ts
Labels: bug

#11676 fix(core, platform): add fix for breadcrumb template not being rendered in Dynamic Page component
  libs/core/dynamic-page/dynamic-page-header/actions/dynamic-page-layout-actions.component.ts
  libs/core/dynamic-page/dynamic-page-header/breadcrumb/dynamic-page-breadcrumb.component.ts
  libs/core/dynamic-page/dynamic-page-header/header/dynamic-page-header.component.html
  libs/core/dynamic-page/dynamic-page-header/header/dynamic-page-header.component.ts
  libs/core/dynamic-page/dynamic-page.module.ts
  libs/core/dynamic-page/index.ts
  libs/core/dynamic-page/tokens.ts
  libs/docs/core/dynamic-page/e2e/dynamic-page.e2e-spec.ts
  libs/docs/core/dynamic-page/examples/dynamic-page-column-layout-example/dynamic-page-column-layout-example.component.html
  libs/docs/core/dynamic-page/examples/dynamic-page-dynamic-container-height-example/dynamic-page-dynamic-container-height-example.component.html
  libs/docs/core/dynamic-page/examples/dynamic-page-example.component.html
  libs/docs/core/dynamic-page/examples/dynamic-page-facets-example/dynamic-page-facets-example.component.html
  libs/docs/core/dynamic-page/examples/dynamic-page-responsive-example/dynamic-page-responsive-example.component.html
  libs/docs/core/dynamic-page/examples/dynamic-page-routing/dynamic-page-routing-example.component.html
  libs/docs/core/dynamic-page/examples/dynamic-page-tabs-example/dynamic-page-tabs-example.component.html
  libs/docs/platform/api-files.ts
  libs/docs/platform/dynamic-page/examples/platform-dynamic-page-example.component.html
  libs/docs/platform/dynamic-page/examples/platform-dynamic-page-facets-example/platform-dynamic-page-facets-example.component.html
  libs/docs/platform/dynamic-page/examples/platform-dynamic-page-flexible-column-example.component.html
  libs/docs/platform/dynamic-page/examples/platform-dynamic-page-non-collapsible-example.component.html
  libs/docs/platform/dynamic-page/examples/platform-dynamic-page-responsive-padding-example.component.html
  libs/docs/platform/dynamic-page/examples/platform-dynamic-page-snap-scroll-example.component.html
  libs/docs/platform/dynamic-page/examples/platform-dynamic-page-tabbed-example.component.html
  libs/platform/dynamic-page/dynamic-page-header/breadcrumb/dynamic-page-breadcrumb.component.ts
  libs/platform/dynamic-page/dynamic-page-header/title/dynamic-page-title.component.ts
  libs/platform/dynamic-page/dynamic-page.component.html
  libs/platform/dynamic-page/dynamic-page.component.ts
  libs/platform/dynamic-page/dynamic-page.module.ts
  libs/platform/dynamic-page/index.ts
Labels: sourcing

#11688 fix(core): import Button css to Select component
  libs/core/select/select.component.scss
Labels: bug

#11689 feat(core): add possibility to apply custom background and CSS to Tree item
  libs/core/tree/components/tree-item/tree-item.component.html
  libs/core/tree/components/tree-item/tree-item.component.ts
  libs/docs/core/tree/examples/simple-tree-example.component.html
  libs/docs/core/tree/examples/simple-tree-example.component.ts
Labels: enhancement

#11677 fix(core, platform): add fix for breadcrumb template not being rendered in Dynamic Page component
  libs/core/src/lib/dynamic-page/dynamic-page-header/actions/dynamic-page-layout-actions.component.ts
  libs/core/src/lib/dynamic-page/dynamic-page-header/header/dynamic-page-header.component.html
  libs/core/src/lib/dynamic-page/dynamic-page-header/header/dynamic-page-header.component.ts
  libs/docs/core/dynamic-page/e2e/dynamic-page.e2e-spec.ts
  libs/docs/core/dynamic-page/examples/dynamic-page-responsive-example/dynamic-page-responsive-example.component.html
  libs/docs/core/message-box/e2e/message-box.e2e-spec.ts
  libs/docs/core/message-box/e2e/message-box.po.ts
  libs/docs/core/message-box/e2e/message-box.ts
  libs/docs/core/message-box/e2e/tsconfig.json
  libs/docs/platform/dynamic-page/examples/platform-dynamic-page-example.component.html
  libs/docs/platform/dynamic-page/examples/platform-dynamic-page-facets-example/platform-dynamic-page-facets-example.component.html
  libs/docs/platform/dynamic-page/examples/platform-dynamic-page-flexible-column-example.component.html
  libs/docs/platform/dynamic-page/examples/platform-dynamic-page-non-collapsible-example.component.html
  libs/docs/platform/dynamic-page/examples/platform-dynamic-page-responsive-padding-example.component.html
  libs/docs/platform/dynamic-page/examples/platform-dynamic-page-snap-scroll-example.component.html
  libs/docs/platform/dynamic-page/examples/platform-dynamic-page-tabbed-example.component.html
  libs/platform/src/lib/dynamic-page/dynamic-page-header/title/dynamic-page-title.component.ts
  libs/platform/src/lib/dynamic-page/dynamic-page.component.html
  libs/platform/src/lib/dynamic-page/dynamic-page.component.spec.ts
  wdio.conf.js
Labels: sourcing, ng15

#11699 fix: add fundamental packages for stackblitz and update common-css
  libs/docs/shared/src/lib/core-helpers/stackblitz/stackblitz-dependencies.ts
  package.json
  yarn.lock
Labels: tooling, dependencies, stackblitz

#11674 docs(core): fix stackblitz examples
  libs/docs/core/card/card-docs.component.ts
  libs/docs/core/carousel/carousel-docs.component.html
  libs/docs/core/carousel/carousel-docs.component.ts
  libs/docs/core/carousel/examples/carousel-auto-slides-example.component.scss
  libs/docs/core/carousel/examples/carousel-auto-slides-example.component.ts
  libs/docs/core/carousel/examples/carousel-background-example.component.scss
  libs/docs/core/carousel/examples/carousel-background-example.component.ts
  libs/docs/core/carousel/examples/carousel-dynamic-items-example.component.scss
  libs/docs/core/carousel/examples/carousel-dynamic-items-example.component.ts
  libs/docs/core/dialog/dialog-docs.component.ts
  libs/docs/core/dialog/examples/dialog-configuration/dialog-configuration-example.component.scss
  libs/docs/core/dialog/examples/dialog-configuration/dialog-configuration-example.component.ts
  libs/docs/core/dialog/examples/dialog-state/dialog-state-example.component.scss
  libs/docs/core/dialog/examples/dialog-state/dialog-state-example.component.ts
  libs/docs/core/facets/examples/facet-alignment-example.component.html
  libs/docs/core/facets/examples/facet-alignment-example.component.ts
  libs/docs/core/facets/examples/facet-examples.component.ts
  libs/docs/core/facets/examples/facet-group-example.component.ts
  libs/docs/core/facets/examples/facet-loading-example.component.ts
  libs/docs/core/facets/examples/form-facet-example.component.html
  libs/docs/core/facets/examples/form-facet-example.component.ts
  libs/docs/core/facets/examples/form-link-facet-example.component.html
  libs/docs/core/facets/examples/image-facet-example.component.html
  libs/docs/core/facets/examples/key-value-facet-example.component.html
  libs/docs/core/facets/examples/rating-indicator-facet-example.component.html
  libs/docs/core/facets/facet-docs.component.html
  libs/docs/core/facets/facets-docs.component.ts
  libs/docs/core/grid-list/examples/auto-height/grid-list-auto-height-example.component.scss
  libs/docs/core/grid-list/examples/default/grid-list-example.component.scss
  libs/docs/core/grid-list/examples/default/grid-list-example.component.ts
  libs/docs/core/grid-list/examples/delete/grid-list-delete-example.component.scss
  libs/docs/core/grid-list/examples/dnd/grid-list-dnd-example.component.scss
  libs/docs/core/grid-list/examples/focusing/grid-list-focusing-example.component.scss
  libs/docs/core/grid-list/examples/footer/grid-list-footer-example.component.scss
  libs/docs/core/grid-list/examples/grid-list.component.scss
  libs/docs/core/grid-list/examples/group/grid-list-group-example.component.scss
  libs/docs/core/grid-list/examples/layout/grid-list-layout-example.component.scss
  libs/docs/core/grid-list/examples/more/grid-list-more-example.component.scss
  libs/docs/core/grid-list/examples/multi-select/grid-list-multi-select-example.component.scss
  libs/docs/core/grid-list/examples/single-select-left/grid-list-single-select-left-example.component.scss
  libs/docs/core/grid-list/examples/single-select/grid-list-single-select-example.component.scss
  libs/docs/core/grid-list/examples/states/grid-list-states-example.component.scss
  libs/docs/core/grid-list/examples/statuses/grid-list-statuses-example.component.scss
  libs/docs/core/grid-list/grid-list-docs.component.html
  libs/docs/core/grid-list/grid-list-docs.component.ts
  libs/docs/shared/src/lib/core-helpers/stackblitz/stackblitz-dependencies.ts
Labels: documentation, stackblitz

#11700 docs(core): fix icon stackblitz examples
  libs/docs/core/icon/examples/icon-businessSuiteInAppSymbols-example.component.scss
  libs/docs/core/icon/examples/icon-businessSuiteInAppSymbols-example.component.ts
  libs/docs/core/icon/examples/icon-color-example.component.scss
  libs/docs/core/icon/examples/icon-color-example.component.ts
  libs/docs/core/icon/examples/icon-tnt-example.component.scss
  libs/docs/core/icon/examples/icon-tnt-example.component.ts
  libs/docs/core/icon/icon-docs.component.ts
Labels: documentation, stackblitz

#11701 docs(core): fix illustration msg stackblitz
  libs/docs/core/illustrated-message/examples/illustrated-message-inline-example.component.ts
Labels: documentation, tooling, stackblitz

#11702 docs(core): update info label examples
  libs/docs/core/info-label/examples/info-label-default-example.component.html
  libs/docs/core/info-label/examples/info-label-example.component.html
  libs/docs/core/info-label/examples/info-label-example.component.scss
  libs/docs/core/info-label/examples/info-label-example.component.ts
  libs/docs/core/info-label/examples/info-label-examples.component.ts
  libs/docs/core/info-label/examples/info-label-icon-numeric-example.component.html
  libs/docs/core/info-label/examples/info-label-text-example.component.html
  libs/docs/core/info-label/examples/info-label-text-icon-example.component.html
  libs/docs/core/info-label/info-label-docs.component.html
  libs/docs/core/info-label/info-label-docs.component.ts
Labels: documentation, tooling, stackblitz

#11713 ci: update dependabot.yml
  .github/dependabot.yml
Labels: tooling

#11718 docs(core): input group stackblitz
  libs/docs/core/input-group/input-group-docs.component.ts
Labels: stackblitz

#11719 docs(core): menu stackblitz
  libs/docs/core/menu/menu-docs.component.ts
Labels: stackblitz

#11720 docs(core): message strip stackblitz
  libs/docs/core/message-strip/examples/message-strip-alert-example.component.ts
  libs/docs/core/message-strip/examples/message-strip-auto-dismiss-example.component.ts
  libs/docs/core/message-strip/message-strip-docs.component.html
  libs/docs/core/message-strip/message-strip-docs.component.ts
Labels: stackblitz

#11721 docs(core): micro process flow stackblitz
  libs/docs/core/micro-process-flow/micro-process-flow-docs.component.ts
Labels: stackblitz

#11722 docs(core): multi input stackblitz
  libs/docs/core/multi-input/examples/multi-input-async-example/multi-input-async-example.component.ts
Labels: stackblitz

#11727 docs(core): panel stackblitz update
  libs/docs/core/panel/e2e/panel.e2e-spec.ts
  libs/docs/core/panel/e2e/panel.po.ts
  libs/docs/core/panel/e2e/tsconfig.json
  libs/docs/core/panel/examples/panel-compact-example.component.html
  libs/docs/core/panel/examples/panel-compact-example.component.ts
  libs/docs/core/panel/examples/panel-expandable-example.component.html
  libs/docs/core/panel/examples/panel-expandable-example.component.ts
  libs/docs/core/panel/examples/panel-fixed-example.component.ts
  libs/docs/core/panel/examples/panel-fixed-height-example.component.ts
  libs/docs/core/panel/panel-docs.component.html
  libs/docs/core/panel/panel-docs.component.ts
Labels: stackblitz

#11728 docs(core): popover stackblitz
  libs/docs/core/popover/examples/popover-simple/popover-example.component.ts
  libs/docs/core/popover/popover-docs.component.ts
  libs/docs/core/popover/popover-header/popover-header.component.ts
Labels: stackblitz

#11729 docs(core): radio btn sb
  libs/docs/core/radio/e2e/radio-button.e2e-spec.ts
  libs/docs/core/radio/e2e/radio-button.po.ts
  libs/docs/core/radio/e2e/tsconfig.json
  libs/docs/core/radio/examples/index.ts
  libs/docs/core/radio/examples/radio-example.component.ts
  libs/docs/core/radio/radio-docs.component.ts
Labels: stackblitz, e2e

#11731 docs(core): side nav sb
  libs/docs/core/side-navigation/examples/side-navigation-compact-example.component.html
  libs/docs/core/side-navigation/examples/side-navigation-example.component.html
  libs/docs/core/side-navigation/examples/side-navigation-examples.component.ts
  libs/docs/core/side-navigation/examples/side-navigation-levels-example.component.html
  libs/docs/core/side-navigation/examples/side-navigation-non-selectable-example/side-navigation-non-selectable-example.component.html
  libs/docs/core/side-navigation/examples/side-navigation-non-selectable-example/side-navigation-non-selectable-example.component.ts
  libs/docs/core/side-navigation/examples/side-navigation-three-levels-example/side-navigation-three-levels-example.component.html
  libs/docs/core/side-navigation/examples/side-navigation-three-levels-example/side-navigation-three-levels-example.component.ts
  libs/docs/core/side-navigation/examples/side-navigation-titles-example.component.html
  libs/docs/core/side-navigation/side-navigation-docs.component.html
  libs/docs/core/side-navigation/side-navigation-docs.component.ts
Labels: stackblitz

#11733 chore(release): publish 0.50.0-rc.21
  CHANGELOG.md
  lerna.json
  libs/btp/CHANGELOG.md
  libs/btp/package.json
  libs/cdk/CHANGELOG.md
  libs/cdk/package.json
  libs/core/CHANGELOG.md
  libs/core/package.json
  libs/cx/CHANGELOG.md
  libs/cx/package.json
  libs/datetime-adapter/CHANGELOG.md
  libs/datetime-adapter/package.json
  libs/i18n/CHANGELOG.md
  libs/i18n/package.json
  libs/moment-adapter/CHANGELOG.md
  libs/moment-adapter/package.json
  libs/nx-plugin/CHANGELOG.md
  libs/nx-plugin/package.json
  libs/platform/CHANGELOG.md
  libs/platform/package.json
Labels: tooling

#11735 docs(core): status indicator sb
  libs/docs/core/status-indicator/e2e/status-indicator.e2e-spec.ts
  libs/docs/core/status-indicator/e2e/status-indicator.po.ts
  libs/docs/core/status-indicator/e2e/tsconfig.json
  libs/docs/core/status-indicator/examples/status-indicator-circular-fill-anti-clockwise.component.html
  libs/docs/core/status-indicator/examples/status-indicator-circular-fill-anti-clockwise.component.ts
  libs/docs/core/status-indicator/examples/status-indicator-circular-fill-clockwise.component.html
  libs/docs/core/status-indicator/examples/status-indicator-circular-fill-clockwise.component.ts
  libs/docs/core/status-indicator/status-indicator-docs.component.html
  libs/docs/core/status-indicator/status-indicator-docs.component.ts
Labels: stackblitz

#11734 docs(core): slider sb
  libs/docs/core/slider/slider-docs.component.html
  libs/docs/core/slider/slider-docs.component.ts
Labels: stackblitz

#11736 docs(core): table stackblitz
  libs/docs/core/table/table-docs.component.ts
Labels: stackblitz

#11740 docs(core): tabs stackblitz
  libs/docs/core/tabs/examples/adding-tab-example/adding-tab-example.component.html
  libs/docs/core/tabs/examples/index.ts
  libs/docs/core/tabs/examples/tab-collapsible-overflow-example/tab-collapsible-overflow-example.component.html
  libs/docs/core/tabs/examples/tab-collapsible-overflow-example/tab-collapsible-overflow-example.component.ts
  libs/docs/core/tabs/examples/tab-counter-example/tab-counter-example.component.html
  libs/docs/core/tabs/examples/tab-counter-example/tab-counter-example.component.ts
  libs/docs/core/tabs/examples/tab-filter-example/tab-filter-example.component.html
  libs/docs/core/tabs/examples/tab-filter-example/tab-filter-example.component.ts
  libs/docs/core/tabs/examples/tab-form-element-example/tab-form-element-example.component.html
  libs/docs/core/tabs/examples/tab-form-element-example/tab-form-element-example.component.ts
  libs/docs/core/tabs/examples/tab-icon-only-example/tab-icon-only-example.component.html
  libs/docs/core/tabs/examples/tab-icon-only-example/tab-icon-only-example.component.ts
  libs/docs/core/tabs/examples/tab-process-example/tab-process-example.component.html
  libs/docs/core/tabs/examples/tab-process-example/tab-process-example.component.ts
  libs/docs/core/tabs/examples/tab-selection-example/tab-selection-example.component.html
  libs/docs/core/tabs/examples/tab-selection-example/tab-selection-example.component.ts
  libs/docs/core/tabs/examples/tab-stacked-content-example/tab-stacked-content-example.component.ts
  libs/docs/core/tabs/examples/tabs-example/tabs-example.component.html
  libs/docs/core/tabs/examples/tabs-example/tabs-example.component.ts
  libs/docs/core/tabs/tabs-docs.component.html
  libs/docs/core/tabs/tabs-docs.component.ts
  libs/docs/core/tabs/tabs-header/tabs-header.component.html
Labels: documentation, stackblitz

#11742 docs(core): tiles sb
  libs/docs/core/tile/e2e/tile.e2e-spec.ts
  libs/docs/core/tile/e2e/tile.po.ts
  libs/docs/core/tile/e2e/tsconfig.json
  libs/docs/core/tile/examples/action-tile-example.component.html
  libs/docs/core/tile/examples/badge-tile-example.component.html
  libs/docs/core/tile/examples/clickable-tile-example.component.html
  libs/docs/core/tile/examples/feed-tile-example.component.html
  libs/docs/core/tile/examples/kpi-tile-example.component.html
  libs/docs/core/tile/examples/kpi-tile-example.component.ts
  libs/docs/core/tile/examples/launch-tile-example.component.html
  libs/docs/core/tile/examples/launch-tile-example.component.scss
  libs/docs/core/tile/examples/launch-tile-example.component.ts
  libs/docs/core/tile/examples/line-tile-example.component.html
  libs/docs/core/tile/examples/misc-tile-example.component.html
  libs/docs/core/tile/examples/misc-tile-example.component.ts
  libs/docs/core/tile/examples/slide-tile-example.component.html
  libs/docs/core/tile/examples/tile-columns-example.component.html
  libs/docs/core/tile/examples/tile-columns-example.component.ts
  libs/docs/core/tile/examples/tile-examples.component.ts
  libs/docs/core/tile/examples/tile-generic-example.component.html
  libs/docs/core/tile/examples/tile-generic-example.component.ts
  libs/docs/core/tile/tile-docs.component.html
  libs/docs/core/tile/tile-docs.component.ts
Labels: stackblitz

#11760 test(core): remove slide tile unit
  libs/core/tile/directives/tile.directives.spec.ts
Labels: unit tests

#11763 test(core): remove compact time picker e2e
  libs/docs/core/time-picker/e2e/time-picker.e2e-spec.ts
  libs/docs/core/time-picker/e2e/time-picker.po.ts
Labels: testing, e2e

#11764 docs(core): timeline stackblitz
  libs/docs/core/timeline/timeline-docs.component.ts
Labels: stackblitz

#11765 test(core): tree stackblitz
  libs/docs/core/tree/tree-docs.component.ts
Labels: stackblitz

#11766 fix(core): deprecate vertical nav + stackblitz fix
  libs/core/vertical-navigation/vertical-navigation.component.ts
  libs/docs/core/side-navigation/e2e/side-navigation-content.ts
  libs/docs/core/side-navigation/e2e/side-navigation.e2e-spec.ts
  libs/docs/core/side-navigation/e2e/side-navigation.po.ts
  libs/docs/core/side-navigation/e2e/tsconfig.json
  libs/docs/core/side-navigation/side-navigation-header/side-navigation-header.component.html
  libs/docs/core/side-navigation/side-navigation-header/side-navigation-header.component.ts
  libs/docs/core/vertical-navigation/vertical-navigation-docs.component.ts
  libs/docs/core/vertical-navigation/vertical-navigation-header/vertical-navigation-header.component.html
  libs/docs/core/vertical-navigation/vertical-navigation-header/vertical-navigation-header.component.ts
Labels: stackblitz

#11768 test(core): tabs test e2e fix
  libs/docs/core/tabs/e2e/tabs.po.ts
Labels: e2e

#11762 fix(core): step input unit test
  libs/core/step-input/step-input.component.spec.ts
Labels: unit tests

#11772 chore(ci): introduce daily e2e/unit run without cache
  .github/workflows/testing.yml
Labels: tooling, unit tests, E2E automation, e2e

#11773 docs(core): dynamic-page stackblitz
  libs/docs/core/dynamic-page/dynamic-page-docs.component.html
  libs/docs/core/dynamic-page/dynamic-page-docs.component.ts
  libs/docs/core/dynamic-page/e2e/dynamic-page.po.ts
  libs/docs/core/dynamic-page/examples/dynamic-page-example.component.ts
Labels: stackblitz

#11774 docs(core): shellbar stackblitz
  libs/docs/core/shellbar/shellbar-docs.component.ts
Labels: stackblitz

#11775 docs(core): flexible column layout stackblitz
  libs/docs/core/flexible-column-layout/flexible-column-layout-docs.component.ts
Labels: stackblitz

#11776 docs(core): layout grid sb
  libs/docs/core/layout-grid/layout-grid-docs.component.ts
Labels: stackblitz

#11777 docs(core): overflow layout stackblitz
  libs/docs/core/overflow-layout/examples/complex/avatar-generator-example.service.ts
  libs/docs/core/overflow-layout/examples/complex/overflow-layout-complex-example.component.ts
  libs/docs/core/overflow-layout/overflow-layout-docs.component.ts
Labels: stackblitz

#11778 docs(core): theming stackblitz
  libs/docs/core/theming/examples/theming-example.component.ts
  libs/docs/core/theming/examples/theming-url-example.component.ts
  libs/docs/core/theming/theming-docs.component.ts
Labels: stackblitz

#11779 docs(core): truncate stackblitz
  libs/docs/core/truncate/truncate-docs.component.ts
Labels: stackblitz

#11784 chore(ci): update testing.yml
  .github/workflows/testing.yml
Labels: tooling, test automation

#11786 docs: remove moment-datetime-adapter stackblitz
  libs/docs/core/moment-datetime-adapter/e2e/moment-datetime-adapter.e2e-spec.ts
  libs/docs/core/moment-datetime-adapter/e2e/tsconfig.json
  libs/docs/core/moment-datetime-adapter/moment-datetime-adapter-docs.component.html
  libs/docs/core/moment-datetime-adapter/moment-datetime-adapter-docs.component.ts
Labels: stackblitz

#11767 fix(core): a11y improvements for Dynamic page header
  libs/core/dynamic-page/dynamic-page-header/header/dynamic-page-header.component.html
  libs/core/dynamic-page/dynamic-page-header/header/dynamic-page-header.component.ts
  libs/core/dynamic-page/dynamic-page-header/subheader/dynamic-page-subheader.component.html
  libs/core/dynamic-page/dynamic-page-header/subheader/dynamic-page-subheader.component.ts
  libs/core/dynamic-page/dynamic-page.component.html
  libs/core/dynamic-page/dynamic-page.component.ts
  libs/platform/dynamic-page/dynamic-page-header/title/dynamic-page-title.component.spec.ts
  package.json
  yarn.lock
Labels: accessibility, sourcing

#11787 docs(core): status indicator stackblitz
  libs/docs/core/status-indicator/examples/status-indicator-clickable-type.component.ts
  libs/docs/core/status-indicator/status-indicator-docs.component.html
  libs/docs/core/status-indicator/status-indicator-docs.component.ts
Labels: stackblitz

#11802 fix(platform): header cell popover freeze button should be keydown, n…
  libs/platform/table/components/table-cell-header-popover/table-cell-header-popover.component.html
Labels: accessibility

#11803 chore(deps): fundamental-styles v0.35.1 and theming-base-content v11.…
  libs/docs/core/icon/examples/icon-tnt-example.component.ts
  package.json
  yarn.lock
Labels: dependencies, theming

#11801 fix(platform): header cell popover freeze button should be keydown
  libs/platform/src/lib/table/components/table-cell-header-popover/table-cell-header-popover.component.html
Labels: bug

#11804 docs(platform): approval flow sb
  libs/docs/platform/approval-flow/examples/platform-approval-flow-custom-status-example.component.ts
  libs/docs/platform/approval-flow/examples/platform-approval-flow-example.component.ts
  libs/docs/platform/approval-flow/platform-approval-flow-docs.component.html
Labels: stackblitz

#11805 docs(platform): button stackblitz
  libs/docs/platform/button/e2e/button.e2e-spec.ts
  libs/docs/platform/button/e2e/button.po.ts
  libs/docs/platform/button/e2e/tsconfig.json
  libs/docs/platform/button/examples/platform-button-examples.component.ts
  libs/docs/platform/button/examples/platform-button-sizes-example.component.html
  libs/docs/platform/button/examples/platform-button-state-example.component.html
  libs/docs/platform/button/platform-button-docs.component.html
  libs/docs/platform/button/platform-button-docs.component.ts
Labels: stackblitz

#11806 docs(platform): datepicker sb
  libs/docs/platform/date-picker/examples/mobile/platform-date-picker-mobile-example.component.ts
  libs/docs/platform/date-picker/platform-date-picker-docs.component.ts
Labels: stackblitz

#11807 docs(platform): datetime picker stackblitz
  libs/docs/platform/datetime-picker/examples/mobile/platform-datetime-picker-mobile-example.component.ts
  libs/docs/platform/datetime-picker/platform-datetime-picker-docs.component.ts
Labels: stackblitz

#11808 docs(platform): icon tab bar stackblitz
  libs/docs/platform/icon-tab-bar/e2e/icon-tab-bar.po.ts
  libs/docs/platform/icon-tab-bar/examples/platform-icon-tab-bar-configurable-paddings-example/platform-icon-tab-bar-configurable-paddings-example.component.ts
  libs/docs/platform/icon-tab-bar/examples/platform-icon-tab-bar-filter-type-example/platform-icon-tab-bar-filter-type-example.component.ts
  libs/docs/platform/icon-tab-bar/examples/platform-icon-tab-bar-icon-only-type-example/platform-icon-tab-bar-icon-only-type-example.component.ts
  libs/docs/platform/icon-tab-bar/examples/platform-icon-tab-bar-icon-type-example/platform-icon-tab-bar-icon-type-example.component.ts
  libs/docs/platform/icon-tab-bar/examples/platform-icon-tab-bar-process-type-example/platform-icon-tab-bar-process-type-example.component.ts
  libs/docs/platform/icon-tab-bar/examples/platform-icon-tab-bar-text-type-example/platform-icon-tab-bar-text-type-example.component.ts
  libs/docs/platform/icon-tab-bar/platform-icon-tab-bar-docs.component.html
  libs/docs/platform/icon-tab-bar/platform-icon-tab-bar-docs.component.ts
Labels: stackblitz

#11816 docs(platform): info label examples cleanup
  libs/docs/platform/info-label/examples/platform-info-label-aria-label-example.component.html
  libs/docs/platform/info-label/examples/platform-info-label-example.component.html
  libs/docs/platform/info-label/examples/platform-info-label-example.component.scss
  libs/docs/platform/info-label/examples/platform-info-label-example.component.ts
  libs/docs/platform/info-label/examples/platform-info-label-numeric-example.component.html
  libs/docs/platform/info-label/examples/platform-info-label-text-and-icon-example.component.html
  libs/docs/platform/info-label/examples/platform-info-label-text-example.component.html
  libs/docs/platform/info-label/platform-info-label-docs.component.html
  libs/docs/platform/info-label/platform-info-label-docs.component.ts
Labels: stackblitz

#11813 fix(platform): prevent keyboard press on checkbox header cell from scrolling page
  libs/platform/src/lib/table/components/table-header-row/table-header-row.component.html
Labels: ng15

#11820 docs(platform): input group stackblitz
  libs/docs/platform/input-group/e2e/input-group.po.ts
  libs/docs/platform/input-group/examples/platform-input-group-form-example.component.ts
  libs/docs/platform/input-group/platform-input-group-docs.component.html
  libs/docs/platform/input-group/platform-input-group-docs.component.ts
Labels: stackblitz

#11821 docs(platform): fdp link stackblitz and docs
  libs/docs/platform/link/e2e/link-page-contents.ts
  libs/docs/platform/link/e2e/link.e2e-spec.ts
  libs/docs/platform/link/e2e/link.po.ts
  libs/docs/platform/link/e2e/tsconfig.json
  libs/docs/platform/link/examples/platform-link-disabled-emphasized-example.component.html
  libs/docs/platform/link/examples/platform-link-disabled-example.component.html
  libs/docs/platform/link/examples/platform-link-emphasized-example.component.html
  libs/docs/platform/link/examples/platform-link-example.component.html
  libs/docs/platform/link/examples/platform-link-example.component.ts
  libs/docs/platform/link/examples/platform-link-examples.component.ts
  libs/docs/platform/link/examples/platform-link-icon-example.component.html
  libs/docs/platform/link/examples/platform-link-inverted-example.component.html
  libs/docs/platform/link/examples/platform-link-standard-example.component.html
  libs/docs/platform/link/examples/platform-link-truncated-example.component.html
  libs/docs/platform/link/platform-link-docs.component.html
  libs/docs/platform/link/platform-link-docs.component.ts
Labels: stackblitz

#11737 fix(core): keyboard enhancements for grid list
  libs/core/grid-list/components/grid-list-item/grid-list-item.component.html
  libs/core/grid-list/components/grid-list-item/grid-list-item.component.ts
  libs/core/grid-list/components/grid-list/grid-list.component.html
  libs/core/grid-list/components/grid-list/grid-list.component.spec.ts
  libs/core/grid-list/components/grid-list/grid-list.component.ts
  libs/docs/core/grid-list/grid-list-header/grid-list-header.component.html
Labels: accessibility

#11817 fix(platform): table toolbar not passing aria label input to search field
  libs/platform/src/lib/table/components/table-toolbar/table-toolbar.component.html
Labels: ng15

#11826 docs(platform): fdp menu stackblitz
  libs/docs/platform/menu/platform-menu-docs.component.ts
Labels: stackblitz

#11827 docs(platform): menu button stackblitz
  libs/docs/platform/menu-button/e2e/menu-button-contents.ts
  libs/docs/platform/menu-button/e2e/menu-button.e2e-spec.ts
  libs/docs/platform/menu-button/e2e/menu-button.po.ts
  libs/docs/platform/menu-button/examples/platform-menu-button-compact-examples.component.ts
  libs/docs/platform/menu-button/examples/platform-menu-button-cozy-example.component.html
  libs/docs/platform/menu-button/examples/platform-menu-button-example.component.ts
  libs/docs/platform/menu-button/examples/platform-menu-button-state-example.component.html
  libs/docs/platform/menu-button/examples/platform-menu-button-state-example.component.ts
  libs/docs/platform/menu-button/platform-menu-button-docs.component.html
  libs/docs/platform/menu-button/platform-menu-button-docs.component.ts
Labels: stackblitz

#11838 docs(platform): message popover stackblitz
  libs/docs/platform/message-popover/examples/default/message-popover-default-example.component.ts
  libs/docs/platform/message-popover/examples/form-container/form-container-example.component.ts
  libs/docs/platform/message-popover/examples/form-generator/form-generator-component-example.component.ts
  libs/docs/platform/message-popover/message-popover-docs.component.html
  libs/docs/platform/message-popover/message-popover-docs.component.ts
Labels: stackblitz

#11839 docs(platform): object status stackblitz
  libs/docs/platform/object-status/e2e/object-status-contents.ts
  libs/docs/platform/object-status/e2e/object-status.e2e-spec.ts
  libs/docs/platform/object-status/e2e/object-status.po.ts
  libs/docs/platform/object-status/e2e/tsconfig.json
  libs/docs/platform/object-status/examples/platform-object-status-example.component.ts
  libs/docs/platform/object-status/examples/platform-object-status-generic-text-example.component.ts
  libs/docs/platform/object-status/examples/platform-object-status-inverted-generic-text-example.component.ts
  libs/docs/platform/object-status/platform-object-status-docs.component.html
  libs/docs/platform/object-status/platform-object-status-docs.component.ts
Labels: stackblitz

#11840 docs(platform): panel stackblitz
  libs/docs/platform/panel/e2e/panel-page-content.ts
  libs/docs/platform/panel/e2e/panel.e2e-spec.ts
  libs/docs/platform/panel/e2e/panel.po.ts
  libs/docs/platform/panel/e2e/tsconfig.json
  libs/docs/platform/panel/examples/platform-panel-compact-example.component.html
  libs/docs/platform/panel/examples/platform-panel-compact-example.component.ts
  libs/docs/platform/panel/platform-panel-docs.component.html
  libs/docs/platform/panel/platform-panel-docs.component.ts
Labels: stackblitz

#11844 docs(platform): slider stackblitz
  libs/docs/platform/slider/e2e/slider.e2e-spec.ts
  libs/docs/platform/slider/e2e/slider.po.ts
  libs/docs/platform/slider/examples/cozy/slider-cozy-example.component.html
  libs/docs/platform/slider/examples/cozy/slider-cozy-example.component.ts
  libs/docs/platform/slider/slider-docs.component.html
  libs/docs/platform/slider/slider-docs.component.ts
Labels: stackblitz

#11845 docs(platform): dynamic page stackblitz
  libs/docs/platform/dynamic-page/examples/platform-dynamic-page-facets-example.component.html
  libs/docs/platform/dynamic-page/examples/platform-dynamic-page-facets-example.component.scss
  libs/docs/platform/dynamic-page/examples/platform-dynamic-page-facets-example.component.ts
  libs/docs/platform/dynamic-page/platform-dynamic-page-docs.component.ts
Labels: stackblitz

#11846 docs(platform): action list item stackblit
  libs/docs/platform/action-list-item/e2e/action-list-item-contents.ts
  libs/docs/platform/action-list-item/e2e/action-list-item.e2e-spec.ts
  libs/docs/platform/action-list-item/e2e/action-list-item.po.ts
  libs/docs/platform/action-list-item/e2e/tsconfig.json
  libs/docs/platform/action-list-item/examples/platform-action-list-item-border-less-example.component.html
  libs/docs/platform/action-list-item/examples/platform-action-list-item-example.component.ts
Labels: stackblitz

#11823 docs(platform): fdp link examples
  libs/docs/platform/link/examples/platform-link-example.component.html
  libs/docs/platform/link/examples/platform-link-example.component.ts
  libs/docs/platform/link/examples/platform-link-misc-examples.component.html
  libs/docs/platform/link/examples/platform-link-misc-examples.component.ts
  libs/docs/platform/link/examples/platform-link-types-example.component.html
  libs/docs/platform/link/examples/platform-link-types-example.component.ts
  libs/docs/platform/link/platform-link-docs.component.html
  libs/docs/platform/link/platform-link-docs.component.ts
Labels: documentation

#11849 docs(platform): object list item stackblitz
  libs/docs/platform/object-list-item/examples/platform-object-list-item-border-less-example.component.ts
Labels: stackblitz

#11850 docs(platform): list stackblitz
  libs/docs/platform/list/e2e/list-contents.ts
  libs/docs/platform/list/e2e/list.e2e-spec.ts
  libs/docs/platform/list/e2e/list.po.ts
  libs/docs/platform/list/examples/platform-list-border-less-example.component.html
  libs/docs/platform/list/examples/platform-list-free-content-example.component.ts
  libs/docs/platform/list/examples/platform-list-with-footer-example.component.html
  libs/docs/platform/list/examples/platform-list-with-group-header-example.component.html
  libs/docs/platform/list/examples/platform-list-with-item-counter-example.component.html
  libs/docs/platform/list/examples/platform-list-with-navigation-example.component.html
  libs/docs/platform/list/examples/platform-list-with-nodata-example.component.html
  libs/docs/platform/list/platform-list-docs.component.html
  libs/docs/platform/list/platform-list-docs.component.ts
Labels: stackblitz

#11853 docs(platform): standard list stackblitz
  libs/docs/platform/standard-list-item/e2e/standard-list-item.e2e-spec.ts
  libs/docs/platform/standard-list-item/examples/platform-standard-list-item-border-less-example.component.html
  libs/docs/platform/standard-list-item/examples/platform-standard-list-item-example.component.html
  libs/docs/platform/standard-list-item/examples/platform-standard-list-unread-example.component.html
  libs/docs/platform/standard-list-item/platform-standard-list-item-docs.component.html
  libs/docs/platform/standard-list-item/platform-standard-list-item-docs.component.ts
Labels: stackblitz

#11855 docs(platform): settings generator stackblitz
  libs/docs/platform/settings-generator/examples/custom-layout/settings-generator-custom-layout-example.component.ts
  libs/docs/platform/settings-generator/examples/dialog/settings-generator-dialog-example.component.ts
  libs/docs/platform/settings-generator/settings-generator-docs.component.ts
Labels: stackblitz

#11857 docs(platform): variant management stackblitz
  libs/docs/platform/variant-management/variant-management-docs.component.ts
Labels: stackblitz

#11858 docs(platform): value-help dialog stackblitz
  libs/docs/platform/vhd/platform-vhd.docs.component.ts
Labels: stackblitz
