Repository SAP/fundamental-ngx, pull requests merged in 2024-01, with the labels that each got.

#11143 fix(core): dynamically render search field
  libs/core/shellbar/shellbar-actions-mobile/shellbar-actions-mobile.component.ts
  libs/core/shellbar/shellbar.component.ts
  libs/docs/core/shellbar/examples/shellbar-collapsible-example.component.html
  libs/docs/core/shellbar/examples/shellbar-collapsible-example.component.ts
Labels: bug, core

#11144 fix(core): toolbar title styling
  libs/core/toolbar/toolbar.component.html
  libs/core/toolbar/toolbar.component.ts
  package.json
  yarn.lock
Labels: bug, core

#11122 fix(platform): settings generator style update
  libs/cdk/utils/directives/overflow-list/overflow-list.directive.ts
  libs/cdk/utils/pipes/async-or-sync.pipe.ts
  libs/docs/platform/settings-generator/examples/custom-control/settings-generator-custom-control-example.component.ts
  libs/docs/platform/settings-generator/examples/default/settings-generator-default-example.component.ts
  libs/docs/platform/settings-generator/examples/dialog/settings-generator-dialog-example.component.ts
  libs/docs/platform/settings-generator/examples/message-popover/settings-generator-message-popover-example.component.ts
  libs/platform/form/form-generator/interfaces/dynamic-form-item.ts
  libs/platform/icon-tab-bar/components/closable-icon-tab-bar.class.ts
  libs/platform/icon-tab-bar/components/icon-tab-bar-base.class.ts
  libs/platform/icon-tab-bar/components/icon-tab-bar-filter-type/icon-tab-bar-filter-type.component.html
  libs/platform/icon-tab-bar/components/icon-tab-bar-filter-type/icon-tab-bar-filter-type.component.ts
  libs/platform/icon-tab-bar/components/icon-tab-bar-icon-type/icon-tab-bar-icon-type.component.html
  libs/platform/icon-tab-bar/components/icon-tab-bar-process-type/icon-tab-bar-process-type.component.html
  libs/platform/icon-tab-bar/components/icon-tab-bar-process-type/icon-tab-bar-process-type.component.spec.ts
  libs/platform/icon-tab-bar/components/icon-tab-bar-process-type/icon-tab-bar-process-type.component.ts
  libs/platform/icon-tab-bar/components/icon-tab-bar-text-type/icon-tab-bar-text-type.component.html
  libs/platform/icon-tab-bar/components/icon-tab-bar-text-type/icon-tab-bar-text-type.component.spec.ts
  libs/platform/icon-tab-bar/components/icon-tab-bar-text-type/icon-tab-bar-text-type.component.ts
  libs/platform/icon-tab-bar/interfaces/tab-config.interface.ts
  libs/platform/settings-generator/default-config.ts
  libs/platform/settings-generator/models/settings.model.ts
  libs/platform/settings-generator/settings-generator-content/settings-generator-content.component.html
  libs/platform/settings-generator/settings-generator-content/settings-generator-content.component.ts
  libs/platform/settings-generator/settings-generator.component.scss
Labels: enhancement, platform

#11148 fix(core): non-focusable object status
  libs/core/src/lib/file-uploader/file-uploader.component.ts
  libs/core/src/lib/object-status/object-status.component.ts
  libs/platform/src/lib/table/table.component.ts
Labels: bug, core, ng16

#11115 fix(platform): combobox selection issue
  libs/platform/src/lib/form/combobox/combobox/combobox.component.spec.ts
  libs/platform/src/lib/form/combobox/combobox/combobox.component.ts
  libs/platform/src/lib/shared/form/collection-base.input.ts
Labels: bug

#11173 fix(docs): add missing font
  apps/docs/src/styles.scss
  libs/cx/schematics/ng-add/styles.ts
  libs/docs/shared/src/lib/core-helpers/stackblitz/code-example-stack/styles.scss
Labels: documentation

#11182 fix(core): dayjs utc offset fix
  libs/core/calendar/calendar-header/calendar-header.component.ts
  libs/core/calendar/calendar-views/calendar-day-view/calendar-day-view.component.ts
  libs/core/datetime/datetime-adapter.ts
  libs/datetime-adapter/src/lib/dayjs-datetime-adapter.ts
  libs/moment-adapter/src/lib/moment-datetime-adapter.ts
  package.json
  yarn.lock
Labels: bug

#11184 fix: add addonIconTitle input to multi input
  libs/core/multi-input/multi-input.component.html
  libs/core/multi-input/multi-input.component.ts
  libs/platform/form/multi-input/multi-input.component.html
  libs/platform/form/multi-input/multi-input.component.ts
Labels: bug

#11197 fix(platform): corrected translations
  libs/i18n/src/lib/models/lang.ts
  libs/i18n/src/lib/translations/translations.ts
  libs/platform/table/components/table-cell-header-popover/table-cell-header-popover.component.html
  libs/platform/table/components/table-cell-header-popover/table-cell-header-popover.component.ts
  libs/platform/table/components/table-header-row/table-header-row.component.html
  libs/platform/table/table.component.html
  libs/platform/table/table.component.ts
Labels: platform, sourcing, table, i18n

#11176 chore(docs): added missing languages into the toolbar
  apps/docs/src/environments/translations.prod.ts
  apps/docs/src/environments/translations.ts
Labels: documentation, i18n

#11172 feat(platform): ariaLabel priority over the ariaLabelledBy
  libs/platform/search-field/search-field.component.html
  libs/platform/table/components/table-toolbar/table-toolbar.component.html
  libs/platform/table/components/table-toolbar/table-toolbar.component.ts
Labels: accessibility, platform

#11196 fix(cdk): tabbable observer out of the zone
  libs/cdk/src/lib/utils/directives/focusable-item/focusable-item.directive.ts
  libs/cdk/src/lib/utils/services/observers/attribute.observer.ts
  libs/platform/src/lib/table/components/table-p13-dialog/columns/columns.component.html
Labels: ng15

#11205 fix(platform): corrected translations
  libs/i18n/src/lib/languages/albanian.ts
  libs/i18n/src/lib/languages/arabic.ts
  libs/i18n/src/lib/languages/bulgarian.ts
  libs/i18n/src/lib/languages/chinese.ts
  libs/i18n/src/lib/languages/chinese_traditional.ts
  libs/i18n/src/lib/languages/croatian.ts
  libs/i18n/src/lib/languages/czech.ts
  libs/i18n/src/lib/languages/danish.ts
  libs/i18n/src/lib/languages/dutch.ts
  libs/i18n/src/lib/languages/english.ts
  libs/i18n/src/lib/languages/finnish.ts
  libs/i18n/src/lib/languages/french.ts
  libs/i18n/src/lib/languages/georgian.ts
  libs/i18n/src/lib/languages/german.ts
  libs/i18n/src/lib/languages/greek.ts
  libs/i18n/src/lib/languages/hebrew.ts
  libs/i18n/src/lib/languages/hindi.ts
  libs/i18n/src/lib/languages/hungarian.ts
  libs/i18n/src/lib/languages/index.ts
  libs/i18n/src/lib/languages/italian.ts
  libs/i18n/src/lib/languages/japanese.ts
  libs/i18n/src/lib/languages/kazakh.ts
  libs/i18n/src/lib/languages/korean.ts
  libs/i18n/src/lib/languages/malay.ts
  libs/i18n/src/lib/languages/norwegian.ts
  libs/i18n/src/lib/languages/polish.ts
  libs/i18n/src/lib/languages/portuguese.ts
  libs/i18n/src/lib/languages/romanian.ts
  libs/i18n/src/lib/languages/russian.ts
  libs/i18n/src/lib/languages/serbian.ts
  libs/i18n/src/lib/languages/slovak.ts
  libs/i18n/src/lib/languages/slovenian.ts
  libs/i18n/src/lib/languages/spanish.ts
  libs/i18n/src/lib/languages/swedish.ts
  libs/i18n/src/lib/languages/thai.ts
  libs/i18n/src/lib/languages/turkish.ts
  libs/i18n/src/lib/languages/ukrainian.ts
  libs/i18n/src/lib/models/lang.ts
  libs/platform/src/lib/table/components/table-cell-header-popover/table-cell-header-popover.component.html
  libs/platform/src/lib/table/components/table-cell-header-popover/table-cell-header-popover.component.ts
  libs/platform/src/lib/table/components/table-header-row/table-header-row.component.html
Labels: ng15

#11228 fix(platform): tree table text overflow
  libs/platform/table/table.component.scss
Labels: platform, table

#11231 fix(platform): tree table text overflow
  libs/platform/src/lib/table/table.component.scss
Labels: ng15

#11203 feat(platform): ariaLabel priority over the ariaLabelledBy (#11172)
  libs/platform/src/lib/search-field/search-field.component.html
  libs/platform/src/lib/table/components/table-toolbar/table-toolbar.component.html
  libs/platform/src/lib/table/components/table-toolbar/table-toolbar.component.ts
Labels: accessibility, platform, ariba, ng15

#11185 fix: add addonIconTitle input to multi input
  libs/core/src/lib/multi-input/multi-input.component.html
  libs/core/src/lib/multi-input/multi-input.component.ts
  libs/platform/src/lib/form/multi-input/multi-input.component.html
  libs/platform/src/lib/form/multi-input/multi-input.component.ts
Labels: ng15

#11200 fix(core): aria-hidden tokenizer if tokenList length is 0
  libs/core/src/lib/token/tokenizer.component.html
Labels: ng15

#11113 chore(docs): splitter docs fixes
  libs/core/src/lib/splitter/README.md
  libs/docs/core/splitter/e2e/splitter.e2e-spec.ts
  libs/docs/core/splitter/e2e/spltiller.po.ts
  libs/docs/core/splitter/examples/api/splitter-api-example.component.ts
  libs/docs/core/splitter/examples/default/splitter-default-example.component.ts
  libs/docs/core/splitter/examples/required-parent-width/splitter-required-parent-width-example.component.ts
  libs/docs/core/splitter/splitter-docs.component.html
  libs/docs/core/splitter/splitter-docs.module.ts
  libs/docs/core/splitter/splitter-header/splitter-header.component.ts
Labels: documentation, core, ng15

#11233 fix(platform): vhd content min height
  libs/platform/value-help-dialog/value-help-dialog/value-help-dialog.component.scss
Labels: bug, platform

#11236 fix(platform): unfrozen area min width
  libs/docs/platform/table/examples/platform-table-freezable-example.component.html
  libs/platform/src/lib/table-helpers/services/table-column-resize.service.ts
  libs/platform/src/lib/table/table.component.ts
  libs/platform/src/lib/value-help-dialog/value-help-dialog/value-help-dialog.component.scss
Labels: ng15

#11237 fix(platform): initial visible columns
  libs/platform/table-helpers/directives/table-initial-state.directive.ts
Labels: bug, platform, table

#11238 fix(platform): initial visible columns
  libs/platform/src/lib/table-helpers/directives/table-initial-state.directive.ts
Labels: ng15

#11239 feat(core,docs): dynamic page tabbed routing
  libs/docs/core/dynamic-page/dynamic-page-docs.component.html
  libs/docs/core/dynamic-page/dynamic-page-docs.component.ts
  libs/docs/core/dynamic-page/examples/dynamic-page-routing/dynamic-page-routing-example.component.html
  libs/docs/core/dynamic-page/examples/dynamic-page-routing/dynamic-page-routing-example.component.ts
  libs/docs/core/dynamic-page/index.ts
  libs/platform/icon-tab-bar/directives/icon-tab-bar-free-content.directive.ts
  libs/platform/icon-tab-bar/icon-tab-bar.component.html
  libs/platform/icon-tab-bar/icon-tab-bar.module.ts
  libs/platform/icon-tab-bar/index.ts
Labels: enhancement, documentation

#11298 feat(platform): vhd validator
  libs/docs/platform/vhd/examples/platform-vhd-basic-example.component.html
  libs/docs/platform/vhd/examples/platform-vhd-basic-example.component.ts
  libs/docs/platform/vhd/platform-vhd.docs.component.html
  libs/platform/value-help-dialog/value-help-dialog/value-help-dialog.component.html
  libs/platform/value-help-dialog/value-help-dialog/value-help-dialog.component.ts
Labels: enhancement, platform

#11175 fix(platform): selection header column width bug
  libs/platform/table/table.component.ts
Labels: bug

#11300 chore: delete cache during netlify build for ng15
  netlify.toml
Labels: ng15

#11303 feat(platform): vhd validator
  libs/docs/platform/vhd/examples/platform-vhd-basic-example.component.html
  libs/docs/platform/vhd/examples/platform-vhd-basic-example.component.ts
  libs/docs/platform/vhd/platform-vhd-docs.module.ts
  libs/docs/platform/vhd/platform-vhd.docs.component.html
  libs/platform/src/lib/value-help-dialog/value-help-dialog/value-help-dialog.component.html
  libs/platform/src/lib/value-help-dialog/value-help-dialog/value-help-dialog.component.ts
Labels: ng15

#11308 fix(core,docs,platform): various defect hunting issues
  libs/core/action-sheet/action-sheet-body/action-sheet-body.component.ts
  libs/core/action-sheet/action-sheet-item/action-sheet-item.component.html
  libs/core/action-sheet/action-sheet-item/action-sheet-item.component.ts
  libs/core/checkbox/checkbox/checkbox.component.html
  libs/core/checkbox/checkbox/checkbox.component.scss
  libs/core/date-picker/date-picker.component.html
  libs/core/date-picker/date-picker.component.ts
  libs/core/dialog/dialog-default/dialog-default.component.html
  libs/core/dialog/dialog-full-screen-toggler-button/dialog-full-screen-toggler-button.component.ts
  libs/core/dialog/dialog.component.ts
  libs/core/file-uploader/file-uploader.component.ts
  libs/core/message-strip/alert/default-config.ts
  libs/core/message-strip/alert/message-strip-alert.service.ts
  libs/core/message-strip/alert/message-strip-alert/message-strip-alert.component.ts
  libs/core/message-strip/alert/open-message-strip-alert.config.ts
  libs/core/message-strip/alert/tokens.ts
  libs/core/popover/base/base-popover.class.ts
  libs/core/popover/popover-service/popover.service.ts
  libs/docs/core/dialog/examples/dialog-full-screen/dialog-full-screen-example.component.html
  libs/docs/core/feed-input/examples/feed-input-disabled-example/feed-input-disabled-example.component.html
  libs/docs/core/feed-input/examples/feed-input-example/feed-input-example.component.html
  libs/docs/core/feed-input/examples/feed-input-grow-example/feed-input-grow-example.component.html
  libs/docs/core/feed-list-item/examples/fli-avatar/fli-avatar-example.component.html
  libs/docs/core/feed-list-item/examples/fli-mobile/fli-mobile-example.component.html
  libs/docs/core/list/examples/list-example.component.html
  libs/docs/core/list/examples/list-examples.component.ts
  libs/docs/core/message-strip/examples/message-strip-alert-example.component.ts
  libs/docs/platform/feed-input/examples/platform-feed-input-disabled-example/platform-feed-input-disabled-example.component.html
  libs/docs/platform/feed-input/examples/platform-feed-input-example/platform-feed-input-example.component.html
  libs/docs/platform/feed-input/examples/platform-feed-input-max-height-example/platform-feed-input-max-height-example.component.html
Labels: bug, documentation, core

#11232 fix(core,platform): touched correct usage
  libs/core/multi-combobox/multi-combobox.component.html
  libs/core/multi-combobox/multi-combobox.component.ts
  libs/docs/core/multi-combobox/examples/multi-combobox-datasource/multi-combobox-datasource-example.component.html
  libs/docs/core/multi-combobox/examples/multi-combobox-datasource/multi-combobox-datasource-example.component.ts
  libs/docs/core/multi-combobox/examples/multi-combobox-forms/multi-combobox-forms-example.component.html
  libs/docs/core/multi-combobox/examples/multi-combobox-group/multi-combobox-group-example.component.html
  libs/docs/core/multi-combobox/examples/multi-combobox-group/multi-combobox-group-example.component.ts
  libs/docs/platform/multi-combobox/examples/multi-combobox-forms/multi-combobox-forms-example.component.html
  libs/platform/form/multi-combobox/commons/base-multi-combobox.ts
  libs/platform/form/multi-combobox/multi-combobox/multi-combobox.component.html
Labels: bug, platform, core

#11309 fix(core): popover footer button overflow
  libs/core/date-picker/date-picker.component.html
  libs/core/date-picker/date-picker.component.scss
  libs/core/datetime-picker/datetime-picker.component.html
  libs/core/datetime-picker/datetime-picker.component.scss
  libs/core/dialog/dialog.component.scss
Labels: bug, core

#11311 feat(core): add full width modifier for Step Input
  libs/core/step-input/step-input.component.html
  libs/core/step-input/step-input.component.ts
  libs/docs/core/step-input/examples/step-inpt-default-example/step-input-default-example.component.ts
Labels: enhancement

#11326 feat(docs): core select form message with triggers
  libs/core/select/select.component.scss
  libs/docs/core/select/examples/select-semantic-state-example/select-semantic-state-example.component.html
  libs/docs/core/select/examples/select-semantic-state-example/select-semantic-state-example.component.ts
Labels: documentation, core

#11330 feat(i18n): replaced generic with generated type
  libs/i18n/src/lib/models/fd-language-key-ctx.ts
  libs/i18n/src/lib/models/fd-language-key-identifier.ts
  libs/i18n/src/lib/models/fd-language-key.ts
  libs/i18n/src/lib/models/fd-language.ts
  libs/i18n/src/lib/models/flat-fd-language.ts
  libs/i18n/src/lib/models/index.ts
  libs/i18n/src/lib/models/patch-language.ts
  libs/i18n/src/lib/pipes/fd-translate.pipe.ts
  libs/i18n/src/lib/translations/translations.spec.ts
  libs/i18n/src/lib/translations/translations_ar.spec.ts
  libs/i18n/src/lib/translations/translations_bg.spec.ts
  libs/i18n/src/lib/translations/translations_cs.spec.ts
  libs/i18n/src/lib/translations/translations_da.spec.ts
  libs/i18n/src/lib/translations/translations_de.spec.ts
  libs/i18n/src/lib/translations/translations_el.spec.ts
  libs/i18n/src/lib/translations/translations_es.spec.ts
  libs/i18n/src/lib/translations/translations_fi.spec.ts
  libs/i18n/src/lib/translations/translations_fr.spec.ts
  libs/i18n/src/lib/translations/translations_he.spec.ts
  libs/i18n/src/lib/translations/translations_hi.spec.ts
  libs/i18n/src/lib/translations/translations_hr.spec.ts
  libs/i18n/src/lib/translations/translations_hu.spec.ts
  libs/i18n/src/lib/translations/translations_it.spec.ts
  libs/i18n/src/lib/translations/translations_ja.spec.ts
  libs/i18n/src/lib/translations/translations_ka.spec.ts
  libs/i18n/src/lib/translations/translations_kk.spec.ts
  libs/i18n/src/lib/translations/translations_ko.spec.ts
  libs/i18n/src/lib/translations/translations_ms.spec.ts
  libs/i18n/src/lib/translations/translations_nl.spec.ts
  libs/i18n/src/lib/translations/translations_no.spec.ts
  libs/i18n/src/lib/translations/translations_pl.spec.ts
  libs/i18n/src/lib/translations/translations_pt.spec.ts
  libs/i18n/src/lib/translations/translations_ro.spec.ts
  libs/i18n/src/lib/translations/translations_ru.spec.ts
  libs/i18n/src/lib/translations/translations_sh.spec.ts
  libs/i18n/src/lib/translations/translations_sk.spec.ts
  libs/i18n/src/lib/translations/translations_sl.spec.ts
  libs/i18n/src/lib/translations/translations_sq.spec.ts
  libs/i18n/src/lib/translations/translations_sv.spec.ts
  libs/i18n/src/lib/translations/translations_th.spec.ts
  libs/i18n/src/lib/translations/translations_tr.spec.ts
  libs/i18n/src/lib/translations/translations_uk.spec.ts
  libs/i18n/src/lib/translations/translations_zh_CN.spec.ts
  libs/i18n/src/lib/translations/translations_zh_TW.spec.ts
  libs/i18n/src/lib/utils/load-json.ts
  libs/i18n/src/lib/utils/load-properties.ts
  libs/i18n/src/lib/utils/resolve-helpers/common-types.ts
  libs/i18n/src/lib/utils/resolve-helpers/resolve-translations-observable.ts
  libs/i18n/src/lib/utils/resolve-helpers/resolve-translations-signal.ts
  libs/i18n/src/lib/utils/resolve-helpers/resolve-translations-sync.ts
  libs/i18n/src/lib/utils/tokens.ts
  libs/i18n/src/lib/utils/translation-resolver.spec.ts
  libs/i18n/src/lib/utils/translation-tester.ts
  libs/nx-plugin/src/executors/transform-translations/duplicates.ts
  libs/nx-plugin/src/executors/transform-translations/executor.ts
  libs/nx-plugin/src/executors/transform-translations/update-typings.ts
Labels: code refactoring, i18n

#11315 docs: add link to version 0.48 as docs
  versions.json
Labels: documentation, tooling

#11331 feat(platform): icon tab bar multi-click tab
  libs/docs/platform/icon-tab-bar/examples/two-click-area/icon-tab-bar-two-click-area-example.component.html
  libs/docs/platform/icon-tab-bar/examples/two-click-area/icon-tab-bar-two-click-area-example.component.ts
  libs/docs/platform/icon-tab-bar/platform-icon-tab-bar-docs.component.html
  libs/docs/platform/icon-tab-bar/platform-icon-tab-bar-docs.component.ts
  libs/platform/icon-tab-bar/components/icon-tab-bar-base.class.ts
  libs/platform/icon-tab-bar/components/icon-tab-bar-text-type/icon-tab-bar-text-type.component.html
  libs/platform/icon-tab-bar/components/icon-tab-bar-text-type/icon-tab-bar-text-type.component.ts
  libs/platform/icon-tab-bar/components/popovers/text-type-popover/text-type-popover.component.html
  libs/platform/icon-tab-bar/components/popovers/text-type-popover/text-type-popover.component.ts
  libs/platform/icon-tab-bar/components/text-type-tab-item/icon-tab-bar-text-type-tab-item.component.html
  libs/platform/icon-tab-bar/components/text-type-tab-item/icon-tab-bar-text-type-tab-item.component.ts
  libs/platform/icon-tab-bar/icon-tab-bar.component.html
  libs/platform/icon-tab-bar/icon-tab-bar.component.scss
  libs/platform/icon-tab-bar/icon-tab-bar.component.ts
  libs/platform/icon-tab-bar/index.ts
Labels: enhancement, platform

#11334 chore: log the commits during gh action
  .github/workflows/create-release.yml
Labels: tooling

#11335 chore: remove git log and disable gh pages cache
  .github/workflows/create-release.yml
Labels: tooling

#11333 fix(core): reactive tabindex property
  libs/core/list/list-focus-item.model.ts
  libs/core/list/list-item/list-item.component.ts
Labels: bug, core

#11336 chore(ci): migrate to node20
  .github/actions/bump-styles-version/action.yml
  .github/actions/bump-version/action.yml
  .github/actions/generate-conventional-release-notes/action.yml
  .github/actions/get-version/action.yml
  .github/actions/npm-publish/action.yml
  .github/actions/release-tags/action.yml
  .github/actions/update-versions/action.yml
  .github/actions/wait-for-netlify/action.yml
Labels: tooling
