Repository SAP/fundamental-ngx, pull requests merged in 2024-12, with the labels that each got.

#12794 fix(docs): extra scrollbar track showing on docs page for chrome
  libs/docs/shared/src/lib/core-helpers/sections-toolbar/sections-toolbar.component.scss
Labels: documentation

#12806 fix(platform): update Load More label with Show More
  libs/i18n/src/lib/translations/translations.properties
  libs/i18n/src/lib/translations/translations.ts
  libs/i18n/src/lib/translations/translations_ar.properties
  libs/i18n/src/lib/translations/translations_bg.properties
  libs/i18n/src/lib/translations/translations_cs.properties
  libs/i18n/src/lib/translations/translations_da.properties
  libs/i18n/src/lib/translations/translations_de.properties
  libs/i18n/src/lib/translations/translations_el.properties
  libs/i18n/src/lib/translations/translations_en_US_sappsd.properties
  libs/i18n/src/lib/translations/translations_es.properties
  libs/i18n/src/lib/translations/translations_fi.properties
  libs/i18n/src/lib/translations/translations_fr.properties
  libs/i18n/src/lib/translations/translations_he.properties
  libs/i18n/src/lib/translations/translations_hr.properties
  libs/i18n/src/lib/translations/translations_hu.properties
  libs/i18n/src/lib/translations/translations_it.properties
  libs/i18n/src/lib/translations/translations_ja.properties
  libs/i18n/src/lib/translations/translations_kk.properties
  libs/i18n/src/lib/translations/translations_ko.properties
  libs/i18n/src/lib/translations/translations_ms.properties
  libs/i18n/src/lib/translations/translations_nl.properties
  libs/i18n/src/lib/translations/translations_no.properties
  libs/i18n/src/lib/translations/translations_pl.properties
  libs/i18n/src/lib/translations/translations_pt.properties
  libs/i18n/src/lib/translations/translations_ro.properties
  libs/i18n/src/lib/translations/translations_ru.properties
  libs/i18n/src/lib/translations/translations_sh.properties
  libs/i18n/src/lib/translations/translations_sk.properties
  libs/i18n/src/lib/translations/translations_sl.properties
  libs/i18n/src/lib/translations/translations_sv.properties
  libs/i18n/src/lib/translations/translations_th.properties
  libs/i18n/src/lib/translations/translations_tr.properties
  libs/i18n/src/lib/translations/translations_uk.properties
  libs/i18n/src/lib/translations/translations_zh_CN.properties
  libs/i18n/src/lib/translations/translations_zh_TW.properties
  libs/platform/list/list.component.ts
Labels: i18n

#12830 chore: remove non-working workflow
  .github/workflows/testing.yml
Labels: tooling
