Repository SAP/fundamental-ngx, pull requests merged in 2024-08, with the labels that each got.

#12214 fix(core): users cannot customize class names on form-messages
  libs/core/form/form-message/form-message.component.ts
Labels: nice to have, core

#12213 fix(core): fixed link navigation on main page
  apps/docs/src/app.config.ts
Labels: documentation

#12230 fix(platform): dismiss existing dialogs before rendering new one
  libs/platform/table/components/table-p13-dialog/table-p13-dialog.component.spec.ts
  libs/platform/table/components/table-p13-dialog/table-p13-dialog.component.ts
  libs/platform/table/components/table-view-settings-dialog/table-view-settings-dialog.component.spec.ts
  libs/platform/table/components/table-view-settings-dialog/table-view-settings-dialog.component.ts
Labels: platform

#12217 docs(core): grid list docs optimization
  libs/docs/core/grid-list/examples/combo-select/grid-list-combo-select-example.component.html
  libs/docs/core/grid-list/examples/combo-select/grid-list-combo-select-example.component.scss
  libs/docs/core/grid-list/examples/combo-select/grid-list-combo-select-example.component.ts
  libs/docs/core/grid-list/examples/default/grid-list-example.component.html
  libs/docs/core/grid-list/examples/default/grid-list-example.component.ts
  libs/docs/core/grid-list/examples/delete/grid-list-delete-example.component.html
  libs/docs/core/grid-list/examples/delete/grid-list-delete-example.component.scss
  libs/docs/core/grid-list/examples/delete/grid-list-delete-example.component.ts
  libs/docs/core/grid-list/examples/index.ts
  libs/docs/core/grid-list/examples/multi-select/grid-list-multi-select-example.component.html
  libs/docs/core/grid-list/examples/multi-select/grid-list-multi-select-example.component.scss
  libs/docs/core/grid-list/examples/single-select-left/grid-list-single-select-left-example.component.html
  libs/docs/core/grid-list/examples/single-select-left/grid-list-single-select-left-example.component.scss
  libs/docs/core/grid-list/examples/single-select-left/grid-list-single-select-left-example.component.ts
  libs/docs/core/grid-list/examples/single-select-right/grid-list-single-select-right-example.component.html
  libs/docs/core/grid-list/examples/single-select-right/grid-list-single-select-right-example.component.scss
  libs/docs/core/grid-list/examples/single-select-right/grid-list-single-select-right-example.component.ts
  libs/docs/core/grid-list/examples/single-select/grid-list-single-select-example.component.html
  libs/docs/core/grid-list/examples/single-select/grid-list-single-select-example.component.scss
  libs/docs/core/grid-list/examples/single-select/grid-list-single-select-example.component.ts
  libs/docs/core/grid-list/grid-list-docs.component.html
  libs/docs/core/grid-list/grid-list-docs.component.ts
Labels: documentation

#12234 fix(core): remove the default background for autofill input
  libs/core/input-group/input-group.component.scss
Labels: bug

#12252 fix(core,platform): fixed limitless in multi-combobox
  libs/core/multi-combobox/base-multi-combobox.class.ts
  libs/core/multi-combobox/multi-combobox.component.spec.ts
  libs/core/multi-combobox/multi-combobox.component.ts
  libs/docs/core/multi-combobox/examples/multi-combobox-datasource/multi-combobox-datasource-example.component.ts
  libs/docs/platform/multi-combobox/examples/multi-combobox-datasource/multi-combobox-datasource-example.component.ts
  libs/platform/form/multi-combobox/commons/base-multi-combobox.ts
  libs/platform/form/multi-combobox/multi-combobox/multi-combobox.component.spec.ts
  libs/platform/shared/domain/data-source.ts
Labels: enhancement

#12235 fix(platform): table headers are not sticky when body is overflowing
  libs/platform/table/table.component.spec.ts
  libs/platform/table/table.component.ts
Labels: table

#12198 docs(core): implement RTL service documentation
  libs/cdk/utils/services/rtl.service.ts
  libs/docs/cdk/api-files.ts
  libs/docs/cdk/docs-data.json
  libs/docs/cdk/docs-routes.ts
  libs/docs/cdk/rtl-service/e2e/rtl-service.e2e-spec.ts
  libs/docs/cdk/rtl-service/e2e/tsconfig.json
  libs/docs/cdk/rtl-service/examples/rtl-service-basic-example/rtl-service-basic-example.component.html
  libs/docs/cdk/rtl-service/examples/rtl-service-basic-example/rtl-service-basic-example.component.ts
  libs/docs/cdk/rtl-service/index.ts
  libs/docs/cdk/rtl-service/project.json
  libs/docs/cdk/rtl-service/rtl-service-docs.component.html
  libs/docs/cdk/rtl-service/rtl-service-docs.component.ts
  libs/docs/cdk/rtl-service/rtl-service-header/rtl-service-header.component.html
  libs/docs/cdk/rtl-service/rtl-service-header/rtl-service-header.component.scss
  libs/docs/cdk/rtl-service/rtl-service-header/rtl-service-header.component.ts
  libs/docs/cdk/rtl-service/tsconfig.json
  libs/docs/shared-pages/library-doc-shell-page.component.ts
  libs/docs/shared/src/lib/core-helpers/directionality/directionality.component.ts
  yarn.lock
Labels: documentation

#12256 fix(core): update avatar state icons
  libs/core/avatar/avatar-icon.pipe.ts
  libs/core/avatar/avatar.component.spec.ts
  yarn.lock
Labels: design

#12231 fix(core,platform): added read only / non-editable state to checkboxes
  libs/core/checkbox/checkbox/checkbox.component.html
  libs/core/checkbox/checkbox/checkbox.component.scss
  libs/core/checkbox/checkbox/checkbox.component.spec.ts
  libs/core/checkbox/checkbox/checkbox.component.ts
  libs/docs/core/checkbox/checkbox-docs.component.html
  libs/docs/core/checkbox/checkbox-docs.component.ts
  libs/docs/core/checkbox/e2e/checkbox-content.ts
  libs/docs/core/checkbox/e2e/checkbox.e2e-spec.ts
  libs/docs/core/checkbox/examples/checkbox-states-example.component.ts
  libs/docs/platform/checkbox/examples/platform-binary-checkbox.component.html
  libs/platform/form/checkbox/checkbox.component.html
Labels: quick fix

#12270 feat(platform): add option to hide refresh and search buttons in Table toolbar search
  libs/docs/platform/table/examples/platform-table-default-example.component.html
  libs/platform/table/components/table-toolbar/table-toolbar.component.html
  libs/platform/table/components/table-toolbar/table-toolbar.component.ts
Labels: enhancement

#12269 fix(core): add i18n for dynamic page
  libs/core/src/lib/dynamic-page/dynamic-page-header/subheader/dynamic-page-subheader.component.ts
  libs/core/src/lib/dynamic-page/dynamic-page.config.ts
  libs/core/src/lib/dynamic-page/dynamic-page.module.ts
  libs/i18n/src/lib/languages/albanian.ts
  libs/i18n/src/lib/languages/arabic.ts
  libs/i18n/src/lib/languages/bulgarian.ts
  libs/i18n/src/lib/languages/chinese.ts
  libs/i18n/src/lib/languages/chinese_traditional.ts
  libs/i18n/src/lib/languages/croatian.ts
  libs/i18n/src/lib/languages/czech.ts
  libs/i18n/src/lib/languages/danish.ts
  libs/i18n/src/lib/languages/dutch.ts
  libs/i18n/src/lib/languages/english.ts
  libs/i18n/src/lib/languages/finnish.ts
  libs/i18n/src/lib/languages/french.ts
  libs/i18n/src/lib/languages/georgian.ts
  libs/i18n/src/lib/languages/german.ts
  libs/i18n/src/lib/languages/greek.ts
  libs/i18n/src/lib/languages/hebrew.ts
  libs/i18n/src/lib/languages/hindi.ts
  libs/i18n/src/lib/languages/hungarian.ts
  libs/i18n/src/lib/languages/italian.ts
  libs/i18n/src/lib/languages/japanese.ts
  libs/i18n/src/lib/languages/kazakh.ts
  libs/i18n/src/lib/languages/korean.ts
  libs/i18n/src/lib/languages/malay.ts
  libs/i18n/src/lib/languages/norwegian.ts
  libs/i18n/src/lib/languages/polish.ts
  libs/i18n/src/lib/languages/portuguese.ts
  libs/i18n/src/lib/languages/romanian.ts
  libs/i18n/src/lib/languages/russian.ts
  libs/i18n/src/lib/languages/serbian.ts
  libs/i18n/src/lib/languages/slovak.ts
  libs/i18n/src/lib/languages/slovenian.ts
  libs/i18n/src/lib/languages/spanish.ts
  libs/i18n/src/lib/languages/swedish.ts
  libs/i18n/src/lib/languages/thai.ts
  libs/i18n/src/lib/languages/turkish.ts
  libs/i18n/src/lib/languages/ukrainian.ts
  libs/i18n/src/lib/models/lang.ts
Labels: i18n, ng15

#12272 chore(deps): theming-base-content version 11.18.0
  package.json
  yarn.lock
Labels: dependencies, theming

#12271 fix(platform): update grouping selection flow to prevent duplications
  libs/platform/table/components/table-p13-dialog/grouping/grouping.component.html
  libs/platform/table/components/table-p13-dialog/grouping/grouping.component.ts
Labels: bug

#12266 fix(platform): add input for restricting table column min width
  libs/docs/platform/table/examples/platform-table-default-example.component.ts
  libs/platform/src/lib/table-helpers/services/table-column-resize.service.spec.ts
  libs/platform/src/lib/table-helpers/services/table-column-resize.service.ts
  libs/platform/src/lib/table-helpers/table.ts
  libs/platform/src/lib/table/table.component.ts
Labels: ng15

#12273 feat(core): add input to customize the datetime format of specific datetime-picker component
  libs/core/date-picker/date-picker.component.ts
  libs/core/datetime-picker/datetime-picker.component.ts
  libs/docs/core/date-picker/date-picker-docs.component.html
  libs/docs/core/date-picker/examples/date-picker-format-example.component.ts
  libs/docs/core/datetime-picker/datetime-picker-docs.component.html
  libs/docs/core/datetime-picker/e2e/date-time-picker.e2e-spec.ts
  libs/docs/core/datetime-picker/examples/datetime-format-example/datetime-format-example.component.html
  libs/docs/core/datetime-picker/examples/datetime-format-example/datetime-format-example.component.ts
  libs/docs/core/dayjs-datetime-adapter/dayjs-datetime-adapter-docs.component.html
  libs/docs/core/dayjs-datetime-adapter/examples/dayjs-datetime-formats-example.component.html
Labels: datepicker

#12233 fix(core): multi input tokens should not have title attr
  libs/core/multi-input/multi-input.component.html
  libs/core/multi-input/multi-input.component.ts
Labels: accessibility

#12287 fix(platform): set default color in _generateTabBarItems to prevent i…
  libs/platform/icon-tab-bar/icon-tab-bar.component.ts
Labels: bug

#12291 test(core): remove compact file uploader example and e2e
  libs/docs/core/file-uploader/e2e/file-uploader.e2e-spec.ts
  libs/docs/core/file-uploader/e2e/file-uploader.po.ts
  libs/docs/core/file-uploader/examples/file-uploader-compact-example/file-uploader-compact-example.component.html
  libs/docs/core/file-uploader/examples/file-uploader-compact-example/file-uploader-compact-example.component.scss
  libs/docs/core/file-uploader/examples/file-uploader-compact-example/file-uploader-compact-example.component.ts
  libs/docs/core/file-uploader/file-uploader-docs.component.html
  libs/docs/core/file-uploader/file-uploader-docs.component.ts
  libs/docs/core/grid-list/e2e/grid-list.e2e-spec.ts
Labels: testing, test automation

#12289 chore(deps): update fundamental-styles packages to version 0.37.5
  package.json
  yarn.lock
Labels: dependencies, fund-styles adoption

#12176 feat(core): implement calendar multi selection option
  libs/core/calendar/calendar-header/calendar-header.component.ts
  libs/core/calendar/calendar-views/calendar-aggregated-year-view/calendar-aggregated-year-view.component.html
  libs/core/calendar/calendar-views/calendar-day-view/calendar-day-view.component.html
  libs/core/calendar/calendar-views/calendar-day-view/calendar-day-view.component.scss
  libs/core/calendar/calendar-views/calendar-day-view/calendar-day-view.component.spec.ts
  libs/core/calendar/calendar-views/calendar-day-view/calendar-day-view.component.ts
  libs/core/calendar/calendar-views/calendar-month-view/calendar-month-view.component.html
  libs/core/calendar/calendar-views/calendar-year-view/calendar-year-view.component.html
  libs/core/calendar/calendar.component.html
  libs/core/calendar/calendar.component.spec.ts
  libs/core/calendar/calendar.component.ts
  libs/core/calendar/types.ts
  libs/core/date-picker/date-picker-mobile/date-picker-mobile.component.ts
  libs/core/date-picker/date-picker.component.html
  libs/core/date-picker/date-picker.component.spec.ts
  libs/core/date-picker/date-picker.component.ts
  libs/core/date-picker/date-picker.model.ts
  libs/core/datetime-picker/datetime-picker.component.ts
  libs/docs/core/calendar/calendar-docs.component.html
  libs/docs/core/calendar/calendar-docs.component.ts
  libs/docs/core/calendar/examples/calendar-form-example/calendar-form-example.component.html
  libs/docs/core/calendar/examples/calendar-form-example/calendar-form-example.component.scss
  libs/docs/core/calendar/examples/calendar-form-example/calendar-form-example.component.ts
  libs/docs/core/calendar/examples/calendar-multi-example.component.ts
  libs/docs/core/calendar/examples/calendar-multi-range-example.component.ts
  libs/docs/core/date-picker/date-picker-docs.component.html
  libs/docs/core/date-picker/date-picker-docs.component.ts
  libs/docs/core/date-picker/examples/date-picker-form-multi-example.component.ts
  libs/docs/core/date-picker/examples/date-picker-form-multi-range-example.component.ts
  libs/docs/core/date-picker/examples/date-picker-format-example.component.ts
  libs/docs/core/date-picker/examples/date-picker-multi-disable-func-example.component.ts
  libs/docs/core/date-picker/examples/date-picker-multi-example.component.ts
  libs/docs/core/date-picker/examples/date-picker-multi-range-example.component.ts
  libs/docs/core/date-picker/examples/date-picker-single-example.component.ts
  libs/docs/core/date-picker/examples/date-picker-today-button-example.component.ts
  libs/docs/platform/date-picker/examples/mobile/platform-date-picker-mobile-example.component.html
  libs/docs/platform/date-picker/examples/mobile/platform-date-picker-mobile-example.component.ts
  libs/docs/platform/date-picker/examples/platform-date-picker-example.component.html
  libs/docs/platform/date-picker/examples/platform-date-picker-example.component.ts
  libs/docs/platform/date-picker/examples/platform-date-picker-format-example.component.html
  libs/docs/platform/date-picker/examples/platform-date-picker-format-example.component.ts
  libs/platform/form/date-picker/date-picker.component.html
  libs/platform/form/date-picker/date-picker.component.spec.ts
  libs/platform/form/date-picker/date-picker.component.ts
  libs/platform/form/datetime-picker/datetime-picker.component.ts
Labels: nice to have

#12259 feat(platform): update naming of functions that get/set the currently rendered rows on the table
  libs/platform/table-helpers/directives/table-draggable.directive.ts
  libs/platform/table-helpers/directives/table-virtual-scroll.directive.ts
  libs/platform/table-helpers/table.ts
  libs/platform/table/table.component.html
  libs/platform/table/table.component.ts
Labels: table

#12308 chore(deps): fundamental-styles 0.37.6
  package.json
  yarn.lock
Labels: dependencies

#12299 docs(core): update dialog example to prevent jaws from reading title twice
  libs/docs/core/dialog/examples/dialog-complex/dialog-complex-example.component.html
  libs/docs/core/dialog/examples/dialog-complex/dialog-complex-example.component.ts
Labels: ng15

#12298 docs(core): update dialog example to prevent jaws from reading title twice
  libs/docs/core/dialog/examples/dialog-complex/dialog-complex-example.component.html
  libs/docs/core/dialog/examples/dialog-complex/dialog-complex-example.component.ts
Labels: documentation

#12307 fix(core,platform): add preventWheelEvents input to busy indicator
  libs/core/src/lib/busy-indicator/busy-indicator.component.ts
  libs/platform/src/lib/table/table.component.html
Labels: ng15

#12295 test(e2e): run e2e on CI without cache
  .github/workflows/on-pull-request.yml
  libs/docs/core/grid-list/e2e/grid-list.e2e-spec.ts
Labels: E2E automation, e2e

#12292 docs(core): form message updates
  libs/docs/core/form-message/form-message-header/form-message-header.component.html
  libs/docs/core/input/examples/input-state-example.component.html
Labels: accessibility

#12327 chore(deps): update fundamental-styles 0.37.7
  package.json
  yarn.lock
Labels: dependencies

#12325 fix(platform): platform table column resizer performance improvements
  libs/platform/src/lib/table-helpers/directives/table-cell-resizable.directive.ts
Labels: ng15

#12323 fix(platform): platform table column resizer performance improvements
  libs/platform/table-helpers/directives/table-cell-resizable.directive.ts
Labels: table

#12322 chore(ci): update yarn 4.4.1
  .github/actions/nodejs/action.yml
  .gitignore
  .yarnrc
  .yarnrc.yml
  README.md
  netlify.toml
  package.json
  yarn.lock
Labels: tooling

#12329 chore(ci): fix ci
  .github/actions/nodejs/action.yml
  .github/workflows/create-release.yml
Labels: tooling

#12330 docs: add link to 0.52
  versions.json
Labels: documentation

#12267 fix(platform): add input for restricting table column min width
  libs/platform/table-helpers/services/table-column-resize.service.spec.ts
  libs/platform/table-helpers/services/table-column-resize.service.ts
  libs/platform/table-helpers/table.ts
  libs/platform/table/table.component.ts
Labels: table

#12335 fix(platform): screenreader should announce posinset and setsize for table header popover
  libs/docs/platform/table/examples/platform-table-custom-column-example.component.html
  libs/platform/src/lib/list/free-content-list-item/free-content-list-item.component.html
  libs/platform/src/lib/list/free-content-list-item/free-content-list-item.component.ts
  libs/platform/src/lib/table/components/table-cell-header-popover/table-cell-header-popover.component.html
Labels: ng15
