Repository SAP/fundamental-ngx, pull requests merged in 2024-03, with the labels that each got.

#11489 fix(platform): prevent space key scrolling
  libs/platform/src/lib/table-helpers/directives/index.ts
  libs/platform/src/lib/table-helpers/directives/table-cell-selectable.directive.ts
  libs/platform/src/lib/table-helpers/table-helpers.module.ts
  libs/platform/src/lib/table/components/table-row/table-row.component.html
  libs/platform/src/lib/table/components/table-row/table-row.component.ts
Labels: ng15

#11488 fix(platform): prevent space key scrolling
  libs/platform/table-helpers/directives/index.ts
  libs/platform/table-helpers/directives/table-cell-selectable.directive.ts
  libs/platform/table-helpers/table-helpers.module.ts
  libs/platform/table/components/table-row/table-row.component.html
  libs/platform/table/components/table-row/table-row.component.ts
Labels: bug, platform, table

#11493 fix(platform): idea for handling scroll when the table header overlapping focused cell
  libs/cdk/utils/directives/focusable-list/scroll.ts
Labels: bug, accessibility

#11485 fix(platform): idea for handling scroll when the table header overlapping focused cell
  libs/cdk/src/lib/utils/directives/focusable-list/scroll.ts
Labels: bug, ng15

#11496 fix(core,platform,docs): defect hunting issues
  libs/core/button/base-button.ts
  libs/core/dialog/base/dialog-base.class.ts
  libs/core/segmented-button/segmented-button.component.ts
  libs/core/shellbar/shellbar-actions/shellbar-actions.component.ts
  libs/docs/core/avatar/examples/avatar-background-image-example.component.html
  libs/docs/core/avatar/examples/avatar-default-image-with-alternative-options-example.component.html
  libs/docs/core/bar/examples/bar-default-example.component.html
  libs/docs/core/bar/examples/bar-header-example.component.html
  libs/docs/core/bar/examples/bar-page-example.component.html
  libs/docs/core/bar/examples/bar-page-responsive-example.component.html
  libs/docs/core/bar/examples/bar-with-title-example.component.html
  libs/docs/core/button/button-docs.component.html
  libs/docs/core/button/button-docs.component.ts
  libs/docs/core/card/examples/card-example.component.html
  libs/docs/core/card/examples/object-card/card-object-example.component.html
  libs/docs/core/dynamic-page/examples/dynamic-page-facets-example/dynamic-page-facets-example.component.html
  libs/docs/core/facets/examples/facet-group-example.component.html
  libs/docs/core/facets/examples/facet-loading-example.component.html
  libs/docs/core/facets/examples/image-facet-example.component.html
  libs/docs/core/feed-input/examples/feed-input-circle-avatar-example/feed-input-circle-avatar-example.component.html
  libs/docs/core/fixed-card-layout/examples/custom-width/fixed-card-layout-custom-width-example.component.html
  libs/docs/core/fixed-card-layout/examples/default/fixed-card-layout-examples.component.html
  libs/docs/core/fixed-card-layout/examples/disabled-drag-drop/fixed-card-layout-disabled-drag.component.html
  libs/docs/core/fixed-card-layout/examples/mobile/fixed-card-layout-mobile-examples.component.html
  libs/docs/core/multi-input/examples/multi-input-new-tokens-example/multi-input-new-tokens-example.component.html
  libs/docs/core/multi-input/examples/multi-input-new-tokens-example/multi-input-new-tokens-example.component.ts
  libs/docs/core/object-page/examples/object-page-example.component.html
  libs/docs/core/popover/examples/popover-dynamic-container-height/popover-dynamic-container-height-example.component.html
  libs/docs/core/popover/examples/popover-programmatic/popover-programmatic-open-example.component.html
  libs/docs/core/popover/examples/popover-simple/popover-example.component.html
  libs/docs/core/schema/src/lib/button.schema.ts
  libs/docs/platform/dynamic-page/examples/platform-dynamic-page-facets-example/platform-dynamic-page-facets-example.component.html
  libs/docs/platform/menu/examples/platform-menu-basic-example.component.html
  libs/docs/platform/menu/examples/platform-menu-x-position-example.component.html
  libs/docs/platform/object-list-item/examples/platform-object-list-item-border-less-example.component.ts
  libs/docs/platform/object-list-item/examples/platform-object-list-item-example.component.html
  libs/docs/platform/object-list-item/examples/platform-object-list-item-with-row-navigation-example.component.ts
  libs/docs/platform/object-list-item/examples/platform-object-list-item-with-row-selection-and-navigation-example.component.ts
  libs/docs/platform/object-list-item/examples/platform-object-list-item-with-row-selection-example.component.ts
  libs/platform/form/form-group/form-field/form-field.component.html
Labels: bug, documentation, platform, core, Defect Hunting

#11467 docs(platform): update table title illustration example
  libs/docs/platform/table/e2e/table.e2e-spec.ts
  libs/docs/platform/table/platform-table-docs.component.html
Labels: documentation, table

#11516 fix(core): update total tokens text
  libs/i18n/src/lib/translations/translations.ts
Labels: i18n

#11513 fix(core): disable form message group prevent defaults
  libs/core/src/lib/form/form-input-message-group/form-input-message-group.component.html
  libs/core/src/lib/form/form-input-message-group/form-input-message-group.component.ts
  libs/core/src/lib/popover/popover.component.ts
Labels: quick fix, ng15

#11517 chore(deps): theming-base-content v.11.12.2
  package.json
  yarn.lock
Labels: dependencies, theming

#11518 fix(platform): upadte vhd search field placeholder
  libs/platform/value-help-dialog/value-help-dialog/value-help-dialog.component.html
Labels: accessibility

#11522 fix(core): pass closeButtonAriaLabel to close btn ariaLabel
  libs/core/dialog/dialog-close-button/dialog-close-button.component.ts
  libs/core/dialog/dialog-default/dialog-default.component.html
  libs/docs/core/dialog/examples/dialog-object-example/dialog-object-example.component.ts
Labels: accessibility, dialog

#11525 fix(core): update total token text 2
  libs/i18n/src/lib/translations/translations.properties
Labels: tooling, i18n

#11523 fix(platform): fix p13n focus elements
  libs/docs/platform/table/e2e/table.po.ts
  libs/platform/table/components/table-p13-dialog/columns/columns.component.html
  libs/platform/table/components/table-p13-dialog/columns/columns.component.ts
  libs/platform/table/components/table-p13-dialog/filtering/filtering.component.html
  libs/platform/table/components/table-p13-dialog/grouping/grouping.component.html
  libs/platform/table/components/table-p13-dialog/sorting/sorting.component.html
Labels: dialog, focus

#11524 chore(deps): semver v.7.6.0
  package.json
  yarn.lock
Labels: dependencies

#11519 fix(platform): fix p13 dialog focus
  libs/docs/platform/table/e2e/table.po.ts
  libs/platform/src/lib/table/components/table-p13-dialog/columns/columns.component.html
  libs/platform/src/lib/table/components/table-p13-dialog/filtering/filtering.component.html
  libs/platform/src/lib/table/components/table-p13-dialog/grouping/grouping.component.html
  libs/platform/src/lib/table/components/table-p13-dialog/sorting/sorting.component.html
Labels: ng15

#11514 fix(core): disable form message group prevent defaults
  libs/core/form/form-input-message-group/form-input-message-group.component.html
  libs/core/form/form-input-message-group/form-input-message-group.component.ts
  libs/core/popover/popover.component.ts
Labels: core, quick fix

#11540 docs(platform): add outer scroll to Table with growing button
  libs/docs/platform/table/child-docs/pagination/table-pagination-docs.component.html
  libs/docs/platform/table/child-docs/pagination/table-pagination-docs.component.ts
  libs/docs/platform/table/examples/custom-pagination/table-custom-pagination-outer-scroll-example.component.html
  libs/docs/platform/table/examples/custom-pagination/table-custom-pagination-outer-scroll-example.component.ts
Labels: table

#11538 chore(deps): update commitlint version 18.6.x
  package.json
  yarn.lock
Labels: dependencies

#11536 chore(deps): update zone.js v0.14.4
  package.json
  yarn.lock
Labels: dependencies

#11544 feat(core): add auto height option for Grid List items
  libs/core/grid-list/components/grid-list-item/grid-list-item.component.html
  libs/core/grid-list/components/grid-list-item/grid-list-item.component.ts
  libs/docs/core/grid-list/examples/auto-height/grid-list-auto-height-example.component.html
  libs/docs/core/grid-list/examples/auto-height/grid-list-auto-height-example.component.scss
  libs/docs/core/grid-list/examples/auto-height/grid-list-auto-height-example.component.ts
  libs/docs/core/grid-list/examples/index.ts
  libs/docs/core/grid-list/grid-list-docs.component.html
  libs/docs/core/grid-list/grid-list-docs.component.ts
Labels: enhancement

#11552 fix(platform): add proper z-index to Table toolbar so checkboxes don't go over it
  libs/platform/table/components/table-p13-dialog/columns/columns.component.scss
Labels: sourcing

#11556 docs(core): update unread examples with aria-description
  libs/docs/core/list-byline/examples/list-byline-unread-example/list-byline-unread-example.component.html
Labels: documentation, accessibility

#11554 chore(deps): theming-base-content v11.13.0
  libs/docs/core/icon/examples/icon-example.component.ts
  libs/docs/shared/src/lib/utilities/icons.ts
  package.json
  yarn.lock
Labels: dependencies, theming

#11553 fix(platform): add proper z-index to Table toolbar so checkboxes don't go over it
  libs/platform/src/lib/table/components/table-p13-dialog/columns/columns.component.scss
Labels: sourcing

#11555 fix(core): remove role region from Dynamic Page component
  libs/core/dynamic-page/dynamic-page-header/subheader/dynamic-page-subheader.component.html
  libs/core/dynamic-page/dynamic-page-header/subheader/dynamic-page-subheader.component.ts
  libs/core/dynamic-page/dynamic-page.component.html
  libs/core/dynamic-page/dynamic-page.component.ts
  libs/core/dynamic-page/dynamic-page.interface.ts
  libs/docs/platform/dynamic-page/e2e/dynamic-page.po.ts
  libs/platform/dynamic-page/dynamic-page.component.html
Labels: accessibility

#11564 docs(core): document the usage of overlay
  libs/docs/core/message-strip/message-strip-header/message-strip-header.component.html
  libs/docs/core/message-strip/message-strip-header/message-strip-header.component.ts
  libs/docs/core/message-toast/message-toast-header/message-toast-header.component.html
  libs/docs/core/message-toast/message-toast-header/message-toast-header.component.ts
Labels: documentation

#11584 fix(platform): [ng-15-downport] add input to remove space node from pprovalFlow graph
  libs/docs/platform/approval-flow/examples/platform-approval-flow-example.component.html
  libs/docs/platform/approval-flow/examples/platform-approval-flow-example.component.ts
  libs/platform/src/lib/approval-flow/approval-flow.component.ts
Labels: ng15

#11566 fix(core): add aria-labelledby for Card component
  libs/core/card/card-title.directive.ts
  libs/core/card/card.component.ts
  libs/core/card/index.ts
  libs/core/card/token.ts
Labels: accessibility

#11600 test(core): remove wrong import
  libs/core/popover/popover-body/popover-body.component.spec.ts
Labels: testing

#11601 fix(i18n): fixed incorrect translation syntax and improved test reports
  libs/i18n/project.json
  libs/i18n/src/lib/translations/translations_ar.properties
  libs/i18n/src/lib/translations/translations_ar.ts
  libs/i18n/src/lib/translations/translations_bg.ts
  libs/i18n/src/lib/translations/translations_cs.ts
  libs/i18n/src/lib/translations/translations_da.ts
  libs/i18n/src/lib/translations/translations_de.ts
  libs/i18n/src/lib/translations/translations_el.ts
  libs/i18n/src/lib/translations/translations_es.ts
  libs/i18n/src/lib/translations/translations_fi.ts
  libs/i18n/src/lib/translations/translations_fr.ts
  libs/i18n/src/lib/translations/translations_he.ts
  libs/i18n/src/lib/translations/translations_hr.properties
  libs/i18n/src/lib/translations/translations_hr.ts
  libs/i18n/src/lib/translations/translations_hu.ts
  libs/i18n/src/lib/translations/translations_it.ts
  libs/i18n/src/lib/translations/translations_ja.ts
  libs/i18n/src/lib/translations/translations_kk.ts
  libs/i18n/src/lib/translations/translations_ko.ts
  libs/i18n/src/lib/translations/translations_ms.properties
  libs/i18n/src/lib/translations/translations_ms.ts
  libs/i18n/src/lib/translations/translations_nl.ts
  libs/i18n/src/lib/translations/translations_no.ts
  libs/i18n/src/lib/translations/translations_pl.ts
  libs/i18n/src/lib/translations/translations_pt.ts
  libs/i18n/src/lib/translations/translations_ro.ts
  libs/i18n/src/lib/translations/translations_sh.ts
  libs/i18n/src/lib/translations/translations_sk.properties
  libs/i18n/src/lib/translations/translations_sk.ts
  libs/i18n/src/lib/translations/translations_sl.ts
  libs/i18n/src/lib/translations/translations_sv.ts
  libs/i18n/src/lib/translations/translations_th.ts
  libs/i18n/src/lib/translations/translations_tr.ts
  libs/i18n/src/lib/translations/translations_zh_CN.properties
  libs/i18n/src/lib/translations/translations_zh_CN.ts
  libs/i18n/src/lib/translations/translations_zh_TW.ts
  libs/i18n/src/lib/utils/translation-tester.ts
Labels: bug, test automation, i18n

#11610 fix(platform): add visual fixes for option list in VHD
  libs/platform/value-help-dialog/components/define-tab/define-tab.component.html
  libs/platform/value-help-dialog/components/define-tab/define-tab.component.scss
  libs/platform/value-help-dialog/components/define-tab/define-tab.component.ts
Labels: bug

#11615 chore: fixed lint issues
  libs/core/popover/popover-body/popover-body.component.spec.ts
  libs/platform/schematics/utils/package-utils.ts
Labels: quick fix

#11586 fix(core): add css fix for missing error in combobox
  libs/core/input-group/input-group.component.scss
Labels: bug

#11591 docs(platform): fix checkbox examples not having proper label
  libs/docs/platform/checkbox/examples/platform-binary-checkbox.component.html
  libs/docs/platform/checkbox/examples/platform-checkbox-a11y.component.html
  libs/docs/platform/checkbox/examples/platform-checkbox-error-handling.component.html
  libs/docs/platform/checkbox/examples/platform-multiselect-checkbox.component.html
  libs/docs/platform/checkbox/examples/platform-tristate-checkbox.component.html
Labels: documentation

#11616 chore(deps): bump fundamental-styles version 0.34.0
  package.json
  yarn.lock
Labels: dependencies

#11520 fix(platform): add validator input for p13 filter component
  libs/docs/platform/table/child-docs/p13-dialog/p13-dialog-docs.component.html
  libs/docs/platform/table/e2e/table-p13-dialog.e2e-spec.ts
  libs/docs/platform/table/e2e/table-settings-dialog.e2e-spec.ts
  libs/docs/platform/table/e2e/table.po.ts
  libs/docs/platform/table/examples/platform-table-p13-filter-example.component.html
  libs/docs/platform/table/examples/platform-table-p13-filter-example.component.ts
  libs/platform/table/components/table-p13-dialog/filtering/filtering.component.ts
  libs/platform/table/components/table-p13-dialog/filtering/filtering.model.ts
  libs/platform/table/components/table-p13-dialog/table-p13-dialog.component.ts
  libs/platform/table/components/table-p13-dialog/table-p13-filter.component.ts
Labels: enhancement

#11535 fix(platform): add validator input for p13 filter component
  libs/docs/platform/table/child-docs/p13-dialog/p13-dialog-docs.component.html
  libs/docs/platform/table/e2e/table-p13-dialog.e2e-spec.ts
  libs/docs/platform/table/e2e/table-settings-dialog.e2e-spec.ts
  libs/docs/platform/table/e2e/table.po.ts
  libs/docs/platform/table/examples/platform-table-p13-filter-example.component.html
  libs/docs/platform/table/examples/platform-table-p13-filter-example.component.ts
  libs/docs/platform/table/platform-table.module.ts
  libs/platform/src/lib/table/components/table-p13-dialog/filtering/filtering.component.ts
  libs/platform/src/lib/table/components/table-p13-dialog/filtering/filtering.model.ts
  libs/platform/src/lib/table/components/table-p13-dialog/table-p13-dialog.component.ts
  libs/platform/src/lib/table/components/table-p13-dialog/table-p13-filter.component.ts
Labels: ng15

#11557 fix: do not set tabindex="-1" in setTabbable
  libs/cdk/src/lib/utils/directives/focusable-item/focusable-item.directive.ts
Labels: ng15

#11590 fix(core): redundant aria-label on select component
  libs/core/src/lib/select/select.component.html
Labels: ng15

#11617 chore: fixed generator and modified structure to make it easier
  libs/docs/btp/docs-data.json
  libs/docs/btp/docs-data.ts
  libs/docs/btp/docs-routes.ts
  libs/docs/btp/tsconfig.json
  libs/docs/cdk/docs-data.json
  libs/docs/cdk/docs-data.ts
  libs/docs/cdk/docs-routes.ts
  libs/docs/core/api-files.ts
  libs/docs/core/docs-data.json
  libs/docs/core/docs-data.ts
  libs/docs/core/docs-routes.ts
  libs/docs/cx/docs-data.json
  libs/docs/cx/docs-data.ts
  libs/docs/cx/docs-routes.ts
  libs/docs/i18n/docs-data.json
  libs/docs/i18n/docs-data.ts
  libs/docs/i18n/docs-routes.ts
  libs/docs/platform/docs-data.json
  libs/docs/platform/docs-data.ts
  libs/docs/platform/docs-routes.ts
  libs/nx-plugin/src/generators/sap-component/add-entry-to-api-files.ts
  libs/nx-plugin/src/generators/sap-component/add-entry-to-docs-routes.ts
  libs/nx-plugin/src/generators/sap-component/files/docs/__fileName__-docs.component.html.template
  libs/nx-plugin/src/generators/sap-component/files/docs/__fileName__-docs.component.ts.template
  libs/nx-plugin/src/generators/sap-component/files/docs/__fileName__-docs.module.ts.template
  libs/nx-plugin/src/generators/sap-component/files/docs/__fileName__-header/__fileName__-header.component.html.template
  libs/nx-plugin/src/generators/sap-component/files/docs/__fileName__-header/__fileName__-header.component.ts.template
  libs/nx-plugin/src/generators/sap-component/files/docs/__name__-header/__fileName__-header.component.ts.template
  libs/nx-plugin/src/generators/sap-component/files/docs/e2e/__fileName__.e2e-spec.ts.template
  libs/nx-plugin/src/generators/sap-component/files/docs/examples/default/__fileName__-default-example.component.html.template
  libs/nx-plugin/src/generators/sap-component/files/docs/examples/default/__fileName__-default-example.component.ts.template
  libs/nx-plugin/src/generators/sap-component/files/docs/index.ts.template
  libs/nx-plugin/src/generators/sap-component/files/docs/project.json.template
  libs/nx-plugin/src/generators/sap-component/files/lib/package.json.template
  libs/nx-plugin/src/generators/sap-component/files/library/__fileName__.component.ts.template
  libs/nx-plugin/src/generators/sap-component/files/library/index.ts.template
  libs/nx-plugin/src/generators/sap-component/files/library/ng-package.json.template
  libs/nx-plugin/src/generators/sap-component/files/library/project.json.template
  libs/nx-plugin/src/generators/sap-component/generation-context.ts
  libs/nx-plugin/src/generators/sap-component/generator.ts
  libs/nx-plugin/src/generators/sap-component/schema.json
  libs/nx-plugin/src/generators/sap-component/utils/ast-utils.ts
  libs/nx-plugin/src/generators/sap-component/utils/linting.ts
Labels: documentation, tooling

#11608 fix(platform): table empty cell screenreader text
  libs/docs/platform/table/examples/platform-table-custom-title-example.component.ts
  libs/platform/src/lib/table/components/table-row/table-row.component.html
Labels: ng15

#11582 fix(core): open combobox on paste event
  libs/core/combobox/combobox.component.html
  libs/core/combobox/combobox.component.ts
Labels: bug

#11565 fix: use paste event to open popover in fd-combobox
  libs/core/src/lib/combobox/combobox.component.html
  libs/core/src/lib/combobox/combobox.component.ts
Labels: ng15

#11634 docs: add 0.49 docs
  versions.json
Labels: documentation

#11646 chore(release): publish 0.49.2
  CHANGELOG.md
  lerna.json
  libs/btp/CHANGELOG.md
  libs/btp/package.json
  libs/cdk/CHANGELOG.md
  libs/cdk/package.json
  libs/core/CHANGELOG.md
  libs/core/package.json
  libs/cx/CHANGELOG.md
  libs/cx/package.json
  libs/datetime-adapter/CHANGELOG.md
  libs/datetime-adapter/package.json
  libs/i18n/CHANGELOG.md
  libs/i18n/package.json
  libs/moment-adapter/CHANGELOG.md
  libs/moment-adapter/package.json
  libs/nx-plugin/CHANGELOG.md
  libs/nx-plugin/package.json
  libs/platform/CHANGELOG.md
  libs/platform/package.json
Labels: tooling

#11563 fix(platform): vhd keyboard improvements
  libs/platform/src/lib/value-help-dialog/components/select-tab/select-tab.component.html
  libs/platform/src/lib/value-help-dialog/value-help-dialog/value-help-dialog.component.html
Labels: ng15

#11653 fix(core): hiding action sheet in shellbar if not needed
  libs/core/shellbar/shellbar-actions-mobile/shellbar-actions-mobile.component.html
Labels: core, quick fix

#11658 fix(platform): added title to filter navigate back button
  libs/i18n/src/lib/models/fd-language-key-identifier.ts
  libs/i18n/src/lib/translations/translations.properties
  libs/i18n/src/lib/translations/translations.ts
  libs/platform/table/components/table-view-settings-dialog/filtering/filter-step.component.html
Labels: accessibility, platform, sourcing, table

#11649 docs(core): list stackblitz examples
  libs/docs/core/list-byline/examples/list-byline-loading-example/list-byline-loading-example.component.ts
  libs/docs/core/list-byline/list-byline-docs.component.ts
  libs/docs/core/list/examples/list-loading-example/list-loading-example.component.ts
  libs/docs/core/list/list-docs.component.ts
Labels: documentation, tooling

#11657 fix(core): pagination accessibility improvements
  libs/cdk/utils/directives/only-digits/only-digits.directive.ts
  libs/core/pagination/pagination.component.html
  libs/core/pagination/pagination.component.ts
Labels: bug, accessibility

#11664 fix: allow synthetic default import
  libs/datetime-adapter/tsconfig.json
  libs/docs/shared/src/lib/core-helpers/stackblitz/code-example-stack/tsconfig.json
  tsconfig.base.json
Labels: tooling
