Repository SAP/fundamental-ngx, pull requests merged in 2024-11, with the labels that each got.

#12671 chore(deps): update lerna 8.1.8
  package.json
  yarn.lock
Labels: tooling, dependencies

#12701 chore(deps): theming-base-content 11.20.0
  libs/docs/core/icon/examples/icon-businessSuiteInAppSymbols-example.component.ts
  package.json
  yarn.lock
Labels: theming

#12704 chore(deps): theming-base-content 11.22.0
  package.json
  yarn.lock
Labels: dependencies, theming

#12664 fix(core,platform): multi input focus switching bug
  libs/core/multi-input/multi-input.component.ts
  libs/platform/form/multi-input/base-multi-input.ts
Labels: bug

#12665 fix(core,platform): multi input focus switching bug
  libs/core/src/lib/multi-input/multi-input.component.ts
  libs/platform/src/lib/form/multi-input/base-multi-input.ts
Labels: ng15

#12742 fix: failing platform table p13 e2e
  libs/docs/platform/table/e2e/table.po.ts
Labels: testing

#12753 fix: i18n translations for November 2024
  libs/i18n/src/lib/translations/translations_ar.properties
  libs/i18n/src/lib/translations/translations_bg.properties
  libs/i18n/src/lib/translations/translations_cs.properties
  libs/i18n/src/lib/translations/translations_da.properties
  libs/i18n/src/lib/translations/translations_de.properties
  libs/i18n/src/lib/translations/translations_el.properties
  libs/i18n/src/lib/translations/translations_es.properties
  libs/i18n/src/lib/translations/translations_fi.properties
  libs/i18n/src/lib/translations/translations_fr.properties
  libs/i18n/src/lib/translations/translations_he.properties
  libs/i18n/src/lib/translations/translations_hr.properties
  libs/i18n/src/lib/translations/translations_hu.properties
  libs/i18n/src/lib/translations/translations_it.properties
  libs/i18n/src/lib/translations/translations_ja.properties
  libs/i18n/src/lib/translations/translations_kk.properties
  libs/i18n/src/lib/translations/translations_ko.properties
  libs/i18n/src/lib/translations/translations_ms.properties
  libs/i18n/src/lib/translations/translations_nl.properties
  libs/i18n/src/lib/translations/translations_no.properties
  libs/i18n/src/lib/translations/translations_pl.properties
  libs/i18n/src/lib/translations/translations_pt.properties
  libs/i18n/src/lib/translations/translations_ro.properties
  libs/i18n/src/lib/translations/translations_ru.properties
  libs/i18n/src/lib/translations/translations_sh.properties
  libs/i18n/src/lib/translations/translations_sk.properties
  libs/i18n/src/lib/translations/translations_sl.properties
  libs/i18n/src/lib/translations/translations_sv.properties
  libs/i18n/src/lib/translations/translations_th.properties
  libs/i18n/src/lib/translations/translations_tr.properties
  libs/i18n/src/lib/translations/translations_uk.properties
  libs/i18n/src/lib/translations/translations_zh_CN.properties
  libs/i18n/src/lib/translations/translations_zh_TW.properties
Labels: i18n

#12720 fix(core,platform): wizard template, a11y updates
  libs/core/form/form-label/form-label.component.html
  libs/core/form/form-label/form-label.component.scss
  libs/core/form/form-label/form-label.component.ts
  libs/docs/core/wizard/e2e/wizard.po.ts
  libs/docs/core/wizard/examples/wizard-dialog-example.component.html
  libs/docs/core/wizard/examples/wizard-example.component.html
  libs/docs/core/wizard/examples/wizard-visible-summary-example.component.html
  libs/platform/wizard-generator/components/wizard-summary-step/wizard-summary-section/wizard-summary-section.component.html
Labels: accessibility

#12783 fix(platform): table spanning
  libs/platform/table/table.component.ts
Labels: table
