Repository SAP/fundamental-ngx, pull requests merged in 2025-08, with the labels that each got.

#13434 fix: remove core/utils and refer directly cdk/utils
  libs/core/action-bar/action-bar.component.ts
  libs/core/utils/filler-test.spec.ts
  libs/core/utils/index.ts
  libs/core/utils/ng-package.json
  libs/core/utils/project.json
  libs/cx/nested-list/nested-list-keyboard.service.ts
  libs/cx/nested-list/nested-list-popover/nested-list-popover.component.ts
  libs/cx/side-navigation/side-navigation.component.ts
  libs/platform/page-footer/page-footer.component.ts
Labels: tooling

#13441 test(ci): revert to NX 21.2
  package.json
  yarn.lock
Labels: tooling

#13442 fix(core): disable tab focus on disabled multi input
  libs/core/multi-input/multi-input.component.spec.ts
  libs/core/multi-input/multi-input.component.ts
Labels: accessibility

#13454 fix(core): import menu css in user menu
  libs/core/user-menu/user-menu.component.scss
Labels: bug
