Repository SAP/fundamental-ngx, pull requests merged in 2025-03, with the labels that each got.

#13086 fix: changes after running build
  libs/i18n/src/lib/translations/translations_ar.ts
  libs/i18n/src/lib/translations/translations_bg.ts
  libs/i18n/src/lib/translations/translations_cs.ts
  libs/i18n/src/lib/translations/translations_da.ts
  libs/i18n/src/lib/translations/translations_de.ts
  libs/i18n/src/lib/translations/translations_el.ts
  libs/i18n/src/lib/translations/translations_en_US_sappsd.ts
  libs/i18n/src/lib/translations/translations_es.ts
  libs/i18n/src/lib/translations/translations_fi.ts
  libs/i18n/src/lib/translations/translations_fr.ts
  libs/i18n/src/lib/translations/translations_he.ts
  libs/i18n/src/lib/translations/translations_hr.ts
  libs/i18n/src/lib/translations/translations_hu.ts
  libs/i18n/src/lib/translations/translations_it.ts
  libs/i18n/src/lib/translations/translations_ja.ts
  libs/i18n/src/lib/translations/translations_kk.ts
  libs/i18n/src/lib/translations/translations_ko.ts
  libs/i18n/src/lib/translations/translations_ms.ts
  libs/i18n/src/lib/translations/translations_nl.ts
  libs/i18n/src/lib/translations/translations_no.ts
  libs/i18n/src/lib/translations/translations_pl.ts
  libs/i18n/src/lib/translations/translations_pt.ts
  libs/i18n/src/lib/translations/translations_ro.ts
  libs/i18n/src/lib/translations/translations_ru.ts
  libs/i18n/src/lib/translations/translations_sh.ts
  libs/i18n/src/lib/translations/translations_sk.ts
  libs/i18n/src/lib/translations/translations_sl.ts
  libs/i18n/src/lib/translations/translations_sv.ts
  libs/i18n/src/lib/translations/translations_th.ts
  libs/i18n/src/lib/translations/translations_tr.ts
  libs/i18n/src/lib/translations/translations_uk.ts
  libs/i18n/src/lib/translations/translations_zh_CN.ts
  libs/i18n/src/lib/translations/translations_zh_TW.ts
  yarn.lock
Labels: tooling

#13087 chore: fix lint errors
  libs/btp/navigation/components/navigation-item/navigation-list-item.component.spec.ts
  libs/btp/navigation/components/navigation-start/navigation-content-start.component.ts
  libs/btp/search-field/src/search-field.component.ts
  libs/core/grid-list/components/grid-list-filter-bar/grid-list-filter-bar.component.ts
  libs/core/input-group/input-group.component.ts
  libs/platform/menu/menu.component.ts
  libs/platform/value-help-dialog/components/select-tab/select-tab.component.ts
  libs/platform/wizard-generator/components/wizard-body/wizard-body.component.ts
Labels: tooling

#13093 docs: bump versions
  versions.json
Labels: documentation

#13094 feat: bring fundamental-styles 0.39
  package.json
  yarn.lock
Labels: fund-styles adoption

#13098 chore: bring theming-base-content version 11.26.0
  libs/docs/core/icon/examples/icon-businessSuiteInAppSymbols-example.component.ts
  libs/docs/core/icon/examples/icon-example.component.ts
  libs/docs/shared/src/lib/utilities/icons.ts
  package.json
  yarn.lock
Labels: dependencies, theming

#13099 fix: remove belize from schematics, update cdk imports in platform table
  libs/core/schematics/add-theming/add-theming.spec.ts
  libs/core/schematics/add-theming/index.ts
  libs/platform/table/components/table-view-settings-dialog/settings-dialog/settings-dialog.component.ts
Labels: ng19

#13041 feat(core): user settings
  libs/core/bar/bar.component.scss
  libs/core/content-density/services/content-density-observer.service.ts
  libs/core/datetime/fd-datetime-adapter.ts
  libs/core/dialog/base/dialog-config-base.class.ts
  libs/core/dialog/dialog-body/dialog-body.component.ts
  libs/core/dialog/dialog.component.html
  libs/core/dialog/dialog.component.scss
  libs/core/dialog/dialog.component.ts
  libs/core/fundamental-ngx.module.ts
  libs/core/index.ts
  libs/core/list/list-item/list-item.component.ts
  libs/core/list/list.component.scss
  libs/core/list/list.component.ts
  libs/core/settings/index.ts
  libs/core/settings/ng-package.json
  libs/core/settings/project.json
  libs/core/settings/settings-container/settings-container.component.spec.ts
  libs/core/settings/settings-container/settings-container.component.ts
  libs/core/settings/settings-content/settings-content.directive.spec.ts
  libs/core/settings/settings-content/settings-content.directive.ts
  libs/core/settings/settings-detail-area/settings-detail-area.directive.spec.ts
  libs/core/settings/settings-detail-area/settings-detail-area.directive.ts
  libs/core/settings/settings-dialog-body/settings-dialog-body.directive.spec.ts
  libs/core/settings/settings-dialog-body/settings-dialog-body.directive.ts
  libs/core/settings/settings-dialog-content/settings-dialog-content.directive.spec.ts
  libs/core/settings/settings-dialog-content/settings-dialog-content.directive.ts
  libs/core/settings/settings-header-button/settings-header-button.directive.spec.ts
  libs/core/settings/settings-header-button/settings-header-button.directive.ts
  libs/core/settings/settings-header/settings-header.directive.spec.ts
  libs/core/settings/settings-header/settings-header.directive.ts
  libs/core/settings/settings-list-area/settings-list-area.directive.spec.ts
  libs/core/settings/settings-list-area/settings-list-area.directive.ts
  libs/core/settings/settings-list-container/settings-list-container.directive.spec.ts
  libs/core/settings/settings-list-container/settings-list-container.directive.ts
  libs/core/settings/settings.component.scss
  libs/core/settings/settings.component.spec.ts
  libs/core/settings/settings.component.ts
  libs/core/settings/settings.module.ts
  libs/docs/core/api-files.ts
  libs/docs/core/docs-data.json
  libs/docs/core/docs-routes.ts
  libs/docs/core/settings-dialog/examples/index.ts
  libs/docs/core/settings-dialog/examples/template-based-settings-byline/template-based-settings-dialog-byline-example.component.html
  libs/docs/core/settings-dialog/examples/template-based-settings-byline/template-based-settings-dialog-byline-example.component.ts
  libs/docs/core/settings-dialog/examples/template-based-settings/template-based-settings-dialog-example.component.html
  libs/docs/core/settings-dialog/examples/template-based-settings/template-based-settings-dialog-example.component.ts
  libs/docs/core/settings-dialog/index.ts
  libs/docs/core/settings-dialog/project.json
  libs/docs/core/settings-dialog/settings-dialog-docs-header/settings-dialog-docs-header.component.html
  libs/docs/core/settings-dialog/settings-dialog-docs-header/settings-dialog-docs-header.component.ts
  libs/docs/core/settings-dialog/settings-dialog-docs.component.html
  libs/docs/core/settings-dialog/settings-dialog-docs.component.ts
  libs/docs/core/settings-dialog/tsconfig.json
  libs/docs/shared/src/lib/core-helpers/sections-toolbar/sections-toolbar.component.scss
  libs/platform/icon-tab-bar/icon-tab-bar.component.html
  libs/platform/icon-tab-bar/icon-tab-bar.component.ts
  libs/platform/table/table.component.ts
Labels: UXC Updates

#13123 fix(platform): do not set focus on list when there is IME processing
  libs/cdk/src/lib/utils/functions/key-util.spec.ts
  libs/cdk/src/lib/utils/functions/key-util.ts
  libs/core/src/lib/multi-combobox/multi-combobox.component.ts
  libs/platform/src/lib/form/combobox/commons/base-combobox.ts
  libs/platform/src/lib/form/multi-combobox/commons/base-multi-combobox.ts
Labels: ng15

#13127 chore(ci): test ci
  .github/workflows/create-release.yml
  libs/i18n/src/lib/models/fd-language-key-identifier.ts
  yarn.lock
Labels: tooling

#13130 fix(cx): update the CX Side nav with latest fund-styles changes
  libs/cx/side-navigation/side-navigation.component.scss
  libs/docs/cx/side-navigation/examples/side-navigation-cozy-wide-icon-3-level-example.component.ts
  libs/docs/cx/side-navigation/examples/side-navigation-cozy-wide-text-only-1-level-example.component.ts
  libs/docs/cx/side-navigation/examples/side-navigation-cozy-wide-text-only-3-level-example.component.ts
  libs/docs/cx/side-navigation/examples/side-navigation-dynamic-width-example.component.ts
  package.json
  yarn.lock
Labels: UXC Updates

#13113 fix(btp): update the styling for Vert nav
  eslint.config.js
  libs/btp/navigation/components/navigation-item/navigation-list-item.component.html
  libs/btp/navigation/components/navigation-item/navigation-list-item.component.ts
  libs/btp/navigation/components/navigation-link/navigation-link.component.ts
  libs/btp/navigation/components/navigation/navigation.component.scss
  libs/btp/navigation/components/navigation/navigation.component.ts
  libs/docs/btp/navigation/examples/basic-example/navigation-basic-example.component.html
  libs/docs/btp/navigation/examples/basic-example/navigation-basic-example.component.ts
  libs/docs/btp/navigation/examples/parent-item-link/navigation-parent-item-link.component.html
  libs/docs/btp/navigation/examples/parent-item-link/navigation-parent-item-link.component.ts
Labels: UXC Updates

#13132 chore(ci): ci scripts cleanup
  .github/actions/nodejs/action.yml
  .github/workflows/create-release.yml
  .github/workflows/on-pull-request.yml
  package.json
  yarn.lock
Labels: tooling

#13137 fix(core): remove Dynamic page shadow when used with Icon Tab Bar
  libs/core/dynamic-page/dynamic-page.component.scss
Labels: bug

#13153 fix(core): add an option to provide more descriptive title for Message Strip dismiss btn
  libs/core/message-strip/message-strip.component.html
  libs/core/message-strip/message-strip.component.ts
  libs/docs/core/message-strip/examples/message-strip-example.component.html
Labels: enhancement, accessibility

#13152 fix(core): set correct height for List with Byline group header
  libs/core/list/list.component.scss
  libs/docs/core/list-byline/examples/list-byline-standard-example/list-byline-standard-example.component.html
Labels: bug

#13151 fix(core): add additional options to set the flexible column layout splitter title
  libs/core/flexible-column-layout/flexible-column-layout.component.html
  libs/core/flexible-column-layout/flexible-column-layout.component.ts
  libs/docs/core/flexible-column-layout/examples/default/flexible-column-layout-example.component.html
Labels: enhancement
