Repository SAP/fundamental-ngx, pull requests merged in 2025-06, with the labels that each got.

#13333 chore: move the issue template
  .github/ISSUE_TEMPLATE/issue.yml
  .github/PULL_REQUEST_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE.yml
Labels: tooling

#13336 fix(core): apply correct class to back and hamburger buttons in ShellBar
  libs/core/shellbar/shellbar.component.html
Labels: bug

#13354 fix: font schematics
  libs/core/schematics/add-theming/add-theming.spec.ts
  libs/core/schematics/add-theming/index.ts
  libs/core/schematics/collection.json
  libs/core/schematics/migrate-to-fdb-splitter/add-btp-package.ts
  libs/core/schematics/migrate-to-fdb-splitter/get-file-dependencies.ts
  libs/core/schematics/migrate-to-fdb-splitter/index.ts
  libs/core/schematics/migrate-to-fdb-splitter/replace-fd-with-btp.ts
  libs/core/schematics/migrate-to-fdb-splitter/replacements.ts
  libs/core/schematics/migrate-to-fdb-splitter/schema.json
  libs/core/schematics/migrate-to-fdb-splitter/schema.ts
  libs/core/schematics/migrations.json
  libs/core/schematics/migrations/migration-0-37/index.ts
  libs/core/schematics/migrations/migration-0-39/index.ts
Labels: tooling

#13352 fix(core): multi-combobox dropdown visual fixes
  libs/core/multi-combobox/multi-combobox.component.scss
  libs/core/multi-combobox/multi-combobox.component.ts
Labels: bug

#13364 fix(core): add option to customize Combobox dropdown width
  libs/core/combobox/combobox.component.html
  libs/core/combobox/combobox.component.ts
  libs/docs/core/combobox/examples/combobox-search-field-example.component.html
  libs/docs/core/combobox/examples/combobox-search-field-example.component.ts
Labels: enhancement

#13367 fix(platform): show Toolbar separator in custom Toolbar inside Platform Table
  libs/docs/platform/table/examples/platform-table-custom-title-example.component.html
  libs/platform/table/components/table-toolbar/table-toolbar.component.html
  libs/platform/table/table.component.scss
Labels: enhancement
